### ISSUE TITLE
Next/previous tab behaviour (making it work on last/first tab)

### ISSUE THREAD

**Issue by stmr** [Robbendebiene/Gesturefy#10]
Hi,
there is one more thing I miss and that's cycling while switching tabs so the next tab switches from the last tab to the first tab and previous tab from the first to the last one. Currently it does nothing, but I guess it works as expected.
Do you mind adding this in the future? :) Thanks

**Comment by Robbendebiene** [comment]
Of course, thanks for the nice idea :)
