### ISSUE TITLE
Sync support

### ISSUE THREAD

**Issue by jusuff** [Robbendebiene/Gesturefy#100]
It would be nice to have settings synchronization. This would allow to keep settings same on different devices.

**Comment by dregad** [comment]
That would be a very useful feature indeed.

As an alternative (or in addition), the ability to save/restore the settings (especially the gestures) to a local file would be nice (FireGestures used to allow that)

**Comment by Robbendebiene** [comment]
@dregad This is already possible. (Look at Settings > About)

**Comment by dregad** [comment]
> This is already possible. (Look at Settings > About)

Duh. I didn't think of looking for that under _About_... 
Thanks !

**Comment by pmalecka** [comment]
This actually works for the onetime setup. Would be possible to have the settings Synced (FF supports this through storage.sync). That way - once the extension is setup on the first computer, logging to Firefox Account on another computer will pull the settings automatically.

**Comment by kingston51** [comment]
Fully agree! Sync of the parameters would be great !
Thanks

**Comment by Robbendebiene** [comment]
Added in [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0)

**Comment by bingoxo** [comment]
> Added in [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0)

I don't see it in latest version , was it removed ?

**Comment by Robbendebiene** [comment]
@bingoxo Yes it was removed in a later version as the implementation caused data loss for multiple users.

It will be reintroduced in the next [major release](https://github.com/Robbendebiene/Gesturefy/pull/715) in a safer manner.
