### ISSUE TITLE
Open Sidebar - Action

### ISSUE THREAD

**Issue by toudas** [Robbendebiene/Gesturefy#101]
Is it possible to built in an gestures for "Open Sidebar"?
Thanks in advance

**Comment by Robbendebiene** [comment]
@toudas  Sadly this is currently not possible, because I can only toggle/open a sidebar which is provided by the addon itself.

**Comment by Robbendebiene** [comment]
I'm closing this, since it is unlikely that Mozilla will implement an API for this.
