### ISSUE TITLE
Gesture delay and right click ubuntu working on other addons

### ISSUE THREAD

**Issue by dfherr** [Robbendebiene/Gesturefy#102]
This is the best addon regarding customizable gestures I've found, but the gesture start seems to lag (~1 second, really annoying).

I've found other addons (https://addons.mozilla.org/de/firefox/addon/mouse-gestures/ , https://addons.mozilla.org/de/firefox/addon/basic-gestures/ ) that do not have that delay and have right click working on ubuntu right now. They lack any customization though and I would like to stick with the firegesture movements I'm used to for years.

My understanding of the Firefox extension API is close to zero, but maybe these extensions can give you a hint on how to improve your addon ;)

I've also had some issues with the restore tab functionality in this addon (opening a window closed ages ago instead of the most recently closed tab), that foxy gestures didn't have in some short tries, but I didn't try it long enough to have more details.

**Comment by TaylorBoy** [comment]
The right mouse button does not work properly

Ubuntu 16.04 57 Mozilla Firefox (64-bit)

**Comment by Robbendebiene** [comment]
> This is the best addon regarding customizable gestures I've found, but the gesture start seems to lag (~1 second, really annoying).

Maybe you are talking about the gesture threshhold which is used to prevent drawing on simple clicks. Just set it to 0 if you don't like it.

> I've also had some issues with the restore tab functionality in this addon (opening a window closed ages ago instead of the most recently closed tab), that foxy gestures didn't have in some short tries, but I didn't try it long enough to have more details.

I remeber this bug happend to me once, but I was pretty sure that this was fixed by firefox, but maybe I was just lucky.

> The right mouse button does not work properly

This is well known: #1.  The right click "fix" will land in firefox 58 as far as I know.

**Comment by dfherr** [comment]
@Robbendebiene i knew about #1 . Just wanted to tell you about some addons that work around that issue.

The delay wasn't based on the treshhold. I tried setting it to 0. It is non existent on my Windows machine though. I'll try it again on linux once Mozilla 58 is out and report it again if it occurs again.
