### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by oz42** [Robbendebiene/Gesturefy#104]
i just installed it, but I see no mouse track while doing gestures, and I cannot record new ones. Restarting browser dis not help.

**Comment by Itchiii** [comment]
Do you use Mac or Linux? 
Then read the discription. 

> For MacOS & Linux users: Use left or middle mouse button due to the different right click/context menu behaviour (see this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1360278))

**Comment by oz42** [comment]
I am on Linux. Thanks for the information!

**Comment by Robbendebiene** [comment]
Duplicate of #1
