### ISSUE TITLE
Doesn't work with pad?

### ISSUE THREAD

**Issue by michaldybczak** [Robbendebiene/Gesturefy#106]
Not sure if this is a bug or a crappy feature? But the plugin seems to be useless on laptops. Or maybe am I missing something?

**Comment by Robbendebiene** [comment]
It's working for me. What is your OS?

**Comment by michaldybczak** [comment]
Manjaro KDE

**Comment by Robbendebiene** [comment]
In this case, please read the [addon description](https://addons.mozilla.org/firefox/addon/gesturefy/) or #1

**Comment by Robbendebiene** [comment]
I testet in on my Linux laptop: middle and left mouse button setting is working with my trackpad and left mousebutton settings is also working with my touchpad.

**Comment by michaldybczak** [comment]
Ah, you meant I have to set it specifically for left button? Yeah, it works now! Thanks :D
