### ISSUE TITLE
about:blank missing body

### ISSUE THREAD

**Issue by luryi** [Robbendebiene/Gesturefy#108]
1 ) Have home page set to about:blank
2a) Middle click home button with mouse to open about:blank in new tab.
-or-
2b) Open a new window (which defaults to showing home page - about:blank)

about:blank is missing `<body></body>` tag and the (Web Developer reports its as `<html><head></head></html>`).
Without a body, gestures do not work.

This issue does not happen when opening an about:blank page otherwise (left clicking on the home button, or typing about:blank into the address bar) - when about:blank is loaded as not the starting page in a new window or tab.

Firefox 57.0 (64-bit)
Windows 10 Pro 10.0.16299

**Comment by Robbendebiene** [comment]
Hmm strange, this seems like a mozilla related bug.

**Comment by luryi** [comment]
Probably, but it doesnt seem to happen when Gesturefy is disabled

**Comment by Robbendebiene** [comment]
@luryi Does this problem still persist? Because everything is working fine for me.

**Comment by luryi** [comment]
Yes, the issue, as described, still affects me.
I've tried to record it (although FRAPS didn't want to record the mouse movement over the problematic about:blank page).
https://imgur.com/a/dLktE
In the recording, I draw try to draw a box using Gesturefy on every page - first this issue page, then I left click the home button (which is set to about:blank) and then I middle click the home button which opens the second tab.
You can see that the two tabs even look a bit different. Here is their Inspector views:
https://imgur.com/a/PrNQ8

While putting this together, I found out that occasionally when I open a new (secondary) Firefox window, the issue is not present when middle clicking the home button to a open a new about:blank tab.

**Comment by Robbendebiene** [comment]
Thanks for the recordings.
However this problem seems to be out of my abilities.

> While putting this together, I found out that occasionally when I open a new (secondary) Firefox window, the issue is not present when middle clicking the home button to a open a new about:blank tab.

Things are getting weirder.. Does it always work in the new window or only in special cases, for example when there are no tabs opened or anything like that?

I guess if you really want that to be fixed you should reach out to Mozilla by creating a bug report here: https://bugzilla.mozilla.org/enter_bug.cgi#h=dupes%7CToolkit The only thing my extension does is injecting a script into the body on document start (page load):
```
      "run_at": "document_start",
      "match_about_blank": true,
      "js": [
            scripts..
      ]
```

**Comment by luryi** [comment]
Sounds good, I'll look into filing a bug with Mozilla.
Thanks for you time.

**Comment by Robbendebiene** [comment]
Closed in an issue clean up process due to missing progress and/or information.
