### ISSUE TITLE
Open new tab AND Open new link in background

### ISSUE THREAD

**Issue by calLsOLoIsNOob** [Robbendebiene/Gesturefy#109]
I miss the old FireGesture setting where you write custom scripts for gestures.

My favourite was a dual action gesture. I would swipe up and either get a new tab. Or open a link in the background.

**Comment by Robbendebiene** [comment]
Luckily this is already implemented, just check the advanced settings under the "link to background/foreground tab" action :)

**Comment by calLsOLoIsNOob** [comment]
Oh you are right. TYVM.

**Comment by Robbendebiene** [comment]
No problem!
