### ISSUE TITLE
Manage text link

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#11]
In case of a text link (see the last string) at http://www.textsnip.com/psog8f the link is not recognized also if selected.
Is possible manage also these type of action?
Thanks.

**Comment by Robbendebiene** [comment]
Thats because I implemented it only for real links. I Never thought about the text selection in this particular case, but your presented use case is persuasive so of course I'm going to implement this :)

**Comment by Robbendebiene** [comment]
Just to be sure, "selected" means, text selection/mark right?

**Comment by happysurf** [comment]
Yes exactly, in this way is possible open a text link also by Firefox context menu but in this case You need to do three operations with a gesture only two.

**Comment by Robbendebiene** [comment]
Done: dcfbf4d4724a854255a3f19ea27ba66b015dbfab will be available in the next version.

**Comment by happysurf** [comment]
Fantastic, thank you very much.

**Comment by happysurf** [comment]
An other similar problem on YouTube.
Go here: https://www.youtube.com/watch?v=CW57r5StUBA&index=3&list=RDUIstc6xdP_0
Under the video select the text link **www.hemispherestudio.com** then perform action "link in a foreground tab".
Nothing happen on Firefox 57beta + W10.

**Comment by Robbendebiene** [comment]
This is not really a bug, because www.xxx.yy is in theory not a valid URL, because the protocol is missing. However since most of the people didn't know about that, browser vendors started accepting them and implemented workaorounds.
