### ISSUE TITLE
Can not work on https://addons.mozilla.org

### ISSUE THREAD

**Issue by linuxunion** [Robbendebiene/Gesturefy#110]
It can not work on https://addons.mozilla.org

**Comment by imrn** [comment]
No addon is allowed to work on addons.mozilla.org.

**Comment by Itchiii** [comment]
You can set `privacy.resistFingerprinting.block_mozAddonManager` to `true` in about:config
For me there's not such an attitude. Others have these.
For more information look here: #6

**Comment by Robbendebiene** [comment]
Duplicate of #6
