### ISSUE TITLE
Rocker gesture Left Click almost never triggered 

### ISSUE THREAD

**Issue by gterras** [Robbendebiene/Gesturefy#111]
Hi, 

Thank you for your nice extension. I'm running FF57 on Linux and noticed the Left Click rocker gesture (meaning hold right click then left click) isn't triggered as long as the pointer hovers the FF contextual menu (which happen almost everytime). If I click and hold the right button, then move away the pointer from the contextual menu, then left click, then the gesture will be triggered. 

Is there a possible fix for this ? Thanks.

**Comment by Robbendebiene** [comment]
This is due to the different right click behaviour on Linux/MacOS. Mozilla community is investigating to fix this: https://bugzilla.mozilla.org/show_bug.cgi?id=1360278

**Comment by gterras** [comment]
Thank you for the link, hope it will get fixed one day.
