### ISSUE TITLE
Open Link Options

### ISSUE THREAD

**Issue by cfairbanks12** [Robbendebiene/Gesturefy#115]
One of the nice things on fire gestures was the ability to not just have a gesture open a link in the current tab but also have it open into a new tab or open into a new window.  It also had the ability when you opened the link to stay on the current page.  I liked this for when I was reading a news type site I could browse though and open a bunch of tabs on all the articles I wanted to read and then could come back and read them one by one.  Thanks

**Comment by Robbendebiene** [comment]
There are 2 actions called "open link to foreground/background tab" and the "open link to window" will be available in the next version.

**Comment by cfairbanks12** [comment]
Nice.  Thank you!

**Comment by Robbendebiene** [comment]
Alright, so I'm closing this :)
