### ISSUE TITLE
New tab open link

### ISSUE THREAD

**Issue by Secsen** [Robbendebiene/Gesturefy#117]
Thanks for the Gesturefly extension. I'm hoping you can add to gestures one which will open a link in a new tab and switch to it. For instance with FireGestures I could put my cursor over a link, drag down, and it would open in a new tab.

**Comment by calLsOLoIsNOob** [comment]
That sounds like "Link to foreground tab". Scroll down in the Gestures setting to find it.

**Comment by Secsen** [comment]
Yes, that’s it. Thank you. I was trying to edit the “open link” gesture.
