### ISSUE TITLE
Right button gesture open context menu and do not work.

### ISSUE THREAD

**Issue by HiddenKnife** [Robbendebiene/Gesturefy#119]
![example](https://user-images.githubusercontent.com/16657797/32976238-935a3df6-cc55-11e7-8f01-f71903466f82.png)

I'm window user. not Linux or Mac.
Right button gesture do not work, like above sreenshot.
Draw gesture and appear gesture state and pop context menu and nothing happen.

**Comment by HiddenKnife** [comment]
I find problem.
When greesmonkey stop operation, Gesturefy work correctlly

**Comment by HiddenKnife** [comment]
https://greasyfork.org/ko/scripts/23772-absolute-enable-right-click-copy
this script disrupt gesturefy.
Would you modify gesturefy?

**Comment by FlowXP** [comment]
in Linux, fresh install, doesn't work right click.
If I set it to middle or left it's ok, but can't use it like that

**Comment by lokielse** [comment]
macOS 10.12.6 

- left button is ok
- middle button is ok
- right button not woking (will open context menu)

**Comment by hyagli** [comment]
@FlowXP and @lokielse please open new issues about your right click problems. 
@HiddenKnife's problem is different.

**Comment by Robbendebiene** [comment]
Linux and MacOS user should look here: #1

**Comment by Robbendebiene** [comment]
@HiddenKnife I looked at the code and I can't do anything, because the script is running "stopImmediatePropagation" on the contextmenu event. If this happens before my event listener gets called, mine won't be called.

**Comment by HiddenKnife** [comment]
@Robbendebiene Foxygesture works correctly even if the script is turned on.
But I want to use Gesturefy. Because Gesturefy is more simple and nice.
Is there any way to fix it? plz

**Comment by Robbendebiene** [comment]
As I said, it depends on the order addons inject their scripts. FoxyGestures, Gesturefy and Greasmonkey  inject their scripts as fast and early as possible, so the first one wins, which is determined by firefox.

It might already work if you remove the `event.stopImmediatePropagation();` from the script.

**Comment by HiddenKnife** [comment]
@Robbendebiene thx.:D.

**Comment by Robbendebiene** [comment]
@HiddenKnife It worked? Nice :)
I'm closing it then.
