### ISSUE TITLE
Gestures doesn't work on the about:* pages

### ISSUE THREAD

**Issue by nxrighthere** [Robbendebiene/Gesturefy#120]
about:newtab / about:addons / about:support / etc

**Comment by calLsOLoIsNOob** [comment]
Yea I noticed that as well. Wasn't a big deal for me, messing with the addon settings isn't a everyday task. 

Didn't think new tabs would be affected though :(

**Comment by shinji2009** [comment]
README.md 

The addon does not work on https://addons.mozilla.org (for further information see this bug), pure svg pages and internal pages like about:newtab, about:addons or other addon option pages.

**Comment by nxrighthere** [comment]
I hope that Mozilla will fix this bug soon...

**Comment by shinji2009** [comment]
i think this is made for purpose for security reasons and never will be fixed

**Comment by Robbendebiene** [comment]
Duplicate of #5
