### ISSUE TITLE
Clear History - action

### ISSUE THREAD

**Issue by nxrighthere** [Robbendebiene/Gesturefy#121]
It would be awesome to have this actions like in the FireGestures:
- Browser restart
- Clear recent history

I'm also have my custom actions for the FireGestures, but they are useless now...

Open All Bookmarks window
```javascript
var organizer = Services.wm.getMostRecentWindow("Places:Organizer");

if (organizer) {
	organizer.focus();
} else {
	var places = window.open("chrome://browser/content/places/places.xul", "places", "chrome, toolbar, resizable");

	places.addEventListener("DOMContentLoaded", function(event) {
		event.originalTarget.defaultView.arguments = ["AllBookmarks"];
	});
	places.focus();
}
```

Open Downloads window
```javascript
var organizer = Services.wm.getMostRecentWindow("Places:Organizer");

if (organizer) {
	organizer.PlacesOrganizer.selectLeftPaneQuery("Downloads");
	organizer.focus();
} else {
	var places = window.open("chrome://browser/content/places/places.xul", "places", "chrome, toolbar, resizable");
	
	places.addEventListener("DOMContentLoaded", function(event) {
		event.originalTarget.defaultView.arguments = ["Downloads"];
	});
	places.focus();
}
```

**Comment by Robbendebiene** [comment]
Saldy those are not possible:
- Browser restart
- Open All Bookmarks window
- Open Downloads window

But it seems like I can delete the complete history (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history/deleteAll) or the history between a specific time range (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history/deleteRange)

**Comment by nxrighthere** [comment]
It's a shame that so many simple but very useful features can't be made with this WebExtensions API...

**Comment by Robbendebiene** [comment]
The implementation is already done but this feature needs to be delayed until this [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1458585) is resolved properly.

**Comment by Robbendebiene** [comment]
The command has been added with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
