### ISSUE TITLE
Hello again. I've come upon 2 bugs.

### ISSUE THREAD

**Issue by calLsOLoIsNOob** [Robbendebiene/Gesturefy#122]
1. For some reason I can't set DU to "Duplicate Tab". Even though there is no conflict with another gesture.

![untitled](https://user-images.githubusercontent.com/33742457/32977772-e8c30d48-cc98-11e7-907b-964f32fc461f.jpg)

2. "Close tab" only works for tabs that already have a web-page in them. They don't close a blank new tab that I just created with "Link to background tab".

Lets say I created 2 blank tabs. Then I decided, I only needed one and try to close the 2nd one. The "Close tab" gesture won't work.

**Comment by uegajde** [comment]
about the second one, it is already said in the readme and issue #5

> The addon does not work on https://addons.mozilla.org (for further information see this bug), pure svg pages and internal pages like about:newtab, about:addons or other addon option pages.

**Comment by uegajde** [comment]
for the first problem, could you check the "DU" is assigned to which action?

just enable the "Display action" and make a "DU" gesture

**Comment by Robbendebiene** [comment]
If you hover over the red field, there sould popup a message containing the action which is already assigend to this gesture.

**Comment by calLsOLoIsNOob** [comment]
Tooltip says: "This gesture is already in use by the """" action."

**Comment by Robbendebiene** [comment]
Does it work if you restore the settings? (You can do this in the About section)

**Comment by calLsOLoIsNOob** [comment]
A Reset fixed it. Thanks again.

**Comment by Robbendebiene** [comment]
Nice to hear that, I hope this won't happen again. If it does, please open a new issue.
