### ISSUE TITLE
Cancel Mouse gesture on Rocker and Wheel gestures

### ISSUE THREAD

**Issue by Eroppo** [Robbendebiene/Gesturefy#123]
I want to thank the developer of this great addon for FF57 and suggest a little improvement: if the mouse is moved while holding right button and scrolling the wheel/clicking left button, it can trigger the drawing gesture in addition to the procesing Wheel or Rocker. Please add some cancel of drawing if some another gesture is made.
Sorry for bad English, hope I made it clear))

**Comment by MusorGaming** [comment]
I run into this issue all the time.
(e.g. accidentally closing tabs when switching tabs with wheel gestures).

Is this bug hard to fix?
I would jump in and try fixing it myself, because it's really, really annoying. 

Without this bug Gesturefy would be the best mouse gestures add-on for sure!

**Comment by Robbendebiene** [comment]
I would say it's medium difficulty. I'll try to fix this in the next release which will be released with Firefox 63.

**Comment by Robbendebiene** [comment]
Available since [Gesturefy 2.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.0.4)
