### ISSUE TITLE
on-off switches in russian locale looks like #$@&%*!

### ISSUE THREAD

**Issue by shinji2009** [Robbendebiene/Gesturefy#124]
![fsvtdsgdf](https://user-images.githubusercontent.com/6340606/32978034-346ac0ec-cc6c-11e7-99f2-8622cb4d96d4.GIF)
![afsdfasdf](https://user-images.githubusercontent.com/6340606/32978035-349172a0-cc6c-11e7-9694-f91af460108d.GIF)

in english everything looks fine

**Comment by Robbendebiene** [comment]
Thanks, I will fix this.

**Comment by Robbendebiene** [comment]
Should be fixed.

**Comment by mikamiel** [comment]
This bug is still present in v1.1.15

**Comment by Robbendebiene** [comment]
You are right, for some reason it was not saved.

**Comment by mikamiel** [comment]
Yes, it's fixed now.
