### ISSUE TITLE
Copy Link to Clipboad

### ISSUE THREAD

**Issue by Dikowda** [Robbendebiene/Gesturefy#125]
A good replacement for FireGesture however there is one option that i really miss.
Would it be possible to add 'Copy link location to clipboard' to the range of gesture options?  I used this feature in FireGesture instead of having to right click on a link and clicking 'copy link location'.

**Comment by Robbendebiene** [comment]
I already implemented this, it will be avaialble in the next update :)

**Comment by Dikowda** [comment]
Great thanks!

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/94de6b8f863006ea53231c31fed272ae4e630050
