### ISSUE TITLE
How to save gestures?

### ISSUE THREAD

**Issue by YvesFranklin** [Robbendebiene/Gesturefy#128]
Hello

I cannot find how to save gestures I defined in thes Gestures page. So I lose it as soon as I go back to web pages. How to do it?

Yves

**Comment by Robbendebiene** [comment]
They are saved automatically, so you should not lose them.

**Comment by YvesFranklin** [comment]
They are not. They stay in red color and are not applied.

**Comment by Robbendebiene** [comment]
This is because the gesture is not valid. Mouse over the red field and you will see a little popup. (My guess is that it is already used by another action)
