### ISSUE TITLE
Adds stray right gesture

### ISSUE THREAD

**Issue by jazzba1** [Robbendebiene/Gesturefy#133]
When reading comments (say after a news story), and your mouse is over someones comment, it adds a gesture on its' own in front of the one you are doing.

**Comment by Robbendebiene** [comment]
I need more information about this. I guess this happens on a particular website? Can you also make a screenshot of whats going on?

**Comment by jazzba1** [comment]
http://tinypic.com/r/2ry0ks5/9
http://tinypic.com/r/j7dcwk/9
...so the 45degree line pops in every time,(and adds as a gesture) say if I want to scroll up .
Many websites......in the comment area.
Win 10...Performance Mouse MX - Rechargeable Wireless Mouse - Logitech

**Comment by jazzba1** [comment]
issue  #105 sounds like a similar issue as mine.

**Comment by Robbendebiene** [comment]
Maybe your problem is also related to this one: https://github.com/Robbendebiene/Gesturefy/issues/130 ?

**Comment by jazzba1** [comment]
yes it is

**Comment by Robbendebiene** [comment]
Should be fixed in the latest version.
