### ISSUE TITLE
OneTab gestures

### ISSUE THREAD

**Issue by Guttts** [Robbendebiene/Gesturefy#135]
I like https://addons.mozilla.org/en-US/firefox/addon/onetab/ a lot. I use it frequently, but it is a chore to right click and move through the menus to make it do what I need and sometimes I need to do it for several tabs individualy in a row. Gesture would be much easier.

Is it please possible to include gestures that would fire actions of this addon? Or allow custom codes and then I would ask for some tips how to write it as I didnt manage that in firegestures and OneTab guys never replied to me.

Im looking for gestures for these actions:
Send only this tab to OneTab
Send tabs on the right to OneTab

Thanks for your addon and any help

**Comment by Robbendebiene** [comment]
If OneTab supports commands for other addons it would be possible in theory. But since it's not open source I don't know. I also have to admit that it's not very high in priority, because of the large amount of feature request and my lack of time.

**Comment by Robbendebiene** [comment]
Closing due to missing information.
Triggering external addon functionality is tracked here: https://github.com/Robbendebiene/Gesturefy/issues/238
