### ISSUE TITLE
Open custom (predefined) link/URL in a new tab

### ISSUE THREAD

**Issue by mikamiel** [Robbendebiene/Gesturefy#139]
Default new(empty) tab in Firefox does not allow gestures on it, that's why it would be great to have a gesture with an action "Open custom (predefined) link/URL in a new tab".
Besides that, this action would be helpful if we want to attach several different links to several different gestures.

**Comment by Robbendebiene** [comment]
Some time ago, this was already requested and I recommended https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/, because it provides a more consistent solution than I could do.

**Comment by mikamiel** [comment]
Thanks, it solved my issue, but anyway i'd like to see this feature in Gesturefy ;)
