### ISSUE TITLE
Open link in background doesn't respect child order

### ISSUE THREAD

**Issue by stmr** [Robbendebiene/Gesturefy#14]
Hi,
using Open link in background doesn't behave the same way as opening through right click -> open in new tab.
Expected behaviour: As long as I stay on the page I'm opening the links from, open each of them to the right of the current latest child. When I switch tab and come back, start over.

Typical use case: You have a gallery of images without lightbox (basically just img elements with links) and you want to open them all in new tabs, but respect the sequence.

Hope you are doing well, keep up the amazing work! :)

**Comment by Robbendebiene** [comment]
You are right :)
Even if I could implement a workaround by my self, I would prefer to wait untill mozilla "fixed" this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1238314
because the workaround would be to messy compared to the gain of functionality.

**Comment by stmr** [comment]
Aw ok, didn't know about that :) Thanks!

**Comment by stmr** [comment]
Bug is now fixed! Yay!

**Comment by stmr** [comment]
This and https://github.com/Robbendebiene/Gesturefy/issues/53 are related? Would be nice to have option even for this one, but I guess it takes quite some time.

**Comment by Robbendebiene** [comment]
@stmr This issue can be closed soon with version 1.1.10, but it will only be available for firefox 57 or later. What options are you thinking about?

**Comment by stmr** [comment]
Many! :D
First of all respecting child order to match behaviour of middleclicking a lot of links from one site (until you leave the tab that's opening links, put the new tabs to the right of parent/last-child)
Then an option to switch this off to behave like it does today (last opened link as the first tab to the right).
More when it comes to closing, but that might be for the https://github.com/Robbendebiene/Gesturefy/issues/53 like when closed, select parent tab, when closed, select right/left tab.
I can also imagine a scenario when it could be handy to have option or separate gesture to behave in opposite direction, opening children as previous tabs (in opposite direction on the tabbar) and when closing, selecting tabs to through the children first (I know that some actions are duplicated in this post, for me the default FF behaviour when using mouse is all I need, now I'm just throwing ideas I've seen in other browsers and stuff)

**Comment by Robbendebiene** [comment]
I guess the FF default behaviour is the prefered way. So due to my laziness, I'll only add these settings if somebody is really requesting them :D

**Comment by stmr** [comment]
Yes please, that's the only thing I miss in WebExtensions era. I think an option to shut the child order off to match the current behaviour would be also great for some and "cheap" to implement.
You're the best!

**Comment by Robbendebiene** [comment]
I agree, but this will have to wait for the next version. (1.1.11)

**Comment by Robbendebiene** [comment]
Done:https://github.com/Robbendebiene/Gesturefy/commit/021a1f2b47a261a559b282195d838418823dd9b9
