### ISSUE TITLE
Linux - Right button gesture open context menu and do not work.

### ISSUE THREAD

**Issue by FlowXP** [Robbendebiene/Gesturefy#142]
Linux OS
    left button is ok
    middle button is ok
    right button not woking (will open context menu)

**Comment by dsrdan** [comment]
Me too.
LMDE2.
right button not woking (will open context menu)

**Comment by AlexVonB** [comment]
FYI this is known to Robbendebiene, see https://bugzilla.mozilla.org/show_bug.cgi?id=1360278#c61
But I +1 this issue, too.

**Comment by jerryjune** [comment]
This should not the firefox bug, it is platform difference. you can use double click to open right contex menu on mac or linux platform. other mouse gestures are all use this way.

**Comment by alexivkin** [comment]
@jerryjune, it is a firefox bug (handling right on mouse down, not mouse up), and it's been committed to the latest trunk. The option to switch mouseup/mousedown will show up in the v59 - it will be called ui.context_menus.after_mouseup
See https://github.com/Robbendebiene/Gesturefy/issues/1

**Comment by HellebardeFox** [comment]
Hello Robbendebiene,

I accidentally triggered the right-click behaviour, yesterday. It could be a possible solution. At least as long Firefox doesn't change.

– Linux Mint 18.2, Firefox 57
– I have installed the Gesturefy-add-on set with right-click
– on website https://dev.twitch.tv/extensions, I accidentally right-clicked the video
  (screenshots on imgur: https://imgur.com/a/1Rxbm)
– the video is embedded in an iframe
– maybe there is a time-racing going on between right-click and iframe-something
– the drawing canvas inside the "div" with "z-index:1999999999" stays sticky
– the drawing disappears sometimes over time (seconds), opening the Firefox-Dev-Tool, clicking randomly or reloading the site

I know it is a kind of a glitch. But it could be used to solve/bootstrap the right-click problem after closer inspections.

Good luck.

**Comment by Robbendebiene** [comment]
I recommend every Linux / MacOS user using the latest Gesturefy version (1.1.17) and Firefox 58 beta (58 b7). Everything should work finde since this version.

**Comment by godliu** [comment]
Hi,
I'm sorry about send questions on there. But I couldn't find macOS thread.

On my iMac/FF58/Gesturefy version (1.1.17) is still not working. When I update FF58, Gesturefy working. But a few minutes later, its connot drow the line.

How can I do this?

**Comment by Robbendebiene** [comment]
@godliu Hey, please provide more detailed information. Otherwise I cannot help you, since I'm not able to test it on MaxOS by my self. 
- How long is "a few minutes later"?
- Does it always work when you start the Browser but stop working over time?
- Does it only stop working on particular websites?
- Are there other addons that may conflic with Gesturefy?
- What happens when you try to draw a line, does the context menu immediately pops up?
- Do gestures work If you set the mouse trigger button to middle or left mouse button?

**Comment by godliu** [comment]
@Robbendebiene Hello. Thank you for your support. I tried to re-install addon and then all become working well.
Thank you for your help.

**Comment by Robbendebiene** [comment]
Since Firefox 58 became stable some days ago I'm closing this issue.
