### ISSUE TITLE
Include option to have "Save Image" use the regular filename

### ISSUE THREAD

**Issue by NicholasFechner** [Robbendebiene/Gesturefy#143]
Currently, "Save image" creates its own filename which includes the domain and path. It would be cool, if you could inlcude an option to keep the original filename.

**Comment by Robbendebiene** [comment]
I will make this the default and try to upload this today (including a little fix for save image)

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/a50c474aba6c181e4b7f3a51c9079018187d308c
