### ISSUE TITLE
Remember last directory for "Save image" action

### ISSUE THREAD

**Issue by terryinflorida** [Robbendebiene/Gesturefy#145]
I am very thankful for the work you are doing on this addon, thank you.

The issue or request I am having is that when using your "save image" it opens to the desktop. 

I have folders and subfolders and I save pictures to a few different folders. I am a hobby photographer and get my ideas mainly from the internet, so I will save lots of photos, be it outdoor, indoor, variations of light, dark. I try to categorize everything... When I am looking for a certain aspect of photography I usually try to stick to one type of photo, so I usually will stay in that one certain folder but that folder may be 5 clicks from my desktop, lol... 

When I use the firefox "save image" after I tell it where to save an image it will open that folder the next time I want to save an image. It opens to the last folder saved to... 

I don't know if its possible to have the Gesturefy addon mimic this or not but it would be extremely helpful....

Right now I find myself right clicking the image and using the firefox "Save Image" just so I don't have to find my buried folder... 

I am getting used to the "Image to tab"...

Thank you for your work on this and the other functions...

**Comment by ricetrippycreeps** [comment]
This is a bug I would most liked resolved.  I do a lot of image/file saving in various folders as well, and being able to save files to the last known folder location really ramps up my efficiency.

**Comment by Robbendebiene** [comment]
I have no idea why it opens the desktop folder as default. The documentation says it should always open the downloads folder (which it does for me). However I noticed another bug, when saving for example your github avatar, it will create 2 folders. I guess this is because of the missing fileextension (I should be able to fix this).

> When I use the firefox "save image" after I tell it where to save an image it will open that folder the next time I want to save an image. It opens to the last folder saved to...

I might be able to mimic it by searching through your download history for the last item you've downloaded. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/search

**Comment by Robbendebiene** [comment]
After digging through the api, I have to say that it's not possible, neither in chrome nor in firefox. I can easily get your last download directory, but I'm not allowed to set it for security reasons.

**Comment by ricetrippycreeps** [comment]
I have the Desktop set as the default location for saved files, so it's essentially defaulting to the downloads folder every time.

**Comment by Robbendebiene** [comment]
For more Infor please read this: https://bugzilla.mozilla.org/show_bug.cgi?id=1394851 (it's already in FF 58)

**Comment by terryinflorida** [comment]
It is not possible to direct it to implement firefoxes "Save As"?

**Comment by Robbendebiene** [comment]
> Would it be possible to implement the keystroke shortcut with a gesture?
> 
> Would it be possible to create a gesture to implement keystroke shortcuts?

This is not possible with webextensions.

**Comment by xxvii** [comment]
Hello,
given that the bug in  https://bugzilla.mozilla.org/show_bug.cgi?id=1394851 seems to be fixed, what is missing now to consent the development of this feature?

**Comment by Robbendebiene** [comment]
@xxvii The bug I've mentioned does not solve the problem. It was just an example and clarified another problem that occured.

If you want this feature to happen you need to open a feature request/bug on bugzilla.
You could name the ticket like this: `Webextensions download API "save as" preference should open the last directory if not specified`

Btw it's always good to mention that Chrome already behaves like this :)

**Comment by Robbendebiene** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1395207 this is fixed in Firefox 78.

**Comment by xxvii** [comment]
Looking forward to see this long awaited feature working again!

**Comment by Robbendebiene** [comment]
I've just tested this with Firefox 78 and it's working now. So I'm closing this, since this will be automatically solved with the next Firefox release.
