### ISSUE TITLE
CANT DISTINGUISH...

### ISSUE THREAD

**Issue by fuorigioco1981** [Robbendebiene/Gesturefy#147]
this add on cant distinguish between undo close tab(restore last closed tab) and new tab.because i map undo close tab with "right left" and new tab with " left right"
any help?

**Comment by Robbendebiene** [comment]
Sorry, I do not understand your problem. If you want to use "left right" for the new tab action, just delete the "left right" gesture for the undo close/restore action.

**Comment by fuorigioco1981** [comment]
in fire gestures we can have "left>right" gesture AND at the same time "right>left" gesture.
in your add on only one of these can happen.can we have both ?

**Comment by fuorigioco1981** [comment]
in foxy gestures also we can have both.can you make it in your add on?

**Comment by Itchiii** [comment]
If you want for undo close tab (restore last closed tab) "right-left" than delete "right-left" on the action 'close tab' and then specify "right-left" for restore-action. 
Or you mean you want two gestures for one action?

**Comment by fuorigioco1981** [comment]
![capture76](https://user-images.githubusercontent.com/33813539/33057557-3e0eabf2-ce94-11e7-8921-301ae13f54eb.JPG)
in foxy gestures.in your add on i assign the same 2 gestures but ONLY one works!(maybe because your app thinksits the same gesture?)

**Comment by Itchiii** [comment]
It works for me.
If a gesture has a red background, it's double and you have to delete that other one.

That works!
![gesturefy](https://user-images.githubusercontent.com/15103402/33060296-12454b58-ce98-11e7-837e-ac4d91c3ff27.PNG)


Here, you have to delete >Remove tab<
![gesturefy2](https://user-images.githubusercontent.com/15103402/33060289-0db052cc-ce98-11e7-9a39-2304c2880264.PNG)

**Comment by fuorigioco1981** [comment]
![capture](https://user-images.githubusercontent.com/33813539/33067932-616df03e-ceb8-11e7-9a55-2edca552c377.JPG)
yes i have it like that .but doesnt work.it works for you?

**Comment by fuorigioco1981** [comment]
ok close the case finally i made it work!thanks for your answers!
