### ISSUE TITLE
embedded Youtube videos while fullscreen.

### ISSUE THREAD

**Issue by ricetrippycreeps** [Robbendebiene/Gesturefy#148]
I noticed that while viewing an embedded Youtube video in fullscreen mode, gestures do not work.  It works fine on a fullscreen video viewed directly on Youtube though.

**Comment by stmr** [comment]
Can confirm this issue on sites where youtube is emmbeded in iframe

**Comment by Robbendebiene** [comment]
Since version 3.0.0 this should no longer be a problem. And with version [3.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.4) even the gesture trail and name should be visible.
