### ISSUE TITLE
Open specific URL

### ISSUE THREAD

**Issue by extragoofy** [Robbendebiene/Gesturefy#151]
I was a FireGestures user before and I enjoyed the feature to enter custom code for a gesture very much.

Specifically, I used this feature to open a pre-defined URL (like Youtube) in a new tab and switching to that tab immediately. It would be amazing if you could enable this feature.

You're doing great work, keep it up!

Cheers

**Comment by Robbendebiene** [comment]
Added in [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0)
