### ISSUE TITLE
Gesture to open Gesturefy settings

### ISSUE THREAD

**Issue by NLZ** [Robbendebiene/Gesturefy#152]
Would it be possible to have a gesture for opening the Gesturefy settings?
Or are the moz-extension: pages privileged like about:, meaning they cannot be opened, as mentioned in #64?

**Comment by Robbendebiene** [comment]
This is easily possible thanks to the [openOptionsPage()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/openOptionsPage) function.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/2a083dd37828aabfe7aa7c42ea4455b66bcc3f3b
