### ISSUE TITLE
Action on save image to last dir

### ISSUE THREAD

**Issue by paul3333** [Robbendebiene/Gesturefy#154]
in my Firefox about:config set the
browser.download.lastDir.savePerSite = false

so all save as action is go to last used dir
but when i draw an action on image to download, the save as location is to default download folder
when i right click on image , select save as from the context menu, is go to last dir
so the action of context menu is correct
the draw action is hardcoded to default download folder
can i change it to last dir ?

**Comment by Robbendebiene** [comment]
Please see this issue: #145

**Comment by Robbendebiene** [comment]
Duplicate of #145
