### ISSUE TITLE
"close tab" does not work always

### ISSUE THREAD

**Issue by derStephan** [Robbendebiene/Gesturefy#157]
Hi,

just switched from fireGestures to Gesturefy. I am using "down" to close the current tab. 

But this does not work with some tabs. Some examples: 

- https://addons.mozilla.org/de/firefox/
- about:preferences
- about:addons

In my opinion, this should work regardless of the content of a tab.

**Comment by uegajde** [comment]
please read the readme, description on AMO or #5 #6 

it is really impacted by the content of a tab.
WebExtension is different from previous API in the concern of security and compatibility. 
As a result, addons now cannot access Firefox internal things and protected website (such as AMO)

**Comment by derStephan** [comment]
Oh, I see. Sorry for the noise. 

May I suggest to add this information to the addon description?

**Comment by uegajde** [comment]
It is already there, although the reason is not clearly explained.

https://addons.mozilla.org/en-US/firefox/addon/gesturefy/
> Limitations / Problems:
>     The addon does not work on https://addons.mozilla.org (for further information see this bug), pure svg pages and internal pages like about:newtab, about:addons or other addon option pages.

By a way, this condition very meets your avatar, "your freedom is sacrificed for security" WWW
very interesting :)

**Comment by uegajde** [comment]
ps. there is a workaround for AMO
set` privacy.resistFingerprinting.block_mozAddonManager` to `true`

**Comment by derStephan** [comment]
>It is already there, 

Oh, I did not see this. Genius idea by mozilla to hide the description of an addon. 

>although the reason is not clearly explained.

That sounds as if this is the addon's fault but it's just not. 

>ps. there is a workaround for AMO
>``setprivacy.resistFingerprinting.block_mozAddonManager to true``

Is there a way to set this while installing/updating the addon? I am asking despite already knowing the answer.

**Comment by uegajde** [comment]
I am not sure.

WebExtension cannot access to preferences in principle.
(see [Does the WebExtensions API provide access to preferences?](https://wiki.mozilla.org/WebExtensions/FAQ#Does_the_WebExtensions_API_provide_access_to_preferences.3F)

However, there are some exceptions. For example, both uBlock and Decentraleyes can modify `network.predictor.enable-prefetch`
(with https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/network)

**Comment by derStephan** [comment]
Let's see what the next versions of firefox will bring. I do not think that all these changes in the API are already over. But I fear that it won't get any better. 

Thanks anyway. Keep up hope!
