### ISSUE TITLE
I am very missing rocking gesture "Skip to the left tab" and "Skip to the right tab".

### ISSUE THREAD

**Issue by ondrejlangrrr** [Robbendebiene/Gesturefy#160]
Please, can you create this gestures? I was using them so much in Firegestures and now they are missing me.

**Comment by Robbendebiene** [comment]
Sorry, I don't understand what the gesture is supposed to do. Which "panel" are you talking about?

**Comment by ondrejlangrrr** [comment]
I am sorry, wrong translation to english. I mean "tab".

Switching left-right witch rocking gestures between the tabs was the best feature in original Firegestures.


![bez nazvu](https://user-images.githubusercontent.com/33865498/33080739-17c8550c-ced9-11e7-8064-5a634f69720b.jpg)

**Comment by mikamiel** [comment]
Do you mean rocker gestures to switch to previous/next tab? They are already implemented, you can find them in the settings, section "More" marked with a star symbol.

**Comment by ondrejlangrrr** [comment]
No, I don't think this gesture. This gesture works only sometimes (I don't know why. Maybe in order of opening?). I need possibility to switch between all of tabs, it is very useful, quick and user-friendly if I work with a large number of tabs.

**Comment by ondrejlangrrr** [comment]
Oh, maybe I understand :( Gesture Fly does not work on any kind of tabs :( This is bad. Very limiting. Can you fix it?

**Comment by Robbendebiene** [comment]
@ondrejlangrrr As stated in the addon description and in a lot of other issues, this cannot be fixed. At the end it should work on most of your tabs unless you are only using about:, webextension: or mozilla addons pages.
