### ISSUE TITLE
Linux/Mac - toggling the option for right click context menu + right click mouse button in options

### ISSUE THREAD

**Issue by stmr** [Robbendebiene/Gesturefy#161]
Hi,
since right click behaviour is fixed in the nightlies starting from today's (21/11) version, I'd suggest Gesturefy toggles the "ui.context_menus.after_mouseup" when enabled/disabled.
Also if the changing succeeds, the "gesture mouse button" in Gesturefy's settings should be changed to "right".

**Comment by Robbendebiene** [comment]
Hey and thanks for your huge participation in this topic! As far as I know I'm still not able to change this option. At least webextensions are not allowed to change any preference in the about:config.

**Comment by stmr** [comment]
I saw you have such a huge amount of issues so I wanted to help somehow 😄 
changing the preferences should be possible through webextensions as https://bugzilla.mozilla.org/show_bug.cgi?id=1360278#c36 says.
But he spoke about some preferences in different API's being exposed to WE and I'm not sure if this one is exposed aswell.

**Comment by Robbendebiene** [comment]
@stmr Yeah, I'm drowning in issues :D

> changing the preferences should be possible through webextensions as https://bugzilla.mozilla.org/show_bug.cgi?id=1360278#c36 says.

Right I remember that, but no one ever mentioned it again, so I thought they only implemented the about: preference.

**Comment by stmr** [comment]
Oh yeah, looks like that, will try to write there again or create a separate bug for it.

**Comment by stmr** [comment]
Great, looks like it could make it to 58, maybe even with exposed pref :)

**Comment by GSF1200S** [comment]
Fix is already backported on Arch. Firefox 57.0-2 contains the about:config preference "ui.context_menus.after_mouseup" works as it should. I think OpenSuse has backported an earlier patch as well. Not sure on other distros

**Comment by stmr** [comment]
There is a bug about exposing this setting to WE, you can track it here https://bugzilla.mozilla.org/show_bug.cgi?id=1419426
It looks very promising!

**Comment by Robbendebiene** [comment]
Hm, I thought they wanted to uplift this property to 58 but it says "Target Milestone: --- → mozilla59"

**Comment by stmr** [comment]
I think the property made it to 58 but exposing made it only to 59 (so far, I think it's waiting for someone to review it for uplifting)

**Comment by stmr** [comment]
It got uplifted so both the option and the ability for WE to change it are fixed

**Comment by Robbendebiene** [comment]
@stmr Yep. I'll update the addon when they release the next beta version which contains the option.

**Comment by Robbendebiene** [comment]
Should be working now, even though I'm currently not disabling the property if the user decides to use another mouse button.

**Comment by Robbendebiene** [comment]
Since this option is also necessary for wheel and rocker gesture, it's currently always enabled whether or not you are using the right mouse button in any way. If someone really needs the default context menu behavior please open a new issue.
