### ISSUE TITLE
Gestures Should Function On Any Tab

### ISSUE THREAD

**Issue by rcorlfl2808** [Robbendebiene/Gesturefy#162]
Gestures seem to be limited only to tabs that have completed a call to a web page.

For example, if a 404 page is popped, the close gesture will not work to delete the tab.  Same thing goes for system tabs, and even the home page.  FireGestures was able to do this, and since this is the only available replacement, many users have to be missing this functionality.

**Comment by uegajde** [comment]
you are not alone. But this problem is not addon's fault.
WebExtension based addons cannot access Firefox internal things and protected website (such as AMO)

please read the readme, description on AMO 
and it is already discussed before. #5 #6 #157 and more :P

**Comment by suhr** [comment]
If there's New Tab Override, why can't gestures work on new tabs?

**Comment by Robbendebiene** [comment]
Because there is a special [manifest property](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/chrome_url_overrides) to do this.

**Comment by suhr** [comment]
By the way, I installed New Tab Override and set the new tab to `about:newtab`. It did this effect:

- The new tab page is now blank
- Gesturefy works on the new tab page

I have no idea why it works, but I pleased with the result.

**Comment by Robbendebiene** [comment]
> By the way, I installed New Tab Override and set the new tab to about:newtab. It did this effect:
> 
>     The new tab page is now blank
>     Gesturefy works on the new tab page

Interesting, this sounds like "about:blank" which is the only about page where Gesturefy works. Maybe NewTabOverride changed your input internaly to about:blank, because technically it should not be able to open about:newtab.
