### ISSUE TITLE
Add "go to the first \ last tab"

### ISSUE THREAD

**Issue by YuriiBar** [Robbendebiene/Gesturefy#163]
Is it possible to?
Thank you

**Comment by sanon** [comment]
Yeah, especially "last tab" is frequently used I think. After opening multiple links (like from Reddit etc.) you want to navigate to the last one and then come to the initial tab by closing them one by one.

**Comment by memiarz** [comment]
Adding "go to first/last tab" gestures would be great.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/2a083dd37828aabfe7aa7c42ea4455b66bcc3f3b
