### ISSUE TITLE
Rocker Gesture - Scroll to the top/bottom

### ISSUE THREAD

**Issue by Sopor-** [Robbendebiene/Gesturefy#166]
I have set the Rocker gesture to scroll up and down and now suddenly (i believe it was after latest update) it won't work. Both gestures do the same thing, scroll up even if i have it set like this:
Left mouse click = up
Right mouse click = down
I'm running Gesturefy 1.1.9 and Firefox 56.0.2 (I don't want to update to version 57 until i have found replacements for all my old extensions), but i was able to install it on version 56 so it should work.

**Comment by Robbendebiene** [comment]
Sorry I'm not supporting older versions of Gesturefy anymore. However you can install the latest Gesturefy version even if it is marked incompatible). The only downside will be, that some of the new actions/settings won't work. You can also try resetting the addon (gesturefy settings > about)
