### ISSUE TITLE
Gesture distance threshold and Gesture sensitivity have no unit

### ISSUE THREAD

**Issue by Sopor-** [Robbendebiene/Gesturefy#167]
`Gesture distance threshold` and `Gesture sensitivity` have no unit. Is it minutes, seconds or milliseconds?

**Comment by jdreesen** [comment]
The descriptions are `The minimum mouse distance until the Gesture gets activated.` and `The minimum mouse distance until a new direction gets recognized. This will also impact the trace smoothness.` so I think it's `px` (pixels).

**Comment by Sopor-** [comment]
Sorry @jdreesen, i was thinking of something else. I mean if it was px, cm or anything else :)
