### ISSUE TITLE
Minimized to Full Screen

### ISSUE THREAD

**Issue by konjdall** [Robbendebiene/Gesturefy#168]
After I minimized from full screen then returned to Firefox again, The fullscreen gone to window mode. Firegestures had had this return option succesfully you can look up their code I think.

**Comment by Robbendebiene** [comment]
> Firegestures had had this return option succesfully you can look up their code I think.

The code doesn't help, because the whole API changed and as far as I know, there is no way to "fix" this.
For more information you can follow this issue: #112 it's kind of related to this one.

**Comment by Itchiii** [comment]
I will close the issue because the issue is duplicated or related to #112
