### ISSUE TITLE
Distinguishing gestures starting on empty space and on links

### ISSUE THREAD

**Issue by sanon** [Robbendebiene/Gesturefy#169]
Hi,

If it's possible can you please make your extension distinguish gestures that start from an empty point on the page and that start from a link so it's possible to set the same gesture for different actions if this is the case. 
Example: I want to use UP for "new tab" and also for "open link in a new background tab". 
Even if these seem to be the same gesture; the first one starting from an empty point on the page and the other one starting from a link should seperate them IMO. 
Thanks...

**Comment by Robbendebiene** [comment]
> Example: I want to use UP for "new tab" and also for "open link in a new background tab".

Please check the "Advanced settings" under the "tab to background/foreground" action.

**Comment by sanon** [comment]
Yeah, I have seen that already... But that opens the new tab as a background tab... I need this gesture to open a new foreground tab if started on an empty point, otherwise the link as a background tab.

**Comment by Robbendebiene** [comment]
We decided that this feature is too specific wherefore we won't implement it. However It will be possible sometime in conjunction with user scripts or when #238 is implemented.
