### ISSUE TITLE
Hybrid gesture for new tab and link to foreground tab

### ISSUE THREAD

**Issue by mattcoz** [Robbendebiene/Gesturefy#17]
FireGestures supported a single hybrid gesture for either opening a new blank tab or opening a link in a new tab. Gesturefy makes you use different gestures.

**Comment by Robbendebiene** [comment]
I agree that this would be a usefully combination. The only thing I'm struggling with is, if I implement a new gesture or change the behavior of the LinkToBackgroundTab and LinkToForegroundTab to open an empty tab if no link was "selected".
Btw, are you sure that FireGestures supported this? At least I wasn't able to find it after a quick look at it.

**Comment by stmr** [comment]
Also, what if you'd like to open the link and just miss it? 😄

**Comment by Robbendebiene** [comment]
Good point. I guess I will add a new hybrid gesture.
Maybe this gesture could also be able to open images in a new tab?
The question is, if there is a link on an image, what will it open? I guess the link would be the desired way, so it would look like this: open link in new tab > open image in new tab > open new empty tab. Any concerns?

**Comment by stmr** [comment]
Sounds good, the question is - will the separated gestures be still there?

Could be a nice idea (but I guess hell to implement) to have the ability to create hybrid gestures from the simple ones. Like "Create multi/hybrid-gesture" button and then drag and drop with ordering of importance like you wrote in the previous post (link new tab > image new tab > new tab).
But that's possibly impossible :)

**Comment by Robbendebiene** [comment]
Of course I will always keep the separated gestures :)

To hell with you! This idea is so good that I even think about taking the effort :D
The only concern I have is, that it is quite useless for the most of the actions/gestures, because nearly all of them are always "feasible" and therefor it would only make sense for gestures like open link, image or search in new tab. :|

**Comment by Robbendebiene** [comment]
Since Gesturefy 1.1.9 there is an option for the "open link to tab" actions, which gives you the opportunity to open an empty tab if no link was selected. (https://github.com/Robbendebiene/Gesturefy/commit/4c208b51d698981648d74fc90d2bc588f13c1bba)
