### ISSUE TITLE
Return to Previous Selected (used/active) Tab?

### ISSUE THREAD

**Issue by memiarz** [Robbendebiene/Gesturefy#171]
Is it possible to add this gesture?

I miss it very much. Before Firefox Quantum I used **All-In-One Gestures** addon, and it worked like a charm there.

**Comment by Robbendebiene** [comment]
Yes this is possible. I'll try to add this in the next version.

**Comment by memiarz** [comment]
Great, can't wait :)

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/2a083dd37828aabfe7aa7c42ea4455b66bcc3f3b
