### ISSUE TITLE
Gesturefy clone?

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#174]
This morning I see this extension on AMO called "**Gesture for Firefox**" but is perfectly the same of Gesturefy.
https://addons.mozilla.org/en-US/firefox/addon/gesture-for-firefox/
Same description and same screenshots.
Whats happen?

**Comment by uegajde** [comment]
i even can find some "Gesturefy" in the "About this extension" :rage:

**Comment by Robbendebiene** [comment]
Thanks for the report! This is literaly pure copy and paste. Even if my addon is open source, he is not allowed to publish it in the way he did it. If you check his other addons you will ntoice that they are clones too.

**Comment by happysurf** [comment]
Incredible, is possible click on "Report this add-on for abuse"...

**Comment by Robbendebiene** [comment]
I reported it yesterday to mozilla, let's see what will happen.

**Comment by rodalpho** [comment]
AMO removed it-- quick response! Very impressed.

**Comment by Robbendebiene** [comment]
@rodalpho Thanks for letting me know.
