### ISSUE TITLE
"Open the home page" gesture  : NOT Works like the home page button.

### ISSUE THREAD

**Issue by HPSysteme** [Robbendebiene/Gesturefy#176]
Hello,
Thank for your addon but i want just to notice an little bug about "Home gesture" :
you write "Works like the home page button." but is false. 

My home button go to "_Quick dial_" addon ( in option linked to a home page like "moz-extension://...") 
But when i do "home gesture"  firefox go on firefox's defaut page, so your addon dont read my homepage choice.

**Comment by uegajde** [comment]
it is like the home page button, but is not a home page button
it opens the link in the Gesturefy's settings (default to be about:home) (instead of what's in the Firefox's settings)

you can modify it
just click the "advanced settings" below the "open homepage", and you will see the input box

**Comment by HPSysteme** [comment]
Thank for this fast reply ^^
But really why dont use preference of Firefox ?

**Comment by uegajde** [comment]
because WebExtension based addons cannot access to Firefox's preferences as usual.
this function is sacrificed for security.

https://wiki.mozilla.org/WebExtensions/FAQ#Does_the_WebExtensions_API_provide_access_to_preferences.3F

**Comment by uegajde** [comment]
i found a API can read (only read) the URL currently set as the browser's homepage.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/homepageOverride

**Comment by Robbendebiene** [comment]
@uegajde Yep, I thought about implementing it, but if it's set to a local file, I'll still experience problems, I guess.
