### ISSUE TITLE
Feature request: Save Link As…

### ISSUE THREAD

**Issue by protist** [Robbendebiene/Gesturefy#178]
I may have missed it, but I'd like to assign the action `Save Link As…` to a gesture. This is the action available in the context menu after right-clicking a link.

**Comment by leonard84** [comment]
Please add this crucial guesture, its the only one I'm missing while transitioning from FireGuestures.

**Comment by Robbendebiene** [comment]
@leonard84 Yes, this should work in the most cases. However (similar to the "Save Image" action) I'm not able to get the right file extension, so you would have to set it manually.

**Comment by leonard84** [comment]
@Robbendebiene I thought the browser takes care of it, if you omit the `filename` https://developer.chrome.com/extensions/downloads#method-download

**Comment by Robbendebiene** [comment]
Maybe chrome does, but Firefox does not. Normally [`onDeterminingFilename`](https://developer.chrome.com/extensions/downloads#event-onDeterminingFilename) is the way to go, but currently Firefox does not support it.

**Comment by protist** [comment]
I'm not sure if helpful, but [Foxy Gestures](https://github.com/marklieberman/foxygestures) can assign a gesture to `Save Link As`. There might be something in their code that is useful.

**Comment by Robbendebiene** [comment]
I'll add this command soon. Even though the problem I mentioned above still exists.

**Comment by Robbendebiene** [comment]
Available in Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0)

**Comment by protist** [comment]
Thank you! Works very well.
