### ISSUE TITLE
Ability to use the same gesture for multiple different actions

### ISSUE THREAD

**Issue by KES777** [Robbendebiene/Gesturefy#180]
I have configured this as next:

http://joxi.ru/Y2L4GQ0inzdaj2

Also I leave untouched this:

http://joxi.ru/brRjbK6HQD3xer

When I press left mouse button on the link and move mouse up/down the page is scrolled up/down

instead of expected open the link in new foreground/background tab

**Comment by KES777** [comment]
It seems you do not distinguish two cases:

1. When I drag mouse from empty space/or just text
2. When I drag mouse from link

**Comment by uegajde** [comment]
actually, you can not assign two or more actions to a gesture
it should be one to one

i guess that removing the assignment of "scroll to top/bottom" can solve your problem

**Comment by KES777** [comment]
I can. My recent gestures work in this way. Why your gestures can not do the same? I think this is not hard to distinguish those two specified cases.

**Comment by Robbendebiene** [comment]
There are too many problems with this concept, even though I would like to implement it. Just to name two of them: action priority (which action should run if both actions are possible), action success detection (for a lot of actions it's unsure if they will succed or not / if they succeded or not)

**Comment by KOTRET** [comment]
@Robbendebiene imho for this case the priority is clear, as the link is more specific than a general page-action.

**Comment by paoloantinori** [comment]
Hi, I'd really like to see this implemented.
@KOTRET  describes what was the logic in FireGestures and even in all the implementation that inspired these tools, running back to the first versions of Opera Browsers.

I can't comment on the "action success detection" but I agree that yeah, if you are on a specific element (url, image, whatever_you_want_to_support) that takes the precedence over other actions.

**Comment by Robbendebiene** [comment]
Since this has too many problems I'm closing this. Those who are interested in hybrid gestures can look here: https://github.com/Robbendebiene/Gesturefy/issues/313
