### ISSUE TITLE
Selecting text works as action

### ISSUE THREAD

**Issue by KES777** [Robbendebiene/Gesturefy#181]
When I try to select text it works as action.

1. Press left button on the page
2. move mouse left
3. Release button

**Comment by Robbendebiene** [comment]
I suppose you've set the mouse gesture button to the left mouse button. You can change it to another button or use one of the supression keys (be aware though if you are on Linux or MacOS you will need Firefox 58 beta to get the right mouse button working)

**Comment by KES777** [comment]
No I did not set. It seems by default.

ok. thank you
