### ISSUE TITLE
Feature request - Minimize to tray

### ISSUE THREAD

**Issue by Ninjo79** [Robbendebiene/Gesturefy#182]
Minimize FF57 to tray. 
Is it possible?

**Comment by Robbendebiene** [comment]
There is an action called "Minimize Window", which should fit your needs.

**Comment by Ninjo79** [comment]
Yes I know that action, but window is minimize only to taskbar.
I had second(expired) addon for minimize to tray.
Could you help me how can I setup gesture to minimize to tray?
Thank You

**Comment by Robbendebiene** [comment]
How do you minimize Firefox to tray without an addon? I never saw that before and I'm also not aware of any webextension API that can do this.
