### ISSUE TITLE
Right click while holding left button.

### ISSUE THREAD

**Issue by Zenzyme** [Robbendebiene/Gesturefy#183]
With Gesturefy enabled, when I drag and select text with the left button, I need to release the left button before right-clicking gives me a context menu. (I need to keep the left held down on certain occasions when the selection is lost when releasing the left button.)

I've found that if I right click somewhere on a page beforehand and get a context menu, I can then proceed to get a context menu while holding the left button as I normally would, though if I reload the page or go to a new page the problem will once again occur.

**Comment by Robbendebiene** [comment]
> With Gesturefy enabled, when I drag and select text with the left button, I need to release the left button before right-clicking gives me a context menu. (I need to keep the left held down on certain occasions when the selection is lost when releasing the left button.)

This is working fine for me, without releasing the left mouse button. Do you have Rocker gestures enabled? Because this will trigger a Rocker gesture, which will prevent the context menu.

**Comment by Zenzyme** [comment]
Rocker gestures are disabled.

**Comment by Zenzyme** [comment]
Oh I guess wheel gestures did it. No way around it then huh?

**Comment by Robbendebiene** [comment]
Oh I see. I may be able to fix this.
