### ISSUE TITLE
New action type: Open link in new (foreground) tab or open new tab

### ISSUE THREAD

**Issue by soerennielsen** [Robbendebiene/Gesturefy#184]
I've been using mouse gestures for almost two decades now, starting with Opera version ancient. 

I've now switched to Gesturefy from (all in one gestures) in firefox. 

Love it, though one of my favorites gestures no longer work properly. 

I used to be able to do "up" to open a new tab OR if I started the gesture from a link, it would open that link in the new tab. 

In gesturify I can have one or the other, not both. Can I please have the same action? Pretty please? ;-)

**Comment by Robbendebiene** [comment]
This is already possible. Checkout the "Advanced settings" under the "link to foreground/background tab" actions :)
