### ISSUE TITLE
For some areas on site Gestures does not work

### ISSUE THREAD

**Issue by KES777** [Robbendebiene/Gesturefy#185]
The site example:

http://joxi.ru/vAWMwOZIkZXbMm

For site `mamba.ru` in specified area gesture does not work

**Comment by Robbendebiene** [comment]
Please send the actual link to the website where the issue appears. I can not find the area shown by your screenshot on mamba.ru.

**Comment by KES777** [comment]
Here is [full link](https://www.mamba.ru/search.phtml?rl=1&from_item=1) but you should be registred user on this site if you wanna to open it.

**Comment by KES777** [comment]
This addon also does not work when not all resources are loaded.

For example if some add is not available. It seems you stick you plug-in to `document.onload` event

**Comment by Robbendebiene** [comment]
> This addon also does not work when not all resources are loaded.

This is not true. Images and other stuff don't have to be loaded, only the the main part of the document.

> For example if some add is not available. It seems you stick you plug-in to document.onload event

If the advertisement is embedded in an iframe (which is quite common) then gestures won't work on that advertisement until it is partially loaded (its document body is available).

**Comment by KES777** [comment]
>If the advertisement is embedded in an iframe

that is iframe

**Comment by KES777** [comment]
hm.... if this standalone file (opened from filesystem). The plugin did not work until that iframe load the add.

Notice. I click not on the iframe.

**Comment by KES777** [comment]
on [this page](http://htmlbook.ru/css/content) the iframe did not work too.
http://joxi.ru/8234Qvpi6BnVqA

I am doubt a bit that advitisement network did not work so often

**Comment by KES777** [comment]
plugin did not work on this [page](https://stackoverflow.com/questions/3508605/how-can-i-transition-height-0-to-height-auto-using-css)

**Comment by Robbendebiene** [comment]
The code snippets preview area is a dynamically created iframe **without a src attribute** (you don't even need to maximize it) so it suffers from the same problem. Basically webextensions script injection does not work on iframes missing the src attribute.
I'm still not sure if this is intended by Mozilla or if it is a bug.

**Comment by KES777** [comment]
And here only **scrollup/scrolldown** did not work too:
http://joxi.ru/krD4yRDi0ln5dr
https://bugzilla.mozilla.org/show_bug.cgi?id=1426617

other gestures work fine

**Comment by Robbendebiene** [comment]
@KES777 This issue seems to be solved, can you confirm this?

**Comment by KES777** [comment]
still an issue
![image](https://user-images.githubusercontent.com/799021/81542741-d01d5600-937d-11ea-9209-afe5bf5a9cf2.png)

at this area gestures does not work.

Last Updated February 19, 2020

**Comment by Robbendebiene** [comment]
I'm not able to test this page, but this is probably due to #258 because gestures work fine on a dynamically created iframe:

`var x = document.createElement("iframe"); document.body.append(x); `

While they don't work on sandboxed iframes:

`var x = document.createElement("iframe"); x.sandbox.add('allow-forms');  document.body.append(x); `

Since the other issue already covers this, I'm closing this one.
Related bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1411641
