### ISSUE TITLE
'Open Home page..' fails with local file

### ISSUE THREAD

**Issue by pdqpat** [Robbendebiene/Gesturefy#189]
My home page is a local file of the form: file:///D:/ ... home.html  The 'Open home page' function doesn't work.  Adding the file url also doesn't work. (Fx 57 'home' icon opens in the existing tab. Links from Thunderbird also open in an existing tab - very inconvenient!)

Update: I edited the local page to use css/js from the web - voila! It now works perfectly. Thank you.

**Comment by uegajde** [comment]
Sadly, it is also limited by the api (WebExtension).
An addons cannot open a local file by itself.

> Firefox: cannot call file URLs in tabs APIs, e.g.: tabs.create or tabs.update. Can attach a content script to those tabs. This means that you can't open a file:// URL and then read through the contents, unless you can get the user to open the file:// for you. 
[WebExtensions/Filesystem](https://wiki.mozilla.org/WebExtensions/Filesystem#Firefox)

**Comment by uegajde** [comment]
although New Tab Override has a workaround to set local file as new tab by loading the HTML file into its storage.
(limitation: it is necessary that any files that get loaded in the HTML file are accessible on the Internet)

**Comment by rodalpho** [comment]
It would be very useful if Gesturefy included the option to select the URL used for new tabs so the user can select "about:blank" (to select the URL bar) or any URL of their choice, as they work with gestures. That would make the New Tab Override addon unnecessary. 

For the OP's issue, my suggestion would be to create a github containing your HTML startpage and use that URL for new tab override. But unfortunately there's no way to automatically select the URL bar as webextensions doesn't allow it.

**Comment by pdqpat** [comment]
This addon would be perfect if it uses the page "title" instead of "new tab" in the titlebar.  :)

**Comment by Robbendebiene** [comment]
@pdqpat I guess you are referring to New Tab Override? If so you should contact its author :)

**Comment by Robbendebiene** [comment]
Since it is very unlikely that it will be possible to open local files in the future, I'm closing this issue.
