### ISSUE TITLE
touchscreen support

### ISSUE THREAD

**Issue by nosferatum23** [Robbendebiene/Gesturefy#191]
All new gestures addons including Gesturefy do not work with touch screen. I can't use any on my MS Surface. It worked perfectly with firegestures though

**Comment by Robbendebiene** [comment]
There is already an [issue](https://github.com/Robbendebiene/Gesturefy/issues/98) addressing this problem, please write there. Also provide more detailed explanation how touch should work/worked for you previously.

**Comment by Robbendebiene** [comment]
Duplicate of #98
