### ISSUE TITLE
Need to switch mouse key to trigger gesture

### ISSUE THREAD

**Issue by Kijewski** [Robbendebiene/Gesturefy#193]
*  Gesturefy 1.1.17 
* Mozilla Firefox 57.0
* Linux 4.13.0-1-amd64
* Debian testing

---

Since right about now the gestures stopped working. I needed to switch to left mouse button to make Gesturify work again. Afterwards I could use the middle mouse button again. First I tried to switch to the right mouse key, but it  did not work (but I did not expect that it would).

I don't know what triggered the error, because after the last update three days ago (2017-11-29) Gesturify worked well. In the mean time neither Gesturify nor Firefox were updated. During my usual session the gestures simply stopped working.

I cannot tell if restarting FF would have fixed the problem. I don't know if that was a random hiccup, and I don't know how to recreate the error.

**Comment by Robbendebiene** [comment]
> I don't know how to recreate the error.

Sorry, but in this case I'm not able to help you.

> I don't know what triggered the error, because after the last update three days ago (2017-11-29) Gesturify worked well. In the mean time neither Gesturify nor Firefox were updated. During my usual session the gestures simply stopped working.

Maybe it was still working, but you tried to draw a gesture on a restricted page like the mozilla addons or some about: pages?
