### ISSUE TITLE
Translate with X - action

### ISSUE THREAD

**Issue by nicholasvalentine** [Robbendebiene/Gesturefy#195]
How about a gesture, that would work similarly to the web search gesture, but instead sends the selected text/link to Google Translate or Bing Translator? There's an add-on which I'm currently using, but I wish I could gesturefy the process :point_right: :point_left: :point_down:

**Comment by Robbendebiene** [comment]
I plan to implement an action where you can open a specific url, which will also allow including the current text selection. But this feature is delayed until: #197

**Comment by Robbendebiene** [comment]
In Gesturefy 2.0.0 this can now be achieved using the "Search Selected Text" command and setting the search engine URL to a translator website (like https://www.dict.cc/)
