### ISSUE TITLE
Feature request - Open new tab at the end of the tabs row

### ISSUE THREAD

**Issue by deemadee** [Robbendebiene/Gesturefy#196]
- Mozilla Firefox 57.0.1
- Gesturefy 1.1.17
- Windows 7 home premium x64

Hello!
First I'd like to thank the developer for making such a nice add-on.  Everything works smooth (except the limitations by the new Firefox engine) =)
The only thing missing for me, is the ability to open link in a new tab (active or not active) with a gesture at the end of the tabs row.
Actually there is a setting in about:config (browser.tabs.insertRelatedAfterCurrent - true or false) that let you to change whether you want your new tabs to be opened next to active focused tab or at the right end of the tabs row. But it doesn't work with this add-on =(
While browsing Internet to solve this issue I have faced an old forum discussion about the similar problem "browser.tabs.insertRelatedAfterCurrent only work if you open a link in a new tab and not when you open a new tab via Ctrl+T or via the plus icon."
So, I suppose that when you make a gesture to open link in a new tab, Firefox treats it some other way. Because when I have the setting "browser.tabs.insertRelatedAfterCurrent - false" and I click on the link with the right mouse button and choose  "Open link in the new tab" everything work the way it should and the tab is opened at the right end of the tabs row.
It would be very nice if this little issue could be solved. Thanx in advance!

**Comment by Robbendebiene** [comment]
@deemadee It's been a long time and you probably don't need this anymore but this will finally be implemented along with #409.

**Comment by Robbendebiene** [comment]
Done: 62f05aeec306c3f4a0aa338ca4cb8284175196da

**Comment by deemadee** [comment]
@Robbendebiene It's really been a long time, but I still needed this improvement, as I'm still using your add-on on day-to-day basis. Thank you for continuous support of the project.

**Comment by deemadee** [comment]
Actually I have tested the new behavior of the "open link in new tab" gesture and I have one little observation about it.
Here is my use case (about:config browser.tabs.insertRelatedAfterCurrent - false): I'm on some Internet site with multiple links, I'm making gesture "open link in new tab" without changing focus (i.e. background tab), background tab opens to the right. Then I'm making another gesture to open another link from the **same site** and the new tab goes to the right end of tabs row. Hooray, Bravo!
So I continue to browse **this site** and open another stack of new tabs, and all of them goes at the right end of the tabs row. My focus is still on the first "left" tab.
But if I will move my focus to the second tab (still having several tabs to the right being opened from the **first site**) and will try to "open link in new tab" (background tab) from **"second site"** it will be inserted next to the current focused tab (i.e. after the **second site** tab). And all other tabs opened from the **second site** will be inserted to the right of the previously opened background tabs from the **second site**. So basically all the new tabs being opened from the **second site** will be inserted in the middle of my tabs row, as the tabs opened from the **first site** will be staying at the right end of the tabs row.
The ideal behavior of the gesture, should work this way:  You have set "about:config browser.tabs.insertRelatedAfterCurrent" to false. If you are making a gesture to open a new tab, it must go to the right end of the tabs row, no matter from which tab you are opening a new tab.
Excuse me for such a meticulous explanation, but I hope You will understand me.
Thanx in advance for Your work  @Robbendebiene !

**Comment by Robbendebiene** [comment]
Thanks for testing and the detailed report. I'll look into it.

**Comment by Robbendebiene** [comment]
@deemadee I cannot reproduce your problem. 
if `browser.tabs.insertAfterCurrent` and `browser.tabs.insertRelatedAfterCurrent` are set to false all of my new tabs are opened at the end of the tab row. 

If this still doesn't work for you then you can change the "new tab position" to "end" instead of using the standard behaviour.
