### ISSUE TITLE
"go to the first tab" won't switch to the pinned tab

### ISSUE THREAD

**Issue by silver-zhao** [Robbendebiene/Gesturefy#201]
If I have a tab pinned, it will automatically be placed in the first. However, I cannot switch to it by using the gesture "go to the first tab". Could you please help fix this? Thanks!

**Comment by Robbendebiene** [comment]
This is not a bug, this behaviour is intended. Since pinned tabs are always visible, you can switch to them quite easily. However I could add an advanced option to change this.

**Comment by silver-zhao** [comment]
That would be very helpful to have an advanced option. In current setting, I can only switch to pinned tabs by keyboard like `command + 1`. It's not easy to switch them by mouse.
