### ISSUE TITLE
Weird behaviour when opening links from duplicated tabs

### ISSUE THREAD

**Issue by stmr** [Robbendebiene/Gesturefy#202]
Hi,
I've just notices a small bug, not important at all but it's one thing that can be polished:
When you duplicate a tab and that duplicate gets opened right next to the original tab, all the links opened from the original tab are treated as a child tabs from the duplicate (they are opening from the duplicate tab even when there are 100 tabs between the original and the duplicate).
Hope you're doing great!

**Comment by Robbendebiene** [comment]
Hey, thanks for the report. 

This problem can occur in several situations, for example:
1. open a new background tab via right click > context menu
2. now open multiple background tabs via gesture
3. switch to one of the background tabs and go back to the parent tab
4. open some background tabs via gesture again

I'm no longer able to fix this without storing some temporary data (so this will be the first action which holds a state in it self), but at least I found a pretty neat way to do this :)
So the next implementation will **only** take tabs into account that were opened via this particular gesture.
