### ISSUE TITLE
Search selected text doesn't open as a child tab

### ISSUE THREAD

**Issue by leudname** [Robbendebiene/Gesturefy#203]
Thank you for this amazing extension.

'Search selected text' gesture opens a new parent tab, as opposed to right-clicking -> search google which opens as a child.

**Comment by Robbendebiene** [comment]
So you are opening multiple searches as background tabs, but you want them to be ordered like link to background tab does? (first opened tab is right to the current and last one is at the end)

**Comment by leudname** [comment]
Sorry, I should've mentioned that I use the Tree Style Tab extension.

The first attachment shows what happens when I use the default firefox search in the second tab, the other when I use the gesture.

![sn1](https://user-images.githubusercontent.com/34315809/33939473-a4ae8818-e00b-11e7-8ed4-451f5f73b27f.jpg)

![sn2](https://user-images.githubusercontent.com/34315809/33939495-b6435c48-e00b-11e7-94ad-f1d92bfadef0.jpg)

It's a minor thing but it stops me from using a gesture in this case. Thanks.

**Comment by Robbendebiene** [comment]
Alright. This will be fixed in the next version.

**Comment by Robbendebiene** [comment]
Does this problem also apply to the "imageToTab" action?

**Comment by leudname** [comment]
Yes, same problem.
