### ISSUE TITLE
Feature Request - Bookmark This Page

### ISSUE THREAD

**Issue by raics** [Robbendebiene/Gesturefy#205]
Hi there, good job on the addon, it's a worthy successor to firegestures

There's a gesture I'm missing, from there, however. It's just the simple 'bookmark this page' (Ctrl+D). Gesturefy has a 'toggle bookmark' which is the same as pressing the star icon, but the problem with that one is that it crams everything into 'other bookmarks' instead of giving you a choice of destination with bookmark menu as default, the way (Ctrl+D) does.

Thanks

**Comment by Robbendebiene** [comment]
I also would find this useful, but with the new api it's currently not possible to open this kind of dialog.

**Comment by jefferysmall** [comment]
That's a shame.  Are there plans at Mozilla to make this possible?  It is a real limitation to add-on development!

**Comment by raics** [comment]
What they should do is provide some real support for gesture addons, some browsers have inbuilt gestures so I suppose there's demand for it and they don't even let you create a decent one yourself. I'm certainly no programmer but having an option to send a custom key combination with a mouse gesture doesn't seem like a security issue.

**Comment by Robbendebiene** [comment]
I'm closing this, since it is unlikely that Mozilla will implement an API for this.
