### ISSUE TITLE
Feature request - Search selected text >in<...

### ISSUE THREAD

**Issue by spaspaspa00** [Robbendebiene/Gesturefy#207]
In Firegestures there was an action to search selected text in chosen search engine: after selecting the text and using the gesture a list of my availible search engines was shown and I could select which search engine to use.
Is it possible to add this action to Gesturefy? Now I can use only one search engine - the one permanently defined in Gesturefy options.

Thanks for making this great addon!

Edit: I think that in English this action is called "Search with.." - not "Search in" as I wrote in topic.

**Comment by Itchiii** [comment]
This is a known feature request. Look here: #89,#149 and #99
