### ISSUE TITLE
Gesturefy options on/off button - no unicode support

### ISSUE THREAD

**Issue by spaspaspa00** [Robbendebiene/Gesturefy#208]
Polish translation. "On" should be "Wł.", Off - "Wył." 
screenshot:
![onoff-pl](https://user-images.githubusercontent.com/34109461/33794301-570cdba4-dcc9-11e7-8bb7-e8b5b2c7ca69.jpg)

**Comment by Itchiii** [comment]
Done. In next version, it will be fixed

**Comment by spaspaspa00** [comment]
Thank you
