### ISSUE TITLE
"Save image" action not working on some images

### ISSUE THREAD

**Issue by Cqfuj** [Robbendebiene/Gesturefy#213]
On Twitter some images aren't saved with the "save image" action. 
The image url ends with `.jpg:large` and I think the `:large` part is the reason why it's not saved. If the url ends with `.jpg` it works fine though it's not the large version.
The same issue happens with `:small`.

**Comment by Robbendebiene** [comment]
Please provide an example url, so I can reproduce the problem.

**Comment by Cqfuj** [comment]
```
https://pbs.twimg.com/media/DPgz9RrX0AArk7Q.jpg:small
https://pbs.twimg.com/media/DPgz9RrX0AArk7Q.jpg
https://pbs.twimg.com/media/DPgz9RrX0AArk7Q.jpg:large
```

**Comment by Robbendebiene** [comment]
It seems like this bug is already fixied in Firefox 58.

**Comment by Robbendebiene** [comment]
I'm closing this, since it's working in the current FF 58.

**Comment by Matthewus** [comment]
I did, i hope i did it correctly, never used Bugzilla before. [https://bugzilla.mozilla.org/show_bug.cgi?id=1469121](url)
