### ISSUE TITLE
Feature Request: Add gesture to open developer tools

### ISSUE THREAD

**Issue by vishvega** [Robbendebiene/Gesturefy#216]
Hi there, 
Great extension, nicely done :) I barely say those words...

Have a request, can you add some option to open up developer tools, and it's features differently? For example, one gesture to open "inspect elements", another to directly open "Network" tab or "performance" tab in developer tools? I think it'll be helpful a lot of people. Anyway, just a suggestion.
Thanks for this one, I like it

**Comment by vishvega** [comment]
Also, I'd like to help translate. are all languages available?

**Comment by Robbendebiene** [comment]
Hi there. Sadly none of this is possible. The API currently does not allow to open any Firefox internal pages nor tools.

> Also, I'd like to help translate. are all languages available?

Translations are managed by [Crowdin](https://crowdin.com/project/gesturefy), it should be pretty self explaining how to use it. If your language is missing, just contact me :)

**Comment by vishvega** [comment]
I can help with English, Italian, German and Sinhalese. Last one is missing, can you please add it?


Another thing, Rather than just using up,down,right,left arrows, can you implement something like drawing special symbols for some action? for example, draw P to make a pdf or print or something. or complex stuff like these are still limited by api?

**Comment by Robbendebiene** [comment]
Sinhalese should be available now.

> Another thing, Rather than just using up,down,right,left arrows, can you implement something like drawing special symbols for some action? for example, draw P to make a pdf or print or something. or complex stuff like these are still limited by api?

This would be possible with some effort, however I have no plans to implement it.

**Comment by Robbendebiene** [comment]
I'm closing this, since it is unlikely that Mozilla will implement an API for this.

**Comment by vishvega** [comment]
> 
> 
> I'm closing this, since it is unlikely that Mozilla will implement an API for this.

Hope is not the worst thing in the world.

**Comment by Itchiii** [comment]
@vishvega 

> Another thing, Rather than just using up,down,right,left arrows, can you implement something like drawing special symbols for some action? for example, draw P to make a pdf or print or something. or complex stuff like these are still limited by api?

With Gesturefy 3.0 (works from Firefox 77) you can do this :)

**Comment by vishvega** [comment]
> 
> 
> @vishvega
> 
> > Another thing, Rather than just using up,down,right,left arrows, can you implement something like drawing special symbols for some action? for example, draw P to make a pdf or print or something. or complex stuff like these are still limited by api?
> 
> With Gesturefy 3.0 (works from Firefox 77) you can do this :)

Hi @Itchiii ,
thank you for the heads up. I'm thrilled :) :) 

anyway, tried to update Gesturefy from official Mozilla addons, but the latest they have is v2.1.6 and Last updated 4 months ago (Feb 19, 2020). Can you please include the Gesturefy 3.0 into official repository? many will be thrilled on the update Im sure.

**Comment by Itchiii** [comment]
@vishvega We had some problem with version 3.0.0 but which hopefully have now been eliminated. On Firefox you should now be able to install the latest version 3.0.1 or Firefox will soon update your version 2.1.6 to 3.0.1 :)

**Comment by vishvega** [comment]
> 
> 
> @vishvega We had some problem with version 3.0.0 but which hopefully have now been eliminated. On Firefox you should now be able to install the latest version 3.0.1 or Firefox will soon update your version 2.1.6 to 3.0.1 :)

it's updated. imma go explore new features right away.. appreciate what Rob and you're doing... keep doing that :)

**Comment by fenjen** [comment]
The gesture is: right click + <kbd>Q</kbd> 😉
