### ISSUE TITLE
Context menu open at second or third time

### ISSUE THREAD

**Issue by vortex9** [Robbendebiene/Gesturefy#22]
Hi
I often use the context menu for searching or the like.
I noticed that context menu does not work immediately
It feels like, the plug is too sensitive to pressing the right button. 

As an option, let me set the sensitivity in the settings. I usually make sweeping gestures.

Win7 x64, FF 55.0.1 x64, Gesturefy 1.0.3.

Perhaps related to https://github.com/Robbendebiene/Gesturefy/issues/19

**Comment by Robbendebiene** [comment]
Already on my list :) Will be implemented in the next update (which will add some more config options)

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/3aabe6d081e1e8b15671c10323797653f6f3b058
