### ISSUE TITLE
Add "scroll left"/"scroll right" to available functions.

### ISSUE THREAD

**Issue by bwucke** [Robbendebiene/Gesturefy#221]
My standard mapping for "wheel rocker" is to scroll while holding the wheel depressed ("middle button") to scroll the page horizontally, in case it doesn't fit. Could you add these functions to the list?

**Comment by Robbendebiene** [comment]
The reason why this hasn't been implemented yet is that the requested functions/commands only make sense for wheel gestures. But our goal is to keep every command at least usable with the normal mouse gesture. Therefore we will only ship this feature as a user script. Unfortunately they are still not possible in Firefox.

**Comment by Robbendebiene** [comment]
Simple user scripts are now available with [Gesturefy 2.1.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.5).
Look for the "Execute User Script" command and use the following code.

Scroll Left script:

`document.scrollingElement.scrollLeft -= 15`

Scroll Right script:

`document.scrollingElement.scrollLeft += 15`

For more information, please visit the [Wiki](https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script).
