### ISSUE TITLE
Canel Mouse Gesture (Timeout)

### ISSUE THREAD

**Issue by RSKIT** [Robbendebiene/Gesturefy#224]
In FireGestures it was possible to set a timeout for a gesture: If the time after the last mouse movement during a gesture was longer than a specified amount of time the gesture was aborted. Is this possible to implement for this addon?

**Comment by Itchiii** [comment]
That is implemented.

> **Gesture timeout**
>Cancels the gesture after the mouse has not been moved for the specified time.

You can find it at: settings -> the third entry.

**Comment by RSKIT** [comment]
This option is not visible on firefox version 56, I guess I was working on a system where the update was delayed. After the update, the option is visible.
Thanks.
