### ISSUE TITLE
Can't use the gesture with GroupSpeedDial add on start page

### ISSUE THREAD

**Issue by bezoeker** [Robbendebiene/Gesturefy#227]
Used the firegestures add-onown, to get gestures working for Quantum I installed gesturefy.
But on the start page (add-on) GroupspeedDail I cant use the gestures with gesturefy: for example undo: close last tab.
Is it possible to get this working on this page?

https://addons.mozilla.org/en-US/firefox/addon/groupspeeddial/reviews/?src=api

moz-extension://9ba5c5cb-4214-4006-accf-d710c3d99c0b/dial.html

**Comment by Robbendebiene** [comment]
There are already a lot of other related issues and it's also sort of stated in the addon description. Anyway, the short answer is: it's not possible due to api limitations.

**Comment by Robbendebiene** [comment]
Duplicate of #5
