### ISSUE TITLE
Feature Request: List of sites on which gestures should always be disabled/suppressed

### ISSUE THREAD

**Issue by jim-p** [Robbendebiene/Gesturefy#231]
There are some sites like tinkercad.com which require using the mouse buttons for movement. Having to always use the suppression key for these sites is a bit tedious, since using gestures on them is rarely if ever desirable.

If we had a way to list or blacklist sites that should always have gestures disabled that would be perfect, perhaps flipping the meaning of the suppression key to override and manually enable gestures on those pages as well.

Thanks!

**Comment by Itchiii** [comment]
Your request to add a blacklist has already been submitted here: #62

**Comment by jim-p** [comment]
Somehow I missed that when I looked through the existing open issues. Thanks for pointing that out!
