### ISSUE TITLE
close tab not working since today 01/28/2018

### ISSUE THREAD

**Issue by sapajou** [Robbendebiene/Gesturefy#237]
movement : Right then Left
... unlucky

**Comment by Itchiii** [comment]
Please give more information about your issue. What did you do that "close tab/Remove tab" does not work? Did you changed a gesture, so that "close tab/Remove tab" has a red color?
And please provide information like the version of Gesturefy and Firefox as well as your operating system.

**Comment by sapajou** [comment]
Hi from France
All is OK *today*
... only the unavailable zoom +/- event : 2 days ago, a right click mouse
+ up or down mouse wheel was a good gesture, but not now...



2018-01-30 20:48 GMT+01:00 Itch <notifications@github.com>:

**Comment by Itchiii** [comment]
Sorry but that's not helpful. What is in the input field of the respective action? Is it red? like this: 

![red1](https://user-images.githubusercontent.com/15103402/35631199-91bb554c-06a3-11e8-9b71-7cc2e8c95ea2.PNG)
or something like this?: 
![red2](https://user-images.githubusercontent.com/15103402/35631201-9377e62a-06a3-11e8-9831-af1da8b1c9a7.PNG)

And we need detailed information on when something did not work.
please read the [contributing file](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md)

If you feel safer writing French, you can do that, we will try to translate that.
Si vous vous sentez plus en sécurité en français, vous pouvez le faire, nous allons essayer de le traduire.

**Comment by sapajou** [comment]
Hi, all is OK  (I forgot to activate the "extra" feature)

2018-01-31 16:33 GMT+01:00 Itch <notifications@github.com>:
