### ISSUE TITLE
Right-click still not available?

### ISSUE THREAD

**Issue by rippeddisc** [Robbendebiene/Gesturefy#239]
Was under the assumption that could go back to using right-click with FF58.  Doesnt seem to be the case.  Sorry if I missed something and appreciate the help.

**Comment by Robbendebiene** [comment]
So you are using Linux or MacOS with the latest Gesturefy version and the context menu still appears if you set the gesture trigger button to the right mouse button?

**Comment by rippeddisc** [comment]
Osx.  And yes. Context menu pops up on my end.  Thanks for quick reply. 

Aaron Feinberg
808.634.5804
www.aFeinPhoto.com
aFeinberg Gallery
 Poipu • St Regis • Wailea

**Comment by Robbendebiene** [comment]
Have you already tried reinstalling Gesturefy? (maybe make a backup of your settings before). Does the context menu popup when you hold or when you release the right mouse button?

**Comment by rippeddisc** [comment]
installing and reinstalling worked.  naturally.  thanks for the reminder.  



www.ExpandingVisualReality.com <http://www.expandingvisualreality.com/>

FACEBOOK <http://www.facebook.com/afeinphoto>
TWITTER <http://www.twitter.com/afeinphoto>
INSTA <https://instagram.com/afeinberg_photography/>

“...this is the best part of the trip....”

rippeddisc@gmail.com
808.634.5804
