### ISSUE TITLE
Closing Tabs via gestures

### ISSUE THREAD

**Issue by Ichisich** [Robbendebiene/Gesturefy#24]
Feature Request:.

Expected behaviour: 
Possibility to set gestures to close tabs to the right/left and close other tabs as it is feasible in the tab context menu.

**Comment by Robbendebiene** [comment]
Thanks for the good idea, will be implemented in the next version.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/55828ab71036c25a9425e132ec420efb36eb8c7f
