### ISSUE TITLE
Feature request - open homepage in new tab

### ISSUE THREAD

**Issue by quiddity-wp** [Robbendebiene/Gesturefy#240]
Hi :-) 
My previous workflow was to open a new tab (gesture up), and then navigate to my homepage (gesture down). This gets me a tab without any history.
This is no longer possible because Firefox doesn't allow gestures on the empty "New Tab" page.

Request: Add a new "advanced setting", or a new gesture type, to "Open homepage in new tab"

p.s. Thank you so much for helping push to get right-click working in linux/mac. Massively appreciated!

**Comment by Robbendebiene** [comment]
This can now be achieved using the new command "Open custom URL in new tab" so I'm closing this.
