### ISSUE TITLE
Feature request - [dialog] back\forward on history

### ISSUE THREAD

**Issue by Dees7** [Robbendebiene/Gesturefy#242]
There is a very useful dialog if right-click on back-button in the Firefox. 
![screenshot_2018-01-31_10-57-38](https://user-images.githubusercontent.com/14229113/35607474-12e9c29e-0676-11e8-9b1b-22d4980e21d4.png)

This dialog was able to show on action in FireGestures. 

Please make action to show this dialog.

**Comment by Robbendebiene** [comment]
This is not possible and was already requested here: https://github.com/Robbendebiene/Gesturefy/issues/190 However I'll implement a popup action (for more information look here: https://github.com/Robbendebiene/Gesturefy/issues/99) when Mozilla provides the [necessary API ](https://bugzilla.mozilla.org/show_bug.cgi?id=1378651)

**Comment by Robbendebiene** [comment]
I'm closing this, since this is covered by the issue I mentioned above.
