### ISSUE TITLE
Settings page is unfilled after restarting Firefox

### ISSUE THREAD

**Issue by Itchiii** [Robbendebiene/Gesturefy#244]
Two issues that are probably related:
First: When restarting Firefox and the settings page of Gesturefy is called directly(start page), all settings are empty (see images). 
Reloading (F5, Ctrl + F5 or Ctrl + R) loads them.
Sometimes it worked normally, but I could not reproduce it properly and seemed to be random.

![gestures_empty](https://user-images.githubusercontent.com/15103402/35629269-72c613d4-069e-11e8-86e0-1fc85b1abfdc.PNG)
![settings_empty](https://user-images.githubusercontent.com/15103402/35629276-78b08464-069e-11e8-90fd-ebbb6013b83b.PNG)

Secondly: A new gesture is set (I tried it with "[Popup] Recently closed tabs" and "Close Window"), after the user has restarted Firefox, with the settings page as the start page (same problem as above), then the previously set gesture is reset to the state it was before the new placement.
But that only happens if Firefox is closed immediately after the gesture is set. If the gesture is tested in another tab or another tab is opened and then the browser starts with the settings page, the new gesture works. (The first problem still exists)

Operating System: Windows 10
Firefox Version: 58.0.1
Gesturefy Version: 1.2.0

**Comment by Robbendebiene** [comment]
Fixed in [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0)
