### ISSUE TITLE
Dark theme for options page

### ISSUE THREAD

**Issue by Gnustier** [Robbendebiene/Gesturefy#246]
Dark theme for options page

Would you please make a optional dark theme for options page, 
in order to take care of eyes at night ?

If not, make a optional theme which inherit colors from browser, 
in order to keep color consistency and visibility when theme of browser is not bright ?

**Comment by Itchiii** [comment]
Yes that is possible and will be available in the next major version

**Comment by Gnustier** [comment]
also the popup menu, please

**Comment by Robbendebiene** [comment]
Added in [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0) (excluding the popup menu for now)
