### ISSUE TITLE
Per-site save

### ISSUE THREAD

**Issue by nayhem** [Robbendebiene/Gesturefy#247]
This is a bit different from the "Save image" issue in #145.

In Firefox there is an optional `browser.download.lastDir.savePerSite` setting that can be added so items from a specific domain can be saved to a remembered location, on a per-domain basis. I'd like to see actions such as "Save Image" and "Save Link" to use Firefox's setting if possible, or perhaps Gesturefy using its own database for per-site saving.

**Comment by Robbendebiene** [comment]
Sorry for the late answer, the issue somehow got lost.
Actually this suffers from the same problem as the issue you've mentioned, because the API only enables me to set a directory relative to the default download directory.

**Comment by Robbendebiene** [comment]
Closing since this cannot be handheld by addons and therefore should be handled by Firefox.

Anyone who is still interested in this feature should create a ticket or contribute here: https://bugzilla.mozilla.org
