### ISSUE TITLE
Gesturefy icon missing

### ISSUE THREAD

**Issue by rubberdawg** [Robbendebiene/Gesturefy#249]
[WIN10 V1709 x64 / FFQ 58.0.1 / Gesturefy 1.2.0]

Per title:  Icon for Gesturefy CANNOT be located anywhere even though it is installed and is listed in about:addons page and fully functional.

Backed up json file > Removed Gesturefy > Restarted FF > Reinstalled Gesturefy > Restored json file.  Gesturefy WORKING but still NO ICON ANYWHERE.

**Comment by Robbendebiene** [comment]
If by icon you mean a [toolbar button](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Browser_action), then there is no such thing. What should be the use case for this button after all?

**Comment by rubberdawg** [comment]
Got it.  Thanks for prompt response.

**Comment by Robbendebiene** [comment]
Alright, no problem. So I'm closing this.
