### ISSUE TITLE
Scroll to the bottom

### ISSUE THREAD

**Issue by CGA11** [Robbendebiene/Gesturefy#25]
Performing this action makes the page freeze at the bottom with no possibility to scroll up again. Doesn't matter if I use the scroll wheel or the scroll bar. Only way to resolve is reloading the page. Firefox 56.0b3.

**Comment by Robbendebiene** [comment]
Thanks for the report. There is already a pull request  #23 from another user to fix this. I'm currently not at my computer for at least one week, so it might take some time until I can release a fix.
Can you send me a website where I can easily reproduce the bug or does it only happen sometimes (I guess so)?

**Comment by CGA11** [comment]
Sorry, I missed that request. Anyhow this affects all websites for me 
but here is an example: https://www.howtogeek.com/. Take your time, no 
worries. Thank you for an excellent extension, it's a perfect 
replacement for Firegestures.

------ Original Message ------

**Comment by uegajde** [comment]
I recently found the key causation is the "custom rescaling" in windows display settings.
This bug can be reproduced in any website if the web is long enough, when I set the custom rescaling to 125%

**Comment by Ichisich** [comment]
On my system every setting despite 100%(default) causes this behaviour.
Firefox 56.0b3 (64bit) - Windows 10

**Comment by Robbendebiene** [comment]
9f84e64195a4cd0f1d9275869a9677673c7d7aa5
