### ISSUE TITLE
Action: Reload iframe only

### ISSUE THREAD

**Issue by jefferysmall** [Robbendebiene/Gesturefy#250]
Great add-on.  Some improvements that I'd like to see:

1) Add support to reload a frame's content rather than the entire document.

2) Make gestures work on a new empty tab.  Currently, it is deactivated, so gesture to close the tab will not work.  (It also doesn't work on various Firefox pages such as the Gesturefly settings page itself.)

3) Add gesture support to open the Gesturefly gestures page in a new tab.

Thanks

**Comment by Itchiii** [comment]
2. Sorry, these things don't  work due API limitations.  See #94 or #6 
And please read the addon description
> The addon does not work on https://addons.mozilla.org (for further information see this bug), pure svg pages and internal pages like about:newtab, about:addons or other addon option pages.

3. This feature already exists.
> **Open Gesturefy settings**
> Opens the Gesturefy settings page.

**Comment by jefferysmall** [comment]
Thanks for the info on #2.

I don't know how I missed #3, but thanks for pointing it out.

**Comment by Robbendebiene** [comment]
Added in [Gesturefy 2.0.0](https://github.com/Robbendebiene/Gesturefy/tree/v2.0.0)
