### ISSUE TITLE
Ctrl+Tab with gesture (better right click+scroll)

### ISSUE THREAD

**Issue by Dituar** [Robbendebiene/Gesturefy#255]
Hi, how to do this
http://i99.fastpic.ru/big/2018/0220/0c/38cc6a7869b164f65b7ec65b884bf20c.jpg
with gesture (better if right click+mouse scroll), like Ctrl+Tab in Firefox, when (browser.ctrlTab.previews is true) it enabled in settings.
it is be better if switch between tabs with mouse scroll.

**Comment by Robbendebiene** [comment]
Hey, this is not possible. The best thing you can do, if you want to switch between tabs fast, is setting the "Previous Tab" and "Next Tab" action as wheel gestures (remember that the site needs to be partly loaded to perform them) , or use the popup gesture "All Tabs" to show a popup which contains all of your tabs.
