### ISSUE TITLE
Paste selected text into address bar / focus address bar

### ISSUE THREAD

**Issue by beelze** [Robbendebiene/Gesturefy#256]
As for now, «search selected text» is limited to only «search text using predefined search engine». But it would be very great to be able to use this action as a convenient replacement for `copy selection to clipboard + open new tab + paste + [press return]. 

Why it is so important for me? First, I use more than one search engine (google, duckduckgo, yandex, wikipedia, some forum searches) and I want to use all this searches the same way. The second – I often do the same combo `copy selection to clipboard + open new tab + paste` for in-text urls (or url parts) on page.

Of course, it is not convenient (and/or smart) to have different gestures (and to retrieve proper search url prefixes). But, if someone often uses different search engines, it is very likely that these engines have keywords assigned. As for me, I use duckduckgo as default search, `gg` prefix for google search, `ww` for wikipedia and so on.
Therefore, for me it would be most convenient to activate gesture and see selected text in addressbar in the new tab, having no selection and caret in the beginning (to prefix text with search engine keyword if needed). All I need then is to press return to start a search. As a side effect, this strategy can be used to directly open selected in-text urls instead of (mostly unwanted) search them.

I realize that FF WE API is immature and perhaps we can not control caret and selection in the address bar, but we can invent some workarounds (simple dialog to preliminarly editing or something else).

**Comment by Robbendebiene** [comment]
This is a nice idea in general. I would call this "focus awesomebar", "selection to address bar", or something like this. However this is currently not possible, because there is no API to focus the address bar (https://bugzilla.mozilla.org/show_bug.cgi?id=1295400)
I plan to add a popup action which displays all your search engines, this would at least give you the ability to combine all your search engines into one gesture.

**Comment by beelze** [comment]
Popup to display search engines is good. But what about textbox to edit the text that was selected? Is there any ability to open new tab emulating awesomebar «parsing» functionality? E.g. to be able to put any text, including search engine prefix, raw url and so on – to get the same results as pasting this text to awesomebar and pressing enter?

**Comment by Robbendebiene** [comment]
I guess I could somehow emulate the awesomebar, but the effort would be equivalent to a new addon. Therefore I would rather wait for an API to focus the awesomebar.

**Comment by beelze** [comment]
So, we can't just invoke something like something.newTab('any text') and get equivalent to put 'any text' to awesomebar and press return? It a heroism to write anything using such a restricted API. Well, seems the one and only way – to press Mozilla devs to implement/expose relevant API?

**Comment by beelze** [comment]
A couple of words about popup with search engines list. It is good, but it is completely different idea.
As for me, desired select-to-awesomebar gesture can not (and should not aim to) fully create «search string» or whatever it can be called, because of:
1. need to use specific search engine
2. need to use extended search engine syntax (e.g. *site:domain.tld* search_string, *not* token and so on)
3. need to alter search_string (remove/add words)
4. need to directly open url (or even it's part, e.g. I want to open top-level page from url)
5. need to «fix» selected search_string (e.g. first/last char occasionally wasn't selected)
So, as for me, the «editing» phase shouldn't be omitted.

**Comment by Robbendebiene** [comment]
> So, we can't just invoke something like something.newTab('any text') and get equivalent to put 'any text' to awesomebar and press return?

Exactly.

**Comment by Robbendebiene** [comment]
Closed in an issue clean up process due to the lack of an appropriate or upcoming API. (Mozilla rejected the required API)
