### ISSUE TITLE
Gestures do not work on page source

### ISSUE THREAD

**Issue by KES777** [Robbendebiene/Gesturefy#259]
How to reproduce:
1. right click on page 
2. View page source

As result you can not control opened tab

All tabs should be under Gesturefy control (IMHO: even blank one)

**Comment by Robbendebiene** [comment]
This is a Firefox API limitation and the same applies to new tab/blank tab. For more information visit the addon description or look [here](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md).

**Comment by KES777** [comment]
I used to use this behavior while using 'Fire gestures' plugin. Sadly that API has changed so much and limit functionality (

**Comment by KES777** [comment]
Also when response is at `json` format I can not use gesutres to refresh the page:

Here is example of request and page showed by browser:

http://feelsafe:3000/text.json

![delete1](https://user-images.githubusercontent.com/799021/37557017-f540fe06-2a06-11e8-9e0c-5a6b76627b43.jpg)

**Comment by Robbendebiene** [comment]
I'm closing this, since it is unlikely that Mozilla will allow extensions to access the page source content.
