### ISSUE TITLE
Ability to clear action's gesture combination

### ISSUE THREAD

**Issue by Lovemetal** [Robbendebiene/Gesturefy#26]
Is there any way to clear a binding? I don't need some of default actions/gestures , but I want to use their gesture combos, and as a workaround I bind them to random gestures, to free up needed combos.

**Comment by uegajde** [comment]
the box showing the gesture combos is an input box
just click the box to focus it then delete the content with backspace button :P

**Comment by Lovemetal** [comment]
Oh, it's an input, now I see. It's not very obvious. Thank you very much, uegajde.

**Comment by uegajde** [comment]
you are welcome

**Comment by Robbendebiene** [comment]
Are there any ideas how to improve it? I found adding an extra delete or "x" button too much.

**Comment by Ichisich** [comment]
A delete section/text in the upper/bottom left of the rec overlay.

**Comment by Lovemetal** [comment]
I agree, Clear or Delete on left of the REC screen is ok. Also you should probably add a hint to Information section on the top of the page.

**Comment by Robbendebiene** [comment]
For now I added the button, it will be available in the next version. 548f0d6749aa5a88a7bd6265c181dd3a66a69464
