### ISSUE TITLE
The 'Save Image' gesture opens the default folder to save

### ISSUE THREAD

**Issue by u2arejust2cute** [Robbendebiene/Gesturefy#261]
Shouldn't it open the same folder that gets openend when using the 'save as' function of the right click menu?

**Comment by Robbendebiene** [comment]
If you mean it should open the last folder/directory you've selected, then this is not possible (reason is described [here](https://github.com/Robbendebiene/Gesturefy/issues/145)). It will always open your Firefox default download folder.

**Comment by Itchiii** [comment]
The Problem is described  in #145 so I will close this issue.
