### ISSUE TITLE
Gestures not working, Rocker/Wheel gesture settings blanked after restarting FF

### ISSUE THREAD

**Issue by tillyboy** [Robbendebiene/Gesturefy#263]
I noticed two bugs:

First is that I cannot use the Mouse wheel gesturem tried to restart FF to get it to work, but it still doesn't do anything. They are also blank in the settings which might be related to #244 . This screenshot illustrates it:

![screenshot from 2018-03-05 17-28-48](https://user-images.githubusercontent.com/31419678/36986858-39bf4ad0-209b-11e8-90a9-dce218834607.png)

The dropdown menus stay empty when I expand them.

My second issue is the 'Page forward' gesture, which for me is super buggy. Most of the time, it will do the exact opposite of what it should, and gets me one step backwards in history. However I noticed that on soundcloud.com, it actually refreshes the site. The gesture is recognized correctly, at least the 'Preview overlay' (or however you may call it) shows 'Page forward' before I release my RMB:

![screenshot from 2018-03-05 17-43-56](https://user-images.githubusercontent.com/31419678/36987519-d5a8e324-209c-11e8-86eb-cf38c2d40bc5.png)

Gesturefy: v1.2.0
Firefox: v58.0.2(64bit)
OS: Manjaro 17.1.6 Hakoila
Kernel: x86_64 Linux 4.15.5-1-MANJARO

If you tell me where to find it I will also send you my config to check wether my errors are reproducible.

Update: The 'Page backward' gesture also exposes inconsistent behaviour. While most of the time, it will bring me one step back in 'Viewing history', which means I cannot go back more than one step. If I go back another step I get back to the page that I started with as it is the last page in terms of last viewed. So using that gesture the only thing I can do is cycle between current page and last page (in terms of browsing history).

Interestingly enough the 'Page forward' gesture implements a 'Page backward' in the way it is supposed to work: By browsing history.

Again I experienced a bug on soundcloud which makes the page refresh, this time on the 'Page backward'. The 'Page forward' gesture now works as expected on soundcloud (and I didn't even restart FF). I guess that soundcloud in particular may be buggy with Gesturefy and that this part of the issue may not be feasible to resolve.

Update2: (Sorry for the spamming)
I am also getting inconsistent behaviour on the 'proper' execution of the 'Page backward' action for the 'Page forward' gesture. E.g. browsing https://dxr.mozilla.org/mozilla-central/source/ it will implement the improper 'Page backward' action which I otherwise get from the 'Page backward' gesture.

**Comment by Robbendebiene** [comment]
About the first bug, have you tried to reset the settings (under about section) or to reinstall Gesturefy?

Second Problem:
The big question for me is, are the normal back/forward history arrow buttons working as expected? I guess soundcloud and other websites where you've encountered problems, manipulate the browser history which may lead to some weird behaviour.
You added a lot of details to your post (wherefore I'm very grateful), but I still can't really reproduce the problem. At least browsing through the folders on: https://dxr.mozilla.org/mozilla-central/source/ works fine for me. A step by step description of a specific website with your concrete actions would be helpful. However if the normal browser back and forth actions also fail, then there is nothing I can do.

**Comment by tillyboy** [comment]
The first bug actually resolved through resetting, however I would then like to file a complaint that it works only once, aka only for one tab instead of the ability of "scrolling through the tabs" while holding down the wheel gesture button. If I want to go multiple tabs, I have to reactivate the gesture button. But I don't know, this might be the intended behaviour. At least it feels that it should behave different.

Here's what I did today to reproduce the second bug:

    https://dxr.mozilla.org/mozilla-central/source/

    -> devtools
    -> platform

backward button works as expected
forward button works as expected

    backwards gesture:
      platform -> devtools (as expected)
      devtools -> platform (wrong behavior)

    forwards gesture:
      platform -> reload (intended?)
      devtools ->source(wrong behavior)
  
This is reproducible even after resetting/reinstalling Gesturefy. One more interesting thing that I noticed is that both gestures, instead of reliably producing one wrong behavior, sometimes reload the underlying page while preserving the gesture overlay including the previously drawn gesture, on top of which I can then draw another one.

**Comment by tillyboy** [comment]
Stupidious me! I just noticed that I still had another gesture plugin (mouse events or something like that) installed. Uninstalling fixed all the issues. But now at least you know to tell everyone who's filing similar bugs that they should uninstall any other plugins related to gestures :D 

I'll still do some testing to see if I get any of the weird behaviour, otherwise I will soon close this. Thanks for the support anyhow :)

**Comment by Robbendebiene** [comment]
@tillyboy Okay, no problem. It's always a pleasure if issues solve this way :)
