### ISSUE TITLE
`Open link in new tab` action opened without `Referer` header

### ISSUE THREAD

**Issue by KES777** [Robbendebiene/Gesturefy#265]
When `Rigth click -> Open link in new Tab` the link is opened in new tab and the `Referer` header is available in request.

But when opening link with `Gesturefy` the link is opened without `Referer` header

Please fix behavior. Do not lose information about we come from.

**Comment by jdreesen** [comment]
But please respect `rel="noreferrer"` ;)

**Comment by Robbendebiene** [comment]
@KES777 Sorry, but this is not possible. At least not without a lot of extra work and two additional permissions.
