### ISSUE TITLE
Gestures don't work

### ISSUE THREAD

**Issue by Masterdaemon** [Robbendebiene/Gesturefy#266]
Hi. The gestures jus work one time, after that they stop working. I need to disable and enable the extension again to make them work again.

**Comment by Robbendebiene** [comment]
Please provide more information as described [here](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md).

**Comment by Masterdaemon** [comment]
Sorry! My fault. The problem was that the time to cancel the gesture I set was too short. (2 secs.)
You can close or delete this coment.

Thanks for your response.
