### ISSUE TITLE
"First Tab" not working

### ISSUE THREAD

**Issue by istrasci** [Robbendebiene/Gesturefy#267]
When I complete the gesture for **First Tab**, nothing actually happens.  However, **Last Tab** works as expected.

---

Gesturefy version: **1.2.0**
FF version:  **58.0.2**
OS:  **Windows 10/Linux Mint 18.3 Mate**

**Comment by Itchiii** [comment]
Maybe you're already in the first tab, but you did not include pinned tabs?
Or is the input field of the gesture red? Then this is already taken.

**Comment by istrasci** [comment]
No, it's not either of these scenarios.  I have Pinned tabs set to **On**, and the gesture is not red/duplicated.

**Comment by Robbendebiene** [comment]
Does it show "First Tab" when you enable the "Display action" property?
Another thing you can try to do is resetting the config under the "About" tab.

**Comment by istrasci** [comment]
Yes, it shows "First Tab" (I already had "Display Action" enabled).  Resetting also did not work.

**Comment by Robbendebiene** [comment]
Do you have any other extensions installed?

**Comment by istrasci** [comment]
Yes, several.  I will try on a clean FF install with Gesturefy as the only extension.

**Comment by istrasci** [comment]
Still does not work.  Here is the dump file of my gestures if it helps.
[Gesturefy 1.2.0.json.zip](https://github.com/Robbendebiene/Gesturefy/files/1838646/Gesturefy.1.2.0.json.zip)

**Comment by Robbendebiene** [comment]
Thanks for the file. I finally know the problem. You do not have any pinned tabs right? If you disable the option it should work, however it also should work with the option enabled. I'll fix this soon.

**Comment by istrasci** [comment]
Yes, if I disable **Include pinned tabs**, it works correctly (goes to the first non-pinned tab).
