### ISSUE TITLE
No Gestures on Blank new Tab

### ISSUE THREAD

**Issue by swueger** [Robbendebiene/Gesturefy#275]
Since Version 1.2.1 i can't use gestures on the newtab Site generated from the Addon "Blank new Tab"

**Comment by Robbendebiene** [comment]
Are you sure that this is related to the update? In other words, if you install the previous version does it work again?
Can you please send me a screenshot of the window that opens if you press  `ctrl + shift + I` on the new tab page?

**Comment by swueger** [comment]
when i go back to 1.2.0 it works.

![screenshot](https://user-images.githubusercontent.com/37861898/38016069-32e2827e-326e-11e8-9b7d-71b5f837bcbf.jpeg)

**Comment by Itchiii** [comment]
For me it doesn't work with Gesturefy 1.2.2 or 1.2.0.
Probably because the addon delete the body tag. (In contrast to the picture above).
Sometime in the console is:
`Error: Could not establish connection. Receiving end does not exist. - backgroundCommon.js` or 
`TypeError: document.body is null - gestureIndicator.js:165:1`

**Comment by swueger** [comment]
With 1.2.2 it works again but only after i opend and closed the new tab once.
The Problem seems to relay on the Operating System too. I have Problems on MacOS while on Windows i dont

**Comment by Itchiii** [comment]
That's strange. With Linux I have the exact behavior as with you with MacOS. But with Windows it doesn't work for me completely.

**Comment by 1fastp11** [comment]
I have the same problem. Open a new blank tab, gestures are disabled. 1.2.2

**Comment by Itchiii** [comment]
Hey @1fastp11 Yes that is known, see here #5 . Swueger said this in connection with the addon "Blank new Tab". Incidentally, a similar problem has been described here #108 .

**Comment by Robbendebiene** [comment]
Closed in an issue clean up process due to missing progress and/or information.
