### ISSUE TITLE
Recording gestures does not work

### ISSUE THREAD

**Issue by lkirbyl** [Robbendebiene/Gesturefy#276]
I've been trying to record Gestures, but it seems like this has stopped working (it definitely did previously).

What I'm doing:
* open addon preferences
* navigate to "gestures“ tab
* click on record button (recording overlay opens)
* Hold gesture button on mouse (I've tried it with all three buttons) and move the mouse
* recording overlay closes, but gesture remains unchanged.

What I'm running:
* Firefox 59.0.2
* Mac OS X High Sierra (or El Capitan on my private one, it works on neither)
* Gesturefy 1.2.1

**Comment by Robbendebiene** [comment]
I'll try to fix this as fast as possible. In the mean time you can either revert to the previous version or you can type the gesture via R L D U.

**Comment by Robbendebiene** [comment]
I updated Gesturfy, please tell me if the new version 1.2.2 fixed the problem for you.

**Comment by lkirbyl** [comment]
Yes, looks good. Thank you!
