### ISSUE TITLE
Feature Request: Previous/Next page by following links with customizable texts

### ISSUE THREAD

**Issue by flowwy** [Robbendebiene/Gesturefy#277]
First of all thank you very much for your work on this extension, full mouse gesture support is the one thing I was missing most on FF Quantum!

Please support commands "Previous page" and "Next page" which would follow links found on the current page that match customizable regular expressions.

The configuration could look like this:
For page back: Previous|Prev|Back|Older|<
For page next: Next|Newer|>

If the page contains a link which matches the regex, the command would have the browser follow that link.

This was so convenient! Browsing through web sites was a breeze and you didn't have to hit the sometimes tiny link to go to the next/previous page (e.g. in forums).

**Comment by Robbendebiene** [comment]
This is an interesting idea, but it is also hard to accomplish. Because searching for special keywords only, wont work if the "Next Page" button is an image or the keyword is written in a different language.

**Comment by ImJezze** [comment]
Back in the days of FireGesture there was a script included that search for such links. However, the script was very limited, but over time I extended it myself and was able to cover pretty much all link variations I came across.

You may find this script useful if you plan to implement this feature in Gesturefy.

[next-page-gesture.js.txt](https://github.com/Robbendebiene/Gesturefy/files/2216413/next-page-gesture.js.txt)

**Comment by Robbendebiene** [comment]
@ImJezze Thanks, I'll have a look into it.

**Comment by Robbendebiene** [comment]
Simple user scripts are now available with [Gesturefy 2.1.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.5). You should be able to use the script from @ImJezze by replacing the 

`var doc = FireGestures.sourceNode.ownerDocument;` with `var doc = document;`

For more information, please visit the [Wiki](https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script).
