### ISSUE TITLE
Wheelgesture compatibility with Tree Style Tabs

### ISSUE THREAD

**Issue by Knatan** [Robbendebiene/Gesturefy#279]
Hello, I used to use an old extension called Fire Gestures which let me execute whatever script I wanted upon triggering a gesture.
It specifically let me use these two codes for my Wheel Gesture:
```
/* Previous Tab - wrapped */
var tab = gBrowser.mCurrentTab;
if(tab.previousSibling)
  gBrowser.mTabContainer.advanceSelectedTab(-1, true);
```
```
/* Next Tab - wrapped */
var tab = gBrowser.mCurrentTab;
if(tab.nextSibling)
  gBrowser.mTabContainer.advanceSelectedTab(+1, true);
```
The advantage of using this code was its compatibility with this extension: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

Scenario: I have Tree Style Tabs, with several Child Tabs collapsed under a parent tab, but I want to scroll down to the next Parent tabs and skip the Child tabs that are currently collapsed.
Bug: With current Gesturefy settings the browser will uncollapse the Child Tabs, and scroll through all the Child tabs, instead of skipping to the other Parent Tabs.
Solution: By using the code above, the collapsed Child Tabs are skipped over.

Is there a possibility you can adopt this code in your extention?

**Comment by Robbendebiene** [comment]
I've added an example in the [wiki](https://github.com/Robbendebiene/Gesturefy/wiki/Send-message-to-other-addon).
I guess what you want is:

```
{
  "type": "focus",
  "tab": "nextSibling",
  "silently": true 
}
```

and
```

{
  "type": "focus",
  "tab": "previousSibling",
  "silently": true 
}
```
