### ISSUE TITLE
Gesturefy and Disqus problem

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#28]
- Set a gesture for open search text in a new foreground tab, in my case Right - Up;
- Visit a page with Disqus area like https://www.phonetoday.it/recensione-xiaomi-amazfit-bip
- Select a text inside the Disqus area in the bottom of page;
- The gesture doesn't work and the path draw line go crazy.

This happen on version 1.0.6, the previous 1.0.5 works fine.

**Comment by Robbendebiene** [comment]
That's an interesting bug, thanks for the report. It seems like the Gesture path always takes the last point of the previous gesture. But as far as I can see this is not related to "search text in new tab" or any other specific Gesture.

**Comment by Robbendebiene** [comment]
should be fixed: fbe4b33e860678d282e7a1f54e0aafad20221bf0

**Comment by happysurf** [comment]
Thank you, I wait for the new version.
