### ISSUE TITLE
 v.1.2.x Abnormally increased distance between mouse cursor and the drawn gesture

### ISSUE THREAD

**Issue by mikamiel** [Robbendebiene/Gesturefy#280]
From version 1.2 i've noticed abnormally increased distance between mouse cursor and the drawn gesture. I mean, drawn gesture is shifted / visually located far away from the cursor arrow. That occurs only when (page zoom is less than 100%  OR  page zoom is greater than 100%) AND page zoom mode set to "text only".
### 1)  page zoom 100% - all works as expected:
![100](https://user-images.githubusercontent.com/18242513/38364959-0f05345a-38f4-11e8-91d7-8e6942e06b3b.png)

### 2)  page zoom 110% - a small shift appears:
![110](https://user-images.githubusercontent.com/18242513/38364968-124a1c3e-38f4-11e8-92f4-7ded5321688a.png)

### 3)  page zoom 150% - much larger shift:
![150](https://user-images.githubusercontent.com/18242513/38364970-142b53c4-38f4-11e8-8ca8-96214dd58fd0.png)

**Comment by Robbendebiene** [comment]
I'll fix this bug after Mozilla implemented [this API](https://bugzilla.mozilla.org/show_bug.cgi?id=1340930).

**Comment by jefferysmall** [comment]
Just confirming that I also see this problem on many pages.

**Comment by Robbendebiene** [comment]
This bug is fixed with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
