### ISSUE TITLE
Can gesturefy EXPORT / ImMPORT it's settings/configuration ?

### ISSUE THREAD

**Issue by CookyHR** [Robbendebiene/Gesturefy#282]
This is a GREAT extension, I'd say perfect

Well, almost : 

I see the same gesturefy now works in different versions of the FireFox too . 

Now only one request (for now?) 
So that 'd be PERFECT if I could - somehow - 
- "**export**" the **setings** of gestures chosen/configured in one profile, 
then transfer that to another machine / user profile / whatever, 
- and **import** it again .

**Comment by Itchiii** [comment]
already implemented #3

**Comment by CookyHR** [comment]
thank you,
Though I 'd probably never 'd looked for that in 'about'. Will look for
it,  then sync between profiles and machines.
:-)

**Comment by Robbendebiene** [comment]
@CookyHR Make sure that you are at least using Firefox 57 with Gesturefy Version 1.1.10 otherwise this feature won't be available.
