### ISSUE TITLE
Feature request: Positioning of gesture names

### ISSUE THREAD

**Issue by internationils** [Robbendebiene/Gesturefy#283]
Hello,
the gesture names appear in the middle of the screen, and it's distracting. It would be great to be able to select placement for them both Vertically (bottom, middle, top) and Horizontally (left, middle, right)
If placed at the bottom, it could be right above the gesture sequences.
Thanks for making this addon work, I've been missing the gestures from Firegestures since the FF transition!

**Comment by Itchiii** [comment]
We understand your problem. However, there are some design choices that make it a bit difficult to solve the problem. But we will think about it :)

**Comment by Robbendebiene** [comment]
The positioning of the action/command name has been added with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
