### ISSUE TITLE
Wheel and rocker gestures: "stuck" action in certain tabs

### ISSUE THREAD

**Issue by wingpin6** [Robbendebiene/Gesturefy#286]
I have set my wheel gestures to page down/up and rocker gestures to change tabs. In autohotkey, this is what I have it set up as:

;-----rocker gestures----
~RButton & LButton::SendInput, ^+{tab}
return
~LButton & RButton::SendInput, ^{tab}
return

;-----wheel gestures-----
~RButton & WheelUp::SendInput, {PgUp}
return
~RButton & WheelDown::SendInput, {PgDn}
return

But with AHK, it is difficult to escape out of the right-click context menu after the action is executed. I disabled my AHK script while using Firefox/Gesturefy to make sure it is not affected with one another to troubleshoot this issue.

The great thing about Gesturefy is that Gesturefy offers the same gestures/customization that I am looking for, and the context menu does not appear with right-click gestures. 

I will use AHK terminology since it is easier for me to explain this issue. Something about the wheel/rocker gestures (doesn't matter if I use left, middle or right mouse button in the case of wheel gesture) in Gesturefy (and even FoxyGestures) will trigger something similar to {ctrl down} in certain tabs. 

It is not really {ctrl down}, because I can type normally within the tab. This means that if I click "w" on my keyboard, it doesn't trigger a close tab via ctrl+w. But when I scroll up it zooms in and if I scroll down, it zooms out, similar to holding ctrl and using the scroll wheel to zoom in/out. The only way to "exit" this zoom in/out scrolling is to tap the right-button again (esc, left ctrl or right ctrl has no effect). If I disable rocker/wheel gestures, then this problem does not happen. In addition, this problem did not occur with FireGestures. Nor does this problem occur with my AHK script.

I cannot replicate this issue 100% of the time; it happens maybe 50% of the time with Gesturefy. I noticed it has a greater chance of occurence when switching tabs with rocker gestures or using browser back/forward which I have set up as right-click + mouse-left gesture and right-click + mouse-right gesture respectively. This issue does not occur if I manually press ctrl+tab or ctrl+shift+tab on my keyboard to switch tabs. I have to disable both wheel gestures and rocker gestures for this issue to not occur. Even though my wheel gestures has no role in changing tabs/changing webpages, the issue occurs if it is on. 

Hope this was understandable; let me know what additional info you need (on latest stable Firefox release with uBlock Origin/Cookies Autodelete/Decentraleyes as my only add-ons).

**Comment by wingpin6** [comment]
So I found that this is actually a conflict between Gesturefy and another add-on called Zoom Page WE (which I use because it seems that there is no default way to set global zoom in Firefox), which has the option to scroll with right-click and zoom wheel turned on by default. Don't know if you want to look into this, but I will close this case. Thanks for your hard work.

**Comment by Robbendebiene** [comment]
@wingpin6 Thanks for your investigation. You can turn off site specific zooming in the about:config as far as I know (`browser.zoom.siteSpecific`) if that's what you want.
