### ISSUE TITLE
Screen flashes as you close/switch tabs with a gesture

### ISSUE THREAD

**Issue by ghost** [Robbendebiene/Gesturefy#287]
Every now and then when I close a tab with a gesture, the screen flashes momentarily before it closes the tab and switches to the next one. It's quite annoying since I discovered this has been affecting my eye health negatively after regular browsing.

Here's a video of it: https://youtu.be/Y2edzCOczgk

As you can probably see, when I use RMB + drag mouse up to close a tab this creates a flashing screen (with a few exceptions).

It never happens if I close the tab manually (Ctrl + W or press the X on the tab).

Edit: This might be related to some API limitation. The same thing happens when I close a tab in Chrome with the add-on crxMouse Chrome Gestures.

Windows 10 Pro x64 (1709 Build 16299.371)
Latest Firefox x64 (59.0.2)
Gesturefy 1.2.2

**Comment by Robbendebiene** [comment]
Hi and thanks for your detailed report.
Unfortunately I do not have the ability to fix this. The best thing you can do, is to create a new ticket [here](https://bugzilla.mozilla.org/enter_bug.cgi#h=dupes%7CToolkit), but I'm afraid that this might be a rare problem and therefore won't get such a high priority.

For the ticket it might be important to point out that my addon is just calling the [tabs.remove()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/remove) function to close the tab.

**Comment by ldgbc** [comment]
Seem to be only affecting certain website, might be due to CSS? I know Youtube is one of the culprit but doesn't notice it with other website.

Perhaps it only related to video stream website?

**Comment by cxrn** [comment]
Sorry for the late reply, but I appreciate the replies.

I'll create a ticket at Mozilla and look further if something can be done.

I'll also see if I experience the same thing on other devices.

> 
> 
> Seem to be only affecting certain website, might be due to CSS? I know Youtube is one of the culprit but doesn't notice it with other website.
> 
> Perhaps it only related to video stream website?

It's a global issue for me and not specific to certain websites.

**Comment by Tesserakt-company** [comment]
I think this might affect me as well, but my loading times are about a second long. I'll keep an eye on it, but I think something was done and I don't get them as often anymore.

**Comment by Robbendebiene** [comment]
I'm closing this since it's not in our abilities to fix this.
