### ISSUE TITLE
Save picture

### ISSUE THREAD

**Issue by netseawolf** [Robbendebiene/Gesturefy#289]
### Add choice in gesture SAVE PICTURE
Add SAVE PICTURE AS
because save picture only do not remember the last saved folder for a website
and "Save picture as" have this function under Firefox and in this case the last saved directory is used

### Your System
- Operating system: Win 10
- Firefox version: 59.0.3
- Gesturefy version: 1.2.2

**Comment by Itchiii** [comment]
Unfortunately, this is currently not possible due to API limitations. This is described in detail here: #145

**Comment by Robbendebiene** [comment]
Duplicate of #145
