### ISSUE TITLE
Scroll gesture doesn't work on text page

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#29]
The gesture scroll on top and scroll on bottom doesn't work in page like this:
https://www.fanboy.co.nz/fanboy-cookiemonster.txt

**Comment by Robbendebiene** [comment]
Thanks. Scroll to top is working for me only the scroll to bottom Gesture has no effect.

**Comment by Robbendebiene** [comment]
fixed: 604a8012043b61ae3ab16a62d87a4844f08066c9

**Comment by happysurf** [comment]
Yes, only scroll on bottom doesn't work.
Thanks for the fast fix.
