### ISSUE TITLE
values resetting to default

### ISSUE THREAD

**Issue by GianniGi** [Robbendebiene/Gesturefy#290]
### Describe your matter in detail

Modify any options, for example default action for a gesture.
After reboot, or after restarting firefox, you'll find that some option have reset to the default value, and that other options, while the value has been set, act as if they're still at the default value. 

### Your System
- Operating system: windows 10
- Firefox version: 60 
- Gesturefy version: latest

**Comment by Robbendebiene** [comment]
Does this only happen if you immediately close/restart firefox without switching to a different tab or closing the settings tab?
