### ISSUE TITLE
Reload frame

### ISSUE THREAD

**Issue by mriveaux** [Robbendebiene/Gesturefy#291]
### Reload frame
In the right menu **This frame -> Reload frame** doesn't exist any gestures. That will be awesome for developers who need this option. Sorry for my english, it's not my mother language. I speak spanish.

### MySystem
- Operating system: Windows 10 Fall Creators/ Ubuntu Mate 16.04:
- Firefox version: 60
- Gesturefy version: 1.2.2

**Comment by Robbendebiene** [comment]
This has already been requested and will be implemented in the upcoming major version :)

**Comment by Robbendebiene** [comment]
Duplicate of https://github.com/Robbendebiene/Gesturefy/issues/250
