### ISSUE TITLE
Save  image save files with % in names 

### ISSUE THREAD

**Issue by shinji2009** [Robbendebiene/Gesturefy#292]
hi
Save image save files with % in names if they are not in english (as i think).
link for example http://joyreactor.cc/post/3484061
op picture saves as KatRaccoon-%D0%9A%D0%BE%D0%BC%D0%B8%D0%BA%D1%81%D1%8B-%D0%BA%D1%83%D1%80%D1%8B-4442270.jpeg
but if save via context menu or ctrl+s it will be saved as KatRaccoon-Комиксы-куры-4442270.jpeg (which is correct and expected behavior)
please fix

win8.1
moz 60.0.1
gest 1.2.2

**Comment by Robbendebiene** [comment]
Thanks for the report.
This will be fixed in the upcomming major release.
