### ISSUE TITLE
A way to, all in one, open tab+paste+go?

### ISSUE THREAD

**Issue by 3d73a4a412** [Robbendebiene/Gesturefy#293]
### Describe your matter in detail

No issue per se, this is more of a question/feature request.
Is there currently a way to setup a gesture that would, all-in-one, create a new tab, paste the contents of the copy buffer, go/enter?
If not, that would be a really useful feature as I find myself needing to search for things from other applications Word, outlook, other browsers, etc 
Thanks!!!

### Your System
- Operating system: win/lin
- Firefox version: ESR / Quantum
- Gesturefy version:

**Comment by Robbendebiene** [comment]
Hey, thanks for your feature request.
There is a similar request for urls: https://github.com/Robbendebiene/Gesturefy/issues/144 but I guess you want to do a websearch with your clipboard contents right?
