### ISSUE TITLE
Close Tab gesture sometimes closes two tabs.

### ISSUE THREAD

**Issue by wupme** [Robbendebiene/Gesturefy#295]
### Describe your matter in detail
Sometimes when i use the gesture to close a tab, it closes two tabs at the same time.
This happens randomly, but approximately 5-10% of the time i use this gesture.

I changed the gesture to "Right-Left", and its literally the only gesture i have not deactivated, because its the only one i really need.

### Your System
- Operating system: Windows 10 enterprise (1709)
- Firefox version: 60.0.1 64bit
- Gesturefy version:  1.2.2

**Comment by Robbendebiene** [comment]
Hey, it is unlikely that Gesturefy is causing this problem. Do you have any other addons installed, or can you reproduce the bug on a clean Firefox profile? Also your config file could be helpfull, you can export it in the settings page under "about".

**Comment by wupme** [comment]
I'm a complete moron.
My GF installed another Gesture addon, and both had the same gesture for closing the tab. I'm sorry.
