### ISSUE TITLE
Implementation of new functions

### ISSUE THREAD

**Issue by BlagoYar** [Robbendebiene/Gesturefy#296]
1. "Save object as ..." - Is it possible to implement this function?
2. Can you make settings for pdf when saving to pdf? General settings are not picked up.

**Comment by Robbendebiene** [comment]
> "Save object as ..." - Is it possible to implement this function?

What do you mean by "Save object as..."? Currently there is a "Save image/Download image" action if you are looking for that. Or do you mean saving every media file which is described in this issue: https://github.com/Robbendebiene/Gesturefy/issues/134

> Can you make settings for pdf when saving to pdf? General settings are not picked up.

What settings do you need for the "save to pdf" action?
