### ISSUE TITLE
手势功能鼠标轨迹显示不正常

### ISSUE THREAD

**Issue by leoninemess** [Robbendebiene/Gesturefy#299]
### Describe your matter in detail
手势功能鼠标轨迹显示不正常

### Screenshots or further assistance
![效果图片](https://user-images.githubusercontent.com/10096945/40713254-06f15426-63ef-11e8-86f3-6616b0fe4292.png)

### Your System
- Operating system: win10 64位
- Firefox version: 60.0.1 (64 位)

- Gesturefy version:

**Comment by Robbendebiene** [comment]
First things first, please try to write in english. Second, please describe steps to repdoruce the problem, otherwise I'm not able to help you. At least it's working for me as expected on https://www.baidu.com/
