### ISSUE TITLE
Add config export and import

### ISSUE THREAD

**Issue by Robbendebiene** [Robbendebiene/Gesturefy#3]
Allow to export and import the current addon configuration.

**Comment by stmr** [comment]
Is it possible to utilize Firefox sync with config? For example to have the same settings on all linked devices? Or does it work this way already? :D

**Comment by Robbendebiene** [comment]
It's possible, but currently the settings are only saved on the local computer. Mainly because some people may want addon sync enabled but also different settings on different devices (like me :D) So I'll need to add a toggle button which enables/disables sync for gesturefy.

**Comment by happysurf** [comment]
Today I have start with a clean profile in Firefox 57beta and I have reinstall all extension included Gesturefy.
I had to manually enter all my gestures, for that please add the Import - Export feature.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/021a1f2b47a261a559b282195d838418823dd9b9
