### ISSUE TITLE
Toolbar download button in private mode

### ISSUE THREAD

**Issue by Matthewus** [Robbendebiene/Gesturefy#300]
### Describe your matter in detail
1. If i download a picture with mouse gesture in a private window the download button in the toolbar does not show up, but the downloaded file shows up in the download folder in Firefox. Is this a bug or a API limitation?
2. Also would it be possible to make gifs from Twitter downloadable with the Save image gesture?
3. Could the settings page run in a private window?
### Your System
- Operating system: Windows 10 64 bit
- Firefox version: Firefox 60.0.1 64 bit
- Gesturefy version: 1.2.2

**Comment by Robbendebiene** [comment]
> If i download a picture with mouse gesture in a private window the download button in the toolbar does not show up, but the downloaded file shows up in the download folder in Firefox. Is this a bug or a API limitation?

This seems to be a Firefox bug, you can create a ticket here: https://bugzilla.mozilla.org/enter_bug.cgi#h=product%7C

> Also would it be possible to make gifs from Twitter downloadable with the Save image gesture?


Twitter gifs aren't actual gifs, they are videos.

> Could the settings page run in a private window?

This will be possible in the next version (Gesturefy 2.0)

**Comment by Robbendebiene** [comment]
@Matthewus Yes, this is considered "normal", even though I would like to change it if there was an easy way to determine the file extension. Btw did you create a ticket on bugzilla.mozilla.org?

**Comment by Matthewus** [comment]
Yes, i hope i did it correctly, never used Bugzilla before. https://bugzilla.mozilla.org/show_bug.cgi?id=1469121

**Comment by Robbendebiene** [comment]
Even though this bug still hasn't been fixed in Firefox I'm closing this issue since it's entirely related to Firefox. I'm still following the bugzilla ticket though.
