### ISSUE TITLE
"[Popup] All tabs" to customizable "Last open N tabs"

### ISSUE THREAD

**Issue by Dituar** [Robbendebiene/Gesturefy#301]
Hi, please add additionally to gesture "[Popup] All tabs" to customizable "Last open N tabs", like Ctrl+Tab in Firefox, when (browser.ctrlTab.previews is true) it enabled in settings.
For exapmle, if N=7 http://i104.fastpic.ru/big/2018/0610/6c/_3692c8e2df1426757a4fce49de21fd6c.jpg, not all tabs, only last open 7 tabs in order of opening. 

- Operating system: win 7 64
- Firefox version: 60.0.2 (64-bit)
- Gesturefy version: 1.2.2

**Comment by Robbendebiene** [comment]
Hey, how about an extra setting for the  "[Popup] All tabs" action to change the tab order in the displayed popup?

**Comment by Dituar** [comment]
Then it turns out, it will be necessary to display the order of all open tabs, and if the user has a lot of them (like me)? Would not it be wasting a lot of memory?
It seems to me that people have tabs in a certain order and remember this order, so sometimes you need to preserve the original order. That's why I think just now, even better to do the "Last open N tabs" function separately, so that you can assign a gesture to "[Popup] All tabs", and another gesture to "Last open N tabs".

**Comment by Robbendebiene** [comment]
Available since [Gesturefy 2.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.0.4)

**Comment by Dituar** [comment]
Thank you very much!

**Comment by Dituar** [comment]
u r the best! :-D

**Comment by Robbendebiene** [comment]
Haha, always nice to hear that :-)
