### ISSUE TITLE
Support For Plain JavaScript Execution On A Gesture Action

### ISSUE THREAD

**Issue by klingel** [Robbendebiene/Gesturefy#304]
_Feature Description_
The ability to execute plain JavaScript on a "Gesture Action" would enable us to do anything we can do with plain JavaScript on the current page - which is quite a lot and of great use. I do not suggest the implementation of a full-fledged elaborated API here as in Feature Request "User Script support #58".

_Example Usage_
With FireGestures I used some plain JavaScript without any of its [Scripting API objects](http://www.xuldev.org/firegestures/makescripts.php) to toggle the language of Wikipedia articles de<-->en by analysing page content and setting a new `window.location`.

_Alternative Solution Via Bookmark(let) Invocation To JavaScript Execution_
The simple and eventually easier solution would be just to support the ability to invoke a bookmark on a "Gesture Action". Then we could assign a special kind of bookmark - a [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet) to execute JavaScript.

**Comment by Robbendebiene** [comment]
> The ability to execute plain JavaScript on a "Gesture Action" would enable us to do anything we can do with plain JavaScript on the current page 

This seems like a good idea with quite a lot of possible use cases.

**Comment by Robbendebiene** [comment]
Due to security reasons I delayed this feature until [this API](https://bugzilla.mozilla.org/show_bug.cgi?id=1437861) is implemented, which should be quite soon.

**Comment by Robbendebiene** [comment]
Simple user scripts are now available with [Gesturefy 2.1.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.5).
Look for the "Execute User Script" command at the bottom of the command bar.

For more information, please visit the [Wiki](https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script).
