### ISSUE TITLE
Next Tab and Previous Tab do not work with Hidden Tabs like Ctrl-Tab does

### ISSUE THREAD

**Issue by bakkerthehacker** [Robbendebiene/Gesturefy#306]
With newer Firefox versions, other extensions such as [Panorama View](https://addons.mozilla.org/en-GB/firefox/addon/panorama-view/) might hide some tabs.  Cycling through tabs using Ctrl-Tab and Ctrl-Shift-Tab (or Ctrl-PageUp/Ctrl-PageDown) respects the hidden tabs and will only cycle through the tabs that are visible, wrapping around correctly when moving off the end. 

When using Gesturefy's Next Tab or Previous Tab, the selected tab might switch to one of the hidden tabs instead of staying on the currently visible tabs.  

Steps to reproduce:
 - Install Gesturefy
 - Install Panorama View
 - Set `extensions.webextensions.tabhide.enabled` to true
 - Create some tab groups in Panorama View
 - Use Ctrl-Tab to switch tabs correctly stays in the tab group
 - Use Gesturefy to switch tabs incorrectly moves to the other tab group.  

OS: linux mint 17.3
Firefox: 61.0
Gesturefy: 1.2.2

**Comment by Robbendebiene** [comment]
As far as I know this is a bug on Mozillas side. At least [this document](https://wiki.mozilla.org/WebExtensions/TabHiding) states that hidden tabs should be excluded by default, when using `browser.tabs.query()` (especially in terms of compatibility to other browsers).
I've created a test addon which clearly shows that this is currently not the case: [testAddon.zip](https://github.com/Robbendebiene/Gesturefy/files/2172051/testAddon.zip)
Can you please create a bug report on [bugzilla](https://bugzilla.mozilla.org), explain the problem and attach the test addon?

**Comment by bakkerthehacker** [comment]
I'm not certain that documentation is entirely up to date.  

The [tab section in mozilla's web extension docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) shows `hidden` as a tab attribute and has no other information about querying hidden tabs.

**Comment by bakkerthehacker** [comment]
See marklieberman/foxygestures#256 for the FoxyGestures version of this issue.  The queries had to be slightly modified to account for `hidden` and all the index based tab stuff had to be changed.
