### ISSUE TITLE
Feature Request -- Please add in fields for "About Firefox" and "Page Info"

### ISSUE THREAD

**Issue by TexasMedic** [Robbendebiene/Gesturefy#308]
### Describe your matter in detail

This is the best mouse gestures addon I have seen for Firefox in a long time.  Great job!

I would like to make a Feature Request to add in fields for "About Firefox" and "Page Info" to the
Gestures section.

### Your System
- Operating system:  Windows 10 Enterprise Version 1803
- Firefox version:  61.0.1 (64-bit)
- Gesturefy version:  1.2.2

**Comment by Robbendebiene** [comment]
> This is the best mouse gestures addon I have seen for Firefox in a long time. Great job!

Thanks, it's always nice to hear something like that.

> "About Firefox"

Do you mean opening the about window which shows the current version and additional information of Firefox? If so then this is currently not possible due to Firefox API limitations and the same applies to opening the "Page Info".

**Comment by Robbendebiene** [comment]
I'm closing this, since it is unlikely that Mozilla will implement an API for this.
