### ISSUE TITLE
#226 may need to be reopened

### ISSUE THREAD

**Issue by smithxl** [Robbendebiene/Gesturefy#309]
Looking for a feature that Simple Mouse Gestures has, I found #226 which is described as "New Tab gesture opens at Home Page (or any designated URL)". When I tried the suggested solution, using Home Page and specifying the URL of the desired page, it opens in the current page, not in a New Tab.

Your UI knocks spots off Simple Mouse Gestures but loses on this particular ability which I use a lot.

**Comment by smithxl** [comment]
Clarification:
I should have said "opens in the current TAB, not in a New Tab".

**Comment by Robbendebiene** [comment]
This will be possible soon in Gesturefy version 2.0.
