### ISSUE TITLE
Gesture: scroll page wise up and down

### ISSUE THREAD

**Issue by Jerry-1984** [Robbendebiene/Gesturefy#31]
这扩展为什么没有上下翻页的手势呢？
Why does this extension not have up and down gestures?

**Comment by Robbendebiene** [comment]
Of course it does, or what do you mean with "up" and "down" gestures?

**Comment by Jerry-1984** [comment]
page up and page down

**Comment by Robbendebiene** [comment]
So you mean scroll to top and bottom? They both exist and should be right after the "previous tab" gesture. Maybe they are mis-translated?

**Comment by uegajde** [comment]
你是指將`http://anywebsite/article/2`
切換成`http://anywebsite/article/1` 或 `http://anywebsite/article/3`的功能嗎?

Do you mean the function to switch from `http://anywebsite/article/2`
to `http://anywebsite/article/1` or `http://anywebsite/article/3`?

**Comment by Jerry-1984** [comment]
Not  scroll to top and bottom，I mean rolling up and down a screen

**Comment by Robbendebiene** [comment]
I still don't get it. Maybe you can explain it in more detail to me, or show me a video. For me it sounds like the functionality of the middle mousebutton click.

**Comment by uegajde** [comment]
所以你是只滑動畫面的長度?

or, do you mean only scroll for the length of the window?

**Comment by Jerry-1984** [comment]
> or, do you mean only scroll for the length of the window?

Yeah, that's what I mean, equivalent of hitting the pageup and pagedown keys on the keyboard
相当于按下键盘上的 pageup 和 pagedown 键

**Comment by Robbendebiene** [comment]
Ahh I get it. I'll add it to the upcoming version.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/55828ab71036c25a9425e132ec420efb36eb8c7f, https://github.com/Robbendebiene/Gesturefy/commit/66007bb6290de5ac09767284976136b29ec1477f
