### ISSUE TITLE
Feature request: show action at the bottom beside the direction arrows

### ISSUE THREAD

**Issue by LupinIII** [Robbendebiene/Gesturefy#312]
I usually use the display of the action only as a kind of "debugging" to see what gesture was recognized. But the popup right at the center of the screen is way too intrusive to leave the feature on. Could you implement an option that can be shown in the same line as the direction arrows right at the bottom of the screen?

**Comment by ldgbc** [comment]
Add CSS support instead then? That way all option/location can be modify as suited.

**Comment by Robbendebiene** [comment]
The positioning of the action/command name has been added with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
