### ISSUE TITLE
Cancel mouse gesture if rocker gesture was successful

### ISSUE THREAD

**Issue by redactedscribe** [Robbendebiene/Gesturefy#320]
Thank you for the extension.

Gesture button set to: right-click

There is an improvement I'd like to see. In the case of holding right-click and then pressing left-click to initiate a rocker gesture, if one moves the mouse, a normal gesture can be performed (since right-click is assigned to perform gestures). This seems bad as accidental extra gestures can be made when the intention is to only perform a rocker gesture.

Ideally, once the left-click has been pressed whilst holding the right-click, require the user to press right-click again if they want to do a further "normal" gesture. This will stop the possibility of a second gesture being performed accidentally after a right- to left-click rocker gesture is made.

Thank you.

Gesturefy, Version: 2.0.0
Firefox 61.0.1
Windows 10 v1803

**Comment by Robbendebiene** [comment]
Thanks for your enhancement suggestion, but it's already on our list :)

**Comment by Robbendebiene** [comment]
Duplicate of https://github.com/Robbendebiene/Gesturefy/issues/123

**Comment by redactedscribe** [comment]
Apologies, I searched but failed.
