### ISSUE TITLE
Gestures not working after update

### ISSUE THREAD

**Issue by revteedub** [Robbendebiene/Gesturefy#322]
### Describe your matter in detail

Gesturefy worked fine yesterday.
Gesturefy updated today, and now I cannot use any gestures.

### Your System
- Operating system: Windows 7 Pro SP1
- Firefox version: Firefox Quantum v61.0.2 (32bit)
- Gesturefy version: 2.0.1

**Comment by Robbendebiene** [comment]
Hey, please try to update gGesturefy under about:addons it should be the same bug as reported here: https://github.com/Robbendebiene/Gesturefy/issues/321

**Comment by revteedub** [comment]
Updated after the auto update, via the "check for updates" in about:config.  Works great now, thanks for the response!
