### ISSUE TITLE
Rocker Gestures open new tab

### ISSUE THREAD

**Issue by scottfweintraub** [Robbendebiene/Gesturefy#323]
### Describe your matter in detail

When I rocker back, I get the prior page in a new tab.  I want the current tab to be reused.  I do have browser.search.openintab set to True, but that doesn't seem appropriate.  I would like search to open new tabs but leave the back button (or things that mimic it) staying in the same tab.
### Your System
- Operating system:   Windows 10 Insider 17733
- Firefox version: 61.0,2
- Gesturefy version: 2.0.1

**Comment by scottfweintraub** [comment]
I just went back to retest it and now this is not happening.  What can cause that to be instable?

**Comment by Robbendebiene** [comment]
Sorry I'm unable to understand your problem correctly. Are you using the "Search selected text" command for Rocker gestures? If so then `browser.search.openintab` has no effect on it (because I cannot read the value of the property).
