### ISSUE TITLE
[Feature Request] Duplicate Option in Open in New Tab Settings

### ISSUE THREAD

**Issue by aksh1618** [Robbendebiene/Gesturefy#324]
First of all, thanks for making and maintaining this amazing extension, and v2.0 is looking really good! 

As to the feature request, It'd be really helpful if the `Open link in new tab` setting includes an option to duplicate the current tab if no URL or link was selected. Or, if possible, the ability to select any other command in this case would be even better.

**Comment by Robbendebiene** [comment]
Hi, I'm glad you like the new version :)

Even though your feature request may seem a little bit different to https://github.com/Robbendebiene/Gesturefy/issues/313 the solutions I think of are equal. Therefore I'm linking this issue to the other and closing this one.
