### ISSUE TITLE
Active Send Keyboard Keypress Command

### ISSUE THREAD

**Issue by ldgbc** [Robbendebiene/Gesturefy#325]
### Describe your matter in detail
Is it not possible yet to send keyboard command? For example, gesture to send a "Ctrl+A" or "Ctrl+S", etc?

### Screenshots or further assistance
N/A

### Your System
- Operating system: Windows
- Firefox version: Firefox 61
- Gesturefy version: 2.0

**Comment by Robbendebiene** [comment]
Unfortunately that is not possible and will probably never be possible. I can only mimic these keyboard combinations (at least most of them).

**Comment by ldgbc** [comment]
Mimic keyboard? So some key still work?

How many years will this issue be open. Curse Mozilla.

**Comment by Robbendebiene** [comment]
> Mimic keyboard? So some key still work?

No, I mean that I can rebuild/reprogram some of the functionality (like opening a new tab for example).

**Comment by Robbendebiene** [comment]
I'm closing this issue, since it seems very unlikely that the Firefox developers will add an API for this (mainly for security reasons).
