### ISSUE TITLE
Open homepage gesture doesn't work

### ISSUE THREAD

**Issue by ericsubach** [Robbendebiene/Gesturefy#326]
Open homepage gesture doesn't work. When I try to use it, I get a popup that says: "OpenHomepage" command failed. The target URL cannot be opened. Click here for more information. (which just goes to https://github.com/Robbendebiene/Gesturefy/wiki/Illegal-URL)

This issue has existed since before the most recent major update.

### My System
- Operating system: Windows 10 x64
- Firefox version: 61.0.2 (64-bit)
- Gesturefy version: 2.0.2

**Comment by Itchiii** [comment]
Which URL did you try to call?
If it's Firefox's default URL (about: home) then it will not work, since Firefox does not allow it.
See #305 

And yes, the wiki is currently only used as a placeholder but will be filled soon.

**Comment by ericsubach** [comment]
My mistake, this is a duplicate of #305.
