### ISSUE TITLE
Fixed tab in firefox cannot be closed

### ISSUE THREAD

**Issue by polyphemus86** [Robbendebiene/Gesturefy#328]
### Describe your matter in detail

After the latest update, the fixed tabs in firefox cannot be closed by mouse gesture. But they can be closed before the update.

### Your System
- Operating system: Win10
- Firefox version: 61.0.2
- Gesturefy version: 2.0.2

**Comment by jdreesen** [comment]
Right, it doesn't work for me, too. No matter whether the option is on or off.

**Comment by Robbendebiene** [comment]
Fixed in Gesturefy 2.0.3

**Comment by polyphemus86** [comment]
Yes I found it has been fixed, Thank you!
