### ISSUE TITLE
Option to use UDRL instead of arrows for gesture directions

### ISSUE THREAD

**Issue by bazzik** [Robbendebiene/Gesturefy#329]
This is Feature Request.

**I would like to have an option to use UDRL letters instead of actual arrow icons for gesture direction.**

Reading arrows is MUCH harder and quite confusing (and therefore time consuming) than UDRL kind of abbreviation where first letter already stands for direction.

For example, if I need to see what gesture that is... then I will have hard time figuring this one out:
![image](https://user-images.githubusercontent.com/1482298/44206266-27fb3e80-a151-11e8-92de-b867cbfa2738.png)

**P.S.** I have noticed that if I select directions on a screenshot above and copy it, I will get "DRUL" in clipboard. So it would be just a matter of not applying that specific font ("firefox-gesture-arrows").

I guess I can override it using Stylus kind of extension (that applies user CSS based on domain)... but I would like to avoid it if possible.

#### Your System
- Operating system: Windows 10 Pro (1803) x64 Build 17134.228
- Firefox version: 61.0.2 x64
- Gesturefy version: 2.0.2

**Comment by Robbendebiene** [comment]
This feature request is now obsolete with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
