### ISSUE TITLE
http://www.ifeng.com/ 不能显示手势路径

### ISSUE THREAD

**Issue by cqcw123** [Robbendebiene/Gesturefy#331]
### Your System
- Operating system:
- Firefox version:
- Gesturefy version:

windows 7 
firefox 61.0.2
Gesturefy 2.0.2

http://www.ifeng.com/ 不能显示手势路径

**Comment by Robbendebiene** [comment]
(I do not speak Chinese, but I guess you mean that the Gesture path is not visible?) It's working for me, so please provide additional information:
1. what is not working exactly and maybe steps to reproduce
2. your settings (you can export them in the add-on settings under "About" via "Backup"

**Comment by cqcw123** [comment]
disable the  Adblock Plus,Gesture is working properly.
