### ISSUE TITLE
[Feature Request] - omit trailing / in URL Hierarchy Up

### ISSUE THREAD

**Issue by RheingoldRiver** [Robbendebiene/Gesturefy#333]
For most sites this doesn't matter, but on wikis if the trailing / is left at the end of the URL, it's treated as a different page from the intended target.

Example - https://lol.gamepedia.com/Faker/Match_History should send to https://lol.gamepedia.com/Faker but instead sends to https://lol.gamepedia.com/Faker/ which doesn't exist when using the URL Hierarchy Up gesture.

Could this be added as a setting to this gesture? Thanks!

**Comment by Robbendebiene** [comment]
What you describe seems like the correct behavior to me. So I would change this in general and always remove the / at the end. Or are there any downsides of it?

**Comment by RheingoldRiver** [comment]
I can't think of any downsides, I just assumed it was like this deliberately so I suggested option instead of change completely.

**Comment by Robbendebiene** [comment]
This should work now since Gesturefy 2.0.3

**Comment by RheingoldRiver** [comment]
Works perfectly, thank you!
