### ISSUE TITLE
A restart of Firefox was needed after update of Gesturefy

### ISSUE THREAD

**Issue by Sopor-** [Robbendebiene/Gesturefy#338]
### Describe your matter in detail
After updating to Gesturefy 2.0.3 the Gesturefy stopped working and i was forced to restart Firefox.
If restart is needed it should tell the user that they need to restart Firefox.

### Your System
- Operating system: Windows 8.1 64-bit
- Firefox version: 61.0.2 64-bit
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
If it happens again please leave a comment here and post the browser console log. You can open the browser console by pressing ctrl + shift + J
