### ISSUE TITLE
Extension not installed by FF Sync

### ISSUE THREAD

**Issue by bubblefoil** [Robbendebiene/Gesturefy#339]
I have installed Firefox on a new system and signed in to my Sync account. FF installed the addons I use on other machines. It did not install Gesturify.

### System
- Operating system: Windows 10
- Firefox version: 61.0.2 (64-bit)
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
You can try to force sync on the computer where Gesturefy is installed and then force sync on the computer where it's not. Thats the only idea I have :|
![sync](https://user-images.githubusercontent.com/13716661/45213547-22000580-b298-11e8-919a-674e4ec9bde8.PNG)
