### ISSUE TITLE
Link to new window 

### ISSUE THREAD

**Issue by glennpeace** [Robbendebiene/Gesturefy#340]
Hello, it'd be cool if the "Open link to new window" gesture could also open an empty window if executed without going over a link.

This would be similar to the option offered by "Open link in new tab" but resulting in a new window.

- Provide detailed steps explaining how to reproduce the problem
When adding a gesture for "Open link to new window" I was expecting to see the option for an empty window.

- System info like: Operating system, Firefox version, Gesturefy version
 Gesturefy, Version: 2.0.3 on Firefox version 61.0.2 (64-bit) on OSX 10.13.6

- The website where you've encountered the problem, if any
NA

- Optionally include screenshots or screen recordings if they help clarify your problem
My suggestion is to mimic this for "Open link in new window"
![image](https://user-images.githubusercontent.com/43011216/45111066-3958ba80-b101-11e8-842c-9ac45c2d2c77.png)

**Comment by Robbendebiene** [comment]
This is a good idea. I'll add this in the next version.

**Comment by Robbendebiene** [comment]
Available since [Gesturefy 2.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.0.4)
