### ISSUE TITLE
Feature Request: Search from clipboard in new tab

### ISSUE THREAD

**Issue by yuguious** [Robbendebiene/Gesturefy#341]
Great add on. Now that ESR has gone quantum, one thing i missed from a previous addon was the ability to search for something from a different program (with ease) using the clipboard.

 IE:
browser.tabs.create({
      url: settings.searchEngineURL + clipboardText,
      .....

Thanks for the great work.

**Comment by Robbendebiene** [comment]
Sounds like a reasonable command. We will add this in the next version which will be released with Firefox 63 :)

**Comment by ldgbc** [comment]
Currently it can open URL from clipboard

**Comment by Robbendebiene** [comment]
Available since [Gesturefy 2.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.0.4)
