### ISSUE TITLE
OpenLinkInNewTab command should return if data does not contain a link

### ISSUE THREAD

**Issue by josh-snoek** [Robbendebiene/Gesturefy#342]
When running this command on a non-link element or blank area of the page, the index is still incremented by however many times the command is run. If it is then run on an actual link (without changing the current tab), the new tab will "jump" over that many tabs.

**Comment by Robbendebiene** [comment]
Thanks for reporting this. We will fix it in the next version.

**Comment by Robbendebiene** [comment]
Available since [Gesturefy 2.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.0.4)
