### ISSUE TITLE
Open Homepage Does Not Work Without Protocol Being Specified

### ISSUE THREAD

**Issue by JamieMeyers** [Robbendebiene/Gesturefy#343]
### Describe your matter in detail
When using the open homepage gesture with a custom, non-local file, URL **without** the protocol (`https://` or `http://`, etc.) being specified, the URL opened is `moz-extension://4c6c09b9-c9ce-47ec-8be8-34d776d685df/<HOMEPAGE_URL>` not `<HOMEPAGE_URL>`. When using a URL with the protocol specified, this issue is not seen.

#### Steps to reproduce:
1. Go to `about:preferences#home` and set the homepage and new windows to custom URL and use `google.com` as the home page.
1. Create a new gesture with Command "Open Homepage"
1. Perform the created open homepage gesture.

#### Expected Results:
The url `google.com` will be displayed.
#### Actual Results:
The url `moz-extension://4c6c09b9-c9ce-47ec-8be8-34d776d685df/google.com` will be displayed.

However, when using the home page as `https://google.com`, the gesture works as expected.

### Your System
- Operating system: Windows 10
- Firefox version: 62.0
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
Thanks for the detailed report. We will perform some checks to work around this.

**Comment by Robbendebiene** [comment]
Available since [Gesturefy 2.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.0.4)
