### ISSUE TITLE
Context menu opens again

### ISSUE THREAD

**Issue by ImJezze** [Robbendebiene/Gesturefy#345]
Today I noticed, that the context menu opens, when I finish a gesture by releasing the right mouse button. I'm quite confused, if I messed with some settings or if it is related to current beta version of Firefox.

The interesting thing is, that it doesn't show the whole context menu you would get without the gesture movement. The context menu only contains:
- View image (URL: blob:null/f32e6788-0b3f-4454-b22a-8c6979887a23)
- Save image as... (file name: "canvas.png", size: page size, content: completely transparent)
- Select all
- Inspect Element

My System:
- Operating system: Windows 10
- Firefox version: 63.0b4 (64-Bit)
- Gesturefy version: 2.0.3

**Comment by Itchiii** [comment]
It will not be on your Firefox version. I have the same system settings as you.
Does this happen on every page or only on certain?
Could you please create a backup of Gesturefy and upload it here?

**Comment by ImJezze** [comment]
I happens on every page.

Backup:
[Gesturefy 2.0.3 Sun Sep 09 2018.zip](https://github.com/Robbendebiene/Gesturefy/files/2364329/Gesturefy.2.0.3.Sun.Sep.09.2018.zip)

I also created a new Firefox profile and disabled all other add-ons. The issue is still there.

**Comment by Robbendebiene** [comment]
I cannot reproduce the error too and honestly have no idea why it's not working on a clean profile. Does the contextmenu still contain the same entries if you disable the gesture trace in the config?

**Comment by ImJezze** [comment]
When I disable the gesture trace, the normal context menu appears.

Actually I only cleanded my profile under about:support, so it was not an entierly new profile. But now I did a complete re-install of Firefox, installed Gesturefy and the issue is gone.

However when I log into my Firefox account and sync the settings, the issue is back. Hope I can find out which setting causes the problem...

**Comment by ImJezze** [comment]
I found the settings.

dom.event.contextmenu.enabled was set to **false**

I reset it back to its default true and everthing is fine now.

**Comment by jatcwang** [comment]
In my about:config `dom.event.contextmenu.enabled` is set to true but context menu was still popping up whenever I use a right click gesture.

Searching around I found that there's a setting `ui.context_menus.after_mouseup` which when set to true means context menu is activated on mouse up event (not mouse down). This fixed it for me.
