### ISSUE TITLE
Address bar is not focused after "New Tab" when using a custom new tab page

### ISSUE THREAD

**Issue by oleg-sgh** [Robbendebiene/Gesturefy#346]
There is no focus of the cursor in the address bar if you open a new tab with a gesture from the open tab.
Video - 
`https://cloud.mail.ru/public/FRCg/PDK9tHzYr`
Quick Dial. Developer Response - 
`https://addons.mozilla.org/en-US/firefox/addon/quick-dial/reviews/1187326/`

- Operating system: Windows 7/64
- Firefox version: Firefox 63.0b3х64 and higher
- Gesturefy version:  2.0.3

**Comment by Robbendebiene** [comment]
This is a Firefox related bug. It occurs when an add-on overrides the new tab page and a new tab is opened via `browser.tabs.create();` Interestingly it seems like it's not reported yet on [bugzilla](https://bugzilla.mozilla.org).

**Comment by oleg-sgh** [comment]
Unfortunately, I'm not strong in English and in terms of and I can not describe this error in Bugzilla.

**Comment by oleg-sgh** [comment]
Thanks, I hope it will be fixed.
Yes, the error occurs in 63 beta, up to the current version of Nightly.

**Comment by Robbendebiene** [comment]
This is [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1485307) in Firefox 64, therefore I'm cloing this issue.

**Comment by oleg-sgh** [comment]
Understood. Thanks.
