### ISSUE TITLE
Add search/filter for command bar

### ISSUE THREAD

**Issue by ldgbc** [Robbendebiene/Gesturefy#350]
### Describe your matter in detail
Can't seem to find any issue with this feature request, might be duplicate. 

Feature request for a "search command" be added for the Command (sidebar) popup. There currently about 25 commands and more to comes in the future. But good if we can filter or search for command by it name and/or description.

### Screenshots or further assistance
![clipboard01](https://user-images.githubusercontent.com/1805303/45499466-d54c8b00-b7bf-11e8-8e63-4f8cc3754e68.jpg)

### Your System
- Operating system: Windows
- Firefox version: FF 61
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
Available in Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0)
