### ISSUE TITLE
Feature Request: Open bookmarks

### ISSUE THREAD

**Issue by sts-33** [Robbendebiene/Gesturefy#352]
Hi, I really like your addon very much.
But there is one problem for me. There is one missing function.
"open bookmarks" by mouse gesture.
Is it possible to add this, maybe in the future?
![1](https://user-images.githubusercontent.com/43304877/45591655-54c19200-b959-11e8-8dca-0c7345706f76.png)

**Comment by Robbendebiene** [comment]
Hey, thanks for your feature request. This was already requested and unfortunately is not possible.

**Comment by Robbendebiene** [comment]
Duplicate of https://github.com/Robbendebiene/Gesturefy/issues/141
