### ISSUE TITLE
Can't restore additional gestures

### ISSUE THREAD

**Issue by Hp93** [Robbendebiene/Gesturefy#353]
I can restore the default gestures with my custom configuration (gesture direction). But the additional gestures, Save image and Toggle bookmark for example, can't be restored from the backup file.

Steps:
1. Add new gesture (Save image or Toggle bookmark)
2. Backup
3. Restore
=> only the default gestures are restored.

### Your System
- Operating system: Windows 10
- Firefox version: 62
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
At the moment all gestures should be restored except of gestures that are linked to a command that requires additional permissions (like Save image or Toggle bookmark). We know that this is not a proper solution nor the expected behavior.

We will fix this once we've found a good workaround.

**Comment by Robbendebiene** [comment]
Fixed in Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0)
