### ISSUE TITLE
Could you support search selected text by default search engine？

### ISSUE THREAD

**Issue by ivysrono** [Robbendebiene/Gesturefy#354]
### Describe your matter in detail
It's search by google.com.
I'd like to search by default search engine setted in firefox.

### Your System
- Operating system: Win10
- Firefox version: 62
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
Available since [Gesturefy 2.0.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.0.4)
