### ISSUE TITLE
[Feature Request] "apply regular expression to URL" gesture

### ISSUE THREAD

**Issue by RheingoldRiver** [Robbendebiene/Gesturefy#355]
The initial thing that I wanted to do to prompt this request was allow "URL Hierarchy Up" to take me from a page like https://lol.gamepedia.com/index.php?title=Template:Infobox_Player/doc&action=edit to https://lol.gamepedia.com/index.php?title=Template:Infobox_Player&action=edit but as I was writing that request I realized it might be better to let you do an arbitrary regex find-replace on a URL and bind that to a gesture. This would let me do that & could allow for a lot more use cases too. Thanks!

**Comment by Robbendebiene** [comment]
We've discussed about this feature and came to the agreement that this is too specific for a seperate command. I'll however add a user script once Gesturefy supports it (support should come with Firefox 64)

**Comment by Robbendebiene** [comment]
Simple user scripts are now available with [Gesturefy 2.1.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.5).
Look for the "Execute User Script" command.

The script code structure could look like this:
`window.location = window.location.href.replace(regexp, newSubStr|function);`

Also set the "Target frame" option to "Top frame".

For more information, please visit the [Wiki](https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script).

**Comment by RheingoldRiver** [comment]
Woah cool, thanks for the update!
