### ISSUE TITLE
Gesturefy Stopped working after upgrade

### ISSUE THREAD

**Issue by gpbenton** [Robbendebiene/Gesturefy#357]
### Describe your matter in detail

After I upgraded Gesturefy today (22nd October) Gesturefy ceases to function.  No trailing lines, settings page is blank.  I have tried re-starting firefox.

### Screenshots or further assistance
![image](https://user-images.githubusercontent.com/1321303/47317845-6fff7b80-d642-11e8-90a8-08ed182418cd.png)

### Your System
- Operating system:  Kubuntu 18.04
- Firefox version:  62.0.3 
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
Hi, unfortunately this is a rare issue.
Have you modified your about:config settings like this:
`webextensions.storage.sync.enabled = false`
If so, make sure to set the property to true.

If not please visit the following issue: https://github.com/Robbendebiene/Gesturefy/issues/327

**Comment by gpbenton** [comment]
Thanks for replying.

I hadn't changed that config setting - it has always been `true` afaik.

Following that issue, I uninstalled gesturefy and reinstalled it, but when I try and restore my saved config, it says the file is not a gesturefy configuration file.  Has the format changed somehow? If so, is there any way I can edit the file to fool the current version?

But many thanks anyway.  I didn't realise how much I missed this addon until it wasn't there :-)

**Comment by Robbendebiene** [comment]
> Following that issue, I uninstalled gesturefy and reinstalled it, but when I try and restore my saved config, it says the file is not a gesturefy configuration file. Has the format changed somehow?

Yep the format has been changed.

> Edit:
> Never mind about the config file. I have gone through it and entered my config manually. A bit of a pain, but it did remind me of a few things I could quicker with gestures.

Okay, nice to hear that :)

**Comment by M0ns1gn0r** [comment]
Just experienced the same problem with the empty setting UI. I removed the extension and then immediately undone the removal of and the settings UI started to display. My settings were lost, however.
