### ISSUE TITLE
Queue two (more?) actions

### ISSUE THREAD

**Issue by zdzisekWithIdea** [Robbendebiene/Gesturefy#359]
Hello!

I'm using your addon and it's great, but there are limitations because of new API and I'm aware of this.

So we can't go directly to the 'homepage', but it's possible to create new tab and close one. It is possible to make one gesture 'trigger' two (or more) actions? What I want to do is open new tab (which is my homepage) and then close current one, but with single gesture.

**Comment by Robbendebiene** [comment]
Hey, thanks for your feature request.
This request has already been made and is called "Hybrid Actions" https://github.com/Robbendebiene/Gesturefy/issues/313.
If you just want to replace the current tab with your homepage, then this is already possible with the normal "Open Homepage" or "Open Custom URL" command.

**Comment by zdzisekWithIdea** [comment]
Sorry about duplicate.

When I use "Open Homepage" command I get this error https://github.com/Robbendebiene/Gesturefy/wiki/Illegal-URL what can be wrong?

**Comment by Robbendebiene** [comment]
I guess you are using about:home as your homepage url i.e. you haven't specified it yet?
If not please send me your homepage url.

**Comment by zdzisekWithIdea** [comment]
Yes, I'm using about:home, because every other 'speed dial' addon is loosing thumbnails/links after some time, not sure what cause this, but this is annoying as hell, so I'm forced to use about:home.

**Comment by Robbendebiene** [comment]
Sadly add-ons cannot open this page due to security reasons. You can read more about it [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1468191).

**Comment by zdzisekWithIdea** [comment]
Thank you very much for help!
