### ISSUE TITLE
blank screen when make gestures

### ISSUE THREAD

**Issue by nexterr** [Robbendebiene/Gesturefy#36]
blank screen when make gestures on http://seasonvar.ru/

**Comment by Robbendebiene** [comment]
Thanks for the report, will be fixed in the next version.

**Comment by happysurf** [comment]
Confirmed also on https://www.deviantart.com/newest/ whith **scroll to the bottom** gesture.

**Comment by Robbendebiene** [comment]
@happysurf Thanks, I fixed it. Even though this bug was different to the first one :)

**Comment by happysurf** [comment]
Thanks, in addition also the **scroll on top** doesn't work on that page.
Surely you have noticed I think. :-)

**Comment by happysurf** [comment]
In RSS pages like this https://github.com/Robbendebiene/Gesturefy/commits/master.atom or any other the gestures are performed but the trace doesn't appear.

**Comment by Robbendebiene** [comment]
@happysurf Thank you very much again. This is also fixed in the next version which will be released soon!

**Comment by Robbendebiene** [comment]
fixed: e2fa7da7ade8438b387976430cddb22c982affed, 7d90a9a4e3aba8d460dba769e3ea756280cd420e
