### ISSUE TITLE
Gesturefy forgets settings and all is back default

### ISSUE THREAD

**Issue by api2001** [Robbendebiene/Gesturefy#360]
### Describe your matter in detail
After installing and configuring the Gesturefy Addon in Firefox yesterday, it happened the third time that all settings were reset to default settings. When I configured it, the addon worked fine on all pages.
Unfortunately I cannot track the issue. A restart of Firefox actually does keep the settings.
I also use Firefox Account Sync - might there be a problem with the settings sync between multiple Firefoxes?

### Your System
- Operating system: Windows 10 Pro
- Firefox version: 60.3.0esr (64bit)
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
I guess that it is syncing your settings from another device where you haven't changed the settings yet. So Firefox is overwriting your settings with the settings from your other machine. Could that be the case?


If so then you can try uninstalling Gesturefy from your second machine > Force Sync > Setup your Gesturefy settings on your first machine > Force Sync on both machines. Now Gesturefy should run on both machines with the same configuration.

**Comment by api2001** [comment]
Okay I could not really reconstruct the problem - it was during the time after setting up GestureFy in one Firefox and also have it on two other systems in sync. Maybe I messed up the syncing.
Since a week or so it works very good.

**Comment by Robbendebiene** [comment]
@api2001 Nice to hear that. I'm closing this issue then.
