### ISSUE TITLE
[Feature Request] Move right tabs to a new window (or split window)

### ISSUE THREAD

**Issue by minterior** [Robbendebiene/Gesturefy#362]
### Describe your matter in detail
As a user, I want to do a mouse gesture to "move" all right tabs to a new browser window. Ideally, including the tab I'm on. This can also be seen as a "window split" because I want to split the window into two cutting in the current tab.

Thank you!

**Comment by Robbendebiene** [comment]
Hey, I like the idea :)
Which window would you expect to be focused, after the split is done? (Even though I'll probably add an option anyway.) I also wonder if it would make sense to have another command "move all left tabs to a new window", but I'm not quite sure if this should affect pinned tabs.

**Comment by minterior** [comment]
Hi, I celebrate you like it :) I used other mouse gesture plugins in the past that had that option.

The use case is normally this: search some stuff in the search engine, accumulate a bunch of tabs of that topic that want to move to a separate window. So said that I would prefer to move the current tab along the right tabs, although it could be a bit strange if the action name is "move right tabs". I think "move left tabs" could be valid to solve that little problem (if it is technically possible).
In both options I would keep the current tab (the one I'm on) as the focused one, so the user is not confused.

Cheers ;)

**Comment by Robbendebiene** [comment]
Available in Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0)
