### ISSUE TITLE
Do not focus duplicate tab

### ISSUE THREAD

**Issue by NiarK** [Robbendebiene/Gesturefy#363]
When using the 'Duplicate tab' command, it would be great to not focus the duplicate tab (or add a 'Focus duplicate tab' option to the 'Duplicate tab' command, like in the 'New tab' command)

I'll explain why:
When I use the 'duplicate tab' command, it wait until the duplicate tab is loaded, and then the duplicate tab gain focus. I often use this command to create a fork and continue the navigation on the current tab. With the current version of Gesturefy, I have to wait that the duplicate tab is fully loaded to do so (and for some page with low internet speed, it can take a while...)
I was used to Mouse Gesture Suite behaviour (which does not focus duplicate tab, but open them in background).

**Comment by Robbendebiene** [comment]
Available in Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0)
