### ISSUE TITLE
Gesturefy not working while page is reloading or incomplete load.

### ISSUE THREAD

**Issue by devymex** [Robbendebiene/Gesturefy#365]
I suppose this problem is similar with https://github.com/Robbendebiene/Gesturefy/issues/6

but is there any chance to cheat or mod firefox?

**Comment by Robbendebiene** [comment]
Hi, this is already stated in the add-on description on [AMO](https://addons.mozilla.org/firefox/addon/gesturefy/)

> The page must be partially loaded to perform gestures.

To answer your question: there is currently no way to work around this and I'm not aware of any Firefox modification (and I can't even imagine one)
