### ISSUE TITLE
Gestures do not work nor do they appear on screen.

### ISSUE THREAD

**Issue by RonWhite** [Robbendebiene/Gesturefy#368]
<!--I've installed Gersterfy and added gestures to in under Windo2ws 10 e, e does not appear on screen and nothing happens. It does not appear on screen and nothing happens.

### Describe your matter in detail
<!--That's it.

- Operating system:
- Firefox version: 63.0.3 64-bit
- Gesturefy version: Don't know. The version number is not included on the About page.

**Comment by Robbendebiene** [comment]
As stated [here](https://github.com/Robbendebiene/Gesturefy/blob/master/CONTRIBUTING.md), please provide more information, otherwise we are not able to help you and have to close this issue.
Have you already tried the [troubleshooting](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting) guide?

**Comment by BalubaTo** [comment]
Same here…
- troubleshooting guide done, all setting ok
- latest Gesturefy version (Updated 21. Nov)
- Firefox 63.0.3
- Mac OSX 10.14.1
- on every page
- no page of G visible (settings, gestures, …)

I think it has to do with the new Firefox version. Happened after auto-update…

**Comment by Robbendebiene** [comment]
What do you see if you open Gesturefys setting page? Can you please provide a screenshot?
Please also check if `webextensions.storage.sync.enabled` is set to `true` (about:config).

**Comment by BalubaTo** [comment]
…set to true checked
Settings page is blank (same like the other items on the list)
<img width="1552" alt="bildschirmfoto 2018-11-25 um 11 50 34" src="https://user-images.githubusercontent.com/45329234/48978229-ac425380-f0a8-11e8-94c4-55806d48b8e1.png">

**Comment by Robbendebiene** [comment]
In this case I require a console log. You can obtain it as described below:
1. open Firefox
2. press ctrl + shift + j
3. copy and paste the log here (or screenshot it if there is no scrollbar)
4. press the clear button in the upper left corner
5. (keep the console open) and open Gesturefy's settings page
6. revert to the console and copy & paste the console log again

**Comment by Robbendebiene** [comment]
Unfortunately there is not a single Gesturefy related error. However there multiple errors about a malformed database. This could be the database where Firefox is saving add-on settings and therefore causing the issue.

I guess reinstalling Gesturefy won't help in this case, but a clean profile could solve this (with all its drawbacks of course). These are just speculations, but there is nothing else I can do.

**Comment by BalubaTo** [comment]
Right, reinstalling doesn't help.
This «clean profile» issue happens once in a while… 
… but well, as you said – has a lot of drawbacks.
Thanks for your work!

**Comment by Robbendebiene** [comment]
@BalubaTo You are welcome. I hope this problem won't appear again anytime soon.
