### ISSUE TITLE
I was wondering If you could add 2 more Gestures to the list. "Close current tab and activate right tab" "Close current tab and activate left tab

### ISSUE THREAD

**Issue by rickd99** [Robbendebiene/Gesturefy#369]
### Your System
- Operating system:
- Firefox version:
- Gesturefy version:

**Comment by rickd99** [comment]
Sorry I dont know how to code or contribute.

**Comment by Robbendebiene** [comment]
Hey, maybe I'm missunderstanding you, but if you just want to focus the left or right tab after closing the current tab, then this is already possible. If you create a gesture with the "Close Tab" command two options will show up and one of them is called "Next tab".
