### ISSUE TITLE
GestureFy resets all settings after updating

### ISSUE THREAD

**Issue by Wicke2d** [Robbendebiene/Gesturefy#371]
After I updated GestureFy all of my custom settings got reset, which is very frustrating. I love the addon and I use it all the time, but this is just disappointing and my trust damaged.

I tried to regain my settings by going to my firefox user profiles to see if I could find a restore file, and I tried rolling back to the previous version, but no.

I also tried backing up the settings now, as I supposed I should I have done before updating, which I had no idea of, but I noticed it doesn't even restore restore everything. The ones that need premissions are excluded.

I just wish updating wouldn't reset the whole addon for me.

**Comment by Wicke2d** [comment]
I do know about the Firefox sync problem, but the thing is I haven't synced Firefox with any other device. I'm unsure about changing identity.accounts.enabled value to false. I'm only having problems with GestureFy.

**Comment by Robbendebiene** [comment]
Of course normally updating does not reset any of your settings.

The only possible explanation is, that you haven't updated Gesturefy for a long time. Since there was a major update (version 2.0) the old config from 1.0 had to be migrated to the new config. This "migration routine" has been removed recently due to code cleanup and because the vast majority of people migrated to 2.0.

Do you still know which version you were using before?

**Comment by Wicke2d** [comment]
That might be the reason. I don't know which version I was using before, but if you tell me how to find out I can certainly try.

**Comment by Robbendebiene** [comment]
I'm not aware of any way to find out the previous version. The Options UI changed with version 2.0 so if this is the first time you see the new options layout you proably were using Gesturefy 1.2.2 before.

There still might be a chance to restore your old settings if you want to. However I **cannot** guarantee that it will work. Here is how:

1. visit: https://addons.mozilla.org/firefox/addon/gesturefy/versions/
2. install version 1.2.2
3. check if your settings are back
4. if so install version 2.0.0 from here https://addons.mozilla.org/firefox/addon/gesturefy/versions/ (most of your settings should be migrated automatically, if not an extra tab should open)
5. check if your settings are migrated
6. update Gesturefy to the latest version
