### ISSUE TITLE
Not working in latest Tor Browser version

### ISSUE THREAD

**Issue by Kiefy** [Robbendebiene/Gesturefy#373]
### Describe your matter in detail
I have been using Gesturefy in Tor Browser for a long time. but after the recent 8.0.4 update. it no longer draws a line when holding the trigger button. In my case RMB. Though I did try the others. 
privacy.resistFingerprinting is false.

### Screenshots or further assistance
There are no visual anomalies and the Settings pages appear as they should.

### Your System
- Operating system: Windows 10 64bit
- Firefox version: Tor Browser 8.0.4 (based on Mozilla Firefox 60.4.0esr) (32-bit)
- Gesturefy version: 2.0.3

**Comment by Robbendebiene** [comment]
It seems like they've disabled the pointer events API (`dom.w3c_pointer_events.enabled`), which is required for Gesturefy in order to work properly. (corresponding ticket: https://trac.torproject.org/projects/tor/ticket/25794)
