### ISSUE TITLE
Can no longer highlight text

### ISSUE THREAD

**Issue by tigerheli** [Robbendebiene/Gesturefy#376]
### Describe your matter in detail
Since I installed Gesturefly in Firefox I can no longer highlight text. Also when in Gmail and clicking on Forward, I can no longer add the recipient.  Disabling Gesturefly makes the problem go away.  
Seems there is some work left to do.  Will uninstall for the time being but thanks for looking into this

### Your System
- Operating system: Windows 10
- Firefox version:  64.0
- Gesturefy version:  2.0.4

**Comment by Robbendebiene** [comment]
Have you changed any of the Gesturefy Settings? Especially the "trigger mouse button"? What happens when you try to highlight text?
