### ISSUE TITLE
Options page does not work with FF developer edition (65.0b8 (64-bit))

### ISSUE THREAD

**Issue by flowwy** [Robbendebiene/Gesturefy#377]
When loading Gesturefy as a temporary addon in FF developer edition 65.0b8 (64-bit) the options page is only showing the navigation tree two times instead of the navigation tree on the left and the actual settings on the right.

![image](https://user-images.githubusercontent.com/9829775/50735467-dd399c00-11af-11e9-83a9-125b466ebb6a.png)

- Operating system: Win7 64bit
- Firefox version: developer edition 64.0b8 (64-bit)
- Gesturefy version: master 4147d9b19f2046c194bbd32dbccc6b8e5ccc0432

Because I'm new to addon development I hope this is no user error.
All I did was clone the repo and load Gesturefy as a temporary plugin.

**Comment by flowwy** [comment]
Temporary loading the plugin was done via "about:debugging" and "Load Temporary Add-on...".

**Comment by flowwy** [comment]
I found the culprit: when removing the trailing comma in src/res/json/commands.json the options page is working again.
I am also new to git and don't know how to provide the patch. Here are the changes to my local repo:

Author: flowwy <deepzen@zoho.com>  2019-01-06 13:57:21
Committer: flowwy <deepzen@zoho.com>  2019-01-06 13:57:21
Parent: 4147d9b19f2046c194bbd32dbccc6b8e5ccc0432 (fixed reset message string)
Branch: master
Follows: v2.0.4
Precedes: 

    Fix for #377 (Options page broken in FF developer edition 65.0b8)

-------------------------- src/res/json/commands.json --------------------------
index ac563c8..01f6778 100644
@@ -388,5 +388,5 @@
       "parseJSON": false
     },
     "group": "advanced"
\-  },
\+  }
 ]

**Comment by Robbendebiene** [comment]
Thanks for the information.
This is because I only commited a subset of my changes. It will be automatically fixed with my next commit.

**Comment by Robbendebiene** [comment]
should be fixed
