### ISSUE TITLE
Can't drag the Addon to the fold menu when I customize the toolbar. 

### ISSUE THREAD

**Issue by Esirn** [Robbendebiene/Gesturefy#379]
Sorry I can't upload the screenshot.
### System
- Operating system: Windows 7, 64bit
- Firefox version: 65.0
- Gesturefy version: 2.0.4

**Comment by Robbendebiene** [comment]
There is no toolbar button for Gesturefy. You can configure it via about:addons > Settings

**Comment by Robbendebiene** [comment]
Duplicate of https://github.com/Robbendebiene/Gesturefy/issues/249
