### ISSUE TITLE
please get us Gesturefy in Opera soon

### ISSUE THREAD

**Issue by gudurti** [Robbendebiene/Gesturefy#380]
### Your System
- Operating system:
- Firefox version:
- Gesturefy version:

**Comment by gudurti** [comment]
we need this Ext. sonn in Opera, please

**Comment by Robbendebiene** [comment]
Similar to this [issue](https://github.com/Robbendebiene/Gesturefy/issues/218) there are currently too many incompatibilities wherefore we wont port Gesturefy to Opera (at least for now).
