### ISSUE TITLE
Feature Request - Adding Prefixes to Links

### ISSUE THREAD

**Issue by mortyobnoxious** [Robbendebiene/Gesturefy#381]
Just like "Open Link in a New Tab" but adding some user defined "thing" beginning of the url.

For example:
This is URL I applied the gesture on: example.com

Gesture will open it in new tab by adding "something" before it:
telegram.me/share/url?url=example.com
about:reader?url=example.com
ssl-proxy.my-addr.org/myaddrproxy.php/example.com

**Comment by Robbendebiene** [comment]
Thanks for the suggestion and the provided use case. Since this seems to be more of a specific use case I tend not to implement it. However I will provide a userscript once the functionality has been added to Firefox.

**Comment by mortyobnoxious** [comment]
@Robbendebiene Hi, I used JS to share _window.location_ to Telegram with this:

`window.open("tg://msg_url?url="+window.location+"","_self");`

Is there a way to do this for URLs where gesture started?

**Comment by Robbendebiene** [comment]
Currently this issue cannot be properly solved by userscripts. But if you want to get the link where the gesture started you can use the TARGET variable to get the element where the gesture started like so:


```
  let node = TARGET;
	while (node !== null && !node.href) {
    node = node.parentElement;
  }
  if (node) alert(node.href)
```

**Comment by mortyobnoxious** [comment]
Thank you so much.

**Comment by Robbendebiene** [comment]
Since version [3.0.3](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.3) tabs and windows can now also be opened via the newly added API methods. See [here](https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script#user-script-api) for more information.

**Comment by mortyobnoxious** [comment]
@Robbendebiene  Hi.
```
let node = TARGET;
while (node !== null && !node.href) {
	node = node.parentElement;
}
if (node) {
	var openthis = "about:reader?url=" + node.href;
	API.tabs.create({url:openthis});
} else {
	openthis = "about:reader?url=" + window.location;
	API.tabs.create({url:openthis});
}
```

I made this but it's not working, is it because of the "about:reader" or did i make something wrong?

**Comment by Robbendebiene** [comment]
>  is it because of the "about:reader"

Hi, yeah sadly it's still not possible for add-ons to open about: urls..
But you could use the `openInReaderMode` property.

`API.tabs.create({url:openthis, openInReaderMode: true});`

**Comment by mortyobnoxious** [comment]
Thank you. If there's anyone need this:

```
let node = TARGET;
while (node !== null && !node.href) {
	node = node.parentElement;
}
if (node) {
	API.tabs.create({url:node.href, openInReaderMode: true});
} else {
	API.tabs.create({url:window.location, openInReaderMode: true});
}
```
