### ISSUE TITLE
Right-click context menu pop up after gesture finished in MacOS and also Windows 10 running on virutal machine

### ISSUE THREAD

**Issue by Griiid** [Robbendebiene/Gesturefy#382]
- MacOS version: Mojave, 10.14.3
- Firefox version: 65.0.1
- Gesturefy version: 2.0.4
- Virutal Machine Windows 10
   - Parallels Desktop version: 14.1.2
   - Firefox version: 65.0.1
   - Gesturefy version: 2.0.4

After drawing gesture finished, the right-click context will pop up, and I need to left click to make it disapeared.

This situation occurs in both the firefox in MacOS, and the firefox in WIndows 10 in parallels desktop (a virtual machine running on MacOS.)

**Comment by Itchiii** [comment]
Did you try the help from the [Troubleshooting Guide](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture) ?

**Comment by Griiid** [comment]
@Itchiii It helps me, thanks!!

Sorry I didn't noticed there's a troubleshotting guide, just searched in the issue list.
