### ISSUE TITLE
Feature request: [Popup] menu can be kept open after click

### ISSUE THREAD

**Issue by YuiTatsumi** [Robbendebiene/Gesturefy#383]
Hope that [Popup] menu can be pinned (i.e. kept open) for searches in background tabs, so that multiple searches can be executed at once.

 e.g. [Popup] Search Engines:
- added an option to keep menu open after click

or

- right-click (or middle-click) popup menu:  pin the menu and search it in background tab

**Comment by Robbendebiene** [comment]
Thanks for the good suggestion.

**Comment by Robbendebiene** [comment]
This is now possible with the release of Gesturefy version [3.0.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.5). You can now use the middle or right mouse button to open the search in the background.
