### ISSUE TITLE
Gesture trace canvas staying in the page

### ISSUE THREAD

**Issue by CrendKing** [Robbendebiene/Gesturefy#384]
### Symptom
In some situations, the gesture trace canvas (the `<div>` with lots of properties) will stay in the page forever. Because the div has the highest z-index, it blocks all the interaction with the page.

### Reproduce
One way to reproduce the problem is to enable wheel gesture and gesture trace. Make the wheel gesture focus left or right tab. Also, make sure both the gesture and wheel buttons are the same (e.g. right mouse button). Draw some gesture without releasing the button, then scroll the wheel. Once focused on the other tab, release the button. Now, switch back to the original tab by clicking the tab.

It looks like the addon triggers the removal of the div from the keyup event of the gesture button. If the event does not trigger on the same page, the removal is missed.

Two observations: 1) Even if I turn off gesture trace, the div is still created. So there is no easy workaround at this moment. 2) Even if turn on gesture timeout, the div stays until a valid keyup event is triggers, ignoring the timeout.

### Suggestion
My suggestions to fix this are: 1) detect tab switching and remove the div; 2) if gesture timeout is enabled, remove the div whenever the timeout happens.

### Screenshots or further assistance
![Div](https://user-images.githubusercontent.com/975235/54087208-e65cfb80-430d-11e9-994a-bb5395c14b03.jpg)

### Your System
- Operating system: Windows 10
- Firefox version: 66
- Gesturefy version: 2.0.4

**Comment by Robbendebiene** [comment]
Thanks for the detailed report! I'll fix this in the upcoming release, but it might take some time since I'm currently doing a lot of code changes.

**Comment by Robbendebiene** [comment]
Fixed in Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0)
