### ISSUE TITLE
Decrease wheel gesture sensitivity for Smooth scrolling mice

### ISSUE THREAD

**Issue by bubblefoil** [Robbendebiene/Gesturefy#385]
Smooth-scrolling mice trigger mouse wheel gestures with the slightest wheel movement. For me, this means tabs switching like crazy when I try to draw a gesture.

I have Logitech M705 mouse with a super-sensitive wheel. It has a button that disengages the stepping mechanism, it does not reduce the sensitivity, though.
Logitech provides [this smooth-scrolling add-on](https://addons.mozilla.org/en-US/firefox/addon/logitechsmoothscrolling/) which makes Firefox react to the tiniest wheel movements and makes scrolling beautifully smooth. I prefer that over the erratic several lines long jumps.

Is it possible to set a dead zone for the mouse wheel before it triggers a gesture?
I understand that it may be harder to implement in the case you had to accumulate the events yourself to check whether the rotation has reach the length of a line. Anyway this is really annoying and I don't want to give up wheel gestures altogether (on all my synced devices).

### System
- Operating system: Windows 10 Pro
- Firefox version: 65.0.1
- Gesturefy version: 2.0.4

**Comment by Robbendebiene** [comment]
Thanks for your detailed request. This sounds like a reasonable enhancement to me. I'll try to add an advanced option to the wheel gesture. However I need your help, can you please follow the steps bellow:

1. Visit this fiddle https://jsfiddle.net/qL0fhdwk/
2. Open the console by pressing `Ctrl + Shift + I`
3. Scroll multiple times up and down with different speeds in the bottom right area
4. Post the outputs from the console here

**Comment by bubblefoil** [comment]
Sure, here you go
https://gist.github.com/bubblefoil/a6de3f43ac6be5b8e536d67353da58da

**Comment by Robbendebiene** [comment]
In Gesturefy [2.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.0) there is an advanced option below the wheel gesture setting. Can you please confirm that it fixes your problem?

**Comment by bubblefoil** [comment]
Thanks for the update!

I can confirm that the wheel gesture is not extremely sensitive as it was before. Even values like 1 or 0.5 prevent from unwanted tab switches.
At this point I can share configuration between PCs with different mice without the annoying behavior of Smooth scrolling.

The only downside is that the wheel gesture is almost useless with the Smooth scrolling mouse because successive wheel events do not accumulate deltaY (I know, some global state...) and I have to scroll fast enough so that browser fires a wheel event with large enough deltaY increment. This is rather difficult because there is some acceleration factor in Logitech SW and often the deltaYs are either too small or a bunch of 2-3line increments are fired.

Furthermore, there seems to be an issue with faster tab switching. During wheel rotation in one direction, occasionally the selection jumps back to some of the previous tabs. I have checked for random opposite scroll events with this code https://jsfiddle.net/n2L5187g/ and the scroll direction is consistent.

Of course, I can live with it as it is now and I will completely understand if you do not feel like improving the feature and close this issue.

PS: Just got an idea for horizontal scroll gestures. Tilting the wheel triggers the same wheel event with deltaX -3/3. Does it make sense? Can I create a separate feature request for this?

**Comment by Robbendebiene** [comment]
> The only downside is that the wheel gesture is almost useless with the Smooth scrolling mouse because successive wheel events do not accumulate deltaY (I know, some global state...) and I have to scroll fast enough so that browser fires a wheel event with large enough deltaY increment. This is rather difficult because there is some acceleration factor in Logitech SW and often the deltaYs are either too small or a bunch of 2-3line increments are fired.

I was afraid of that. In this case I'll keep this issue open and try to improve this.

> PS: Just got an idea for horizontal scroll gestures. Tilting the wheel triggers the same wheel event with deltaX -3/3. Does it make sense? Can I create a separate feature request for this?

There already exists an issue for this #221

**Comment by Robbendebiene** [comment]
This bug is fixed with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
