### ISSUE TITLE
设置无法保存

### ISSUE THREAD

**Issue by Astringentfruit** [Robbendebiene/Gesturefy#387]
### Your System
- Operating system:Windows10
- Firefox version:66.03（64位）
- Gesturefy version:2.0.4
我花了很多时间完成了个性化设置，但是备份文件没有备份我的设置，而是依旧备份默认设置。另外，电脑每次重启都会丢失我的设置，变为默认设置。我很愤怒！

**Comment by Astringentfruit** [comment]
I spent a lot of time completing the personalization, but the backup file didn't back up my settings. It still backed up the default settings. In addition, every time the computer restarts, it will lose my settings and become the default setting. I am angry!

**Comment by Robbendebiene** [comment]
Are you using Firefox sync? If so you are probably encountering the same problem as issue: #378 

>  but the backup file didn't back up my settings. It still backed up the default settings.

Are you sure about this? Can you please change some settings, make a backup file and post it here?
