### ISSUE TITLE
Context menu issue

### ISSUE THREAD

**Issue by ysu2** [Robbendebiene/Gesturefy#388]
Gents, 
I'm wondering; is there any way to get mouse gestures work without opening the context menu, yet without allowing websites to change my context menu?

I've been to the troubleshooting page here
https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture

But it seems it's either all or nothing, which seems rather stupid for an approach.
Is that right? Is firefox that dumb?  Or am I missing something?

**Comment by Robbendebiene** [comment]
Sadly not, because Gesturefy relies on the same technology that webpages uses.

**Comment by ysu2** [comment]
I was afraid of that.   Bugger. 
Thanks, nonetheless.
