### ISSUE TITLE
Left Mouse Button 

### ISSUE THREAD

**Issue by WhoWouldaThunk** [Robbendebiene/Gesturefy#39]
You can't open links using mouse gestures when you have it set to use the left mouse button.

**Comment by Robbendebiene** [comment]
Thanks for the report. This is because it starts dragging the link right? This is already fixed in the next version which I will submit to mozilla today.

**Comment by Robbendebiene** [comment]
fixed: e2fa7da7ade8438b387976430cddb22c982affed

**Comment by WhoWouldaThunk** [comment]
Works great! The only issue I've noticed with it is you can't select text as it tries to draw a gesture. This doesn't affect me, but for some people it may. I'm not sure if there's anyway around it, but the addon I was using, all in one gestures, fixed that issue by allowing you to have a modifier key, which when held down, would ensure no gesture was started so that the default browser behaviour resumed.

Anyway, cheers and thanks for the effort put into this extension!

**Comment by Robbendebiene** [comment]
Yeah adding a modifier key would be the only way to solve this. I guess I will add one in on of the next updates :) There is also another problem with scrollbars, you can't really use them because it will also start a gesture, but maybe I can fix this without the need of a modifier key.

**Comment by WhoWouldaThunk** [comment]
Ah I didn't notice that one as I very rarely have need to click on a scroll bar. I know it works fine in the addon I mentioned, but that uses the old api so...Could you add a dead area e.g. windowHeight - 10, windowWidth - 10, so that the scroll area isn't affected? Not sure what you're able to do now.

One thing I've noticed, unrelated to this issue, is that the addon doesn't seem to have a timeout for gestures? E.g. if you start drawing one, but decide to 'cancel' it, you just don't move your mouse for x seconds.

**Comment by Robbendebiene** [comment]
> Could you add a dead area e.g. windowHeight - 10, windowWidth - 10, so that the scroll area isn't affected?

I had a similar idea, but this would only fix it for the main page scroll bar. Currently I'm thinking about canceling the gesture if any scroll event occurs (not tried yet).

> One thing I've noticed, unrelated to this issue, is that the addon doesn't seem to have a timeout for gestures? E.g. if you start drawing one, but decide to 'cancel' it, you just don't move your mouse for x seconds.

That's right, I for my self found it useless / more time consuming, because when I need to cancel a gesture I'm just moving my mouse quickly in random directions, until it won't match any defined gesture.
But I guess some people prefer the timeout, so feel free to create a new feature request issue, which ensures that I won't forget about it :)
