### ISSUE TITLE
Layer problem at HBO GO

### ISSUE THREAD

**Issue by matiffeder** [Robbendebiene/Gesturefy#390]
Layer problem at HBO GO

There may be a bug in Gesturefy. When I at HBO GO and enlarged (fullscreen) the player, the layer of player seems become disabled. So that when I want click on the progress bar or any buttons, it doesn't click on the player but the link on the page which behind the player.

When the player is "fullscreen", I see the video in whole screen. (The control panel in player covered the red square. I can not click on control panel but the links in the red square) 
https://i.imgur.com/mYJLZun.jpg

Windows 10 1803
Firefox 66.0.3 tested only enabled Gesturefy 2.0.4
Gesturefy 2.0.4

**Comment by Robbendebiene** [comment]
Sorry I don't really get the problem and because I do not have access to HBO GO I'm not able to test it by my self.

Am I understanding you correctly, that your described problem only happens when Gesturefy is installed? And the problem occurs right after the page is loaded (and you clicked the full screen button) without performing any gesture?

**Comment by matiffeder** [comment]
Yes, it only happens when there is only Gesturefy installed.
It happened after the page is loaded. I didn't use any gesture during this progress.

**Comment by Robbendebiene** [comment]
Sorry I have no idea how Gesturefy can cause such a problem. Can you please double check that the error doesn't exist when Gesturefy is disabled?

**Comment by matiffeder** [comment]
Yes, if Gesturefy is disabled there will no bug.

**Comment by Robbendebiene** [comment]
Thankfully! I really had no idea what could cause the problem :)
I guess you have to contact the website owner.

**Comment by matiffeder** [comment]
I am very sorry. Can you help me to delete the issue if you want? Thank you!

**Comment by Robbendebiene** [comment]
No problem. If you wish so, I'll delete this issue :)
