### ISSUE TITLE
[Gesture Request] Reload a page bypassing cache

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#391]
Will be great have also this gesture for reload a page from the server without cache like with Ctrl + F5 shortcut.

**Comment by despecial** [comment]
+1

**Comment by Robbendebiene** [comment]
This is already available. Please check the settings of the "Reload Tab" command (simply create a new gesture an choose "Reload Tab"). It's called "Reload Cache" and if turned on the cache will be bypassed.

**Comment by happysurf** [comment]
> 
> 
> This is already available. Please check the settings of the "Reload Tab" command (simply create a new gesture an choose "Reload Tab"). It's called "Reload Cache" and if turned on the cache will be bypassed.
Sorry, I had missed this option.
