### ISSUE TITLE
[feature request] delete cookie for current domain

### ISSUE THREAD

**Issue by despecial** [Robbendebiene/Gesturefy#392]
Is this possible? I remember it from previous addons (firegestures)

**Comment by Robbendebiene** [comment]
This should be possible, but can you please specify which cookies should be deleted?

**Comment by despecial** [comment]
I would suggest all cookies for the current page.
e.g. google.com?... > removes all .google.com cookies

**Comment by Robbendebiene** [comment]
I've struggled a lot with this decision but I've decided not to add this feature.
Reasons:
- very specific with little usage
- users may not understand which cookies are actually removed and which are not
- doesn't fit to other commands
- user scripts can at least remove all cookies that are accessible by JavaScript

The best solution would be if a cookie manager/removal add-on would provide an API for this, which Gesturefy could then use (with the Send message to other add-on command)
