### ISSUE TITLE
FireFox auto-removed the Gesturefy extension

### ISSUE THREAD

**Issue by larryedwards** [Robbendebiene/Gesturefy#395]
### Describe your matter in detail
Tonight, FireFox (current version) removed a number of the extensions I had installed, including yours. The message says the security of the extension has not been verified. 

If I try to reinstall any of the removed extensions, that is blocked (but giving a misleading error message saying "check your connection" - which isn't the reason - FF blocks this).

Hope you can get it verified and going again soon!

### Your System
- Operating system:  Win7 x64
- Firefox version:   66.x
- Gesturefy version:  Unknown, since FF removed it.
![Screen-Shot](https://user-images.githubusercontent.com/3360573/57175558-f965e680-6df9-11e9-84a0-deb992e4e8fd.png)

**Comment by Robbendebiene** [comment]
I'm currently unable to install any add-on from AMO. So it seems like there is a problem on AMO which might be related to your problem.

**Comment by larryedwards** [comment]
What is AMO?

-- Larry

===== Orig. Msg. =====

**Comment by Robbendebiene** [comment]
AMO = Mozilla Add-ons = https://addons.mozilla.org

**Comment by Damus765** [comment]
This issue is due to expiration of Mozilla's signing cert.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1548973.

**Comment by Robbendebiene** [comment]
You can already install a Hotfix for this. For more information checkout here: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by larryedwards** [comment]
Thanks, Robin.

   About:Studies says the hotfix is installed, but none of the subject
extensions have been reactivated. So it seems Moz still has work to do
on the fix. (BTW, this is on a PC running Windows.)

-- Larry

===== Orig. Msg. =====

**Comment by Robbendebiene** [comment]
I'm closing this since Mozilla released an update which fixes the problem.
