### ISSUE TITLE
Doesn't work on https://support.mozilla.org/en-US/

### ISSUE THREAD

**Issue by ilozen** [Robbendebiene/Gesturefy#396]
As in topic. Works on other sites without issues but not anywhere within https://support.mozilla.org

**Comment by Robbendebiene** [comment]
This is a known limitation done by Mozilla. No add-on can run on these pages for security reasons. You can find a list of all the affected websites here: https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#gesturfy-is-not-working-at-all
I'm also not happy with that decision, but there is nothing I can do about it.
