### ISSUE TITLE
Feature request: Touchscreen and touchpad support

### ISSUE THREAD

**Issue by DanielValahul** [Robbendebiene/Gesturefy#397]
Hello,

First of all I'd like to thank you for this extension, it adresses a feature that Firefox really misses.
As a laptop user not always having a mouse, it's hard to do gestures with the touchpad because the left/right click sensitive area is too small and has to be pressed for the whole gesture. It's currently impossible to do any gesture with the touchscreen.
I think that a way to improve the experience for touchpad or touchscreen users would be to add a separate option. For example instead of clicking the gesture could be done by swiping with 2 or 3 fingers. For reference I think Edge has really good touchscreen/touchpad gestures.

**Comment by Robbendebiene** [comment]
Hi, thanks for your feature request. I can completely empathize with you when it comes to using mouse gestures on laptops with a touchpad. There already is an issue for touchscreen support, but it's current lacking a proper concept (#98)
An extra swipe gesture as you suggested is too specific for this add-on and would also require a lot of effort for this simple feature, sorry for that. However what I do consider is a keyboard trigger button (more info: #274).

**Comment by Robbendebiene** [comment]
Closing this issue in favor of #98 and #274
