### ISSUE TITLE
Gesturefy not working in system pages

### ISSUE THREAD

**Issue by ZEN268** [Robbendebiene/Gesturefy#398]
Gesturefy not working when i open extensions tab, or tab with settings or even specific  site such a addons.mozilla.org. And I could not find settings which allows that.

Also wheel gestures NOT working on mozilla's home page.

My system
windows 7
Firefox 67
Gesturefy version: 2.0.4

**Comment by jdreesen** [comment]
Did you read the "Limitations / Problems" section in the readme?

**Comment by ZEN268** [comment]
I just read it and i'm very sorry that not did it before. 
By the way will those issues be fixed in future?

**Comment by jdreesen** [comment]
Those are limitations in Firefox itself and can only be fixed by Mozilla. There's nothing the author of this addon can do.

**Comment by ZEN268** [comment]
Okay, I got it. Thank you for the answer!
