### ISSUE TITLE
Add feature to cancel gestures

### ISSUE THREAD

**Issue by matiffeder** [Robbendebiene/Gesturefy#399]
There is a function that press a key before gesture to disable Gesturefy now.
There is also a timeout to cancel Gesturefy.
But I think maybe you can also add a function to press a key to cancel Gesturefy after people draw a wrong gesture.
Anyway, I really like your addon.
Thanks for your hard works!

**Comment by Robbendebiene** [comment]
Hi, thanks for your feature request. What I do to cancel a gesture is just to move my mouse rapidly in random directions directions around the screen so I can assure that none of my gestures maps and release the mouse button. But I see that this is not an ideal way or solution. What do you think about extending the functionality of the "disable mouse gestures key" so it disables mouse gestures or cancels them?

**Comment by matiffeder** [comment]
_**What do you think about extending the functionality of the "disable mouse gestures key" so it disables mouse gestures or cancels them?**_

For example, when I draw a wrong gesture, I can simply press ESC to cancel the gesture. Or when I use right button on mouse to draw a gesture, I can use left click to cancel the gesture.

I don't if there a better way to cancel a gesture or maybe most people don't need this feature. Anyway, thank you for caring my suggestion. :)

**Comment by Robbendebiene** [comment]
This is now possible with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
