### ISSUE TITLE
Wheel gesture in tabbar

### ISSUE THREAD

**Issue by elsi** [Robbendebiene/Gesturefy#40]
switch tab bar

Request

**Comment by Robbendebiene** [comment]
You mean switching tabs while scrolling over the tab bar? If so then this is sadly currently impossible with the new webextensions API.

**Comment by TheBigFatTony** [comment]
It can be done! There is a very simple workaround: https://forum.manjaro.org/t/howto-enable-tab-switching-in-firefox-using-mouse-wheel/39954
Tested under Windows and Fedora. (Firefox 60.0.2)

**Comment by Itchiii** [comment]
That is interesting
Thank you for informing us @TheBigFatTony :)

**Comment by steffenbr** [comment]
Thanks @TheBigFatTony. Another option for when using Tree Style Tabs is https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab-mouse-wheel/.

**Comment by Robbendebiene** [comment]
@TheBigFatTony Of course it's possible if you have access to the chrome code like the older addons had :) but it's not possible for addon developers, which rely on the API that is provided by the Firefox devs. Anyway thanks for posting this!

**Comment by cyberoblivion** [comment]
This should just be the native default behavior. We should not need a plugin to do this. What else would you expect the scroll wheel to do when the cursor is over the tab panel?

**Comment by Robbendebiene** [comment]
Closing this, since it became very unlikely that Mozilla will ever add an API for this. Maybe there will be a build in setting some day.
