### ISSUE TITLE
右键单击标签页无法关闭当前标签页

### ISSUE THREAD

**Issue by tmkmk** [Robbendebiene/Gesturefy#402]
### Describe your matter in detail

安装这个插件的主要目的,也是唯一目的 右击关闭当前标签页.在插件设置中,已经设置了.但是毫无用处.包括左击 也设置为了关闭当前标签页 都不行. 右键(或 左键)单击标签页与没有安装 Gesturefy  前无任何区别.

### Your System
- Operating system:win10 LTSC
- Firefox version:68.0b9 (64 位)
- Gesturefy version:2.0.4

**Comment by Robbendebiene** [comment]
Please write in english, otherwise I cannot help you and have to close this issue.

**Comment by tmkmk** [comment]
right click tab, unable to close the current tab
