### ISSUE TITLE
Duplicating tabs doesn't work anymore

### ISSUE THREAD

**Issue by SebastianZ** [Robbendebiene/Gesturefy#404]
### Describe your matter in detail
After the update to versino 2.1.0 the action to duplicate a tab didn't work anymore. A quick check in the Browser Content Toolbox showed an error:

Error: settings is undefined
commands.js

Obviously, this is due to the newly introduced option wether to focus the duplicated tab, which is not set when you previously assigned the action a gesture.

The simple fix was to set the option whether to focus the tab or not.

As this can happen with any new options that are introduced, I suggest to implement default values for them as a fallback and check whether the `settings` variable is defined.

### Screenshots or further assistance

![settings undefined in commands.js](https://user-images.githubusercontent.com/958943/60652860-3aee2e80-9e49-11e9-9b7c-b955d470bf02.png)

### Your System
- Operating system: Windows 10
- Firefox version: 67.0.4
- Gesturefy version: 2.1.0

Sebastian

**Comment by Robbendebiene** [comment]
Damn, I forgot about that.. Thanks for the report.

> As this can happen with any new options that are introduced, I suggest to either implement default values for them as a fallback and check whether the settings variable is defined.

I agree on that.

**Comment by Robbendebiene** [comment]
fixed in [Gesturefy 2.1.1](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.1) (not perfect yet)

**Comment by SebastianZ** [comment]
That should at least fix the error. So thank you for the extremely fast fix!

Let me know if I should file a separate issue for introducing a general way to fall back to the default value in such cases.

Sebastian
