### ISSUE TITLE
Gesture doesn't timeout

### ISSUE THREAD

**Issue by R0nd** [Robbendebiene/Gesturefy#405]
### Describe your matter in detail
Gesture timeout doesn't work correctly with the latest release. Gesture trace/command overlay disappears after timeout, but the action still triggers when I release the button.
Reproduction steps:
1. Enable gesture timeout
2. Start drawing a gesture
3. Wait until the timeout and overlay disappearance
4. Release the button

### Your System
- Operating system: Windows 10
- Firefox version: 67.0.4
- Gesturefy version: 2.1.0

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll try to fix this as soon as possible.

**Comment by Robbendebiene** [comment]
fixed in [Gesturefy 2.1.1](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.1)

**Comment by SebastianZ** [comment]
Had the same issue with 2.1.0. I can confirm that it's fixed with 2.1.1. Thanks for the extremely fast fix, @Robbendebiene!

Sebastian
