### ISSUE TITLE
"[Popup] All Tabs" has stopped working on some sites

### ISSUE THREAD

**Issue by Dituar** [Robbendebiene/Gesturefy#406]
"[Popup] All Tabs" has stopped working on some sites now (like https://e.mail.ru/messages/inbox/ not work inaf but work at https://mail.ru/ ; at https://3dnews.ru/ Popup blinks for 0.1 sec and disappears; at https://www.avito.ru/rossiya too), but always worked before. I think its after update Gesturefy, but i cant install previos version, to check. How to downgrade to chek, to help you?
PS. "[Popup] Recently closed tabs" work well.

### Your System
- Operating system: win7
- Firefox version: 67.0.4
- Gesturefy version: 2.1.1

**Comment by Robbendebiene** [comment]
Hey, thanks for your report. So far I was able to reproduce the problem on https://3dnews.ru/ 

> How to downgrade to chek, to help you?

You can download older versions here: https://addons.mozilla.org/en/firefox/addon/gesturefy/versions/ It would be helpful if you could test if this problem already existed in the previous version.

**Comment by Dituar** [comment]
at https://yandex.ru/ not work too, if u know it's biggest serch site in RU
Version: 2.1.0  i restore config "Gesturefy 2.0.4 Sun Jan 13 2019" but not work too:
at https://yandex.ru/ not work
at https://www.avito.ru/rossiya not work. i dont know why, but "[Popup] All Tabs" sometimes skroll page.
at https://3dnews.ru/  not work
Version 2.0.4 i restore config "Gesturefy 2.0.4 Sun Jan 13 2019" but Gesture "[Popup] All Tabs" and "[Popup] Recently closed tabs" not restored. I create them.
at https://yandex.ru/ work
at https://www.avito.ru/rossiya work. 
at https://3dnews.ru/  work
Problem in update Gesturefy.

**Comment by Robbendebiene** [comment]
Can you please test version 2.0.4

**Comment by Dituar** [comment]
i test. you skipped it
Version 2.0.4 i restore config "Gesturefy 2.0.4 Sun Jan 13 2019" but Gesture "[Popup] All Tabs" and "[Popup] Recently closed tabs" not restored. I create them.
at https://yandex.ru/ work
at https://www.avito.ru/rossiya work.
at https://3dnews.ru/ work
Problem in update Gesturefy.

**Comment by Robbendebiene** [comment]
Okay. thanks, I'll look into it.

**Comment by Dituar** [comment]
thx!

**Comment by Dituar** [comment]
PS. I think I configured Gesturefy well for more people, it's sipmle and intuitive. We can think and can improve it even to add it as default to Gesturefy. Becouse i think to new users Gesturefy it well be useful. May be create new "Issues" to discuss how improve it for default (for more people)?

**Comment by Robbendebiene** [comment]
Fixed in Gesturefy [2.1.2.](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.2)
