### ISSUE TITLE
disable onboarding site

### ISSUE THREAD

**Issue by eworm-de** [Robbendebiene/Gesturefy#407]
### Describe your matter in detail
Version 2.1.1 introduced an onboarding site, which is a great idea and well done.

However I have systems that are deployed without a Firefox profile and destroyed after first use. Every time users are annoyed with the onboarding site.

Please add on option to disable the onboarding site. I would like to see a setting `extensions.gesturefy.noOnboarding` or similar, which I could add to a global `prefs.js`.

### Your System
- Operating system: Arch Linux
- Firefox version: 67.0.4
- Gesturefy version: 2.1.1

**Comment by Robbendebiene** [comment]
Hi, can you please further describe how your system works. Is Gesturefy installed as a [global](http://kb.mozillazine.org/Installing_extensions#Global_installation) add-on? I never installed an add-on globally, how does the add-on storage work there? Does Gesturefys settings reset every time the profile is deleted?

> Please add on option to disable the onboarding site. I would like to see a setting extensions.gesturefy.noOnboarding or similar, which I could add to a global prefs.js.

Unfortunately this is not possible, extensions cannot read about:config properties. However [managed storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed) might be the solution for this. This API allows me to read properties from a json manifest located at a [specific directory](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location) defined by the administrator.

**Comment by eworm-de** [comment]
> Hi, can you please further describe how your system works. Is Gesturefy installed as a [global](http://kb.mozillazine.org/Installing_extensions#Global_installation) add-on?

Yes, the extension is installed to `/usr/lib/firefox/browser/extensions/{506e023c-7f2b-40a3-8066-bc5deb40aebe}.xpi`.

> I never installed an add-on globally, how does the add-on storage work there? Does Gesturefys settings reset every time the profile is deleted?

The settings are still stored in profile. This is fine if the administrator wants to force a specific addon to be installed and the profile persists. In my case the profile does *not* persist.

> > Please add on option to disable the onboarding site. I would like to see a setting extensions.gesturefy.noOnboarding or similar, which I could add to a global prefs.js.
> 
> Unfortunately this is not possible, extensions cannot read about:config properties.

I have some entries `extensions.*`, so I thought it is possible, at least with specific conditions... Hmm, don't know.

> However [managed storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed) might be the solution for this. This API allows me to read properties from a json manifest located at a [specific directory](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location) defined by the administrator.

So I would have to store a file in `/usr/lib/mozilla/managed-storage/gesturefy.json`? Fine with me.

**Comment by Robbendebiene** [comment]
> The settings are still stored in profile. This is fine if the administrator wants to force a specific addon to be installed and the profile persists. In my case the profile does not persist.

I still don't get the use case of your scenario. Why would one use Gesturefy or another add-on when its settings are not saved (because the profile does not persist)?

> So I would have to store a file in /usr/lib/mozilla/managed-storage/gesturefy.json?

Yes

**Comment by eworm-de** [comment]
> > The settings are still stored in profile. This is fine if the administrator wants to force a specific addon to be installed and the profile persists. In my case the profile does not persist.
> 
> I still don't get the use case of your scenario.

Ok, let's see some scenarios.

Consider you are pupil or student and visit IT courses. You sit down, power on the device in front of you, finally you start Firefox. Before you can start surfing you have to close a number of popups and onboarding sites. That happens every time you power on the device...
The device in front of you is just a thin client, that connects to a virtual machine - deployed in hundreds. After each session the virtual machine is destroyed and a clean one is deployed. A friendly administrator pre-installed some useful addons, but as no profile exists the popups and onboarding sites appear again and again.

You are administrator and have your daily tools on bootable USB storage, like [this one](https://www.eworm.de/linux/nepu/). You boot the system, start Firefox and a number of popups and onboarding sites welcomes you. You have to close these before you can start to google your problem.
Again, nothing is stored in a profile. This happens every time you boot from your USB storage.

> Why would one use Gesturefy or another add-on when its settings are not saved (because the profile does not persist)?

Well, Gesturefy has good default settings, no need to save anything. ;)

I love Gesturefy and of course I will continue using it on my usual machines. The current behavior is fine for 99.9% use cases. However I will have to stick with version 2.0.4 or remove Gesturefy completely form virtual environment and live system if I can not disable the onboarding site. I do not like both of these choices.

**Comment by Robbendebiene** [comment]
I'm sorry, but I decided not to implement a managed storage option.

As a workaround I wrote a tiny add-on that immediately closes the on-boarding page if it gets opened. It's far from perfect but maybe it serves your needs.

[remove-onboarding.zip](https://github.com/Robbendebiene/Gesturefy/files/3875577/remove-onboarding.zip)

Before you can install the extension you first need to change the `xpinstall.signatures.required preference` in `about:config` to **false**. Then you can go to `about:addons` click the gear icon and select "install from file" (even if you are probably not installing it this way)

Is there a reason why you can't ship your VM with a very basic preset-up Firefox profile, so the on-boarding page won't show up?
