### ISSUE TITLE
add to "Open link in new tab" function "New tab position"

### ISSUE THREAD

**Issue by Dituar** [Robbendebiene/Gesturefy#409]
add to "Open link in new tab" function "New tab position", like Gesture "New tab".
it's better if "Open link in new tab"="U", and "Open link in new tab"with"New tab position=left tab"="UL"

### Your System
- Operating system:win7 x64
- Firefox version:67.0.4
- Gesturefy version:2.1.1

**Comment by Robbendebiene** [comment]
Done: 62f05aeec306c3f4a0aa338ca4cb8284175196da

**Comment by Robbendebiene** [comment]
Added in Gesturefy [2.1.2.](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.2)
