### ISSUE TITLE
Firefox esr version can not install it

### ISSUE THREAD

**Issue by ctrlbbj** [Robbendebiene/Gesturefy#412]
### Describe your matter in detail

Gesturefy can not install on Firefox ESR Version.
The minimum available version number is 63, but the esr version is lower than 63. Can this be fixed?
### Your System
- Operating system: Win 10 x64
- Firefox version: 60.8.8esr

**Comment by jdreesen** [comment]
The latest ESR version is Firefox 68 (but ESR 60 is still supported for ~14 weeks).

**Comment by Robbendebiene** [comment]
@jdreesen is right. But to be honest, if this wouldn't be the case I wouldn't "fix" this. At the end of the day one can always use an older version of Gesturefy where the feature which caused the minimum version change is not available.

**Comment by Robbendebiene** [comment]
@jdreesen is right. But to be honest, if this wouldn't be the case I wouldn't "fix" this. At the end of the day one can always use an older version of Gesturefy where the feature which caused the minimum version change is not available.
