### ISSUE TITLE
[Suggestion] "Middle mouse PASTE" function

### ISSUE THREAD

**Issue by kramola-RU** [Robbendebiene/Gesturefy#413]
Could you add the "middle mouse paste" function?
I know that the Firefox has a built-in function "middle mouse paste".
But this function works poorly - it can`t make replace the selected text by text from clipboard when doing paste.

**Comment by Robbendebiene** [comment]
Sorry, but this goes beyond Gesturefys intended use. I suggest using another add-on. [This](https://addons.mozilla.org/firefox/addon/autocopyselection2clipboard/) may satisfy your needs.

**Comment by kramola-RU** [comment]
It`s clear.
Thank you for the reply.
