### ISSUE TITLE
[Bug] Gesture not working if the pointer return from scrollbar

### ISSUE THREAD

**Issue by gabelluardo** [Robbendebiene/Gesturefy#414]
### Describe your matter in detail
When the gesture arrives on the scrollbar the application seems to crash and the line appears disconnected from the pointer

To reproduce:
1. Made a gesture
2. Continue without release the mouse button till the scrollbar
3. Release the mouse button on the scrollbar
4. Return from the scrollbar into the page

### Screenshots or further assistance
![Screenshot_20190717_160745](https://user-images.githubusercontent.com/42920247/61382593-5fb4be00-a8ad-11e9-84b4-4690755aa400.png)
![Screenshot_20190717_161225](https://user-images.githubusercontent.com/42920247/61382786-b4f0cf80-a8ad-11e9-8a79-cda8c68bd228.png)

### Your System
- Operating system: Kubuntu 18.04 LTS
- Firefox version: 68.0 (64 bit)
- Gesturefy version: 2.1.1

**Comment by Robbendebiene** [comment]
Thanks for the report. I know the reason of this bug, but the fix might be a little bit hard.

**Comment by Robbendebiene** [comment]
This bug is fixed with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
