### ISSUE TITLE
Doesn't work on certain page

### ISSUE THREAD

**Issue by jim829** [Robbendebiene/Gesturefy#415]
Webpage: http://www.jonhunt.com/undying2/index.html

Functions tested: Close Tab, Next Tab, Previous Tab

- Operating system: Windows 10 1903
- Firefox version: 68.01
- Gesturefy version: 2.1.1

I've read that the extension doesn't work on iframes due to an issue with Firefox but I'm coming from FireGestures which has no problem working on this page or any with iframes. If you could work around this issue I'd likely prefer your extension because it has a smaller footprint.  Thanks.

**Comment by Robbendebiene** [comment]
On which part exactly does Gesturefy not work? Can you please add a screenshot of the problematic region? Because it's working for me.

**Comment by jim829** [comment]
In this [pic](https://imgur.com/TIziijS), it's showing the frame left.html which isn't working for me, only the very left sidebar region works for gestures. It also doesn't work on my Motorola modem's page, which didn't work with FireGestures either until a bug report was filed and fixed. I think it uses the same trickery as Stylus to expose iframes. As per their options page... "Exposes the top site domain in each iframe. Enables writing iframe-specific CSS like this: html[stylus-iframe$="twitter.com"] h1 { display:none }".

**Comment by Robbendebiene** [comment]
Gesturefy uses another approach to deal with iframes. Nevertheless it should work in every iframe/frame except for dynamically created frames (as far as I know no extension can handle this properly).

> Edit 2: I figured part of the problem out. It doesn't work with resistFingerprinting enabled. It'd be great if it did, if not no big deal. Thanks.

Gesturefy does not work properly with resistFingerprinting enabled. This is a known issue and stated for example in the add-on description. The reason for this is the other approach it uses to deal with frames. The Mozilla devs however are aware of that problem and are willing to fix this someday.

**Comment by jim829** [comment]
> This is a known issue and stated for example in the add-on description.

I feel dumb now and sorry to waste your time. Go ahead and close/delete this if you like. I read a comment you made about resistfingerprinting not being very effective and so I'll henceforth keep it disabled.

**Comment by Robbendebiene** [comment]
No problem :)
