### ISSUE TITLE
Tooltips remain visible when opening new tab

### ISSUE THREAD

**Issue by nayhem** [Robbendebiene/Gesturefy#416]
### Describe your matter in detail
As of version 68 or so, using the "New tab" or "Open link in new tab" gestures while hovering over an element with a tooltip (HTML "title" attribute) causes the tooltip to reappear over the new tab. The tooltip remains visible until returning to the originating tab, where the tooltip can be dismissed by normal behaviors. The tooltip sometimes remains visible when Firefox is minimized, and can appear over other programs while Firefox is in the background.

### Screenshots or further assistance
![Capture](https://user-images.githubusercontent.com/36061320/61999959-4962eb00-b081-11e9-8703-0b7aa2b02212.PNG)

### Your System
- Operating system: Windows 10 Home 1903
- Firefox version: 68.0.1
- Gesturefy version: 2.1.1

**Comment by Stimmenhotel** [comment]
Same for switching the tab focus.

**Comment by Robbendebiene** [comment]
This is a Firefox related bug. It will be fixed in the next version as far as I know ([more information here](https://bugzilla.mozilla.org/show_bug.cgi?id=1550637))

**Comment by Robbendebiene** [comment]
I'm closing this issue since it will be fixed in Firefox 69
