### ISSUE TITLE
Manual language selection

### ISSUE THREAD

**Issue by bubblefoil** [Robbendebiene/Gesturefy#418]
I would appreciate if there was a language settings which would override the system language.
I translate the Czech localization but my system and applications are in English so I cannot easily check the outcome.

**Comment by Robbendebiene** [comment]
Gesturefy is using the i18n api which automatically returns the best matching translation. So Gesturefy itself cannot specify which language to use, but according to mdn you can set the language in about:config. Check out the first five steps here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Testing_out_your_extension
