### ISSUE TITLE
Scroll to bottom not working from top of page 

### ISSUE THREAD

**Issue by trogau** [Robbendebiene/Gesturefy#419]
I'm only having this problem on one particular site; ordinarily I'd hesitate before logging but this extension seems to work so perfectly everywhere else I thought it might be of interest. 

The ABC website in Australia has a weird issue where I the scroll to bottom gesture doesn't fire only if I'm already at the top of the site. 

To reproduce: 

1) Go to https://www.abc.net.au/news/
2) Perform the scroll-to-bottom gesture and note that it doesn't fire - it correctly draws the gesture on the screen and flashes up the 'scroll to bottom' text, but the viewpoint does not scroll to the bottom. 
3) Press the down arrow to scroll down one unit (or click the down arrow in the vertical scroll bar once). 
4) Try the scroll-to-bottom gesture & note that it works as expected. 
5) Try scroll-to-top gesture; it works as expected. 
6) Try scroll-to-bottom again & note that it no longer works now you're back at the top of the page. 

Other gestures work as expected. 

I note that if I load the page and hit 'End' on the keyboard, it dynamically loads some content at the bottom of the page, perhaps that is messing with the `ScrollBottom` function?

I replaced the `code` section of `ScrollBottom` with the following and it works as expected on the ABC site, although I didn't test it widely on others: 

`
  let scrollingElement = (document.scrollingElement || document.body);
  scrollingElement.scrollTop = scrollingElement.scrollHeight;
`

### Your System
- Operating system: Windows 8.1
- Firefox version: v68.01
- Gesturefy version: 2.1.1 (loaded from file as temporary add-on)

**Comment by Robbendebiene** [comment]
Thanks for the detailed report. Unfortunately this is a known [issue](https://github.com/Robbendebiene/Gesturefy/issues/264) and we do not know how to solve it.
Your solution does only work in this specific case and also ignores the scroll duration of the Scroll To Bottom command (It will always take 1 second);

**Comment by trogau** [comment]
No problems, thanks for the update. Feel free to close this issue & I can monitor from the other one (apologies, I didn't find that one in an obviously too-quick search).

**Comment by Robbendebiene** [comment]
> (apologies, I didn't find that one in an obviously too-quick search).

No problem :) Your issue made me revisit the topic and I might implement a workaround.
