### ISSUE TITLE
[Bug] Pasting with gesture on Incognito (Firefox) pastes two times 

### ISSUE THREAD

**Issue by GeroDolja** [Robbendebiene/Gesturefy#422]
With one of the latest Firefox update pasting something with a gesture pastes two times. Only happens on Incognito mode and Firefox.

- Operating system: Windows 7
- Firefox version: 69.0.1 (64-bits)
- Gesturefy version: 2.1.2

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll look into it.

**Comment by Robbendebiene** [comment]
Fixed in [Gesturefy 2.1.3](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.3)
