### ISSUE TITLE
get to the root url of a website

### ISSUE THREAD

**Issue by Ridbowt** [Robbendebiene/Gesturefy#425]
Hello! Is it possible to implement the ability to go to the main page (root url) of a website? For example, we are on the page: _https://example.com/one/two/three/_ and we want to get directly to _https://example.com/_ with a single mouse gesture! It's possible now, but it's onerous to do so: _https://example.com/one/two/three/ >> https://example.com/one/two/ >> https://example.com/one/ >> https://example.com/_

**Comment by Robbendebiene** [comment]
Simple user scripts are now available with [Gesturefy 2.1.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.5).
Look for the "Execute User Script" command and use the following code.

`window.location = "/"`

Also set the "Target frame" option to "Top frame".

For more information, please visit the [Wiki](https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script).
