### ISSUE TITLE
[Bug] Restarting FF and restoring tabs with non-standard zoom level will offset the gesture trace

### ISSUE THREAD

**Issue by ganego** [Robbendebiene/Gesturefy#426]
### Describe your matter in detail
- Use "Zoom Page WE" (https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/) to set a default zoom level for all sites of 150% (for example).  
- Make FF remember the session when closing (General options -> "Restore previous session").
- Open at least two website tabs.
- Close FF, open FF - the old session should now be reused and the previously selected tab should load.
- Right-click on the other open tab and select "Reload Tab". 
- Switch to this tab after it loaded.
- Draw a gesture -> Gesture will be offset from the mouse position.

### Screenshots or further assistance
https://imgur.com/bo9tLkH

### Your System
- Operating system: W7x64
- Firefox version: 69.2
- Gesturefy version: 2.1.2

**Comment by Robbendebiene** [comment]
I followed your instructions, but I was not able to reproduce the problem. Your issue seems similar to: #421 

Some questions:

- Does this problem only occur if you restart Firefox?
- Does it only occur on the first page?
- Does the problem disappear when you reload the tab?

**Comment by ganego** [comment]
> I followed your instructions, but I was not able to reproduce the problem. Your issue seems similar to: #421

Yes it's similar. I still wanted to make a new bugreport since I could reproduce this 100%. I just wrote the description out of my head and did not check again, sorry. 
I updated the description. You have to have two opened tabs when restarting and have the second one load via the right-click menu for this tab.

> Some questions:
> 
>     * Does this problem only occur if you restart Firefox?
I only switched to Quantum some days ago, but yes it seems so. But I never tried session restore via another addon yet.

>     * Does it only occur on the first page?
On every page you load the way I (now) described above (I use FoxyTab addon to reload dozens of tabs after a restart).

>     * Does the problem disappear when you reload the tab?
Yes.

**Comment by Robbendebiene** [comment]
All right I was able to reproduce it. I'll look into it.

**Comment by Robbendebiene** [comment]
Fixed in [Gesturefy 2.1.3](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.3)

**Comment by ganego** [comment]
Thank you. Will report back once it got pushed to AMO.

**Comment by ganego** [comment]
Works fine, thank you.
