### ISSUE TITLE
[bug] Open link in new tab doesn't work with image links

### ISSUE THREAD

**Issue by ZaPPZion** [Robbendebiene/Gesturefy#427]
I'm not sure if this has always been the case, but lately I've been noticing that if I use the "Open link in new tab" gesture over images (starting on the image actually) that are links (specifically on for example youtube), the links are not opened, but a new tab is opened. The gesture works fine if I'm starting from the text below the image.

OS: win10
Firefox version: 70.0 (64-bits)
Gesturefy 2.1.3

**Comment by Robbendebiene** [comment]
So far I was only able to reproduce the issue on youtube thumbnails. For some weird reason their custom elements do not return a parent node..
This could be a Firefox bug, do you know if it worked in a previous version?

**Comment by Robbendebiene** [comment]
I may implement a fallback for this.

**Comment by ZaPPZion** [comment]
Wow, yea, youtube is indeed the problem. If I just use the gesture and stay within the image bounds, it's no issue indeed. The gesture used to work fine, just an occasional (1 in 50 or so) miss, but that might be user-error or just the browser not being fast enough and the mouse already leaving, so that wasn't an issue. But it's def youtube javascript causing this indeed. Odd choice to remove a link from an image if there's no mouse present.

**Comment by Robbendebiene** [comment]
This bug is fixed with the release of [Gesturefy version 3.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.0).
