### ISSUE TITLE
Switch to new empty tab when opened with gesture

### ISSUE THREAD

**Issue by Discothorsten123** [Robbendebiene/Gesturefy#429]
Opening a new tab with Ctrl-T switches to it automatically, doing it via mouse gesture does not. Please change this so behavior is consistent.

Thanks so much.

- Firefox version: 70
- Gesturefy version: 2.1.3

**Comment by Robbendebiene** [comment]
Just Reassign the "New Tab" command and activate the "Focus new tab" option.

**Comment by Discothorsten123** [comment]
Ok, that works. Thanks so much for the quick reply!

I guess this feature was introduced after I had the gesture assigned since it is on by default, but only for newly assigned gestures.

Thanks again!
