### ISSUE TITLE
Bookmark Link gesture

### ISSUE THREAD

**Issue by kirill9000** [Robbendebiene/Gesturefy#43]
...would be much appreciated. :)

**Comment by Robbendebiene** [comment]
Good idea, I'll add this in the next version :)

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/4c208b51d698981648d74fc90d2bc588f13c1bba

**Comment by kirill9000** [comment]
Thank you! I have one suggestion: make Gesturefy deduce link title from surrounding elements instead of using domain name. See Mozilla's algorithm that does it [here](https://dxr.mozilla.org/mozilla-central/rev/97efdde466f18cf580fda9673cf4c38ee21fc7b7/browser/modules/ContextMenu.jsm#304).

**Comment by Robbendebiene** [comment]
Alright, I can not promise that my upcoming implementation will exactly work like mozilla's algorithm, but it should be good enough.
