### ISSUE TITLE
Frequently have to repeat gestures

### ISSUE THREAD

**Issue by Beckfield** [Robbendebiene/Gesturefy#430]
Nearly every time (I'd guess 90% of the time), when I try to gesture to go back (rtclk+slideleft), it fails to work the first time. The trail it draws doesn't completely draw, and when I repeat the gesture, the original path and the new path are drawn together, and the 'back' operation works. This is extremely annoying, making Gesturefy nearly unusable.
This happens on pretty much any page, but Google is an easy example. It doesn't matter if the page is fully loaded or not, so it's not a matter of trying too soon. It also happens when going forward (rtclk+slideright), so it isn't specific to one gesture.
 
- Operating system: Windows 10 and Linux Mint 19.1
- Firefox version: 70.0 (Windows) and 69.x (Linux)
- Gesturefy version: 2.04

**Comment by Robbendebiene** [comment]
Can you please update Gesturefy to the latest version and check if the issue still exists?
If this doesn't help, please try Gesturefy in a new clean Firefox user profile and check if the issue persists.

At the moment I cannot reproduce the problem, everything is working as expected for me.
