### ISSUE TITLE
OSX right click window focus behaviour

### ISSUE THREAD

**Issue by ledeniz** [Robbendebiene/Gesturefy#433]
Hello there,

I'm pretty sure this issue only occurs on OSX and I'm not sure if this is managable by the extension, so feel free to close this issue if you know that it's not possible.

### Describe your matter in detail
An "inactive" (= not focused) firefox window stays inactive, even if I start/perform a gesture in it. This is especially tedious when you have the habit to open a new tab and start typing, because normally this would result with a focused url bar in a new tab, but you'll end up typing in the window that is still focused. 

As said, I don't know if it's possible to "steal" the focus because it seems that right click on OSX never leads to a focused window :(

### Your System
- Operating system: OSX Catalina 10.15.1
- Firefox version: 70.0.1
- Gesturefy version: 2.1.3

**Comment by Robbendebiene** [comment]
Hi there, I wrote you a tiny add-on that should focus the main window on startup. If this does not work I'm probably not able to solve your problem.

[start-up-focus.zip](https://github.com/Robbendebiene/Gesturefy/files/3875331/start-up-focus.zip)

You can test the extension by setting the `xpinstall.signatures.required` preference in `about:config` to **false**. After that you can install it on `about:addons` by clicking the gear icon and selecting "install from file"

More details here: https://extensionworkshop.com/documentation/develop/testing-persistent-and-restart-features/#what-do-i-do-to-ensure-i-can-test-my-extension

**Comment by Robbendebiene** [comment]
What happens when you click in the area below without previously focusing the window: https://codepen.io/Robbendebiene/pen/XWWGOMY Do you get the alert?

**Comment by ledeniz** [comment]
Yes! That works with right click. The window is still not focused though (I fear this cannot be forced?)

**Comment by Robbendebiene** [comment]
Please test it again and see if the window now receives focus? (https://codepen.io/Robbendebiene/pen/XWWGOMY)

**Comment by Robbendebiene** [comment]
Btw, just for my personal interest. Does the same problem occur if you change your mouse gesture button to the left mouse button? Or does the window then receive focus once you click? I guess so from reading your first comment.

**Comment by ledeniz** [comment]
> Please test it again and see if the window now receives focus? (https://codepen.io/Robbendebiene/pen/XWWGOMY)

It does not receive focus :/

Interestingly, if I set the left mouse button as the mouse gesture button, the window receives focus _but_ I can't draw gestures with that click.

**Comment by Robbendebiene** [comment]
This is strange. I wonder why they decided to only focus windows on left click.
As a last chance you can try to install the following add-on as I described in my first comment.

[focus-on-pointerdown.zip](https://github.com/Robbendebiene/Gesturefy/files/3886839/focus-on-pointerdown.zip)

This should always focus the Firefox window you clicked in (regardless if it was the middle, right or left mouse button). Note like Gesturefy this does not work for restricted pages like about:addons.

If this does not work I'm out of ideas and there is probably no way I can fix this :|

**Comment by ledeniz** [comment]
Unfortunately that does not seem to work. I guess this really is an OS(X) level problem.
But I appreciate your help! Thanks for your commitment.

**Comment by Robbendebiene** [comment]
Too bad. :|
If you ever find a solution or workaround, it would be nice if you could post it here. In the meantime I'm closing this issue.
