### ISSUE TITLE
data: is not a privileged URI

### ISSUE THREAD

**Issue by ganego** [Robbendebiene/Gesturefy#436]
https://github.com/Robbendebiene/Gesturefy/blob/107baf55492a25fd1ad4ebe7ea66770862e8778e/src/core/commons.js#L133

data: is not a privileged URI:
https://hg.mozilla.org/mozilla-central/file/bb0febbdbb25/toolkit/components/extensions/MatchPattern.cpp#l266

This leads to another interesting question:
Why does Gesturefy still properly work on data: pages despite the check?

Test:
`data:text/plain;charset=utf-8,foo` -> Gestures work fine.

Why do you even have this check in the first place anyway?  
FF won't allow the addon to run if it detects a privileged site, so checking for it again does nothing (and you are missing some privileged URIs in this list...).  
In addition to that, it prevents me - who tries to make addons work on about: pages again - from using the addon, since now not only do I have to patch FF code, but also the extension.  

-----------------------------------
And since I actually first tested this with svg and just later found out that other data: pages will work:

Why does Gesturefy not work on svg data: pages? FoxyGestures works perfectly fine, so it cannot be a FF issue.

Test svg as data: that works fine with FoxyGestures but not with Gesturefy:

`data:image/svg+xml;charset=utf-8,%3Csvg width='16' height='16' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M10.9234032,9.50890701 C12.737938,6.95888863 12.2955018,3.44377439 9.90564952,1.42294873 C7.51579721,-0.597876924 3.97603357,-0.45005508 1.76298925,1.76298925 C-0.45005508,3.97603357 -0.597876924,7.51579721 1.42294873,9.90564952 C3.44377439,12.2955018 6.95888863,12.737938 9.50890701,10.9234032 L14.3442769,15.758773 C14.7423023,16.0996333 15.3356221,16.0767159 15.706169,15.706169 C16.0767159,15.3356221 16.0996333,14.7423023 15.758773,14.3442769 L10.9234032,9.50890701 Z M6.01781012,10.0405971 C3.8016267,10.0405971 2.00505507,8.24402543 2.00505507,6.02784201 C2.00505507,3.81165859 3.8016267,2.01508696 6.01781012,2.01508696 C8.23399354,2.01508696 10.0305652,3.81165859 10.0305652,6.02784201 C10.0305652,7.09209082 9.60779398,8.11275077 8.85525643,8.86528832 C8.10271888,9.61782587 7.08205893,10.0405971 6.01781012,10.0405971 Z' fill-rule='nonzero' fill='%23000'/%3E%3C/svg%3E`

**Comment by Robbendebiene** [comment]
> data: is not a privileged URI:
> https://hg.mozilla.org/mozilla-central/file/bb0febbdbb25/toolkit/components/extensions/MatchPattern.cpp#l266

The data URIs are one of the restricted URI types that cannot be opened in a tab (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create). It's the same for local files, Gesturefy can run in local files, but cannot open them. The purpose of the function is to check if I can actually do something with the URL (obviously I can access the content of the URI therefore I don't call that function when downloading data URI images). 


> This leads to another interesting question:
> Why does Gesturefy still properly work on data: pages despite the check?
> Test:
> data:text/plain;charset=utf-8,foo -> Gestures work fine.
> 
> Why do you even have this check in the first place anyway?
> FF won't allow the addon to run if it detects a privileged site, so checking for it again does nothing (and you are missing some privileged URIs in this list...).
> In addition to that, it prevents me - who tries to make addons work on about: pages again - from using the addon, since now not only do I have to patch FF code, but also the extension.
> 

Please have a look at the code where the function is actually used.

> Test svg as data: that works fine with FoxyGestures but not with Gesturefy:

I would eat one's hat if Foxy Gestures or any other extension that relies on the Canvas API (or other HTML based UI) would **completely** work on a pure svg page. The only thing that's working, is the detection of the mouse movement, everything else (the UI) cannot work and is not working. You could argue that at least the gesture detection functionality should work on svg pages. You've got a point there.
