### ISSUE TITLE
Scroll Up and Down gestures

### ISSUE THREAD

**Issue by kirill9000** [Robbendebiene/Gesturefy#44]
Currently they scroll full page up/down, but it would be more convenient if they scrolled slightly less, like PgUp/PgDown buttons do (~95% of the page).

**Comment by Robbendebiene** [comment]
I totally agree with that. The only thing I'm unsure about is the exact percentage value. Because it changes depending on the window size.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/4c208b51d698981648d74fc90d2bc588f13c1bba
