### ISSUE TITLE
Open link in a new tab modification

### ISSUE THREAD

**Issue by Fercik86** [Robbendebiene/Gesturefy#440]
I would like to request slight change to open link in a new tab function. I highly appreciate that there is option to open home page when there is no link where gesture started but I would like that home page to be opened in the foreground not background as links are. I think it is more logical way of using it. It does not have to permanent change. Even by adding some toggle to change this functionality it would be very appreciated.

**Comment by Robbendebiene** [comment]
Thanks for your feature request.
As all software developers we always have to walk the thin line between keeping Gesturefy simple and uncluttered and providing maximum customization. While I can understand your use case, I consider this feature as too specific to be added. Sorry for that.

However we are thinking about a solution that could solve your and a lot of other use cases. It's the ability of chaining multiple commands together (#313). So you would have a combination of [Open Link In New Tab] and [New Tab] command. If the first one fails the next one will be executed and so on. Unfortunately we haven't found a good UI representation for this yet.

**Comment by Fercik86** [comment]
The chaining of multiple commands would be an amazing feature to add in my eyes. I can already think of few use cases. I am missing the feature I mentioned because I only recently switched from chrome where I was using different kind of extension where new tab worked as I mentioned.

**Comment by Robbendebiene** [comment]
I'm closing this issue in favor of #313
For any further ideas related to this topic, please comment there.
