### ISSUE TITLE
Option for Wheel Gestures to ignore Suspended/Discarded Tabs

### ISSUE THREAD

**Issue by Trixlight** [Robbendebiene/Gesturefy#442]
For quite some time, **Wheel Gestures** correctly supports the "_Hidden Tabs_" feature in Firefox.
That's great, but there's still a "_Suspended/Discarded Tabs_" feature that Gesturefy doesn't support yet.

It will be nice to have an additional checkbox under the **Wheel Gestures** settings that can allow the function for **Wheel Gestures** to ignore this "_Suspended/Discarded Tabs_."

**Comment by Robbendebiene** [comment]
I can see some use cases. This will be added to the "Focus X tab" commands like #443

**Comment by Robbendebiene** [comment]
Added in Gesturefy version [2.1.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.4)
