### ISSUE TITLE
Option for Wheel Gestures: don't wrap between the last and first tabs

### ISSUE THREAD

**Issue by Trixlight** [Robbendebiene/Gesturefy#443]
Currently, after reaching the last tab using **Wheel Gestures**, if you continue switching tabs, you will return to the first tab.

It would be nice to be able to disable this behaviour under **Wheel Gestures** settings.

**Comment by Robbendebiene** [comment]
This is a good idea. However this setting will be added to the "Focus Right Tab" and "Focus Left Tab" commands, since every possible command can be assigned to wheel gestures, so it is not a wheel gesture specific setting.

**Comment by Trixlight** [comment]
Fair.
But since "Focus Right Tab" and "Focus Left Tab" is the default actions for Wheel Gestures, it's unlikely that the user will check them. So you might as well put a small notification on the Wheel Gestures setting page? Just to let the user know that this option exists.

**Comment by Robbendebiene** [comment]
> But since "Focus Right Tab" and "Focus Left Tab" is the default actions for Wheel Gestures, it's unlikely that the user will check them  So you might as well put a small notification on the Wheel Gestures setting page? 

This problem also applies to default mouse gestures. As for example the "New Tab" gesture has some settings of which the user might not be aware of.

We know this problem, but haven't figured out a good solution yet. A new issue for this problem might be helpful in order to work towards a solution.

**Comment by Robbendebiene** [comment]
Added in Gesturefy version [2.1.4](https://github.com/Robbendebiene/Gesturefy/releases/tag/v2.1.4)
