### ISSUE TITLE
Issue on touch enabled Windows devices

### ISSUE THREAD

**Issue by Fercik86** [Robbendebiene/Gesturefy#444]
I found issue with gesturefy while using my secondary Windows machine that has touchscreen. For some reason I cant left click on any links. I tried troubleshooting first whether its the device problem but other browsers worked just fine. After launching firefox in safe mode it also worked fine. Then when I was going through extensions I found it was caused by gesturefy. What is weird for me is that everything else that needs left click/tap works just fine. When I try clicking/tapping I only get the link preview on sites that have any. When using mouse/touchpad everything is fine. Any idea what might be causing this behaviour and some way to remedy it?

**Comment by Robbendebiene** [comment]
Since I cannot reproduce your issue I need a little bit more information and I'm still not sure when exactly your problem occurs.

>  For some reason I cant left click on any links.

Are you interacting via touch screen or mouse?

Can you select text or stop/play videos?
Do you have Wheel or Rocker gestures enabled?
Which version of Gesturefy and Firefox are you using?

**Comment by Fercik86** [comment]
I am using latest version of both gesturefy and firefox.
I have wheel and rocker gestures enabled but when I tried turning them off it didnt help I also tried to change action button from right click but it did not help as well.
VIdeos are no problem also operating firefox like clicking back/home/zoom is just fine
Only problem is with hypertext links like you get when googling something. When I try to click such link with mouse it works just fine. When I try to use touch input it sipmly will not let me click it. Right click and other touch functions work just well. But when I try to simply tap I cant. Sometimes I get preview of the link the same way as when you hover cursor over link. 
If this is still not helpful enough I can try to record this behaviour and send it to you.

**Comment by Fercik86** [comment]
Here is the video demonstrating what the issue is
https://send.firefox.com/download/4123871e74320f34/#0h_EFzkLqPDnXg5Vo8KAvg

**Comment by Robbendebiene** [comment]
Thanks for the video.
I finally have an idea where the source of the problem could be located.

Can you please test the following:

1. Open https://codepen.io/Robbendebiene/pen/JjoqpOP
2. Click the link with your mouse and save/note the displayed values.
**3. Do the previous step again but use your finger/touch input instead.**
4. Please provide me the output data

**Comment by Fercik86** [comment]
https://send.firefox.com/download/488b8c5b96ffa99b/#Ak_6jVxlKBrQDsDwSDXqDA
the first try is with mouse the second one is touch

**Comment by Robbendebiene** [comment]
I have no clue how Gesturefy can cause this issue.
Can you please double check that everything is working when you disable Gesturefy completely.
Also double check that wheel or rocker gestures are not causing the problem.

You can also try to increase the gesture distance threshold up to 200 (You can find this in Gesturefy Settings, Advanced Settings right at the beginning). But I doubt that this will solve the problem.

**Comment by Fercik86** [comment]
I did a more "proper" check now with restarting firefox after every change I made not just refreshing the site. It is the wheel gesture that is causing this issue. Rocker works just fine. When I changed wheel gesture mouse button from left click to right click issue was resolved as well. I am sorry for misreporting but I thought just refreshing would be good enough same as when adding new gestures apparently I was wrong.

**Comment by Robbendebiene** [comment]
>  It is the wheel gesture that is causing this issue. 

Thanks! This makes at least a little bit more sense to me :)
 I'll look into it again.

> but I thought just refreshing would be good enough same as when adding new gestures apparently I was wrong.

You shouldn't even have to reload the page when you change a setting.

**Comment by Robbendebiene** [comment]
Sorry for the late reply.
I need you to test another thing for me, in order to comprehend the bug.

When you click the area with your mouse here: https://codepen.io/Robbendebiene/pen/poJyoOg a popup should open. Does it also open when you use touch?

**Comment by Robbendebiene** [comment]
Are you also sure that only wheel gestures cause the problem and rocker does not?
It makes sense to me that wheel gestures can cause this problem when set to left mouse button, but in this case rocker gestures should have the same problem.

**Comment by Fercik86** [comment]
Everything works just fine with both rocker gestures enabled. I have set focus previous tab for both of them. And here is result from test site https://send.firefox.com/download/0223fb328b49a418/#VbJZEaEjUOP_R4lEzp7EwQ
first try is with regular mouse second is with touch. At least now there is some difference.

**Comment by Robbendebiene** [comment]
I released another Gesturefy version which should fix your issue. It should be available in about one or two days. It would be nice if you could confirm that :)

**Comment by Fercik86** [comment]
My notebook finally received update for gesturefy and from initial testing it seems that the issue has been resolved. Many thanks

**Comment by Robbendebiene** [comment]
Thanks for confirming that. :)
