### ISSUE TITLE
dont make gestures show up for rightclick draggin in own application?

### ISSUE THREAD

**Issue by fredlllll** [Robbendebiene/Gesturefy#445]
hi, couldnt find anything on this yet, so i figured i ask here:

im making my own application and i want to move a camera by rightclick dragging. this now makes gesturefy come up and i start drawing gestures instead of controling my app. what can i do in my app to not draw gestured when im trying to control my viewport?

here a little videoclip of what happens when i try to rightclick drag on my viewport: https://send.maketheory.com/viewer?File=21813be4-7357-4fee-9eec-434b8703baee.mp4 (sorry for the weird hoster, its a work thing)

i noticed the behaviour with other applications too and its annoying that i cant control them with gesturefy enabled

**Comment by Robbendebiene** [comment]
Hi, you can enable a "Gesture suppression key" like Ctrl or Shift in the Gesturefy settings. So when you hold the specific key, while doing something with right click, gestures are not detected. Alternatively you can blacklist your site in Gesturefy (I would recommend this if you are using your site very frequently)

Hope this helps.
