### ISSUE TITLE
Trail draws very slowly with layout.css.devPixelsPerPx increased

### ISSUE THREAD

**Issue by clavinet** [Robbendebiene/Gesturefy#447]
- Operating system: openSUSE Tumbleweed 20200205
- Firefox version: 72.0.2
- Gesturefy version: 2.1.4
When setting a different value than 1 to layout.css.devPixelsPerPx in about:config, the gesture trail draws very slowly. It happens on all pages.

**Comment by Robbendebiene** [comment]
I've tried to reproduce the issue without any luck. Are you sure it's caused by the layout.css.devPixelsPerPx setting?

**Comment by clavinet** [comment]
The issue doesn't appear anymore, current software versions:
- Operating system: openSUSE Tumbleweed 20200220
- Firefox version: 73.0
- Gesturefy version: 2.1.6

I'm still using a custom layout.css.devPixelsPerPx setting, but the trail draws smoothly now. Perhaps the Firefox or Gesturefy update in the meantime resolved it.
