### ISSUE TITLE
Mouse text selection broken by latest Gesturefy on MacOS

### ISSUE THREAD

**Issue by arty-name** [Robbendebiene/Gesturefy#448]
### Describe your matter in detail
After getting the notification that my installed version of Gesturefy was updated I started seeing that I cannot select text using mouse anymore. Pressing left mouse button on text and moving the mouse does not have any effect. Disabling Gesturefy and reloading the page resolves the issue: I can select the text again. Re-enabling Gesturefy and reloading the page breaks it again. In addition I noticed that focusing some inputs was broken, for example the search input in the [navigation bar here](https://reactjs.org/docs/getting-started.html).

### Your System
- Operating system: MacOS Mojave 10.14.6
- Firefox version: 72.0.2
- Gesturefy version: 2.1.5

**Comment by Robbendebiene** [comment]
Strange, I only did some slight changes. Do you have wheel gestures enabled?

**Comment by arty-name** [comment]
Just changing the mouse button from middle to right didn’t help me. But when I disabled wheel gestures Gesturefy stopped breaking text selection.

**Comment by Robbendebiene** [comment]
> Just changing the mouse button from middle to right didn’t help me. But when I disabled wheel gestures Gesturefy stopped breaking text selection.

Can you please doublecheck that? Because this shouldn't be the case.

**Comment by arty-name** [comment]
I can only do that tomorrow, will report back

**Comment by arty-name** [comment]
Looks like a new version has been released before I could doublecheck the issue. With the new version I cannot reproduce the bug anymore. Thank you for the fix, @Robbendebiene!

**Comment by Robbendebiene** [comment]
Thanks for the fast report and confirmation!
I'm closing this.
