### ISSUE TITLE
[Request] pinned tabs action

### ISSUE THREAD

**Issue by tail09099** [Robbendebiene/Gesturefy#454]
My English is poor. I'm sorry.

The pinned tab closed with the "close tab" gesture is also closed.
The gesture "Close other tabs" does not close the pinned tab.
I don't want pinned tabs to close.

**Comment by Robbendebiene** [comment]
Sorry, I'm not sure if I understand you correctly.

> The pinned tab closed with the "close tab" gesture is also closed.

If you don't want to close pinned tabs, then you need to edit the gesture (or create a new one) > click the command button (Close Tab) > in the opened sidebar choose "Close Tab" > another command specific settings panel opens which should contain a "Close pinned tabs" setting

**Comment by tail09099** [comment]
Thank you very much.
I understood the command.

**Comment by g-i-o-r-g-i-o** [comment]
great tool :-) thanks

![Image](https://github.com/user-attachments/assets/8a0960bf-59f0-4798-957b-6d2e15e9c4dd)
