### ISSUE TITLE
 Cursor misplaced in address bar after autocompletion when opening new tab with gesture

### ISSUE THREAD

**Issue by mattcoz** [Robbendebiene/Gesturefy#455]
I originally reported this as a bug in Firefox, but it looks like it might be in Gesturefy instead.

https://bugzilla.mozilla.org/show_bug.cgi?id=1628721

> If you start typing in the new address bar it will autocomplete the URL and place the cursor at the end of the text. This is misleading because it appears that continuing to type would place text at the cursor location. But, it does not, it places it at the original cursor location. In the old address bar, the autocompleted part was highlighted. This at least gave visual indication that typing would overwrite it.

I've been able to narrow it down to happening when I open a new tab with a mouse gesture and start typing. It also happens if I change the gesture to _not_ focus the tab, switch to the tab, focus the address bar, and start typing. If I take focus away from the address bar and then focus it again, the cursor behaves normally. It does not happen with a gesture to open a new window. It does not happen if I open a new tab with the new tab button. I've tested with all other add-ons disabled to make sure there is not another conflict.

Windows 10
Firefox Nightly 77 (Can't reproduce in Firefox 75)
Gesturefy 2.16

**Comment by Robbendebiene** [comment]
Thanks for the report. However Gesturefy has no control over the address bar. Gesturefy uses the [tabs.create API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create) to open a new tab, but cannot focus the address bar and also cannot control where the cursor should be placed. So this has to be a Firefox bug.

I was not able to reproduce your problem, but I've only tested it in Firefox 75.

**Comment by mattcoz** [comment]
Ok, well maybe it's a bug with the API then, thanks.
