### ISSUE TITLE
help create a custom gesture 

### ISSUE THREAD

**Issue by Mrakobes666** [Robbendebiene/Gesturefy#457]
help create a custom gesture 
1. open the link in the current tab 

2. copy the link text (name) for example the LINK NAME leads to https://github.com/Robbendebiene/Gesturefy - copy it "LINK NAME"

**Comment by Robbendebiene** [comment]
I'm not sure if I understand you correctly.
Do you want to open the link AND copy the link name (not url)?
This would be a combination of these two issues/user scripts: https://github.com/Robbendebiene/Gesturefy/issues/381 and https://github.com/Robbendebiene/Gesturefy/issues/386

**Comment by Mrakobes666** [comment]
Thanks, the way to copy the link name works!

"Open link in current tab" does not work, please give me a way

**Comment by Robbendebiene** [comment]
There already exists a command for this. It's called "Open Link".
