### ISSUE TITLE
Beg to bulid an extension in Chrome

### ISSUE THREAD

**Issue by lyscop** [Robbendebiene/Gesturefy#458]
It is a nice extension in Firefox. I use Firefox and Chrome at the same time and I prefer to Chrome, but it is not on the Chrome store, so there is not an extension as good as Gesturefy in Chrome, so I beg you that could you build an extension in Chrome. Thank you all the time.

**Comment by Robbendebiene** [comment]
I'm glad you like Gesturefy, but I already declined this request here: https://github.com/Robbendebiene/Gesturefy/issues/218

The Firefox API is already quite limited and in most cases chrome's API is even worse. So some parts of Gesturefy couldn't even theoretically be ported to chrome. I'm sorry for that.

**Comment by lyscop** [comment]
Hi,

Thank you for your email.

I get it, and I find Chrome is so bad for its API, now I turn to Firefox.

Best.

Robbendebiene <notifications@github.com> 于2020年4月22日周三 下午5:35写道：

**Comment by Robbendebiene** [comment]
Thank you for your understanding!
