### ISSUE TITLE
No gestures in Reader View

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#46]
No gestures on any page in Reader View.

**Comment by Robbendebiene** [comment]
Thanks for the report. This is currently a webextension api limitation, but according to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1371786) mozilla is working on it.

**Comment by happysurf** [comment]
Thanks for the info.
Come on Mozilla devs. :-)

**Comment by Robbendebiene** [comment]
Closed in an issue clean up process due to the lack of an appropriate or upcoming API.
