### ISSUE TITLE
Gesturefy stopped executing commands "undo close tabs" and "closed tabs popup"

### ISSUE THREAD

**Issue by chuvak2033** [Robbendebiene/Gesturefy#461]
Windows 10, FF 75.0, Gesturefy 2.1.6
When executing gestures that should commands "undo close tabs" and "closed tabs popup" nothing happens. More recently, everything worked. The add-on was not deleted and the settings did not change. Just at one point I noticed that these commands stopped executing. Perhaps this happened after upgrading to version 75.
PS. Similar add-on "Foxy Gestures" also stopped executing commands "undo close tabs".
P.P.S. Just now FF updated to version 76 and all start working. Problem solved))

**Comment by Robbendebiene** [comment]
Thanks for your report. I don't know what caused the bug. Since both of these commands rely on the "sessions" API and permission I guess something went wrong with that.
If the problem happens again, please post a console log (open console by CTRL + SHIFT + J, minimize it, perform the gesture, look for any new console outputs).

**Comment by csahba** [comment]
Reproduced, on newest firefox 77.0.1 but started happening on 76 I think.

console readout for either is the same:

```
entry is undefined ext-browser.js:957
    convertFromSessionStoreClosedData chrome://browser/content/parent/ext-browser.js:957
    tabs chrome://browser/content/parent/ext-browser.js:1170
    map self-hosted:240
    convertFromSessionStoreClosedData chrome://browser/content/parent/ext-browser.js:1169
    getRecentlyClosed chrome://browser/content/parent/ext-sessions.js:34
    getRecentlyClosed chrome://browser/content/parent/ext-sessions.js:122
    AsyncFunctionNext self-hosted:693
```
A bug in the sessions api?

**Comment by csahba** [comment]
Update

When I reinstalled the addon, and then readded permissions it started to work again. I think I may have a corrupted session, I had a window ith 1700 tabs I closed but is still in my recently closed windows, and I can't seem to shake it form my session.

**Comment by csahba** [comment]
As a consequence of this potentially corrupted session the restore tab function sometimes restores windows even with that setting set to off

**Comment by Robbendebiene** [comment]
@csahba I also still encounter this problem from time to time. The Firefox sessions API is still bugged.
