### ISSUE TITLE
The close gesture does not respect the tabs last-opened order

### ISSUE THREAD

**Issue by AlexandreBonneau** [Robbendebiene/Gesturefy#463]
*Disclaimer ; that problem has existed for months (years?) now, and I just got around to open a bug about it.*

### The problem
Given you have the following tabs:
`[A] B C D`
*(The `[]` symbolize the tab that has the focus)*
When you ctrl+tab you get the last-used order, for instance, you visited the tabs in that order, the last one being the most recent one:
`C B D A`

Using the old firegesture extension, if I were to close my current tab using the gesture, then Firefox would respect my ctrl+tab settings and I would get:
`[A] B C D` -> `B C [D]`, with `D` being the most recent used tab.
*(Do note that weirdly Firefox does NOT currently respect that last-opened order when using the close icon !?)*

Now, Gesturefy ignores that order and keeps focusing on the tab that is on the right of the tab you close, so it currently does that:
`[A] B C D` -> `[B] C D`

Would it be possible to make Gesturefy aware of the ctrl+tab preference?

### My system
- Operating system: Linux Debian Bullseye
- Firefox version: `77.0b5`
- Gesturefy version: `2.1.6`

**Comment by Robbendebiene** [comment]
> (Do note that weirdly Firefox does NOT currently respect that last-opened order when using the close icon !?)

As far as I know Firefox never did this. At least there is no about:config property for this.

> Now, Gesturefy ignores that order and keeps focusing on the tab that is on the right of the tab you close, so it currently does that:
> [A] B C D -> [B] C D

If you edit your gesture and reset the command to "Close Tab" a settings panel will open where you can enable this behavior.

**Comment by AlexandreBonneau** [comment]
This is *nice*!
Thanks for the tip :)

**Comment by LukeOwlclaw** [comment]
> If you edit your gesture and reset the command to "Close Tab" a settings panel will open where you can change this behavior.

@Robbendebiene Thanks, that is exactly what I was looking for.

The related setting can be found here (about:preferences -> Tabs):
![image](https://user-images.githubusercontent.com/2737900/131301527-3202973a-f914-489d-8701-b20cab1370ca.png)

Firefox version 91.0.2
