### ISSUE TITLE
Gesturefy has been updated and no works on the current ESR.

### ISSUE THREAD

**Issue by kokos76** [Robbendebiene/Gesturefy#468]
Thanks for the extension! Please, could you prohibit updating the extension to incompatible versions with the current ESR?

**Comment by Robbendebiene** [comment]
Hi I cannot prevent Gesturefy from updating. This is done by Firefox. However Firefox (in theory) will not update Gesturefy if the version is not compatible. Which version of Gesturefy are you using? Which one were you using before? How did you noticed that it's not compatible?

**Comment by kokos76** [comment]
This is a Firefox synchronization bug. Everything is fine on the desktop, but when I synchronized the extensions with the laptop, the firmware installed the latest version of the extension on the laptop. On the desktop and laptop, I use the latest stable version of the ESR - 68.8.0

**Comment by Robbendebiene** [comment]
Sorry, but there is nothing I can do about that.
I probably would recommend you to exclude extensions from Firefox sync until both Firefox instances are updated to the same version or minimum version of Gesturefy.

You can also report this issue to the Firefox dev team here: https://bugzilla.mozilla.org

**Comment by kokos76** [comment]
Ok, I just manually installed the extension version suitable for ESR 68.8.
Thank you again for your work!
