### ISSUE TITLE
FocusLeftTab/FocusRightTab gestures do not cycle after update to 3.0.0

### ISSUE THREAD

**Issue by jfolz** [Robbendebiene/Gesturefy#471]
Not a big deal. This issue is mainly meant to inform others if they encounter the same problem :)
After the update to 3.0.0 my tab switching gestures were not cycling anymore (jumping to other end of the tab list when you reach the end).
I tried a couple of things, but ultimately deleting the gestures and adding them back - making sure cycling is enabled - fixes this.

**Comment by Robbendebiene** [comment]
Thanks for your report. It's probably because I've changed the default value of tab cycling to disabled. Sorry about that.

I cannot really fix this issue anymore but I'll keep it open to help others that encounter the same problem, as you suggested :)

**Comment by StentMan** [comment]
The issue jfolz reported also happens for me (FF 77.0.1 64 bit on Windows 10). However, I use wheel gestures (right click + scroll wheel up/down) to move around tabs (left/right). Now I can no longer quickly move from the rightmost open tab to the leftmost open tab, which is a bit of a shame.
Anyway around that?

**Comment by jfolz** [comment]
@StentMan find the wheel gestures in extras. Change them to focus WITHOUT cycling (remember to save). Then change back to focus WITH cycling. Should work now.

**Comment by WebFreak001** [comment]
for me it was also enough in the gestures redefining left/right to the same tab focus command, then turning off and on the tab cycling button (maybe this toggling off and on step wasn't needed actually)

![screenshot of cycle tab setting](https://wfr.moe/f6x3ef.png)

**Comment by StentMan** [comment]
thank you for the detailed explanation, that did the trick.

**Comment by robme** [comment]
This has stopped working for me. I've checked @WebFreak001's comment and that is how it is set up, but it does not loop around any more. On Windows 10.

**Comment by Robbendebiene** [comment]
@robme Please try to recreate the entire gesture.

**Comment by robme** [comment]
Yes now it works after deleting the gesture and recreating it.
