### ISSUE TITLE
New action: Inspect element

### ISSUE THREAD

**Issue by bouchedid** [Robbendebiene/Gesturefy#473]
Thanks for the outstanding extension you provide. I would like another to map 'Inspect element' to a gesture. Would that be possible?

In case of multiple Iframe I guess inspecting the global document would do.

**Comment by Robbendebiene** [comment]
Hi, thanks for your feature request.
Unfortunately extensions cannot open browser sidebars, devtools, consoles or anything like that. Add-ons also cannot trigger keyboard shortcuts, so this is currently not possible.

**Comment by bouchedid** [comment]
I see, such a shame! I'll live without it then, thanks for the quick response

**Comment by Robbendebiene** [comment]
Duplicate of #216
