### ISSUE TITLE
[Bug] Right Click Context Menu Disabled on Video Elements

### ISSUE THREAD

**Issue by jmbarber19** [Robbendebiene/Gesturefy#474]
### Description
In order to reproduce this issue, with Gesturefy enabled and the activation button set to right-click, attempt to right click a video element (eg [https://www.w3schools.com/html/html5_video.asp](url)) and no context menu will appear. Disabling Gesturefy and right clicking a video will cause a context menu to appear like normal. These issue occurs regardless of the website. Additionally changing the activation button to left or middle-click will allow normal right click context menus on videos.

### System
- Operating system: Windows 10
- Firefox version: 77.0.1 (64-bit)
- Gesturefy version: 3.0.0

**Comment by Clae224** [comment]
I just got the same bug on Linux.

- OS: Ubuntu 19.10 x86_64
- Firefox version: 77.0.1 (64-bit)
- Gesturefy version 3.0.0

It is reproducible on videos opened with Firefox (i.e. locally saved videos) and disabling the add-on fixes the issue.

**Comment by isn0t** [comment]
I can confirm this behaviour.

Operating system: Windows 10
Firefox version: 77.0.1 (64-bit)
Gesturefy version: 3.0.0

**Comment by Robbendebiene** [comment]
Thanks for the bug report. I'll fix this as soon as possible.

Meanwhile I suggest using a "Deactivation key" in the settings page as a workaround. You should be able to open the context menu while holding the key. (untested though)

**Comment by isn0t** [comment]
Thank you for your feedback and the (working) workaraound!

**Comment by Robbendebiene** [comment]
Version 3.0.1 is out. Can someone please confirm, that this is fixed?

**Comment by isn0t** [comment]
I can confirm, that it works perfect now - no need anymore for the workaround! Thank you, great service!
