### ISSUE TITLE
previous/next page gestures don't work in responsive view mode

### ISSUE THREAD

**Issue by xxvii** [Robbendebiene/Gesturefy#475]
Hello,
nice update but I noticed that when in responsive view mode (Ctrl+Shift+M), the gestures for previous/next page (in history) gestures don't work.
The gesture is recognized (I see the name of the gesture displayed on screen) but nothing happens.
If I come back to the normal desktop view (Ctrl+Shift+M again), the gestures work again.

### Your System
- Operating system: windows 10
- Firefox version: 77.0.1
- Gesturefy version: 3.0.0

**Comment by Itchiii** [comment]
This will be fixed in Firefox Version 78. It's not up to us. You also cannot use the back button of Firefox in this mode.

**Comment by xxvii** [comment]
@Itchiii yes, I realized that just a couple hours ago...Browsing history is completely broken when in responsive design mode, so also the buttons don't work...feel free to close the issue if you want.

Thank you anyway!

**Comment by xxvii** [comment]
@Itchiii I'm sorry to bother again on the problem...I just updated to Firefox 78 but the issue still persist, even on a clean profile.
Where did you read that this would be fixed on FF 78? I can't find the issue on bugzilla...
Thanks

**Comment by Robbendebiene** [comment]
Can you please open a bugzilla ticket for this? Since Gesturefy relies on functions provided by Firefox this probably suffers from the same problem as the Firefox history buttons, which also don't work.

**Comment by xxvii** [comment]
@Robbendebiene here it is: https://bugzilla.mozilla.org/show_bug.cgi?id=1649537

**Comment by Robbendebiene** [comment]
Since this bug will be fixed in Firefox 79 I'm closing this again. In the meantime setting the following about:config property should do the trick: `devtools.responsive.browserUI.enabled`
