### ISSUE TITLE
Gesturefy stopped working with Firefox 77

### ISSUE THREAD

**Issue by froooze** [Robbendebiene/Gesturefy#476]
### Describe your matter in detail
Gesturefy stopped working on Firefox. I still can draw lines, but they have no affect.  

### Your System
- Operating system: MX-Linux
- Firefox version: 77.0.1
- Gesturefy version:  3.0.0

**Comment by froooze** [comment]
https://github.com/Robbendebiene/Gesturefy/issues/472

**Comment by Itchiii** [comment]
Duplicated #472
