### ISSUE TITLE
Link does not open on Twitter Card

### ISSUE THREAD

**Issue by merkatz** [Robbendebiene/Gesturefy#48]
ex. https://twitter.com/firefox/status/912667980521238528
I can not open a link even if I do a gesture on "Link to foreground tab" "Link to background tab" on this kind of Twitter card.

**Comment by Robbendebiene** [comment]
So you try to open the link on the image, which leeds to this page: https://blog.mozilla.org/blog/2017/09/26/firefox-quantum-beta-developer-edition/?utm_content=buffer8e5c2&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer with the mouse gesture and the link does not open in a new tab?

**Comment by merkatz** [comment]
Sorry. I could not open it in Firefox 55.0.3, but in Developer Edition I was able to open it.
I will wait for Firefox update.
