### ISSUE TITLE
README - Lost all your gestures on the recent update? Please read here.

### ISSUE THREAD

**Issue by Robbendebiene** [Robbendebiene/Gesturefy#480]
**The recent update's config migration process leads to a corrupted config when using Firefox sync.**

**Explanation:**
The config gets migrated multiple times. First time on the first machine that receives the update, second time a the next machine that receives the update, but this version already receives a migrated config from Firefox.
(at least this is what I guess from all the error logs I've received)

**Solution:**
The only real "solution" is to reset Gesturefy (Options page > About section > Reset). Even though your config is corrupted you can still create a backup of it. You can post your corrupted config file here (pleas attach as file) and I will try to fix it or at least extract some useful information out of it.

Sorry for the trouble.

**Comment by mamoch** [comment]
If you look at an export of a sane config and compare it to an export of a corrupted one, you might figure out quite easily, how to correct it.

For me it were just wrong surrounding additional `name` variables, e.g.:
**wrong:**
```
"command": {
  "name": {
    "name": "NewTab",
    "settings": {
      "position": "default",
      "focus": true
    }
  }
},
```
**correct:**
```
"command": {
    "name": "NewTab",
    "settings": {
      "position": "default",
      "focus": true
    }
},
```
After correcting all occurences, the config could be imported and everything was working again.

**Comment by rippeddisc** [comment]
Upon req....here is my not working config file;

{
  "Settings": {
    "Gesture": {
      "mouseButton": 2,
      "suppressionKey": "",
      "distanceThreshold": 10,
      "distanceSensitivity": 10,
      "Timeout": {
        "active": false,
        "duration": 1
      },
      "Trace": {
        "display": true,
        "Style": {
          "opacity": 0.8,
          "strokeStyle": "#00AAA0cc",
          "lineWidth": 10,
          "lineGrowth": true
        }
      },
      "Directions": {
        "display": true,
        "Style": {
          "color": "#FFFFFF",
          "backgroundColor": "#000000",
          "backgroundOpacity": 0.3,
          "fontSize": "8vh",
          "textAlign": "center"
        }
      },
      "Command": {
        "display": true,
        "Style": {
          "backgroundColor": "#0000004d",
          "backgroundOpacity": 0.3,
          "fontSize": "6vh",
          "fontColor": "#FFFFFFff"
        }
      }
    },
    "Rocker": {
      "active": false,
      "leftMouseClick": {
        "name": "PageBack"
      },
      "rightMouseClick": {
        "name": "PageForth"
      }
    },
    "Wheel": {
      "active": false,
      "mouseButton": 1,
      "wheelUp": {
        "name": "FocusRightTab"
      },
      "wheelDown": {
        "name": "FocusLeftTab"
      }
    },
    "General": {
      "updateNotification": true,
      "theme": "dark"
    }
  },
  "Gestures": [
    {
      "command": "FocusLeftTab",
      "settings": {
        "cycling": true,
        "excludeDiscarded": false
      },
      "gesture": "UL"
    },
    {
      "command": "FocusRightTab",
      "settings": {
        "cycling": true,
        "excludeDiscarded": false
      },
      "gesture": "UR"
    },
    {
      "command": "OpenLinkInNewTab",
      "settings": {
        "position": "default",
        "focus": false,
        "emptyTab": false
      },
      "gesture": "D"
    },
    {
      "command": "CloseTab",
      "settings": {
        "nextFocus": "default",
        "closePinned": false
      },
      "gesture": "DR"
    },
    {
      "command": {
        "name": "OpenAddonSettings"
      },
      "pattern": [
        [
          -1,
          0
        ],
        [
          0,
          1
        ],
        [
          1,
          0
        ],
        [
          0,
          -1
        ],
        [
          -1,
          0
        ]
      ]
    },
    {
      "command": {
        "name": "FocusLeftTab"
      },
      "pattern": [
        [
          0,
          -1
        ],
        [
          -1,
          0
        ]
      ]
    },
    {
      "command": {
        "name": "FocusRightTab"
      },
      "pattern": [
        [
          0,
          -1
        ],
        [
          1,
          0
        ]
      ]
    },
    {
      "command": {
        "name": "ScrollTop",
        "settings": {
          "duration": 100
        }
      },
      "pattern": [
        [
          0,
          -1
        ]
      ]
    },
    {
      "command": {
        "name": "PageForth"
      },
      "pattern": [
        [
          1,
          0
        ]
      ]
    },
    {
      "command": {
        "name": "PageBack"
      },
      "pattern": [
        [
          -1,
          0
        ]
      ]
    },
    {
      "command": {
        "name": "ReloadTab",
        "settings": {
          "cache": true
        }
      },
      "pattern": [
        [
          0,
          -1
        ],
        [
          0,
          1
        ]
      ]
    },
    {
      "command": {
        "name": "CloseTab",
        "settings": {
          "nextFocus": "default",
          "closePinned": true
        }
      },
      "pattern": [
        [
          0,
          1
        ],
        [
          1,
          0
        ]
      ]
    },
    {
      "command": {
        "name": "NewTab",
        "settings": {
          "position": "default",
          "focus": true
        }
      },
      "pattern": [
        [
          -1,
          0
        ],
        [
          1,
          0
        ]
      ]
    },
    {
      "command": {
        "name": "OpenLinkInNewTab",
        "settings": {
          "focus": false,
          "emptyTab": false
        }
      },
      "pattern": [
        [
          0,
          1
        ]
      ]
    },
    {
      "command": {
        "name": "NewWindow"
      },
      "pattern": [
        [
          0,
          1
        ],
        [
          1,
          0
        ],
        [
          0,
          -1
        ]
      ]
    }
  ],
  "Blacklist": []
}

**Comment by Robbendebiene** [comment]
Here is your fixed config file:
[GConfig.txt](https://github.com/Robbendebiene/Gesturefy/files/4755026/GConfig.txt)

You will have to rename it to .json if you want to import it directly.

You should recreate some of your gestures like the one for "Open Gesturefy settings".

interestingly your config was broken in a very different way.

**Comment by leventeliu** [comment]
Ok, it's not a big deal cause I always have my backup config in my onedrive... until it told me that version 3 cannot recognize a 2.x.x config. Seriously bro? I literally reported your addon in a temper today😂

**Comment by Itchiii** [comment]
@leventeliu I don't want to be offensive, so just for clarification. You reported an add-on that had a bug in the sync that occurred after a major upgrade and we could have helped you to fix your config for version 3 instead of noting it in the feedback issue, giving a bad review or just changing the add-on? Nice bro.

**Comment by leventeliu** [comment]
@Itchiii My apologies, I shouldn't do that. But the lack of config compatibility nowadays still seems ridiculous to me.

**Comment by Itchiii** [comment]
@leventeliu The principle has changed significantly and we are of course sorry that there were problems. You could also install 2.1.6, upload your old config there and then update to 3.0.2, which would re-migrate the old config.
