### ISSUE TITLE
Change to tab to the left or right do not cycle when reaching the end

### ISSUE THREAD

**Issue by GridCube** [Robbendebiene/Gesturefy#481]
the behavious of ctrl-tab or shift-ctrl-tab associated to guestures do not cycle to the first or last tab respectively when reaching the end of the possibilities

**Comment by E2A4E789A3DCC7236FF998692ADE60E2** [comment]
You have to manually switch "Tab cycling" toggle in Gesturefy settings.
Go to Gesturefy settings page - Extras - Wheel gesture - Advanced settings - click on "Focus left tab" gesture action - find and click on "Focus left tab" on Command bar - switch "Tab cycling" option "off" and "on" again.

**Comment by GridCube** [comment]
I see, thanks!
