### ISSUE TITLE
Close Tab not focusing Next tab properly

### ISSUE THREAD

**Issue by E2A4E789A3DCC7236FF998692ADE60E2** [Robbendebiene/Gesturefy#483]
Focused tab not reacting to mouseover event, i.e. mouse pointer not changing shape to "beam" or "hand" when it's placed over a link or editable text.

Steps:
Open a webpage in a new tab (1)
Open a link from the webpage in new background tab (2)
Switch to the background tab (2)  with "Focus right tab" command bound to Wheel Down + Right mouse button.
Close the tab (2) with Close Tab command.
Focused tab (1) should be affected by the issue.

Windows 10 Pro 2004
Firefox 77.0.1
Gesturefy 3.0.0

**Comment by Robbendebiene** [comment]
Thanks for the report. This should be fixed in the next update.
