### ISSUE TITLE
Command "Close All Tabs"

### ISSUE THREAD

**Issue by dima6526** [Robbendebiene/Gesturefy#489]
Hi, could you look into adding a command to close all open tabs, but without closing the main window (when "closing the last tab closes the window" is disabled in autoconfig). At present there is a toolbar button add-on that does that, but it would be great to have it as a part of Gesturefy.

**Comment by Robbendebiene** [comment]
Hi, the use case is very specific, that's why we will probably not add this as a predefined command. However I will soon extend the "user script" command with some API that makes it possible to program this command.

I'll provide the script here once I released the update.

**Comment by dima6526** [comment]
Great, looking forward.

**Comment by Robbendebiene** [comment]
Once you received the update to version 3.0.3 you can use the following script to remove **all** tabs in the current window. For me it closes the whole window, but from your writings I guess there is an about:config property which will prevent this in your case?

```
const queryTabs = API.tabs.query({
  hidden: false,
  currentWindow: true
});

queryTabs.then((tabs) => {
  const tabIds = tabs.map(tab => tab.id);
  API.tabs.remove(tabIds);
});
```

**Comment by dima6526** [comment]
Exactly, there is a pref  browser.tabs.closeWindowWithLastTab  which you set to false. Thanks for your efforts!

**Comment by dima6526** [comment]
Thanks it works now!

**Comment by Robbendebiene** [comment]
Nice :)
