### ISSUE TITLE
Scroll up and New Tab not working

### ISSUE THREAD

**Issue by rippeddisc** [Robbendebiene/Gesturefy#490]
Recently updated.

Added in a simple UP motion for Scroll Up.  Not saving/Not working.

Added RIGHT - LEFT for New Tab.  Not saving/not working. 

### Your System
- Operating system: OSX 10.14.6
- Firefox version: 77.0.1
- Gesturefy version: 3

**Comment by Robbendebiene** [comment]
Can you please check if https://github.com/Robbendebiene/Gesturefy/issues/480 solves your problem? Otherwise please backup your config and post it here.
