### ISSUE TITLE
Google Maps context menu doesn't open (without deactivation key)

### ISSUE THREAD

**Issue by mpopp75** [Robbendebiene/Gesturefy#492]
At Google Maps - https://www.google.com/maps/ - opening the context menu now requires the deactivation key with Gesturefy 3, unlike Gesturefy 2 where a right click opened the context menu without deactivation key.

A possible solution could be to trigger a gesture only when the mouse is moved. Or whatever Gesturefy 2 did to get this right.

### System
- Operating system: Xubuntu 18.04 64bit
- Firefox version: Firefox 77.0.1
- Gesturefy version: 3.0.1

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll look into it.

**Comment by Robbendebiene** [comment]
This should be fixed in the version 3.0.2. It should be available soon.
