### ISSUE TITLE
Left click + right click

### ISSUE THREAD

**Issue by barisand** [Robbendebiene/Gesturefy#495]
Hej!

First of all, thanks for this great extension!!!
In the new version of FF (77.0.1), there is black hole in the system.
I used to play the online minesweeper (http://minesweeperonline.com/#). If i use the left and the right click in the same time, sometimes the button are "stock". They stay the pushed status.
If i turn off my Gesturefy the leftirght click works fine. 

Thanks 
barisand

- Operating system: W10
- Firefox version: 77.0.1
- Gesturefy version: 3.0.1

**Comment by Robbendebiene** [comment]
Hi, thanks for the report.
However I'm not quite sure if I understand the problem. Can you somehow visualize it to me? Maybe by a short screen recording or bay 2 screenshots (one with the bug and one with Gesturefy disabled)?

**Comment by Robbendebiene** [comment]
This is probably fixed in version 3.0.3.
