### ISSUE TITLE
"Focus Right Tab" command does not loop back to the first tab when on the last-most tab anymore.

### ISSUE THREAD

**Issue by Sashraan** [Robbendebiene/Gesturefy#498]
Previously, Gesturefy's "Focus Right Tab" function could be used from the last tab to "wrap around" back to the first tab.

However, ever since the latest big update (the one with the new "smooth" gesture recognition), this command does not work that way anymore.

Was this change part of the huge code update?
Is there a way to "revert back" to the old "Focus Right Tab" behaviour?
Could a new command -- potentially better titled "Focus Next Tab" -- be added to the gesture commands in order to revert this change somehow?

Thanks for any clarification on this!

Sincerely,
A Gesturefy user who really likes the ability to wrap around to the first tab using the same gesture as swapping to the next tab in line.

Your System
- Operating system: Windows 10
- Firefox version: 77.0 (64-bit)
- Gesturefy version: 3.0.2

**Comment by Itchiii** [comment]
Look here #471, everything is described there.

**Comment by Sashraan** [comment]
Apologies, I searched but didn't find that previous thread. Closing this one, and many thanks to you! :)
