### ISSUE TITLE
Possible to make gestures working on about:blank/new tab page, about:addons

### ISSUE THREAD

**Issue by ryanbr** [Robbendebiene/Gesturefy#5]
Enable gestures to other tabs, like about:blank/new tab page, about:addons  .. something I miss in firegestures :)

**Comment by Robbendebiene** [comment]
So basically you want to open a specific page on a particular gesture?

**Comment by ryanbr** [comment]
I use Up arrow (New tab), and Down arrow (close tab), and it would nice if it work basically anywhere in the browser (well, anywhere its feasible)

**Comment by Robbendebiene** [comment]
Ah I see what you mean. Sadly this is impossible with the new firefox api as I stated on the [mozilla addon page](https://addons.mozilla.org/en-US/firefox/addon/gesturefy/). Because the api does not allow to inject scripts into pages like about:addon, about:blank etc. nor does it grant access to the full browsers chrome window (what the old api does which FireGestures is using).

**Comment by ryanbr** [comment]
Well, one day I guess.

**Comment by Robbendebiene** [comment]
I hope so too :)

**Comment by ryanbr** [comment]
Seems a bit strange, I can expect about:addons to be restricted, but addons.mozilla.org is just a website

**Comment by Robbendebiene** [comment]
I've already searched for the reason, but I couldn't find anything. Please let me know if you do!

**Comment by ryanbr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1310082  related?

**Comment by Robbendebiene** [comment]
Closed in an issue clean up process due to the lack of an appropriate API or upcoming API.

**Comment by soc** [comment]
For those people who land on this issue because they are annoyed that the extension doesn't work on the new-tab page:

Gesturefy works if you select "Blank Page" under Preferences -> Home (equivalent to setting `about:blank` instead of `about:newtab`).

**Comment by vovavili** [comment]
Hello, I've added a request on Firefox Ideas for Mozilla to implement API tweaks for this feature. Please support by liking and commenting - https://mozilla.crowdicity.com/post/746390

**Comment by DweyBx** [comment]
Wait so this not fixed yet ??

**Comment by kunkanader** [comment]
FF userchrome hacks have been providing support for this for years now.
E.g [xiaxiaoflood](https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/chrome/mouseGestures)
