### ISSUE TITLE
Gestures don't work in certain places

### ISSUE THREAD

**Issue by thany** [Robbendebiene/Gesturefy#50]
Gestures don't work in the bleak "new tab", they don't work in the addons or preferences tabs. They magically don't work on addons.mozilla.org.

**Comment by thany** [comment]
So for example the "close tab" or "close window" gestures should basically work in *anything* that is closable. Even a modal dialog.

**Comment by Robbendebiene** [comment]
This is a known limitation, please read the addon description here: https://addons.mozilla.org/firefox/addon/gesturefy/. The new API is restricted to webpages only, so I sadly can't implement this.

**Comment by thany** [comment]
So we should issue a bugreport at Mozilla?

**Comment by Robbendebiene** [comment]
Feel free to do so, but they won't fix it, because these limitations exist due to security reasons.
