### ISSUE TITLE
"Open in new Tab" Gesture breaks if Letter + ":" is selected

### ISSUE THREAD

**Issue by LauraWirtz** [Robbendebiene/Gesturefy#504]
### Describe your matter in detail

The gesture "open in new foreground tab" breaks when a text containing at least one letter followed by ":" is selected. I have not tested all letters, but numbers don't cause this.

Firefox will try to open the selected text instead of the link the gesture was performed on

I have found this while having a Reddit comment where a paragraph starts with "edit:" selected, but it works on any site, also using inspect element to add [letter]: to a paragraph.
[1](https://www.reddit.com/r/funny/comments/5gn8ru/guardians_of_the_front_page/datqkrx/)
[2](https://www.reddit.com/r/funny/comments/5gn8ru/guardians_of_the_front_page/datv5f2/)
[3](https://www.reddit.com/r/pics/comments/5bx4bx/thanks_obama/d9s3llm/)

### Screenshots or further assistance

![image](https://user-images.githubusercontent.com/54887239/84828827-f7bfa800-b026-11ea-8563-51ce741cbd23.png)

### Your System
- Operating system: Windows 10
- Firefox version: 77.0.1 (64-bit)
- Gesturefy version: 3.0.2

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll fix this.

**Comment by Robbendebiene** [comment]
Should be fixed in version [3.0.3](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.3).
