### ISSUE TITLE
No Gestures and cannot define one in Kubuntu 20.04

### ISSUE THREAD

**Issue by ataugur** [Robbendebiene/Gesturefy#506]
### Describe your matter in detail

I installed gesturify addon and checked the configuration screen. There were no gestures there. I cannot define a new gesture either. Right click does not work. On a web page when I right click and draw a gesture I see the gesture trace but nothing happens

### Screenshots or further assistance
![image](https://user-images.githubusercontent.com/10577819/84879570-1019dc00-b094-11ea-8ab3-9cf94769b516.png)

### Your System
- Operating system: Kubuntu 20.04
- Firefox version: 77.0.1. 64 bit
- Gesturefy version: 3.0.2

**Comment by Robbendebiene** [comment]
Please try to reset gesturefy.
You can do this in the "About" section.

**Comment by ataugur** [comment]
It worked. Thanks

It is weird because it was a fresh installation of Kubuntu and Firefox but Gesturefy was reverted back via Firefox sync

**Comment by Robbendebiene** [comment]
Yeah, sync can cause a lot of problems. Especially if you have an older Gesturefy version (2.x.x) installed on another computer.
