### ISSUE TITLE
Since last update (v3), right click on Linux displays the context menu

### ISSUE THREAD

**Issue by LeBlondTenebreux** [Robbendebiene/Gesturefy#507]
### Describe your matter in detail
This was not a issue anymore for months, but it seems there's a regression: when right clicking to draw a gesture, the context menu displays and messes up everything, especially on small screens or small popup windows as the priority is given to the context menu rather than the gesture when drawing on it.

### Screenshots or further assistance
![BugGesturefy](https://user-images.githubusercontent.com/19548211/85004361-c266a780-b157-11ea-9935-db01971d9a60.png)

### Your System
- Operating system: Manjaro Linux 5.6.16-1-MANJARO x86_64 20.0.3 Lysia
- Firefox version: 77.0.1
- Gesturefy version: 3.0.2

**Comment by Robbendebiene** [comment]
Have you tried the Troubleshooting guide: https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting ?

Does this happen every time on every page?

**Comment by LeBlondTenebreux** [comment]
Ow, thank you, the ui.context_menus.after_mouseup was set to false; things are back to normal now!
