### ISSUE TITLE
Scroll to bottom / top gestures do not work on pages without html doctype in versions >=3.0.3 

### ISSUE THREAD

**Issue by mgwolff** [Robbendebiene/Gesturefy#508]
In Gesturify versions 3.0.3 and 3.0.4, gestures to scroll to the bottom or top of a page do not work anymore for pages without an html doctype. 

For example, in the sample.html file from the attached [sample.zip](https://github.com/Robbendebiene/Gesturefy/files/4822494/sample.zip), the scroll to the bottom or top gestures do not work for me. Other gestures work fine. 
After adding `<!DOCTYPE html>` at the top of the file and refreshing the browser, the scroll gestures start working.

### Your System
- Operating system: Linux
- Firefox version: 77.0.1 (64-bit)
- Gesturefy version: 3.0.3 and 3.0.4

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll look into it.

**Comment by Robbendebiene** [comment]
This is should be fixed with the release of Gesturefy version [3.0.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.5).
