### ISSUE TITLE
"Save image" no longer saves image, opens dialog instead

### ISSUE THREAD

**Issue by CptDiomedes** [Robbendebiene/Gesturefy#510]
Actual (current) behavior: When using the "Save image" action, a "Save As" dialog is opened, necessitating further confirmation of saving

Expected (previous) behavior: Upon using "Save image" the image is immediately saved into the downloads folder

Essentially, instead of actually saving the image like it used to, it now duplicates the behavior of Right click > Save Image As...

I haven't used it for a while so I don't know when this first appeared, but it this change of behavior has a very large impact on usability as previously you could simply save an image with a 1 second gesture and move on, now you need to confirm the dialog for every image. 

### System
- Operating system: Windows 10.0.18362 Pro 
- Firefox version: 77.0.1
- Gesturefy version: 3.0.4

**Comment by Robbendebiene** [comment]
Have you tried reassigning the command to the gesture and disabling the "prompt" setting?

**Comment by CptDiomedes** [comment]
Ah, that was it! Now I wonder if I missed that "prompt" setting earlier... Thanks.
