### ISSUE TITLE
Search selected text gesture...usually does not complete or it constructs an improper URL

### ISSUE THREAD

**Issue by heydres** [Robbendebiene/Gesturefy#511]
Using latest Firefox 78.0 Beta on Win7....using a gesture in the shape of a G (which it recognizes correctly)

Searching for text using a custom gesture either:
- Gets no response
- The text search is just appended to the URL www.google.com>    www.google.comtextsearchedfor

**Comment by Robbendebiene** [comment]
Did you configure the Search command using a custom search URL? Can you please export your config and upload the file here? (You probably have to rename it from json to txt.)
