### ISSUE TITLE
Gestures doesn't work on this site

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#512]
### Describe your matter in detail
On this site https://www.artsper.com/en/contemporary-artworks/painting the gestures doesn't work.

### Your System
- Operating system: Windows 10 - 2004
- Firefox version: 79 beta1
- Gesturefy version: 3.0.4

**Comment by happysurf** [comment]
Very strange, after some attempts now works.

**Comment by Robbendebiene** [comment]
Works for me. If it occurs again please report it again maybe also with some logs from the console. (open the console -> reload the page -> try to draw a gesture -> post logs here)

**Comment by Robbendebiene** [comment]
@happysurf Just reopen this if it happens again.
