### ISSUE TITLE
Poor visibility of active command

### ISSUE THREAD

**Issue by xxvii** [Robbendebiene/Gesturefy#516]
Hello,
I'm using Gesturefy 3.0.5, Firefox 78.0.1 on Windows 10.

Since the redesign of the options panel (I don't remember which version it was) I noticed a very poor visibility of the command related to the gesture.

I dare you to find the active command in the list within 2 seconds, especially when it is towards the bottom of the list and you have to scroll along tens of commands watching carefully not to miss the almost invisible dot ;)

This happens in both the dark and light themes.

Also the new gear icon is not very visible.

An increase of the contrast would be VERY appreciated, thank you!

![Annotazione 2020-07-08 112213](https://user-images.githubusercontent.com/962750/86901726-4c79ae80-c10d-11ea-83c7-068f8d739f7b.jpg)

**Comment by Robbendebiene** [comment]
> Since the redesign of the options panel (I don't remember which version it was) I noticed a very poor visibility of the command related to the gesture.

Just for clarification: The command panel basically never changed. The only thing that changed in version 3.0.5 are the icons on the right which were previously thin info icons. These have been removed and instead there is now an indicator (gear icon) if the command has additional settings. The subtile gray is by intention since its only an indicator and not a button nor a readable text, which should draw attention.

> I dare you to find the active command in the list within 2 seconds, especially when it is towards the bottom of the list and you have to scroll along tens of commands watching carefully not to miss the almost invisible dot ;)

I agree that the "active command indicator" is very inconspicuous and also doesn't explain itself very well what it actually indicates.

**Comment by xxvii** [comment]
> Just for clarification: The command panel basically never changed. The only thing that changed in version 3.0.5 are the icons on the right which were previously thin info icons. These have been removed and instead there is now an indicator (gear icon) if the command has additional settings. The subtile gray is by intention since its only an indicator and not a button nor a readable text, which should draw attention.

Ok, so I probably remembered the plugin I used to use before Firefox Quantum, I think it was Firegestures :)
You're right about the gear icon, it's more cosmetic than functional...

> I agree that the "active command indicator" is very inconspicuous and also doesn't explain itself very well what it actually indicates.

Maybe something like a checkbox conveys better the idea of something that is "selected".
But I think that the Gesturefy's users are tech-savvy enough to understand the purpose of the dot (or an analogous symbol) anyway...it's not difficult to graps...it's difficult to see! 🤣

**Comment by Robbendebiene** [comment]
> But I think that the Gesturefy's users are tech-savvy enough to understand the purpose of the dot (or an analogous symbol) anyway...it's not difficult to graps...it's difficult to see! rofl

Agree. The bullet will have the same color as the text in the next version. (should be enough as far as I can tell from my testing)

**Comment by Sopor** [comment]
It is very hard to see the actual gestures too. In the linked video i have two `Reload all` and the first one it looks like `↑↑` but it is `↑↓↑`. In the other `Reload all` it looks like `↑↑→`, but it is `↑↓↑→`. I know ↑↑ is impossible to have, but it must be possibly to improve it so it will show the gesture more clearly...

So it is not easy to see the gestures when it overlap as you can see [here](https://gofile.io/d/WLCUwi).

Sorry that i jumped in here, but it was a similar issue. If you want i can create a new one if you believe it is something you can improve?

**Comment by Robbendebiene** [comment]
@Sopor I suggested in the upgrading information page of version 3 to redraw such gestures. Just draw them a little bit diagonal, this won't really effect the matching of the gesture. When browsing you most certainly aren't drawing it perfectly up and down either. 


![grafik](https://user-images.githubusercontent.com/13716661/88454503-76063a00-ce70-11ea-8d1e-29047c4a7334.png)

> but it must be possibly to improve it so it will show the gesture more clearly...

I'm not aware of any good solution for this. The only thing I can think of is showing the arrow moving along the path on mouse over.

**Comment by Sopor** [comment]
> I'm not aware of any good solution for this. The only thing I can think of is showing the arrow moving along the path on mouse over.

@Robbendebiene Yes, showing some arrows sound like a good idea 👍

**Comment by Robbendebiene** [comment]
@Sopor I meant that the arrow of the gesture would move along with the animated path, not showing additional arrows, because gestures can no longer be "translated" to simple arrows (like up down right etc.) You can now use any direction.

**Comment by Robbendebiene** [comment]
This issue is solved with the release of Gesturefy version [3.0.6](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.6).

@Sopor If you have additional ideas or solutions in mind please open a new issue.

**Comment by Sopor** [comment]
@Robbendebiene I can't see any difference :(
