### ISSUE TITLE
Command menu does not open for pre-defined gestures (Firefox)

### ISSUE THREAD

**Issue by blairtj** [Robbendebiene/Gesturefy#517]
I am unable to assign a command for predefined gestures. 

The new version of Gesturify came with several useful predefined gestures but I am unable to specify commands for them. When I create a custom gesture and click on the command field, I get a tray menu slide out from the right hand side. But when I open a predefined gesture and click in the command field, nothing happens. 

To use these useful gestures I had delete the built-in versions and create custom versions of them.

### Screenshots or further assistance
![image](https://user-images.githubusercontent.com/68022104/86942772-678ef300-c0fa-11ea-8d18-1e28d5ec9091.png)

### Your System
- Operating system: Windows 10
- Firefox version: 78.0.1
- Gesturefy version: 3.0.5

**Comment by Robbendebiene** [comment]
Are you using Firefox sync? If so you probably experience the same issue as: https://github.com/Robbendebiene/Gesturefy/issues/513
and https://github.com/Robbendebiene/Gesturefy/issues/506

**Comment by blairtj** [comment]
Hi @Robbendebiene , yes, I do use Firefox Sync between my workstation and my laptop. They are currently both on Gesturify 3.0.5 but likely upgraded to V3 at different times so configs could have gotten crossed. I reset the settings from About and does indeed now work as expected.

I love Gesturify. I don't use lots of gestures, but the ones I use, I use all the time. And love the new version.
