### ISSUE TITLE
Don`t work inside some areas

### ISSUE THREAD

**Issue by kramola-RU** [Robbendebiene/Gesturefy#519]
Gesturefy **3.05**
Firefox 78.02 (32-bit)
Windows 10 x64 LTSB 2016

The two defaults gestures "Scroll Up to Top" and "Scroll Down to Bottom" don`t work inside some areas.

For example:
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474#1

![146](https://user-images.githubusercontent.com/51376332/88092513-44078600-cb99-11ea-83c3-187385572c97.png)

The Gesturefy **2.1.6**  don`t have this problem.

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll look into it.

**Comment by kramola-RU** [comment]
One more area. Check it please.
https://www.newsru.com/
The area is located at the bottom of the page.

![147](https://user-images.githubusercontent.com/51376332/88238991-d425f800-cc8b-11ea-8cf9-38f726efbc04.png)

 The Gesturefy **2.1.6** is also affected

**Comment by Robbendebiene** [comment]
The second problem cannot be fixed. The element inside the box/iframe is actually scrollable (you will notice a slight movement when you use the scroll up and down gestures inside that box/iframe) but the scrollbar is hidden.

**Comment by kramola-RU** [comment]
But CentBrowser does not have this problem.
So there is an algorithm to workaround (maybe I'm wrong).

**Comment by Robbendebiene** [comment]
I guess they are not forced to use the webextensions API. I also can imagine a solution for Firefox add-ons, but the effort would be tremendous compared to the benefit.

**Comment by kramola-RU** [comment]
Clear.

**Comment by Robbendebiene** [comment]
Should be fixed in version [3.0.6](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.6)

**Comment by kramola-RU** [comment]
Robbendebiene, thank you very much !

**Comment by Robbendebiene** [comment]
Thanks for your report and understanding :)
