### ISSUE TITLE
Can't start gesture from tab

### ISSUE THREAD

**Issue by thany** [Robbendebiene/Gesturefy#52]
If I could start the "close tab" gesture from the tab itself, I could close an inactive tab that way. So I position my mouse cursor on the inactive tab, I don't click to activate it, and then I commence the "close tab" gesture (which is down-right for me, so it could work).

I know the ancient and crapped up Opera could do this very well. FireGestures and FoxyGestures both cannot do this. But maybe you can.

**Comment by Robbendebiene** [comment]
This is a nice idea, but sadly impossible, because I can only detect the mouse movement etc. on web pages and as you've already noticed some webpages are even excluded.

**Comment by thany** [comment]
Will this be taken up with Mozilla? It is ultimately their fault for ditching XPCOM and replacing it with hardly anything in comparison...

**Comment by Robbendebiene** [comment]
As far as I know they won't implement anything like that, at least not in the near future.

**Comment by jlvermeulen** [comment]
You realise that when your mouse is on the tab, simply middle-clicking will close it, right? No need for any gestures.

**Comment by nouinoui** [comment]
Hello
Personally i got a gesture to open a new tab (for me: up) but if i opened it accidently it would be cool to close it with a gesture too (for me: down right), so going on the tab with the mouse to middle-click it is longer for me to do so.

Would it still be impossible with the new Mozilla?

Sorry for my poor English.

**Comment by Robbendebiene** [comment]
@nouinoui 
The only thing you can do is to change the new tab page to either about:blank or a website using e.g. this addon: https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/

**Comment by nouinoui** [comment]
Thank you a lot!

**Comment by thany** [comment]
@jlvermeulen You're missing the point. I'm not looking for a workaround for just the close gesture.
What about a duplicate gesture? Or a "close all except this one" gesture? Or a reload gesture?
