### ISSUE TITLE
pack back / forward move across tabs, not page history

### ISSUE THREAD

**Issue by adotbur** [Robbendebiene/Gesturefy#520]
When using gestures to go back a page (assume page history) it actually moves to another tab.  Same with move forward.  Gif attachment shows how this is working.  

![DnIgn9eWFl](https://user-images.githubusercontent.com/68659905/88210744-a789c600-cc22-11ea-8101-9ab7db54ce71.gif)

### Your System
- Operating system: Windows 10
- Firefox version: 78.0.2
- Gesturefy version: 3.0.5

**Comment by Robbendebiene** [comment]
Can you please export/backup your gesturefy config and attach it here?

**Comment by Robbendebiene** [comment]
This is probably caused by another add-on (perhaps even a mouse gesture add-on like foxy gestures). Closing this due to missing response.
