### ISSUE TITLE
Mouse cursor doesn't change! #bug

### ISSUE THREAD

**Issue by danchanru** [Robbendebiene/Gesturefy#521]
If I **close a tab** with a mouse gesture, the mouse cursor gets stucked and **doesn't change to a pointer cursor**, if I hover over a link. Only if I hover over the top Firefox menu and then hover over links, it will behave normal. 

This is very annoying, because that's the main reason why I use these gestures (to save time, not have to move my cursor too far). Version 3.0.4 has also problem with that.

- Operating system: Win 10
- Firefox version: 78.0.2 (64-bit)
- Gesturefy version: 3.0.5

**Comment by jdreesen** [comment]
Duplicate of #514. This is a bug in Firefox 78 and will be fixed in 79 which will be released next Tuesday.

**Comment by danchanru** [comment]
Yes, I've just realized that it also doesn't work in previous versions. Thanks for letting me know!

**Comment by Robbendebiene** [comment]
Duplicate of #514
