### ISSUE TITLE
donate?

### ISSUE THREAD

**Issue by CondomsPreventCoinkydinks** [Robbendebiene/Gesturefy#522]
how/where do we donate to show appreciation and support continued maintenance/development?

btw changing 'matching-algo' to 'shape-independent' has really helped me cut down on gestures being missed.

cheers Dev, this is my fave addon and can't see anything else topping it any time soon. take my money!

**Comment by Itchiii** [comment]
First of all, thank you very much for wanting to make a donation! 

Since the topic came up from time to time, we will write a more detailed text in the next days.

**Comment by Robbendebiene** [comment]
Thank you from my side as well. I've now created a tiny FAQ page, so if you are still interested please visit [this page](https://github.com/Robbendebiene/Gesturefy/wiki/FAQ#where-and-how-can-i-support-gesturefy).
