### ISSUE TITLE
when finish draw gesture, then popup context menu.

### ISSUE THREAD

**Issue by mobumh** [Robbendebiene/Gesturefy#524]
### Describe your matter in detail

when draw gesture with right mouse button, and release button then popup context menu.

like this

![gesturefy_bug](https://user-images.githubusercontent.com/7764801/88481247-3e44e280-cf95-11ea-8f57-90d81065de22.gif)

### Your System
- Operating system: Windows 10 Pro Build 18362.19h1_release.190318-1202
- Firefox version: 78.0.2 (64-bit)
- Gesturefy version:  3.0.6

**Comment by Robbendebiene** [comment]
Have you already checked the [troubleshooting guide](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture)?

**Comment by mobumh** [comment]
> 
> 
> Have you already checked the [troubleshooting guide](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture)?

thank you problem solved!
