### ISSUE TITLE
Option to disable mouse gestures

### ISSUE THREAD

**Issue by ihabunek** [Robbendebiene/Gesturefy#525]
This may be a strange request for a mouse gestures extension. :)

I use Gesturefy solely for rocker & wheel gestures, but I keep accidentally activating mouse gestures when I don't want to. I would love to be able to disable them altogether, while keeping rocker & wheel gestures.

E.g. either add a On/Off switch for gestures, or add "None" as an option in "Settings > Activation button".

**Comment by Robbendebiene** [comment]
While I can understand your request, I never designed Gesturefy with wheel or rocker gestures in mind. They where added afterwards for people who didn't want to install a separate add-on to get this kind of functionality. So I always considered mouse gestures to be the core functionality of Gesturefy, wherefore it seems odd to add a switch to disable them. (even though it wouldn't be that hard). I also can't think of any other program that has a switch to disable its main functionality and in addition I want to keep the settings page as simple as possible.

So I'm sorry but I probably won't implement a disable button.

However you can kind of disable mouse gestures if you delete all gestures and set the "distance threshold" to 999.
