### ISSUE TITLE
"Open clipboard URL" command for strings without http(https) prefix

### ISSUE THREAD

**Issue by kramola-RU** [Robbendebiene/Gesturefy#526]
The Gesturefy is unable to recognize the phrases like **github.com** (or **www.github.com**) as an URL and therefore the "Open clipboard URL" does not work.
Could you to fix that ?

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll improve this for all commands that handle links/URLs.

**Comment by Robbendebiene** [comment]
This should now work in [Gesturefy 3.0.7](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.7)

**Comment by kramola-RU** [comment]
> This should now work in [Gesturefy 3.0.7](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.7)

Yes! I have already tried :)
THANK YOU VERY MUCH !

**Comment by Robbendebiene** [comment]
Greate! Happy to help :)

**Comment by HAMiDY25** [comment]
Does not work with capital letters.🤔

**Google.com**
**google.Com**
**Github.com**

Long address does not work too, does the problem relate to this issue?
**`github.com/Robbendebiene/Gesturefy`**

**Comment by Robbendebiene** [comment]
@HAMiDY25 This sounds like a bug. Can you please open a new issue for this? (so I don't lose track of this)
