### ISSUE TITLE
Gesture "Close Tab" closes two tabs

### ISSUE THREAD

**Issue by blacky22983** [Robbendebiene/Gesturefy#527]
### Describe your matter in detail
Gesture "Close Tab" -> "right mousebutton, down, right" closes two tabs at 75% probability.
I already deleted the gesture and recreated it.

### Screenshots or further assistance
![Screenshot 2020-08-01 085228](https://user-images.githubusercontent.com/69070383/89096140-7ce2fe80-d3d4-11ea-831f-0b2bf06177d3.png)
![Screenshot 2020-08-01 085305](https://user-images.githubusercontent.com/69070383/89096141-7e142b80-d3d4-11ea-938c-186c673c6f13.png)

### Your System
- Operating system: Windows 10, Build 20175.rs_prelease.200717-1349
- Firefox version: 79.0 (64-bit)
- Gesturefy version: 3.0.6

Greets, Martin

**Comment by Robbendebiene** [comment]
Can you please export/backup your config and attach it here?

**Comment by blacky22983** [comment]
Renamed it from .json to .txt due to upload restrictions.

[Gesturefy 3.0.6 Sat Aug 01 2020.txt](https://github.com/Robbendebiene/Gesturefy/files/5009995/Gesturefy.3.0.6.Sat.Aug.01.2020.txt)

**Comment by Robbendebiene** [comment]
So far I'm not able to reproduce it. I don't think that there will be any errors logged, but please try to open the the inspection console for Gesturefy. The screenshot should show you how to do so.

After you've done that, try to reproduce the error, then switch back to the console/tab and post any errors here. (you can ignore the "sendRemoveListener on closed conduit ..." errors)
![grafik](https://user-images.githubusercontent.com/13716661/89097209-33e37800-d3dd-11ea-8708-42b5f2047016.png)

**Comment by Robbendebiene** [comment]
Btw do you have any other add-ons installed that might cause this kind of issue?

**Comment by blacky22983** [comment]
found it...when running the debugging tool, I saw that there was FoxyGestures...
Wasn't at the add-ons menu nor the settings menu.

Removed it manually, now Gesturefy runs fine!

**Comment by Robbendebiene** [comment]
Nice.

Just a tip: I've noticed that you did not recreate your gestures after the release of Gesturefy v3. I recommend either: recreating them OR resetting your gestures to the default Gesturefy gestures and modifying them ADDITIONALLY changing the matching algorithm in the settings might help you (since you use only basic gestures)

Of course if you don't experience any problems with these gestures you don't have to take any action.

**Comment by blacky22983** [comment]
Just resetted the settings, and recreated my "close tab".
works like a charm!.

Thanks for your effort.
