### ISSUE TITLE
Close Tab and Focus Left Tab

### ISSUE THREAD

**Issue by tockar** [Robbendebiene/Gesturefy#53]
Hello, 

Loving your addon, it looks simple, nice, and works fast.

One gesture I would love to see in Gesturefy is ability to close tab and focus left tab (available in FireGestures in the scripts page). So default gesture focused right tab after closing current one, while this action focused left one.

This might be fairly easy to add in Gesturefy by combining "Remove tab" and "Previous tab", or by using existing code from "New tab right"/"New tab left" to close tabs instead of opening new one. Note: I'm not a programmer, just my thinking.

Any chance for adding this/these actions to Gesturefy? Thanks for reading!

**Comment by Robbendebiene** [comment]
I'm glad you like my addon and appreciate your suggestion.
As you already mentioned, this should be fairly easy to implement. How do you think about an extra setting for "close tab", where you can specify if either the right or the left tab will gain focus? Or do you think I should add an extra action for this?

**Comment by tockar** [comment]
I think the best way, and also consistent with already existing settings, is to do it like with "New tab" options - generic "Remove tab", like it is right now, and two additional actions "Remove tab right" and "Remove tab left".

**Comment by tockar** [comment]
Current default behaviour is right tab, usually. But if you click the link on one tab and then close this new tab, Firefox will focus previous tab, the one that had link you just closed. Which usually will be tab on the left. This is what "Remove tab" currently does and it should stay this way, in my opinion.

**Comment by rodalpho** [comment]
Just came here to request something similar. Here's how I would like it to work.

1) Open new tab: to the right of the current tab
2) When closing a tab: focus the previously selected tab

As always, configurability is king and it would be great for the user to be able to choose whether to select right tab (default Fx), left tab, or last selected tab.

**Comment by Robbendebiene** [comment]
@tockar Thanks for the clarification. I'm currently thinking about removing the "new tab right/left" actions and adding an advanced setting to "new tab" which lets you define where the tab should be opened. Then I would do the same thing for "remove tab". Just because I want to minimize the amount of actions which nearly do the same thing.

@rodalpho I was going to write "no" because I would have to keep track of the last selected tab, but I think I found a nice trick to get the last selected tab, without that. So I would add this as a further option out of 4, which would be: Focus - Default, Right, Left, Previous

**Comment by rodalpho** [comment]
That would be perfect!

This was actually one of the primary purposes I used Tab Mix Plus for in pre-57 Fx.

**Comment by tockar** [comment]
> Then I would do the same thing for "remove tab". Just because I want to minimize the amount of actions which nearly do the same thing.

Understandable from your point of view, but if that means I can't have two gestures to close the tab, your changes does not solve the issues for me. :(

**Comment by Robbendebiene** [comment]
@tockar I'm sorry for that, but I will close the issue since it's implemented in the new version (though not exactly as desired).
