### ISSUE TITLE
scroll up/down does not work for text boxes

### ISSUE THREAD

**Issue by Klumbumbus** [Robbendebiene/Gesturefy#532]
### Describe your matter in detail
- Have a page with a scrollable textbox, e.g. edit a wikipedia page, e.g. https://de.wikipedia.org/w/index.php?title=JOSM&action=edit
- Do your gesture to scroll down

This is a problem since version 3. In version 2 if you did your gestures inside the text box then the text box scolled up/down and if you did your gestures outside the textbox the page scrolled up/down. Now in version 3 always the whole page scrolls up/down and there is no way to scroll up/down the textbox with a gesture.

(While writing this issue I noticed that it works fine here in this github textbox. However this is the first textbox I noticed where it works with version 3. On wikipedia or other pages it doesn't work.)

### Your System
- Operating system: Windows 10 Pro 1909
- Firefox version: 79.0 64-bit
- Gesturefy version: 3.0.6

**Comment by Robbendebiene** [comment]
Thanks for the detailed report. I'll look into it.

**Comment by Robbendebiene** [comment]
This should be fixed in [Gesturefy 3.0.7](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.7)

**Comment by Klumbumbus** [comment]
It works fine for me. Thank you!

**Comment by Robbendebiene** [comment]
Thanks for the confirmation!
