### ISSUE TITLE
down - right gesture sometimes detected as down or not detected at all

### ISSUE THREAD

**Issue by tinkn69** [Robbendebiene/Gesturefy#533]
Deleted the default gesture for letter L which was scroll to bottom of page.
Created NEW gesture for right click to close tab (gesture is letter L)
Does NOT always work, it will scroll to the bottom of page instead of closing the tab and sometimes takes several tries!

### Your System
- Operating system: Windows 7 x64
- Firefox version: 79.0 32 bit
- Gesturefy version:  Gesturefy, Version: 3.0.6

**Comment by Robbendebiene** [comment]
This sounds more like a gesture mismatch rather than a bug in the close tab command. Read more about the marching algorithms here https://github.com/Robbendebiene/Gesturefy/wiki/Matching-Algorithm and try switching to "shape independent".
