### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by karinaardos** [Robbendebiene/Gesturefy#534]
Hey. A very good add-on for Firefox.
How do I add a keyboard shortcut from another extension to a new gesture?
For example, I create a new gesture and want to assign it a keyboard shortcut from another extension.

**Comment by Robbendebiene** [comment]
This is not possible. Browser extensions/add-ons cannot trigger keyboard shortcuts. The other add-on you want to use may support an API that can be used by Gesturefy.  More info here: https://github.com/Robbendebiene/Gesturefy/wiki/Send-message-to-other-addon
