### ISSUE TITLE
The gesture "[popup] search engine" interfere with "QuickDial" add-on.

### ISSUE THREAD

**Issue by TM1207** [Robbendebiene/Gesturefy#536]
"QuickDial" add-on and "[popup] search engine" of "Gesturefy" interfere with each other, so if I search any site on "[popup] search engine", I will be redirected to the top page of "QuickDial".

### Your System
- Operating system: Windows 7 (64 bit)
- Firefox version: 80.0
- Gesturefy version: 3.0.6

**Comment by Robbendebiene** [comment]
This will be fixed in the following issue: #530

**Comment by Robbendebiene** [comment]
Duplicate of #530
