### ISSUE TITLE
Duration set to be in ms

### ISSUE THREAD

**Issue by knoajp** [Robbendebiene/Gesturefy#545]
The title describes all.
Not a critical issue, but I suppose it to be easy to modify. 😃

**Comment by Robbendebiene** [comment]
Do you mean the gesture timeout duration? You can set it in 0.1s steps.

**Comment by knoajp** [comment]
Ohhhhhh I can, I can now.
I did failed at that time for some unknown reason, but now I can.
I'm very sorry for bothering...

**Comment by knoajp** [comment]
I realize that it was because I tried ".250" for it.
It just require 0.1s steps, okay. (but why?)

**Comment by Robbendebiene** [comment]
Good question. I guess I thought no one will need such a detailed timeout, but I'll probably remove this restriction.

**Comment by knoajp** [comment]
Thank you for considering.
I don't have any deep thoughts, just divide 1s by 4, and I often use .5, .25, and even .125 for any sort of purposes. 🤣
