### ISSUE TITLE
Pinned tab are closed with "close tab" gesture

### ISSUE THREAD

**Issue by byzod** [Robbendebiene/Gesturefy#546]
### Describe your matter in detail
Pinned tab are closed with "close tab" gesture while it shouldn't

### Your System
- Operating system: win 10
- Firefox version: 82b9
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment]
Can you please try to delete and recreate the gesture with its specific setting?

**Comment by byzod** [comment]
Uh, sorry I found the option not to close pinned tab, it's on by default. Problem solved

**Comment by Robbendebiene** [comment]
All right, thanks for the response. I'm closing this issue then :)
