### ISSUE TITLE
Can Gesturefly be made to work on Mozilla pages?

### ISSUE THREAD

**Issue by jefferysmall** [Robbendebiene/Gesturefy#547]
I understand that Mozilla apparently disables add-ons on their pages, including the built-in ones like about:config, add-ons, etc.  I was wondering if there is any way to override this and get my gestures to work there?  It's a real PITA to not have uniformity of operation everywhere.  Thanks.

- Operating system: Xubuntu 20.04
- Firefox version: 81.0.2
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment]
As far as I know there only exists a workaround for restricted domains like mozilla.org: https://github.com/gorhill/uMatrix/wiki/Privileged-Pages
I don't think there is something similar for about:add-ons etc.  Not even the screenshot tool is allowed to run there, even though they added some exceptions like about:reader.

**Comment by jefferysmall** [comment]
I though this was the case but wanted to ask just in case I was missing out on something.  I appreciate the reply.
