### ISSUE TITLE
New action: Zoom image under cursor

### ISSUE THREAD

**Issue by rodalpho** [Robbendebiene/Gesturefy#55]
In FireGestures I had mouse wheel gestures that dynamically zoomed-in/out the image under the mouse cursor. I found this really useful and would like similar functionality in Gesturefy.

Actually, custom scripts like FireGestures had would be even better.

**Comment by Robbendebiene** [comment]
To be honest, I have no idea how this should look like. Can you please explain it a little bit further, maybe by uploading screenshots before and after zooming the image. Also the code of the custom script could be helpful.

**Comment by rodalpho** [comment]
The scripts are "enlarge image size" and "reduce image size" on the following page.

http://www.xuldev.org/firegestures/getscripts.php

Way it works is to put the mouse cursor on top of an image, hold the RMB and scroll up, and the image dynamically grows larger with the page reflowing around it.

**Comment by Robbendebiene** [comment]
After testing things and thinking some time about it, I decied against adding it. My main reasons are:
1. there are only a few use cases
2. no consistence behaviour across webpages, aspecially the user script you've send me, is not working properbly on every image/webpage and therefore would require additional code.

So I'm sorry for that, but you have to live without it, at least until Gesturefy [supports user scripts](https://github.com/Robbendebiene/Gesturefy/issues/58).
