### ISSUE TITLE
Req: XPI-file: Non-cryptic name

### ISSUE THREAD

**Issue by Jonta** [Robbendebiene/Gesturefy#550]
Right now, going to `~/.mozilla/firefox/[profile-ID]/extensions/`, this extension is identified by an opaque hex-string

An example of an extension that has a clear name, is HTTPS Everywhere: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

=)

### Your System
- Operating system: Ubuntu 20.04 LTS
- Firefox version: 82.0 64-bit
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment]
Hi, I'm not sure if I understand the point of this issue. Do you want me to change this because of better readability?
This "cryptic name" is an ID that was generated by Mozilla, because I didn't provided one myself. Switching to a different one now would lead to several problems.

**Comment by Jonta** [comment]
Ability to see which is which at a glance was what I had in mind, yes

What problems would it lead to?

=)

**Comment by Robbendebiene** [comment]
If I'd change the ID none of the current users will receive updates anymore. Additionally some other add-ons that can communicate with Gesturefy will have to update the ID in their code too.
