### ISSUE TITLE
Paste data from previously saved list

### ISSUE THREAD

**Issue by enskrgz** [Robbendebiene/Gesturefy#554]
example :

Paste the predetermined message when the right key + left key +1 combination

**Comment by Robbendebiene** [comment]
Please add more details.
What is a "motion edit page"?
What are your use cases of this functionality?

> when the right key + left key +1 combination

I'm sorry, but I don't understand what you mean by that.

**Comment by enskrgz** [comment]
We will state the list in Gsturefy fixed information.
Paste data from previously saved list

List:
1 Hello

2 how can i help you?

3 If we can get your name, surname, open address and telephone information, we can create your cash order at the door.

![resim](https://user-images.githubusercontent.com/25265946/101589645-ef569180-39f9-11eb-9d91-155c4a6084c6.png)

**Comment by Robbendebiene** [comment]
Sorry, but this is a too specific use case in order to be implemented as a single command.

**Comment by Robbendebiene** [comment]
You can use the user script command with the following script:

```
// switch between sessionStorage or localStorage depending on how long you want to save your decision
const STORAGE = sessionStorage || localStorage;

const TEXT_LIST = [
  "Hello",
  "World"
]

function isEditableInput (element) {
  const editableInputTypes = ["text", "textarea", "password", "email", "number", "tel", "url", "search"];
  return (
    (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA')
    && (!element.type || editableInputTypes.includes(element.type))
    && !element.disabled
    && !element.readOnly
  );
}

if (isEditableInput(TARGET)) {
  const index = Number(STORAGE.getItem('Gesturefy_Paste_Text_Index')) || 0;
  TARGET.value += TEXT_LIST[index];
  STORAGE.setItem('Gesturefy_Paste_Text_Index', (index + 1) % TEXT_LIST.length);
}
```
You need to start the gesture on the input field you want to paste the text into. Be aware though that user scripts currently do not work on some webpages (like Github).
