### ISSUE TITLE
Context menu opens on Windows while right mouse button is down

### ISSUE THREAD

**Issue by LeventDal** [Robbendebiene/Gesturefy#555]
In every gesture attempt gesture is not accepted and context menu is shown.
I've uninstalled/reinstalled, tried fast/slow and long/short movements but the result is the same.
I've disabled almost all other add-ons, restarted the browser but the problem persists.

### System
- Operating system: Windows 10
- Firefox version: 83.0
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment]
Are you using Firefox incognito mode? If yes please check in about:addons that you allowed Gesturefy to run in private windows.

If that's not the case have you already tried to reset the Gesturefy config in the Settings page > About tab?

**Comment by LeventDal** [comment]
I am using both and problem persists in both. 
Context menu fires up instantly after I click right button.
I've also tried config reset.

**Comment by LeventDal** [comment]
Now I tried it with left mouse button and it works.

**Comment by Robbendebiene** [comment]
Then you are probably experiencing one of the issues listed in the [troubleshooting guide](https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting).

**Comment by LeventDal** [comment]
Unfortunately those did not help. It feels like right click does not register. It fires up the context menu instantly before Gesturefy.
I've tried after disabling all add-ons as well.

Middle click works fine but right is no good. (Left also works but it is unpractical as it prevents text selection etc.)

**Comment by Robbendebiene** [comment]
Strange.. When you right click with your mouse, does the contextmenu appear when the mouse button is down or when you release it (mouse button goes up)?

**Comment by LeventDal** [comment]
When I press down right button it fires up the context menu.

I realized something new, If I move the mouse fast and then click the button sometimes the gesture works.

**Comment by Robbendebiene** [comment]
> When I press down right button it fires up the context menu.

All right this should be the problem. Mouse gesture extensions can only work if the context menu opens on mouse up. MacOS and Linux open the contextmenu one mouse down, because of that there exists an extra option for them that changes that. However Windows should always open the contextmenu on mouse up, therefore the option does not work for Windows. I guess you somehow modified the Windows contextmenu behaviour? Does it also open on mouse down in other applications like the file explorer?

**Comment by LeventDal** [comment]
You are right about mousedown. It happens everywhere but I am not sure what caused this.
I've tried with touchpad and it doesn't fire up context menu immediately. Also gestures work with touchpad.

**Comment by Robbendebiene** [comment]
I can't even find a way how [this behaviour](https://superuser.com/questions/1083706/show-context-menu-on-mouse-down-event) could be enabled on windows. You were talking about touch input, maybe it is somehow related to this? Or your mouse is somewhat special and initiates the mouseup before you even released the button. I'm just throwing out guesses..

**Comment by LeventDal** [comment]
Thank you for your assistance. I think the issue can be closed as it seems to be unrelated to the add-on itself.
It may be a reference for similar issues in the future.

**Comment by Robbendebiene** [comment]
All right. If you ever find a solution it would be nice if you could post it here (also out of personal interest) :)
