### ISSUE TITLE
Save image not remembering the last open folder.

### ISSUE THREAD

**Issue by rawdez** [Robbendebiene/Gesturefy#556]
### Describe your matter in detail
when saving images if you select another folder for a current image the next one still is opening an old folder not the one you selected.
but if you try and save the next one image using Right click and Save as it opens that another folder as expected.

### Your System
win10 x64
firefox84 beta8
Gesturefy, Version: 3.0.7

**Comment by Robbendebiene** [comment]
I cannot reproduce the problem on my end, everything is working as expected (Firefox 83). Since Gesturefy doesn't control this behaviour it would have to be a Firefox bug anyway.
Have you changed any about:config parameters? Maybe you can test it again on a fresh profile or with the current stable Firefox release.

**Comment by rawdez** [comment]
>Have you changed any about:config parameters
no. i use noscript and ublock, maybe they mess something up. 
my ff was behaving strange thats the reason for trying firefox84 beta8, ended up refreshing firefox (instead of uninstalling/reinstalling it), also its EME free build but it didn't change anything until refreshing ff and essentially removing my old profile. also rekt ff is the reason why i tried Gesturefy at all (smartup gestures got rekt too). now everything works fine in smartup gestures though including saving images.
https://github.com/zimocode/smartup 

at this point i am kind of tired messing with ff - (re)-installing it and configuring addons - to check how it'll work with ff 83, but you probably can check how smartup deals with saving images, maybe it'll help.

this is a list of active permissions for Gesturefy
Required permissions for core functionality:
    Access your data for all websites
    Read and modify browser settings
    Display notifications to you
Optional permissions for added functionality:
    Access browser tabs
    Access recently closed tabs
    Input data to the clipboard
    Download files and read and modify the browser’s download history

this is a list of active permissions for smartup gestures 
Required permissions for core functionality:
    Access your data for all websites
    Monitor extension usage and manage themes
    Display notifications to you
    Access recently closed tabs
    Access browser tabs
Optional permissions for added functionality:
    Download files and read and modify the browser’s download history

**Comment by rawdez** [comment]
checked about:config with word download
thats bold ones
browser.download.autohideButton	false
browser.download.lastDir %here is the path to the last opened folder%
browser.download.panel.shown	true
browser.download.useDownloadDir	false
browser.download.viewableInternally.typeWasRegistered.svg	true	
browser.download.viewableInternally.typeWasRegistered.webp	true	
browser.download.viewableInternally.typeWasRegistered.xml	true

everything else is default (thin font)

**Comment by Robbendebiene** [comment]
> but you probably can check how smartup deals with saving images, maybe it'll help.

As I said, extensions cannot really influence which download directory will be opened. You can see below that both extensions use the same API call.

smartUp:
```
chrome.downloads.download({url:_url,saveAs:true};
```
Gesturefy:

```
const downloadId = await browser.downloads.download(queryOptions);
```

Does the problem occur on every image combination or only on a certain ones, or maybe a certain website?

**Comment by rawdez** [comment]
any site, e.g. inst. open a bunch of images in tabs and saving them one by one selecting folder and closing tab. every next image when saving opens the last folder where you saved the previous image.
FF updated to 84 still the same. Right click -> Save image as... works fine. smartUp works fine. Gesturefy seem to be stuck at one particular folder.

probably just some glitch with my particular ff config/plugins set, SNAFU, not surprised at this point. anyway thanks for your time and keep up. i'm just gonna use smartUp for now.
