### ISSUE TITLE
Copy Image Location Feature Suggested!

### ISSUE THREAD

**Issue by KenseiSins** [Robbendebiene/Gesturefy#559]
Hi this isn't a bug, Gesturefy is amazing. But is there anyway we can implement a "Copy Image Location"
this is say, when you are looking for thumbnails from google for a large number of folders.
and you spot the one you like, 
copy image doesn't work, as it copy's the actual image for paint.net or photoshop or w/e
copy link location doesn't work because it copies the link of the search result and not it's image, eg. A bank's icon could be linked to the actual bank page, not the image itself.

maybe i'm just an idiot when it comes to copying links because if there was an easier way to do this somebody please tell  me.
also when I right click, i can usually use the keyboard hot keys for faster prompt. eg. V for save link, Y for copy link location
but the hotkey for Copy IMAGE location is O, except there is another function that also comes before that. So I have to press O not once, but TWICE and then hit enter, because there's more than 2 queries. (#FirstWorldProblems)

Thank you!

**Comment by Robbendebiene** [comment]
Of course this is a reasonable feature request. It honestly surprises me that no one ever asked for this before.
I'll add this in the next version!

BTW Gesturefy is all about  #FirstWorldProblems :D

**Comment by KenseiSins** [comment]
Warmest Regards, C. “Chihiro” K.
⚊ ⚋ 𝌀
⚌ ⚍ ⚎ ⚏ 𝌁 𝌂 𝌃 𝌄
𝌅
☰ ☱ ☲ ☳ ☴ ☵ ☶ ☷
𝌆 𝌇 𝌈 𝌉 𝌊 𝌋 𝌌 𝌍
𝌎 𝌏 𝌐 𝌑 𝌒 𝌓 𝌔 𝌕
𝌖 𝌗 𝌘 𝌙 𝌚 𝌛 𝌜 𝌝
𝌞 𝌟 𝌠 𝌡 𝌢 𝌣 𝌤 𝌥
𝌦 𝌧 𝌨 𝌩 𝌪 𝌫 𝌬 𝌭
𝌮 𝌯 𝌰 𝌱 𝌲 𝌳 𝌴 𝌵
𝌶 𝌷 𝌸 𝌹 𝌺 𝌻 𝌼 𝌽
𝌾 𝌿 𝍀 𝍁 𝍂 𝍃 𝍄 𝍅
𝍆 𝍇 𝍈 𝍉 𝍊 𝍋 𝍌 𝍍
𝍎 𝍏 𝍐 𝍑 𝍒 𝍓 𝍔 𝍕

**Comment by Robbendebiene** [comment]
This command is now available in [Gesturefy 3.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.1.0)
