### ISSUE TITLE
Custom "New Tab" page

### ISSUE THREAD

**Issue by rodalpho** [Robbendebiene/Gesturefy#56]
As the new Firefox doesn't allow gestures in about:newtab, would be great to configure the page opened for a new blank tab. Ideally one of the speed dial extensions would work, or I guess I'd just put duckduckgo.com. 

Same functionality you already have in "open homepage", but in a new tab or background tab. Note this would also apply to "open link in new tab/background tab" if the gesture is not performed over a link.

**Comment by Robbendebiene** [comment]
This seems similar to the following issue: https://github.com/Robbendebiene/Gesturefy/issues/51
But since this can easily be achieved by installing another addon (for example the one I mentioned in the issue), I probably won't add this kind of functionality.

**Comment by rodalpho** [comment]
Sorry to hear it; seems to me that since mouse gestures don't work on about:newtab it makes a lot of sense to allow the user to change the new tab page in your addon.
