### ISSUE TITLE
Feature Request: Add Dark Theme to "[Popup] All Tabs" (and other gestures that create popups)

### ISSUE THREAD

**Issue by redactedscribe** [Robbendebiene/Gesturefy#562]
### Describe your matter in detail
Using the "[Popup] All Tabs" gesture creates a popup that is themed in white. Ideally Gesturefy would support a dark theme for any and all gestures that create popups such as this one. The theme could be set by / follow the Gesturefy theme buttons in the Gesturefy settings sidebar, be independently set, or determined by the system's theme. I'd be happy with just a manual setting.

Thanks!

### Your System
- Operating system: Windows 10 20H2
- Firefox version: 84.0.2
- Gesturefy version: 3.0.7

**Comment by Robbendebiene** [comment]
Using the settings page theme is the best approach in my opinion. It also makes the general theme setting more useful and noticeable since the settings page is rarely visited after the gestures are set up.

**Comment by Robbendebiene** [comment]
This is now implemented in [Gesturefy 3.1.1](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.1.1)
