### ISSUE TITLE
gestures dont work for .xml files

### ISSUE THREAD

**Issue by LastExceed** [Robbendebiene/Gesturefy#565]
if the URL ends with `.xml`, gestures stop working. doesn't matter whether or not the file content is actually xml.
**real world example:** https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xml
**artifical example:** opening an empty file called `something.txt` with firefox works fine, but renaming it to `something.xml` breaks all gestures

- Operating system: Win10
- Firefox version: 85.0.2
- Gesturefy version: 3.0.7

**Comment by LastExceed** [comment]
seems like anything ending with `.xml` is blacklisted or sth. create an empty file `something.txt`, open it with firefox and everything will work fine, then rename that same file to `something.xml` and gestures stop working

**Comment by Robbendebiene** [comment]
Thanks for the report. I can fix this case since the xml shows an html file. But if a plain XML file is shown like [this one](https://www.w3schools.com/xml/note.xml) it's not possible to properly display anything (like the gesture trace).

**Comment by LastExceed** [comment]
i understand that you can't do any visual gestures on plain xml, but can you enable scroll and rocker gestures at least or is that impossible too ?

**Comment by Robbendebiene** [comment]
Yes. Wheel gestures, rocker gestures and normal gestures will work after the fix. Just any visual indication of gestures won't work.

**Comment by Robbendebiene** [comment]
This should be fixed in [Gesturefy 3.1.1](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.1.1)
