### ISSUE TITLE
This is a great addon, and hope you can add more gestures.

### ISSUE THREAD

**Issue by Dynamith** [Robbendebiene/Gesturefy#570]
For examples:
- The three custom buttons of the scroll gesture can be set separately and used at the same time.
- Add gestures for dragging text, links, and pictures.

These gestures can make the operation more convenient, and I wish your addon will be better and better.

**Comment by Robbendebiene** [comment]
Thank you for you kind words.
Both of your examples have already been requested before: #389 and #200.

**Comment by Dynamith** [comment]
That is great! But I found that these two requirements have been mentioned for a while, would you have the intention to include them in the plan?

**Comment by Robbendebiene** [comment]
I do, especially #389. But for both features I couldn't come up with a simple UI that integrates well in the current one yet.

**Comment by Dynamith** [comment]
OK, I'm looking forward to you implementing them. And other addons on Firefox may inspire you, such as GragToGo and SmartUpFeatures.

**Comment by Robbendebiene** [comment]
All right, you can follow the other issues for any updates or leave further suggestions there.
I'm closing this as a duplicate.
