### ISSUE TITLE
Reloading page doesn't remember where you were on the page

### ISSUE THREAD

**Issue by bottleblue** [Robbendebiene/Gesturefy#573]
If I do a gesture for reload it doesn't remember where I was browsing on the page. It always goes back to the top. Firefox's reload button does remember my place. FoxyGestures (which I was using previously) also remembers. Is Gesturefy using something different from Firefox's reload command?  It's pretty annoying to lose your place all the time and constantly scroll back to where you were.

### Your System
- Operating system:  Win10
- Firefox version: 86
- Gesturefy version: 3.1.1

**Comment by Robbendebiene** [comment]
Can you please check if the "reload cache" setting is enabled for the command? (just reassign the Reload Tab command to your gesture in order to do this)

**Comment by bottleblue** [comment]
Ah yes that was the problem. The reload cache was enabled. I thought I had disabled it when I created the gesture. I have a separate gesture to reload the page with reloading cache.  

Thx for the help!

**Comment by Robbendebiene** [comment]
No problem :)
