### ISSUE TITLE
Add gesture to pin a tab

### ISSUE THREAD

**Issue by HASJ** [Robbendebiene/Gesturefy#574]
### Describe your matter in detail

Is there a command to pin a tab or am I missing something?

### Your System
- Operating system: Windows 10
- Firefox version: 86.0
- Gesturefy version: 3.1.1

**Comment by Robbendebiene** [comment]
Yes, it's called "toggle pinned tab" because it does both: it unpins pinned tabs and pins unpinned tabs.

**Comment by HASJ** [comment]
@Robbendebiene It's the translation in my language that's wrong then. Thanks.

**Comment by Robbendebiene** [comment]
@HASJ What's your language?

**Comment by HASJ** [comment]
> 
> 
> @HASJ What's your language?

pt-BR

**Comment by Robbendebiene** [comment]
Can you provide a better translation then the given one? I suppose currently it is "Alternar separador fixo"?
