### ISSUE TITLE
Undo close tab doesn't work anymore

### ISSUE THREAD

**Issue by isn0t** [Robbendebiene/Gesturefy#577]
Hello everybody
I love this addon. 
Since a couple of weeks, I can't undo a closed tab. 
Is this a known issue?

- Operating system: Windows 10
- Firefox version: 86.0.1
- Gesturefy version: 3.1.1

**Comment by isn0t** [comment]
Found the solution myself:
I had to uninstall Gesturefy completely, close and reopen Firefox and redo all gestures.
Now it works like a charm again.

**Comment by Robbendebiene** [comment]
Glad you found a solution. This was probably a permission error. Recreating the gesture or reassigning the restore tab command would have probably been enough. You can also see the granted permissions in about:addons > Gesturefy > Permissions

**Comment by isn0t** [comment]
Hey - thank you for your message. I didn't expect a reaction.

I tried to recreate the gesture and did cancel the tab command. Both actions weren't succesful.

So I decided to describe the way it finally worked.

Pete


20. März 2021, 22:28 von ***@***.***:
