### ISSUE TITLE
User Script support

### ISSUE THREAD

**Issue by kirill9000** [Robbendebiene/Gesturefy#58]
Like in FireGestures/FoxyGestures. Are there plans to implement something similar?

**Comment by Robbendebiene** [comment]
I won't implement custom scripts in the nearby future (due to the lack of time), but I'm not disinclined in principle.

**Comment by JimboMonkey1234** [comment]
I'm really interested in this. Is there any work-in-progress / spec thought out? I'd contribute if I'm able.

**Comment by Robbendebiene** [comment]
@JimboMonkey1234 This feature will require a config file change, an ui change in the options page and some basic changes to the addon core. Wherefore I consider this as a major update, which will not happen this year.

My plan is to completly remove the list of actions and instead give the user the ability to add and configure actions as needed. At this point implementing user scripts as an seperated configurable action should be fairly easy.

The advantages are, that the user can have the same action (with different configs) for multiple gestures and the simple integration of user scripts.

**Comment by ledemon** [comment]
if not scripts at least custom shortcuts (keybinds)¿?

**Comment by Robbendebiene** [comment]
While user scripts where already available in Gesturefy for some time, an API to manipulate windows and tabs just landed in version [3.0.3](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.0.3). Have a look at the wiki for more information: https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script
