### ISSUE TITLE
"Gesturey could not be verified for us in Firefox and has been disabled."

### ISSUE THREAD

**Issue by aboose-aboose-aboose** [Robbendebiene/Gesturefy#581]
### Describe your matter in detail
gesturefy is automatically disabled due to not being signed as an addon for firefox

### Screenshots or further assistance
![image](https://user-images.githubusercontent.com/42923683/113366908-6b5d4800-930f-11eb-9749-120701c4ccd4.png)

### Your System
- Operating system: win10
- Firefox version: 87
- Gesturefy version: 3.1.2 april 1st 2021 version

**Comment by aboose-aboose-aboose** [comment]
Fixed by reinstalling.

**Comment by Robbendebiene** [comment]
Strange. There must have been an issue with the installation.
I'm glad you were able to fix it. If it happens again feel free to reopen this issue.
