### ISSUE TITLE
Page Back (left swipe) actually moves to previous tab and not previous page

### ISSUE THREAD

**Issue by hcksharp** [Robbendebiene/Gesturefy#582]
Issue I am having is that it jumps tabs and does not go to the previous page on left swipe. This is when multiple tabs are open. If a single tab is open works as intended.

- Operating system: Win10
- Firefox version: 87.0 (64-bit)
- Gesturefy version: 3.1.2

**Comment by Robbendebiene** [comment]
This sounds like you have another mouse gesture extension installed, can you please check that? If not please backup your config (under settings > about) and attach it here.
