### ISSUE TITLE
Wheel Gesture: When Using Wheel to Switch Tabs, Tabs are Skipped

### ISSUE THREAD

**Issue by sinrig** [Robbendebiene/Gesturefy#586]
### Describe your matter in detail
Turned on Wheel Gesture in Settings/Extra
Settings as shown on attached image
With 6 tabs open in Firefox, hold down right mouse button and scroll
Tab focus changes, but skips over a tab each time, so I can select only every _second_ one
What I've tried:
   - changing the sensitivity from the default (2); many values tried, including 1 and 10
   - turning off "smooth scrolling" in Firefox
   - using a different mouse
None of these made any difference at all.

### Screenshots or further assistance
Screenshot of "Extra" settings

### Your System
- Operating system: Windows 20H2; build 19042.928
- Firefox version: 88.0
- Gesturefy version: 3.1.2
![ExtrasSettings](https://user-images.githubusercontent.com/25424002/117064692-80edd500-acf4-11eb-894f-81a46458901c.png)

**Comment by Robbendebiene** [comment]
Can you please look into the settings of the "Focus left/right tab" command (just reselect them in the command bar) and make sure that "exclude discarded tabs" is disabled?
If this isn't the problem it would be helpful if you gut attach your config here (you can export it in the about section).
Is there anything special with the skipped tabs, any patterns? Do you use other extensions? Do you use a special mouse, lets say a mouse with a smooth scrolling wheel?

**Comment by sinrig** [comment]
It turns out that the problem was caused by another extension that was interfering with Gesturefy. Sorry for the false alarm.
