### ISSUE TITLE
Very hard to invoke a gesture on twitch.com

### ISSUE THREAD

**Issue by StentMan** [Robbendebiene/Gesturefy#587]
### Describe your matter in detail
I have a rather simple gesture to open a new tab: up and right. It is super easy to invoke it everywhere except, it seems on twitch.com. Yes, even when matching algorithm is Shape-Independent. 

To recreate the issue:
1. Download the attached file, rename it .txt --> .json
2. From Gesturefy options, restore the settings I'm using.
3. Open twitch.com and goto any **live stream** like https://www.twitch.tv/esl_sc2 (this streamer is a pretty safe bet: it's either streaming or replaying an old stream).
4. Try invoking the gesture to open a new tab (Up and Right). Doesn't matter where, exactly, you try the gesture, on top of the video stream, over the chat on the right, or below the video stream, it take more than a few tries for it to work.
5. For comparison's sake, try that gesture on some other streamer's page that's currently offline and not streaming (or replaying or hosting) such as https://www.twitch.tv/nojokechess, or some other site like https://www.google.com/.

### Screenshots or further assistance
Attached: A backup of my settings. I had to rename the .json file to .txt in order to upload it. Just rename it back to .json and you should be able to import it.
[Gesturefy 3.1.2 Wed May 19 2021.txt](https://github.com/Robbendebiene/Gesturefy/files/6510683/Gesturefy.3.1.2.Wed.May.19.2021.txt)

### Your System
- Operating system: Window 10 64bit
- Firefox version: 88.0.1 64 bit
- Gesturefy version: 3.1.2

**Comment by StentMan** [comment]
NVM, I logged out and in and everything seems to be working fine.

**Comment by StentMan** [comment]
Sigh, I was wrong, it seems. Something's consistently not working as smoothly on twitch.com

**Comment by Robbendebiene** [comment]
I'm not able to reproduce this. Can you please attach a video recording of the problem? My guess would be that the stream itself utilizes most of your system resources so that the mouse/gesture lags behind. After the restart the resources got freed (on a fresh start there are typically more resources left) and everything worked more smoothly.
