### ISSUE TITLE
Why incompatible with Waterfox all of a sudden?

### ISSUE THREAD

**Issue by br4nnigan** [Robbendebiene/Gesturefy#591]
### Describe your matter in detail
Unable to install

### Your System
- Operating system: Manjaro Linux
- Firefox version: Waterfox 78.12.0.
- Gesturefy version: 3.1.2

I changed the min version manually and the addon seems to work fine.

So if the only reason you put the latest version of Firefox as strict min that you want to encourage people to update their stuff I think that would be unfortunate. I think FOSS is about choice, about freedom of the user. In that sense I think it would be desirable to use the ESR release as strict min if possible.

**Comment by Robbendebiene** [comment]
> So if the only reason you put the latest version of Firefox as strict min that you want to encourage people to update their stuff I think that would be unfortunate.

That's definitely not the case and I find it somehow disrespectful to even assume that. Why should I want people to update their Browser?

A min version is set when a new Gesturefy feature is introduced that depends on a new Firefox feature. I doubt that you were able to check every single command/feature of Gesturefy.

> I think FOSS is about choice, about freedom of the user. In that sense I think it would be desirable to use the ESR release as strict min if possible.

I don't see how this violates freedom of choice. People with older Firefox versions should simply install an [older version](https://addons.mozilla.org/firefox/addon/gesturefy/versions/) of Gesturefy. When their browser gets updated then Gesturefy will also be updated to the next compatible release. There is nothing wrong with using an older version.

-----------------

The only thing we currently (probably) agree on is the fact that Manjaro is a good Linux distro.

**Comment by br4nnigan** [comment]
Ok I'm sorry having assumed that. I guess it's the frustration of fighting uphill battles. Btw I tried an older version (3.1.0 I think) and the preferences wouldn't come up. Probably should have tried just the last version before, because that must be the one which ran fine. But anyway, I'm fine now with the functions I use. Thank you.

**Comment by Robbendebiene** [comment]
I'm glad for your understanding.
To be fair, I wish Mozilla would just show/provide users an older (compatible) version on the add-ons page instead of marking it as "incompatible".

> I guess it's the frustration of fighting uphill battles.

I understand that.

> Btw I tried an older version (3.1.0 I think) and the preferences wouldn't come up. 

Not sure what went wrong. Sometimes removing and immediately reinstalling an add-on causes problems for me too, which I normally "solve" by a restarting Firefox. If you still encounter an issue with installing an older version feel free to reopen this issue.
