### ISSUE TITLE
Multipurpose gesture - Search selection in new tab succeeds when there is no selection

### ISSUE THREAD

**Issue by gouravkr** [Robbendebiene/Gesturefy#593]
I created a multipurpose gesture with the following actions:
1. Open link in new tab
2. Search text selection in new tab
3. New Tab

What this gesture is expected to do is the following:
1. If the starting point of the gesture is a link, then it will open the link in new tab
2. If the starting point is not a link but text selection, then it will search for that text
3. If there is neither a link nor any text selection, it will simply open a new tab

The first two conditions work as expected. However, the third doesn't. Even if there is no selection, the second action gets triggered.

### Your System
- Operating system: Windows 10
- Firefox version: 89.0.1 (64 bit)
- Gesturefy version: 3.2.0

**Comment by gouravkr** [comment]
Turns out there is already a fix for this. I looked through the source code and found this function: https://github.com/Robbendebiene/Gesturefy/blob/dbbd507cc6f06b38defe4b7d431807b499d0d234/src/core/commands.js#L1133

There is a setting called openEmptySearch which can be toggled to false while defining the gesture. This then causes the gesture to fail and move to the next one in case there is not selected text on the page.

**Comment by Robbendebiene** [comment]
Glad you figured it out yourself and I'm happy to see someone already using the new multi purpose command :)

**Comment by gouravkr** [comment]
This particular gesture was my most used gesture in the original Opera browser, before it moved to Chromium. I really missed it. The moment I saw Multipurpose gesture in the changelog, this was the first thing that came to mind. I'm so glad I can finally recreate it. Thanks for making it possible :)
