### ISSUE TITLE
Gesture trail misplaced on iframes

### ISSUE THREAD

**Issue by 0x6de** [Robbendebiene/Gesturefy#595]
### Description

the line drawn is sometimes not under the mouse cursor as you can see in the video below. This happens only on twitch streams pages. Pausing the stream fix the issue, but after resuming the stream, the bug reoccur. I had this bug with previous version of Gesturefy as well.
~~I can't reproduce this easily as it occurs from time to time and it's not happening every time i load a stream page.~~ 
After some testing, i can reproduce the issue. It seems to be linked to twitch on stream [extension](https://dev.twitch.tv/docs/extensions) . The bug occurs on every stream that have an extension activated. Disabling the extension fix the issue.

### exemples
 [this stream dosen't have an extension](https://www.twitch.tv/esl_sc2)
 [this stream does have an extention](https://www.twitch.tv/btsbrasiltv)

### video

https://user-images.githubusercontent.com/33762261/124362089-3d034780-dc33-11eb-8d97-d89f752a8ad7.mp4

### system

- _Operating system_: windows 10
- _Firefox version_:  Nightly 91.0a1
- _Gesturefy version_: 3.2.0

**Comment by Robbendebiene** [comment]
Sorry for the late response, I couldn't find the time to look into it until now. First of all thanks for the detailed report.

I've setup an example to reproduce this issue more easily: https://codepen.io/Robbendebiene/pen/NWjgeVm
It only happens in the special case where one starts a gesture inside an iframe which is repositioned via the CSS transform property. The good news are I know the cause of this problem. The bad news are I'm not aware of any good solution at the moment 😐

----------------

HTML inspection of the twitch website:
![grafik](https://user-images.githubusercontent.com/13716661/126199076-88db7563-68cf-470d-9de2-4573d2d2dbfc.png)

**Comment by Robbendebiene** [comment]
Hi, I've just tried to reproduce the bug with Firefox fission enabled and wasn't able to do so. 
Fission is the codename for a new architectural change in Firefox that targets frames. By now it should already be enabled by default if not: go to about:config > fission.autostart > true > restart

@0x6de Can you please check if you can still reproduce the bug?

**Comment by 0x6de** [comment]
Hi ! Sorry for the very very late response.
I just tested to reproduce the bug on Firefox version: 101.0a1 with fission enabled and can confirm the bug don't occurs anymore.
As far as i can see, Fission was released with Firefox version 95, so it seems to be fixed for all Firefox channels (release/beta/nightly/developper). 
Thanks !
