### ISSUE TITLE
Gesturefy is not compatiable with Firefox ESR 78.12.0

### ISSUE THREAD

**Issue by cljnnn** [Robbendebiene/Gesturefy#597]
### Describe your matter in detail

It can not be enabled with this message:
Gesturefy is not compatiable with Firefox 78.12.0

### Your System
- Operating system: windows 10
- Firefox version: 78.12.0esr
- Gesturefy version: 3.2.0

**Comment by Robbendebiene** [comment]
The latest version of Gesturefy requires Firefox 86+. Consider installing a previous version (e.g. version 3.1.1) from here: https://addons.mozilla.org/firefox/addon/gesturefy/versions/

**Comment by cljnnn** [comment]
Thanks for your help. It does work. Great.
