### ISSUE TITLE
With Beta MacOS Monterey, trackpad right click is broken

### ISSUE THREAD

**Issue by thomasd3** [Robbendebiene/Gesturefy#598]
The messages must be sent a different way because all gesture plugins have this problem, and both on Firefox and Chrome.

However, I found that if you press the trackpad with two fingers (right click) and move horizontally first, then it works. If you move vertically first, it goes to scrolling and no gesture will work.

**Comment by Robbendebiene** [comment]
Sorry but I don't know what I could do about that. You can probably solve this by disabling 2 finger scrolling somewhere in your settings. MacOS is probably not sending the right click/mouse move events because it thinks you want to scroll up and down, so this is out of my control.

**Comment by thomasd3** [comment]
yes, I think something has changed in the event reporting on MacOS. All gesture plugins have it both on Firefox and Chrome.
I've tried to disable the two finger scrolling, but it doesn't do anything. It also looks like Better Touch Tool has the same problem.

I have reported the issue to Apple, we'll see if this changes on the next beta.

**Comment by thomasd3** [comment]
MacOS Monterey build 21A5304g fixed it.
