### ISSUE TITLE
Gesturefy cannot be used when the website connection timeout

### ISSUE THREAD

**Issue by ant3st** [Robbendebiene/Gesturefy#603]
### Description:
网站连接超时导致页面载入出错，此时无法使用Gesturefy。
The website connection timeout causes a page loading error, and Gesturefy cannot be used at this time.

### Screenshots:
<img width="955" alt="Snipaste_2021-08-23_15-05" src="https://user-images.githubusercontent.com/23309682/130405302-b0601d93-5b37-4df5-9813-edbad6714584.png">

and this one:

<img width="840" alt="Snipaste_2021-08-23_21-50" src="https://user-images.githubusercontent.com/23309682/130459048-7020ac3b-0e81-421e-abff-43185d013806.png">

### System:
- Operating system:Windows & MacOS
- Firefox version:Nightly 91.0.1
- Gesturefy version:3.2.0

**Comment by Robbendebiene** [comment]
Hi, thanks for the detailed report.
What you've encountered is a limitation of the Firefox add-on API. It's already stated in the[ add-on description](https://addons.mozilla.org/en-US/firefox/addon/gesturefy/):

> The page must be partially loaded to perform gestures.

Put simply, a part of Gesturefy needs to run in every webpage, so when the loading of the webpage fails Gesturefy won't load either.

At the time of writing this is impossible to solve.
