### ISSUE TITLE
"Recently closed tabs" shows up in top left corner

### ISSUE THREAD

**Issue by CrendKing** [Robbendebiene/Gesturefy#605]
### Describe your matter in detail

In the current released version of Firefox (91.0.2), the "[Popup] Recently closed tabs" window shows up exactly at the mouse cursor position. However, in vanilla Firefox Beta (92.0b) and Nightly (93.0a), the window shows up at top left corner, making it difficult to use.

### Screenshots or further assistance

![Gesture](https://user-images.githubusercontent.com/975235/131215450-792d493f-4703-4fc5-8c71-92a419082b0f.jpg)

### Your System
- Operating system: Windows
- Firefox version: Firefox 92.0b9
- Gesturefy version: 3.2.0

**Comment by mpopp75** [comment]
The same happens with the "[Popup] Search Engines" popup window and potentially with other popups as well.

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll look into it.

**Comment by Robbendebiene** [comment]
This is fixed in the latest release ([Gesturefy 3.2.1](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.1))
