### ISSUE TITLE
Reopen closed tab doesn't work

### ISSUE THREAD

**Issue by xxvii** [Robbendebiene/Gesturefy#608]
### Describe your matter in detail
Since upgrading to FF 92.0, the gesture associated with "Reopen closed tab" doesn't work.
The gesture is recognized (I see the command on screen) but nothing happens.
Firing the command from the tab's dropdown menu works.

The same gesture works in FF 93.0b2
I already tried to delete and recreate the gesture to no avail.

### Your System
- Operating system: Windows 10
- Firefox version: 92.0
- Gesturefy version: 3.2.1

**Comment by Robbendebiene** [comment]
Can you please try to reassign the "Reopen closed tab" command (or recreate the entire gesture) in the settings page? Alternatively you can also go to `about:addons` > Gesturefy > Permissions and make sure "Access recently closed tabs" is checked.

**Comment by xxvii** [comment]
Hello @Robbendebiene , I tried both things but it still doesn't work

**Comment by Robbendebiene** [comment]
Does the regular Firefox "Restore closed tab" work for you?

If so then please follow the steps below:

- Open a new tab
- Enter `about:devtools-toolbox?type=extension&id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D`
- Switch to the "Console" tab in the top bar and clean the console via the "bin" icon (top left)
- Try your "Restore closed tab" gesture in a different tab
- Go back to the console, copy and paste all outputs into the issue

**Comment by xxvii** [comment]
I don't know what happened but now it seems to work, I only restarded the pc.

Anyway I did as suggested and this is the output:

Error: Please use $(ref:runtime.getURL). background.js:31
    d moz-extension://999d212a-68b5-4af1-9021-8776be60062b/background/background.js:31
Error: Please use $(ref:runtime.getURL). background.js:14587
    set_icon moz-extension://c430dc7b-4b99-4e1c-ad1b-08d11dcf808e/background.js:14587
Error: Please use $(ref:runtime.getURL). background.js:31
    d moz-extension://999d212a-68b5-4af1-9021-8776be60062b/background/background.js:31

**Comment by Robbendebiene** [comment]
All right, thanks for the feedback.
Looks like the errors come from a different extensions.
If your problem reoccurs just reopen the issue or add another comment.
