### ISSUE TITLE
Return to previous scroll level

### ISSUE THREAD

**Issue by madprops** [Robbendebiene/Gesturefy#614]
Hi, thanks for this very useful firefox addon. 

Sometimes I slide up to go to the top of a page, but then realize I actually want to go back to the previous scroll position I was at, maybe to re-read something. I was wondering if it would make sense to have some gesture that would jump back to the previous position. Say for instance I was reading some post near the middle of the screen, and I jump up; at this point I haven't scrolled manually, just used the gesture; if the last position is saved it could be used to jump back to where I was before the jump. I don't know if it makes sense.

**Comment by Robbendebiene** [comment]
It's now possible to define a fallback command for user scripts by using the multi purpose command. [Gesturefy 3.2.2](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.2).
