### ISSUE TITLE
Add scroll distance setting for scroll page down/up commands

### ISSUE THREAD

**Issue by hpirila** [Robbendebiene/Gesturefy#616]
### Problem description
The scroll down and scroll up are scrolling too much when there is a static banner on top of the screen. See the screenshot examples to clarify.

The failed case, for example cnn.com here but many other sites as well.

You can see the last row 'Sailing ship captures a narco sub'
<img width="920" alt="nok1" src="https://user-images.githubusercontent.com/37920282/138992976-410887ea-46bf-4e91-b0b1-93e7c0de6ff2.png">

After one scroll down using the gesture, the row 'Sailing ship captures a narco sub' is not visible in the screen any more. It scrolled down slightly too much. It happens only in the pages which has this kind of non-moving banner on top. I mean the row on top with content 'CNN World US Politics Business Health...'

<img width="921" alt="nok2" src="https://user-images.githubusercontent.com/37920282/138993189-2ab74049-f175-4ac9-ae60-bc05bad02cf9.png">

Now the OK case where there is no static banner on top, it works fine:

You can see the bottom row says: 'Turn-based games with thousands of human opponents'
![ok1](https://user-images.githubusercontent.com/37920282/138991874-0072f53f-be3f-46be-9131-2d7e3d13a332.png)

After scrolling one time down using gesture:
You can see the row with 'Turn-based games with thousands of human opponents' is nicely the first row.
![ok2](https://user-images.githubusercontent.com/37920282/138991986-efb8ecbd-e3f8-471c-872c-66df3152244c.png)

### Your System
- Windows 10
- Firefox version: 93.0
- Gesturefy version: 3.21.

**Comment by Robbendebiene** [comment]
This feature is now available in [Gesturefy 3.2.2](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.2).
