### ISSUE TITLE
[Popup] commands stopped working after update to Gesturefy 3.2.2

### ISSUE THREAD

**Issue by Lola-Lilypistol** [Robbendebiene/Gesturefy#618]
### Describe your matter in detail

I have right-click right gesture set up as [Popup] Search engines but earlier today it stopped working. Restarted the browser, checked for updates, checked for Gesturefy updates, hasn't worked. Thank you for your time

### Your System
- Operating system: Windows 10
- Firefox version: 94.0
- Gesturefy version: 3.2.2

**Comment by Robbendebiene** [comment]
Thanks for the report, I've noticed this too.
I try to release a hotfix today. For now you can only downgrade to the previous version.

**Comment by Robbendebiene** [comment]
This should be fixed in the [latest version](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.3).

To get the latest version just go into the Firefox add-on manager, click the gear icon and choose "check for updates".

**Comment by Lola-Lilypistol** [comment]
Worked. Thank you so much!
