### ISSUE TITLE
blacklist and disable button

### ISSUE THREAD

**Issue by kent1026** [Robbendebiene/Gesturefy#62]
some 3D website use all mouse key 、 shift、ctrl and alt 
example: Onshape
it's possible add blacklist and disable button ?
THX

**Comment by Robbendebiene** [comment]
So you want to completely disable gesturefys functionality for a certain page, right? What do you mean by "disable button"?

**Comment by kent1026** [comment]
like a on/off switch 
it can stop gesturefys

**Comment by Robbendebiene** [comment]
Sure, but where should it appear? on right click/context menu, as a toolbar button, or in the options page?

**Comment by kent1026** [comment]
toolbar is better
thanks

**Comment by Robbendebiene** [comment]
I decided to implement the blacklist for the options page, but I wont add the toolbar button, because it seems to be overkill. I think this should still fulfill your request.

**Comment by zweicoder** [comment]
@Robbendebiene blacklisting / toolbar button to toggle on/off will be a very useful feature! Is this already implemented in 1.1.14? I have to manually disable the plugin on various pages now

**Comment by Robbendebiene** [comment]
@zweicoder Not yet.

**Comment by jim-p** [comment]
A blacklist will be an excellent feature, please also consider an option to flip the meaning of the suppression key for blacklisted sites. For example, if a site is on a blacklist, pressing the suppression key will activate gestures rather than the usual behavior.

**Comment by nazar-pc** [comment]
I'm playing with Tinkercad lately and have to disable extension while doing so, otherwise it is impossible to use it. There are more and more web-based apps like that and option to blacklist some pages/domains would be an awesome addition to have.

**Comment by Robbendebiene** [comment]
In Gesturefy 2.0.0 you can now blacklist websites via URL match patterns in the Gesturefy config. Since this is a rarely required functionality we decided (for now) against a browser action button.
