### ISSUE TITLE
Gesturefy broken after recent update

### ISSUE THREAD

**Issue by m0nac0** [Robbendebiene/Gesturefy#620]
### Describe your matter in detail
Since approx. 2 days Gesturefy is completely broken for me. The settings page is blank, mouse gestures are not shown anymore and rocker gestures do not work. I have installed the most recent update today, but it didn't solve the issue.

I also tried disabling and re-enabling the extension without success.

### Your System
- Operating system: Windows 10
- Firefox version: 94.0.1
- Gesturefy version: 3.2.3

**Comment by Robbendebiene** [comment]
> Since approx. 2 days Gesturefy is completely broken for me. The settings page is blank, mouse gestures are not shown anymore and rocker gestures do not work.
This was about the time I released a new update. So this sounds very much like a damaged config.

Can you please open the console in the settings page (ctrl + shift + K), reload and post any errors here?

If you are familiar with HTML you can also add the class "loaded" to the root element in the settings page  `<html class="light-theme loaded"><head>` and then try to export your current settings under "About".

**Comment by Robbendebiene** [comment]
You can also backup your current config by going to: `about:devtools-toolbox?id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D&type=extension`

Then copy and paste the contents from the Extension Storage tab into a text/json file.

![image](https://user-images.githubusercontent.com/13716661/140540918-33edf395-f4e7-43ff-93e1-45d2a84b9c40.png)

**Comment by m0nac0** [comment]
@Robbendebiene Sorry, I was only now able to try your suggestions.

> Can you please open the console in the settings page (ctrl + shift + K), reload and post any errors here?

I see 5 consecutive `Uncaught (in promise) Error: An unexpected error occurred` errors without any more details.

> If you are familiar with HTML you can also add the class "loaded" to the root element in the settings page <html class="light-theme loaded"><head> and then try to export your current settings under "About".

I tried this, but then the resulting page is still very broken (labels missing etc.) I was able to make my way to the about page and find the backup button, but clicking it does nothing.

> You can also backup your current config by going to: about:devtools-toolbox?id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D&type=extension

> Then copy and paste the contents from the Extension Storage tab into a text/json file.

Unfortunately, both the settings page and the storage tab of the developer console are completely blank, so there is nothing to copy for me.

**Comment by Robbendebiene** [comment]
Thanks for your feedback.

> Unfortunately, both the settings page and the storage tab of the developer console are completely blank, so there is nothing to copy for me.

This sounds very odd. Even without a config Gesturefy should fall back to the defaults and run fine. This strengthens my belief in a damaged config file, which is probably not recoverable.

Are you using any other extensions that save some data on local storage?

You can rename the "storage" folder inside your Firefox profile folder (more details here: https://support.mozilla.org/en-US/questions/1289725) but in this case you will loose a lot of other settings as well. I'm unable to find the exact location where Firefox stores add-on settings. As far as I know since Firefox 63 all add-on settings are stored inside a single indexDB file.

**Comment by m0nac0** [comment]
Thank you for your help, but I just reinstalled Gesturefy and it works fine again (after all, its not much to configure).

Keep up the great work!

**Comment by Robbendebiene** [comment]
Your welcome! Hopefully the problem won't arise again, if so feel free to reopen this issue.
