### ISSUE TITLE
Previous page

### ISSUE THREAD

**Issue by GGGesture** [Robbendebiene/Gesturefy#623]
Since the recent update the gesture for PREVIOUS PAGE is broken, it always skips back two pages.

### Your System
- Operating system: Windows 10
- Firefox version: 94.0.1
- Gesturefy version: 3.2.4

**Comment by Robbendebiene** [comment]
Everything works as expected for me. Do you have any other extensions installed?
If not can you please share your config file (you can export it in the settings page under "About").

**Comment by GGGesture** [comment]
You're right. I don't know why but Foxy Gestures enabled itself thus the gesture was executed twice.
