### ISSUE TITLE
"Scroll Page Down" scrolls to the very top of the page

### ISSUE THREAD

**Issue by timgws** [Robbendebiene/Gesturefy#626]
[Gesturefy export.json](https://github.com/Robbendebiene/Gesturefy/files/7552039/Gesturefy.3.2.4.Wed.Nov.17.2021.json.txt)

If I use the "Scroll Page Down" gesture, the page scrolls to the very top of the page. The only time it does not happen is if you are already at the bottom of the page.

It seems to happen only recently (last 7 or so days?).

### Your System
- Operating system: macOS 11.5.1
- Firefox version: 94.0.1
- Gesturefy version: 3.2.4

**Comment by Robbendebiene** [comment]
In theory this shouldn't have happened, but somehow the new "scroll proportion" setting is missing in your config.

You can either reassign the "Scroll Page" commands to your gestures or import the fixed config:
[Gesturefy.3.2.4.Wed.Nov.17.2021.json.txt](https://github.com/Robbendebiene/Gesturefy/files/7553399/Gesturefy.3.2.4.Wed.Nov.17.2021.json.txt)

**Comment by timgws** [comment]
@Robbendebiene thanks for that! Reassigning the commands fixed the problem!
