### ISSUE TITLE
Css scroll-behavior overrides scroll gesture duration

### ISSUE THREAD

**Issue by trondsg** [Robbendebiene/Gesturefy#630]
### Describe your matter in detail
Affected commands are: Scroll to bottom, scroll to top.
Using: Duration = 0

Problem: Some pages set scroll-behavior to smooth, which seems to override duration.

Preferred solution: Always act as if scroll-behaviour: auto.

### Screenshots or further assistance
html file showing the problem
[test.md](https://github.com/Robbendebiene/Gesturefy/files/7780559/test.md)

### Your System
- Operating system: Linux
- Firefox version: 95.0
- Gesturefy version: 3.2.4

**Comment by Robbendebiene** [comment]
Thanks for the detailed report.
I should be able to fix this.

**Comment by trondsg** [comment]
I found out I could fix this by setting layout.css.scroll-behavior.enabled to false in Firefox. This removes all smooth scroll, which is what I want.

**Comment by Robbendebiene** [comment]
This has been fixed in [Gesturefy 3.2.5](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.5)
