### ISSUE TITLE
Feature Request: "Disable on this page"

### ISSUE THREAD

**Issue by xxxmicrobexxx** [Robbendebiene/Gesturefy#633]
It would be great if gesturefy could be disabled on a page by page (or site by site) basis.  This can be done with plug-ins like ad blocker and privacy badger.

For example, in Tinkercad (and many online 3D programmes) right click is to rotate the view, but gesturefy wants to go page back.  I have to disable gesturefy completely.

Perhaps because gesturefy is tab/browser based it can't detect the site, but if it is possible, this would be a great feature.

**Comment by Robbendebiene** [comment]
Hey, you can already do this by adding "exclusions" inside the Gesturefy settings page.
This might not be as convenient as a single "disable on this site" button, but I guess for the quite rare cases where one wants to disable gestures it might be enough. What do you think?

**Comment by xxxmicrobexxx** [comment]
PERFECT!  Thanks.  Didn't spot that buried in _addon > manage > options > settings > exclusions_, but there isn't much you can do about the depth.

Also, it didn't work with `https://www.tinkercad.com/*` but what does work is `*://*.tinkercad.com/*` so thanks for your help page.
