### ISSUE TITLE
Open URL in Incognito

### ISSUE THREAD

**Issue by zitozi** [Robbendebiene/Gesturefy#639]
Is there a way to set a specific URL to open in incognito? I've try to use scripts but it is not working for me, I can only set a URL to open in a new window or tab using the gestures.

**Comment by Robbendebiene** [comment]
Hi, do you want something like the "Open Custom URL In New Tab" command, but instead of opening a specific URL in a new tab it should open it in a new private window? Or do you want to open a link/url on a webpage in a new private window?

**Comment by zitozi** [comment]
The first option. For example set (https://mail.google.com) to open in a private window every time i do a specific gesture.

**Comment by Robbendebiene** [comment]
All right. This is currently not possible, but I'll try to add this soon.

**Comment by Robbendebiene** [comment]
Implemented in release [3.2.6](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.6)
