### ISSUE TITLE
Where is the "Auto Save Image" option? 

### ISSUE THREAD

**Issue by K8522** [Robbendebiene/Gesturefy#640]
Up until this morning I was able to use a gesture to just auto save an image, but then (literally after using it all day), I did a reboot and after the reboot, all my gestures were gone, and when I went to recreate them, I couldn't find a whole bunch of commands that were there before, most notably "Auto save picture" which I used a ton. It's weird to me that everything got reset after a random reboot (I reboot every day) and that suddenly things are no longer working. I'm on Gesturefy 3.2.5 and Firefox 100.0.2. As far as I know, there was no update before I rebooted. How do I get my old settings back or at least, some of the old commands I was using? 

Thanks for a great product, love the app and have been using for many many years! I was like a fish on dry land when it broke just now. 

EDIT: Okay I guess you can set the prompt to "Off"... the other one I used was "reload tab" (left-up) and then "reload tab + cache" which was (left-up-right). I hope I'll still be able to do that. :-) Anyway I guess this can be marked as solved.

**Comment by Robbendebiene** [comment]
I have no idea what happened. Clearly something must have been changed. Maybe some misbehavior of a cleanup program. I really don't know.

Gesturefy never had a command named "Auto save picture", you probably used "Save Image" and renamed it.
Unfortunately now that you've overridden the config by creating new gestures we no longer have a chance of restoring your previous config.

> Thanks for a great product, love the app and have been using for many many years! I was like a fish on dry land when it broke just now.

Always happy to hear that (at least the first part 😅)
If the problem occurs again, just reopen the issue so we can track down the problem.
