### ISSUE TITLE
Reset Zoom command is actually Set Zoom to 100%

### ISSUE THREAD

**Issue by byzod** [Robbendebiene/Gesturefy#641]
### Describe your matter in detail
My default zoom level is 150%, but using the `reset zoom` command reset the room level to 100% instead of 150%

### Screenshots or further assistance

![An1](https://user-images.githubusercontent.com/848607/171391772-016a7d5d-19c2-4b4c-b678-3f4cb2895ef5.gif)

### Your System
- Operating system: win10 x64
- Firefox version: 100b9
- Gesturefy version: 3.2.5

**Comment by Robbendebiene** [comment]
Hi, thanks for the detailed report.
Unfortunately I'm not able to fix this yet, but I've created a ticket on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1772166

**Comment by Robbendebiene** [comment]
The missing underlying functionality got implemented in Firefox. So this bug should be fixed in Firefox 110.
If this is not the case please let me know.
