### ISSUE TITLE
Paste clipboard cannot work somtimes

### ISSUE THREAD

**Issue by popyoung** [Robbendebiene/Gesturefy#644]
I set an action to "Paste clipboard", but it cannot work in some pages.

e.g. There are two pages from Stackoverflow. The first it works while the second it does not. And I cannot tell the reason.
https://stackoverflow.com/questions/22147988/paste-client-clipboard-in-js
https://stackoverflow.com/questions/72853100/is-there-a-similar-approach-to-customcreationconverter-in-system-text-json

- Operating system: Win10
- Firefox version: 91.12esr
- Gesturefy version: 3.2.5

**Comment by Robbendebiene** [comment]
Hi, it works for me on both pages. Please be more specifc where exactly it doesn't work. Maybe share a screen recording (for example using [this website](https://www.flexclip.com/tools/screen-recorder/)).

**Comment by popyoung** [comment]
Oh, I forgot it after I posted this. And oddly enough, today I cannot reproduce the issue either. I will close this topic until something new is found.
