### ISSUE TITLE
Change popup command font size

### ISSUE THREAD

**Issue by OLOPOLON** [Robbendebiene/Gesturefy#645]
Is it possible to add option to changing font size in gestures, which display pop-up with search engines and recently closed tabs?
I tried find some CSS code to add userchrome.css, but I failed. I'm total amateur in programming, I'm only user. 

You made great addon. For me is a game changer in browsing internet. Greetings from Poland.

**Comment by Robbendebiene** [comment]
Hi, I'm glad you like the add-on.
In theory it is easy to change the font size in code. My problem is that exposing this as a setting would clutter the UI/options page for a rarely used feature.

Would it help you if Popups would use the standard font size of Firefox which you can also change in the Firefox settings page?

**Comment by OLOPOLON** [comment]
Thanks for answer. Perhaps it's  a good solution, but I will know for sure, if I test it first.

**Comment by OLOPOLON** [comment]
After your proposition, I was discovered that font size is depending at level of zoom particular site, which is dependent  from Zoom Page WE addon. That's why your solution is not convenient for me. It just has to be that way.

**Comment by Robbendebiene** [comment]
My suggestion would be to use the [userContent.css](https://superuser.com/questions/318912/how-can-i-override-the-css-of-a-site-in-firefox-with-usercontent-css) file.
I've even made a little change in release [3.2.6](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.6) to simplify this.

**How to:**
1. got to `about:config` and make sure `toolkit.legacyUserProfileCustomizations.stylesheets` is to `true`
2. Create the `userContent.css` as described [here](https://superuser.com/questions/318912/how-can-i-override-the-css-of-a-site-in-firefox-with-usercontent-css)
3. Go to `about:debugging#/runtime/this-firefox` and search for Gesturefy to find its internal UUID
4. Copy the following code into your  `userContent.css` substituting the placeholder by the UUID.
```
@-moz-document url-prefix(moz-extension://INTERNAL_UUID/core/views) {
  :root {
    font-size: 30px !important;
  }
}
```
Note though that this depends on Gesturefy internals which may change with a new release.

**Comment by OLOPOLON** [comment]
Sadly, your solution don't work for me. Pop up command font size still depends from level zoom of particular site. Maybe without Zoom Page WE addon, it will be a good soultion, but I need it as Gesturefy. Anyway thanks for help.
