### ISSUE TITLE
Page cannot be scrolled

### ISSUE THREAD

**Issue by ygoe** [Robbendebiene/Gesturefy#646]
### Describe your matter in detail
The "Scroll to top" and "Scroll to bottom" gestures do nothing on this website:
https://www.energie-experten.org/

Other gestures like "Back" work fine.

### Your System
- Operating system: Windows 10
- Firefox version: 103.0.2
- Gesturefy version: 3.2.5

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll look into it.

**Comment by Robbendebiene** [comment]
Fixed in release [3.2.6](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.6)
