### ISSUE TITLE
Losing Response to keyboard Enter/Return event

### ISSUE THREAD

**Issue by dbcliu** [Robbendebiene/Gesturefy#65]
When Gesturefy is enabled in FF57 beta7 and previous versions, some web pages lose response to keyboard Enter/Return event. Examples could be found on bing.com or baidu.com. When Gesturefy is disabled, we can type in keywords, press Enter, and get/refresh search results. But when Gesturefy is enabled, pressing Enter doesn't have any effect.

**Comment by Robbendebiene** [comment]
I also came across this bug on other websites, but I can not imagine any point in the source code where Gesturefy could cause this kind of problem. And things get much weirder, the problem only occurs sometimes AND apparently only when I install it directly from https://addons.mozilla.org.

**Comment by dbcliu** [comment]
So weird! This issue doesn't occur on sites like google & imdb. I wonder if Bing and Google are using different techniques (maybe html or JS) to achieve the responding actions. I guess that one may conflict with something in Gesturefy, while the other may not. Since I'm not a programmer, I can only offer limited experience. I hope it will be a little helpful.

**Comment by Robbendebiene** [comment]
Do you have Rocker or Wheel gesture enabled? If so please disable them and try again.

**Comment by dbcliu** [comment]
It seems the Wheel gesture is causing the problem. When disabled, all works.
Before i open this issue here, my suspicion was first on Rock gesture, so i disabled it, and nothing changed. Why didn't i try disabling wheel gesture!?...

**Comment by Robbendebiene** [comment]
Wheel gesture and Rocker gesture are both effected by this bug. But it should be fixed in the next version. If you want to test it, you can download it here: https://github.com/Robbendebiene/Gesturefy/archive/master.zip, unzip and load it on the "about:debugging" page via "load addon temporary" by selecting the manifest.json. (do not forget to disable your current version of gesturefy if you try this out)

**Comment by Robbendebiene** [comment]
Should be fixed, if not please let me know.
(https://github.com/Robbendebiene/Gesturefy/commit/fec9f7fec76acdd523d909e2ab8021ff45a4229e)
