### ISSUE TITLE
"Close tabs of same domain" gesture

### ISSUE THREAD

**Issue by Argument7** [Robbendebiene/Gesturefy#650]
### Your System
- Operating system: Windows 10
- Firefox version: 104.0 (64 bit)
- Gesturefy version: 3.2.6

Please add the "Close tabs of same domain" gesture.

**Comment by Robbendebiene** [comment]
You can use the user script command for this with the following script:
```js

const queryTabs = API.tabs.query({
  hidden: false,
  currentWindow: true,
  url: `${location.origin}/*`
});

queryTabs.then((tabs) => {
 const tabIds = tabs.map((tab) => tab.id);
 API.tabs.remove(tabIds);
});

```

**Comment by Argument7** [comment]
> 

Thank You! Works fine!

**Comment by Robbendebiene** [comment]
Nice!
Be aware though that user scripts still suffer from a little[ Firefox bug](https://github.com/Robbendebiene/Gesturefy/issues/569), so it may not work on some websites.
