### ISSUE TITLE
Feature Request: Commands to scroll left and right with mouse gestures

### ISSUE THREAD

**Issue by Hackgets** [Robbendebiene/Gesturefy#651]
I know similar requests have existed in the past, but I prefer to scroll in all directions with mouse gestures, not the wheel. With autoscroll, I have to do a middle click, which sometimes opens links unintentionally.

**Comment by Robbendebiene** [comment]
Please be more specific of what the actual command should do. Should it scroll to the left / right end of the page, or should it only scroll a certain amount horizontally?

**Comment by Hackgets** [comment]
Certain amount. It would be nice to be able to set that amount.

**Comment by Robbendebiene** [comment]
#221 describes how to use a user script in order to do this.

If you want a smooth transition use the following code:

Scroll right
```
document.scrollingElement.scrollBy({
  left: 300,
  behavior: 'smooth'
})
```

Scroll left
```
document.scrollingElement.scrollBy({
  left: -300,
  behavior: 'smooth'
})
```
