### ISSUE TITLE
Increase URL affecting more than what should be based on regex

### ISSUE THREAD

**Issue by BumperB** [Robbendebiene/Gesturefy#652]
When using the website Derpibooru I browse through my watched shortlist and like to use the increase URL number, problem is that it changes more of the URL and ends up breaking it. If I were on page 2 the URL would be: "https://derpibooru.org/search?page=2&q=my%3Awatched" and so naturally I would like to go to: "https://derpibooru.org/search?page=3&q=my%3Awatched". Unfortunately for some reason, despite my efforts troubleshooting the regex, every time I use increase URL it alters the "my%3Awatched" to "my%253Awatched" and breaks the php request. I can't see why it would be doing this, but I've just been dealing with it and not using Gesturefy in this scenario, but probably better I make aware the problem so that anyone in a similar (albeit less pony based) environment can rely on the plugin.

### Your System
- Operating system: Windows 10
- Firefox version: 3.2.6
- Gesturefy version: 3.2.6

**Comment by Robbendebiene** [comment]
Thanks for the report. I was able to reproduce it and will look into it.
