### ISSUE TITLE
Backup button doesn't work

### ISSUE THREAD

**Issue by pdqpat** [Robbendebiene/Gesturefy#654]
Procedure:  Open Gesturefly settings  > About  > Backup
Nothing happens.  Clicking Restore brings up a popup window to choose a file.
Closing/reopening Firefox has no effect.
   Windows 10 Home version 21H2 build 19044.1889
   Firefox version 105.0.1
   Gesturefy, Version: 3.2.6

**Comment by Robbendebiene** [comment]
Since Firefox 98 files are automatically saved/downloaded to your download directory (https://support.mozilla.org/en-US/kb/manage-downloads-preferences-using-downloads-menu). Can you please check if you can find the backup files in your download directory?

**Comment by pdqpat** [comment]
Thank you. I changed my download settings and there they all are.  Sorry for the bug report.

**Comment by pdqpat** [comment]
Firefox settings has a checkbox to 'Always ask you where to save files'.  I checked it on again and all is well.  It's just an extra click. When I clicked the Gesturefly 'backup' button with that setting cleared, maybe a message indicating that the backup file had been stored in my default folder would be helpful.
