### ISSUE TITLE
Display gesture trace does not turn off

### ISSUE THREAD

**Issue by fwong88** [Robbendebiene/Gesturefy#660]
Toggling trace on lets me choose colour, width, etc. of the trace.

Toggling trace off displays a thin purple trace line. I cannot seem to turn trace off entirely. A prior version of Gesturefy did not have this issue (firefox sync on another device somehow caused an update on my main PC).

### Your System
- Operating system: Windows 10 Pro
- Firefox version: 106.0.2 (64-bit)
- Gesturefy version: 3.2.7

**Comment by Robbendebiene** [comment]
This sounds like you have another gesture extension like Foxy Gestures installed.
