### ISSUE TITLE
Any way to prevent tab scrolling not working when loading slow sites?

### ISSUE THREAD

**Issue by bottleblue** [Robbendebiene/Gesturefy#661]
### Describe your matter in detail
I have wheel gestures enabled, using right mouse button to trigger the gesture. Wheel gesture up is set to Focus left tab. Wheel gesture down is set to Focus right tab. Opening a slow loading site or a site having trouble loading prevents tab scrolling from working at all. You have to wait for it to finish or move your mouse instead. Is there any way around this?  As an example I used the chinese site 163.com. It took about 7-10 seconds (showed a blank white page) to begin loading the page for some reason  and I couldn't scroll to another tab to let it finish loading.

I don't think this is a problem with Gesturefy. This happens on other tab scrolling extensions also so I believe it's a Firefox issue. But I was wondering if there was some way around this.

### Your System
- Operating system: Win 10 pro 21H2
- Firefox version: 106.0.1
- Gesturefy version: 3.2.7

**Comment by Robbendebiene** [comment]
This is a know (and where unfortunate) limitation.
From the add-on description:
> The page must be partially loaded to perform gestures.

Add-ons that want to catch any mouse events (clicks, mouse movement etc.) have to run code in the active webpage. As long as the website isn't loaded the add-on code isn't loaded as well wherefore the add-on cannot work.

**Comment by bottleblue** [comment]
I see. Thx for the explanation.
