### ISSUE TITLE
Right click-drag brings context menu

### ISSUE THREAD

**Issue by thomasd3** [Robbendebiene/Gesturefy#664]
### Describe your matter in detail

When I make a gesture, it is executed properly, however, after the gesture is executed, the Right click context menu is displayed.

For example, I if I make a gesture to close a tab, after the tab is closed, the browser shows the previous tab with the context menu where the mouse cursor is.

This is not a new problem, it has appeared before in the past.

A new profile does NOT fix this.

### Screenshots or further assistance

I've attached a short video

https://user-images.githubusercontent.com/14313218/209794694-9bb6559d-af6c-4fbe-829f-c20768980732.mov

### Your System
- Operating system: MacOS Ventura 13.2
- Firefox version: 108.0.1
- Gesturefy version: 3.2.7

**Comment by Robbendebiene** [comment]
Have you tried/verified the following: https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture ?

Does this only occur for gestures that change the active tab (like close tab, or switch to right/left tab)?

**Comment by thomasd3** [comment]
@Robbendebiene This has fixed it!

And, yes, only when you change tab.

Thanks a lot!
