### ISSUE TITLE
Has URLLevelUp changed behaviour?

### ISSUE THREAD

**Issue by Tabiskabis** [Robbendebiene/Gesturefy#665]
I used URLLevelUp to get to from a 1-level URL (example.com/?what=ever) to its root-URL (example.com/).
This does not work anymore since a few days.

- MacOS 10.14
- Firefox 108.2
- Gesturefy 3.2.7

**Comment by Robbendebiene** [comment]
There hasn't been any recent updates and the behaviour seems as expected to me
`example.com/?what=ever` is already the "root URL", it just has a parameter.
However `example.com/what` would change to `example.com` upon executing the command.
