### ISSUE TITLE
Feature Request: Touchpad Pinch and Drag to Zoom in and Zoom Out

### ISSUE THREAD

**Issue by lamyergeier** [Robbendebiene/Gesturefy#666]
### Describe your matter in detail

Is it possible to add the feature: Touchpad Pinch and Drag to Zoom in and Zoom Out

### Your System
- Operating system:Linux
- Firefox version:108.2
- Gesturefy version:3.2.7

**Comment by Robbendebiene** [comment]
Please be more specific about your feature request.
Is it a new functionality, a new command, etc. ?

If you you are looking for something like this: https://addons.mozilla.org/en-US/firefox/addon/multi-touch-zoom/ then this is out of scope for Gesturefy. Gesturefy is a mouse gesture extension that allows you to execute commands via user defined mouse movements. It has no special relation to trackpad or touchpad gestures.

**Comment by lamyergeier** [comment]
Ok Thanks. You may close the issue.
