### ISSUE TITLE
Second time all settings have been resetted

### ISSUE THREAD

**Issue by akswiff** [Robbendebiene/Gesturefy#672]
Hi, for the second time within a few weeks all settings have been resetted (after an update of Firefox I guess).

- Operating system: Windows 10 21H2 Build 19044.2728
- Firefox version: 111.0.1 (64-Bit)
- Gesturefy version: 3.2.7

Console log is empty:

![Screenshot 2023-03-29 223647](https://user-images.githubusercontent.com/20814945/228661501-fc6f903c-402b-4230-b6cd-a057e11585aa.jpg)

**Comment by Robbendebiene** [comment]
The last Gesturefy update was released on October 2022, so two updates in a row seems unlikely to me.
Please provide at least the minimal information (noted in the issue template) about what Gesturefy version you use, OS etc.

Since the settings are stored in your Firefox profile there are a lot of other potential reasons your settings get deleted.

**Comment by akswiff** [comment]
An FF update I guess. I added information about OS Version etc.

**Comment by Robbendebiene** [comment]
Okay, so for now I can only give you the advice to look into the extension storage (see image below) when the problem occurs again before creating any new gestures.


![grafik](https://user-images.githubusercontent.com/13716661/229177306-2d41c15a-28a6-480c-879b-5fea08b5c7ba.png)



Gesturefy itself only clears the storage when pressing the "reset" button in the settings page. So if it somehow gets deleted then it must be an external cause (perhaps Firefox itself or some cleanup software).
If your gestures seem to be lost but the settings are still available in the storage then it might be a bug in Gesturefy. In this case please upload your extension storage here.

You can copy the individual sections via right click:

![grafik](https://user-images.githubusercontent.com/13716661/229179998-39197c57-8bb5-408e-b9ea-db09caf36602.png)
