### ISSUE TITLE
Stopped working in Firefox 112.0b9 developer edition, win10

### ISSUE THREAD

**Issue by balwierz** [Robbendebiene/Gesturefy#673]
Gesturefy is enabled and listed in about:addons.
It is not possible to perform any gesture. I have not touched addons for many months. It used to work well.

The addon works under regular Firefox 111.0.1 on the same OS.

### Your System
- Operating system: Windows 10, Build 19041
- Firefox version: 112.0b9 developer edition
- Gesturefy version: 3.2.7

**Comment by Robbendebiene** [comment]
Have you tried this on a clean profile for 112.0b9?

Also a console log might help:
   - Enter `about:devtools-toolbox?type=extension&id=%7B506e023c-7f2b-40a3-8066-bc5deb40aebe%7D` in your address bar 
   - Switch to the "Console" tab in the top bar
   - Copy and paste all outputs into the issue
   
   You also may check the web console (ctrl + shift + I) on a website like https://example.com/. Open the console, reload the page and try to perform a Gesture.
