### ISSUE TITLE
Gesture still caught despite URL being excluded.

### ISSUE THREAD

**Issue by Aryetis** [Robbendebiene/Gesturefy#674]
### Describe your matter in detail

Issue happens when running the StableDiffusionWebui locally ( https://github.com/AUTOMATIC1111/stable-diffusion-webui/ ) with the 3d open pose editor extension installed ( https://github.com/nonnonstop/sd-webui-3d-open-pose-editor ). 

Nothing in the inspector indicates another website/address. Everything is local.
Despites having put `http://127.0.0.1` in the exclusion list.
The "3d OpenPose" iframe is still catching my right click and drawing stuff instead of letting me rotate the camera.

### Screenshots or further assistance
![gesturefyOpenPose](https://user-images.githubusercontent.com/4246001/230789966-b7843d5a-2cab-4dad-9706-c88928f9ae08.jpg)

### Your System
- Operating system: Win11 22H2
- Firefox version: 111.0.1
- Gesturefy version: 3.2.7

**Comment by Robbendebiene** [comment]
Exclusions require an url match pattern. Try `http://127.0.0.1:7860/*` or `http://127.0.0.1:*`

**Comment by Aryetis** [comment]
Okay thanks.
I have no explanations, I don't know how many combinations I tried but gestures used to be ignored outside of the frame but not in frame....
Now with `http://127.0.0.1:7860/*` gestures are ignored all across the page. Thanks. I'll go sit at the shameful corner.

**Comment by DARKFiB3R** [comment]
> Exclusions require an url match pattern. Try `http://127.0.0.1:7860/*` or `http://127.0.0.1:*`

Showing an example of this in the settings, like you have done here, would be really helpful.

The only time I have ever used wildcards previously, is when I learnd I could use them while searching in Windows Explorer, e.g. *.jpg

So my stupid ass has been so frustrated with this for months, thinking it just doesn't work.

All is well now :)

**Comment by Robbendebiene** [comment]
Thanks for the feedback.

Good news is that this section will be completely removed in the future.
Firefox itself will allow to exclude extensions on different domains/urls and Gesturefy will utilize this functionality to provide an easy "disable on this site" button :)

**Comment by DARKFiB3R** [comment]
Oh, sweet. Thanks for letting me know :)

And thank you for Gesturefy. It's one of those great little qulity of life improvments that you set and forget, and don't realise how much of a difference it makes untill you use a broswer without it for any length of time.
