### ISSUE TITLE
[Feature Request] Add a way to execute Shortcuts

### ISSUE THREAD

**Issue by SvenPan** [Robbendebiene/Gesturefy#676]
It would be nice to have an Option for some Gestures, that could input some keys, to open for example Firefox menus (Ctrl+Shift+O - Firefox Bookmarks).

I tried to make it work with Execute User Script, but it didnt work, sadly.

here the last version of the tried javascript code:
let e = new KeyboardEvent( "keypress", { bubbles : true, cancelable : true, key : "O", char : "O", shiftKey : true , ctrlKey : true});
window.dispatchEvent(e);

maybe if there is the possability to excute that idea as javascript, then an how to on the github page is enough(?).

**Comment by Robbendebiene** [comment]
This is prohibited because it would be a huge security risk if every extension or website could execute any arbitrary short cut.

Duplicate of #325
