### ISSUE TITLE
Custom activation button?

### ISSUE THREAD

**Issue by githubtefo** [Robbendebiene/Gesturefy#678]
Hey there - is there any way I can chose a custom activation button?
I have a logi mouse with a 4th button (BUTTON_Forward).
Thanks!

**Comment by Robbendebiene** [comment]
If you are asking for further mouse activation buttons then this is not possible as described here: https://github.com/Robbendebiene/Gesturefy/issues/628

**Comment by githubtefo** [comment]
> Single-button devices may emulate additional buttons with combinations of button and keyboard presses.
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons#firefox_notes

I could remap the forth mouse button to a keyboard action... In that case, is it possible to assign a custom activation button from the keyboard?

**Comment by Robbendebiene** [comment]
@githubtefo Currently not (see https://github.com/Robbendebiene/Gesturefy/issues/606). It has been on my list for quite a while but I never found time to implement it.
