### ISSUE TITLE
Wrong gesture deleted (data loss)

### ISSUE THREAD

**Issue by ygoe** [Robbendebiene/Gesturefy#68]
Steps to reproduce:

1. Click on the dot next to one of the actions in the settings
2. Click Cancel
3. Click on the dot of another action
4. Now click Delete

Actual behaviour:

The gesture of the first action is deleted.

Expected behaviour:

The gesture of the second action is deleted.

Version: 1.1.9 on Firefox 56, Windows 10

**Comment by Robbendebiene** [comment]
Thank you very much for this detailed explanation.
The fix (93ca20d2e428a37bda94084708a81746a4eeec08) will be available in the next version (1.1.12)

**Comment by ygoe** [comment]
Thanks, verified.
