### ISSUE TITLE
Gesture Request: Close left or right tab, not all left or right tabs

### ISSUE THREAD

**Issue by zhufeng** [Robbendebiene/Gesturefy#686]
### Describe your matter in detail

There are 2 gestures for closing all left or right tabs, but no gesture to close 1 tab left or right to current tab.

### Your System
- Operating system: win10 x64 19044.3448
- Firefox version:115.3.0 esr
- Gesturefy version:3.2.8

**Comment by Robbendebiene** [comment]
This can be achieved via [user scripts](https://github.com/Robbendebiene/Gesturefy/wiki/Execute-user-script). See: https://github.com/Robbendebiene/Gesturefy/issues/214

Note though that they currently don't work on some pages (#569)
