### ISSUE TITLE
Feature request: Disable extension on certain pages

### ISSUE THREAD

**Issue by FrankIJskes** [Robbendebiene/Gesturefy#688]
I use a local linux firefox to access a remote desktop that runs windows. On this desktop this extension is also running in firefox. 
I'd like to use gestures only on the remote deskop, not to close the local tab and loose the remote session.

A 'blacklist' feature of some sort would really help out for this, so that the 'close tab' feature does not work locally.

As i am thinking about it, it could become very complex very fast (like disable certain gestures on certain websites), so just completely disabling the extension for 'blacklisted' websites would be enough for this purpose.

**Comment by Robbendebiene** [comment]
> so just completely disabling the extension for 'blacklisted' websites would be enough for this purpose.

This is already possibles using "Exclusions" in Gesturefy's options page. You can read more about them here: https://github.com/Robbendebiene/Gesturefy/wiki/Exclusions

> As i am thinking about it, it could become very complex very fast (like disable certain gestures on certain websites), 

As you already said implementing a per command blacklist takes some effort. To me it doesn't meet the cost/benefit ratio, so I'd consider this out of scope for Gesturefy.
