### ISSUE TITLE
Open link in new tab doesn't work on https://archive.org/

### ISSUE THREAD

**Issue by MJ1979** [Robbendebiene/Gesturefy#689]
Perfect, absolutely perfect extension... 
There is only one site (https://archive.org/), where open link in new tab doesn't work (when trying to open link of a book with gesture). 

If you want to test here is a link for example  
https://archive.org/search?query=Nikola+Tesla

Just as I was preparing the link above I've noticed that your other extension (Type to search) which I've installed today also doesn't recognize search box on that site so I had to disable it.

The issues are probably due to how that site was set-up and and not due to your extensions.

Thanks again for your great contribution... It saves me time every day...
All the best...

My System
- Operating system: Windows 10
- Firefox version: 119
- Gesturefy version: 3.2.9

**Comment by Robbendebiene** [comment]
Thanks for the report. I appreciate the nice words as well :)

I was able to fix the issue. The only fear I have is that I broke some "target detection" somewhere else (other commands or websites). Would be nice if you could test it as well.

You can try it as well by downloading https://github.com/Robbendebiene/Gesturefy/archive/refs/heads/master.zip
Extract the zip and then re-zip everything inside the `src` directory.
- For a temporary installation (will be uninstalled on browser restart) go to `about:debugging#/runtime/this-firefox`, click "load temporary add-on" and choose the zip
- For a permanent installation got to `about:addons` and install it by clicking the "gear" icon

> Just as I was preparing the link above I've noticed that your other extension (Type to search) which I've installed today also doesn't recognize search box on that site so I had to disable it.

I actually don't maintain the "Type to search" extension any more. It never had a large user base and especially I stopped using it quite quickly my self so I lost interest and motivation.

**Comment by MJ1979** [comment]
Thank you for the quick solution and response...

I've tried permanent installation but FF won't allow it. I get pop-up that it's not verified extension. 
The xpinstall.signatures.required is set to false, but it seems that it does not do the trick anymore...

**Comment by MJ1979** [comment]
Ok, so I've tried the temporary installation and it works perfectly!!!

Thank you so much.... can't wait for the official release....

Thank you again and all the best...
