### ISSUE TITLE
New action for Back or close

### ISSUE THREAD

**Issue by ygoe** [Robbendebiene/Gesturefy#69]
I'm using a custom action in FireGestures to go back but if it's the first page in history, then close the tab. Here's the custom JavaScript, in case it will be any useful in Firefox 57 (still on Firefox 56, evaluating replacements for November).

```
var wm = Components.classes["@mozilla.org/appshell/window-mediator;1"]
                   .getService(Components.interfaces.nsIWindowMediator);
var enumerator = wm.getEnumerator(null);
var winCount = 0;
var myWindow;
while(enumerator.hasMoreElements()) {
  myWindow = enumerator.getNext();
  winCount++;
}

if (getBrowser().canGoBack)
    //getBrowser().goBack();
    BrowserBack();
else if (getBrowser().mTabContainer.childNodes.length == 1)
{
    if (winCount > 1)
        window.close();
    else
    {
        getBrowser().removeTab(getBrowser().selectedTab);
        setTimeout(myWindow.minimize, 10);
   }
}
else
    getBrowser().removeTab(getBrowser().selectedTab);
```

Could this action be added to the addon?

**Comment by Robbendebiene** [comment]
I have to admit, that this would be an useful option for the backwards action, but the webextension API currently does not provide a proper way to get the history of a single tab. I would have to inject a little peace of code in the tab itself which checks, if there are any further entries in the history and then (in the case of no further entries) sends a message to my addon which indicates, that the tab should be closed (because a tab can not close itself).

Because of this complications I won't implement it, but I'm looking forward to a better history API by mozilla. For more information:
https://bugzilla.mozilla.org/show_bug.cgi?id=1378651
https://bugzilla.mozilla.org/show_bug.cgi?id=1381922

**Comment by ygoe** [comment]
Thank you for the explanation. I voted for both Mozilla bugs. I guess Firefox will remain a noticeable bit less comfortable for a long while now.

**Comment by ygoe** [comment]
Is this possible now?

**Comment by Robbendebiene** [comment]
Sorry, but this is still not possible.

I plan to add some API to user scripts so you can close tabs via a user script. However even then the solution for your problem would still be a little bit hacky, since there is no proper history API provided by Firefox.

**Comment by Robbendebiene** [comment]
The best workaround so far I found is the following user script:

```
window.history.back();
setTimeout(async () => { 
	const tabs = await API.tabs.query({active: true, currentWindow: true});
    API.tabs.remove(tabs[0].id);
}, 500);
```

**Comment by Robbendebiene** [comment]
After more than 2 years there is still no hope for the Firefox API that is required to properly solve this issue. Since the workaround kind of works, I consider this issue as solved.

**Comment by norill** [comment]
> 
> 
> Sorry, but this is still not possible.
> 
> I plan to add some API to user scripts so you can close tabs via a user script. However even then the solution for your problem would still be a little bit hacky, since there is no proper history API provided by Firefox.

haven't tested it but looks like this api has the required functionality
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history

**Comment by Robbendebiene** [comment]
> haven't tested it but looks like this api has the required functionality
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history

No, this API can only retrieve the browser history and not the history of individual tabs.

**Comment by Robbendebiene** [comment]
@ygoe This is the reason for the error: https://github.com/Robbendebiene/Gesturefy/issues/569

**Comment by ygoe** [comment]
Great, I already came to that Firefox bug through a limitation of FireMonkey (and already noticed your name there). Doesn't look like Firefox is doing much for extensibility. I'm wondering what all those new versions every couple weeks are for.

**Comment by norill** [comment]
i have implemented the functionality required to make this possible, but the patch is stuck with no one to review it.
[](https://bugzilla.mozilla.org/show_bug.cgi?id=1760523)

**Comment by ygoe** [comment]
> The best workaround I found so far is the following user script:
> 
> ```
> window.history.back();
> setTimeout(async () => { 
>     const tabs = await API.tabs.query({active: true, currentWindow: true});
>     API.tabs.remove(tabs[0].id);
> }, 500);
> ```

This has the limitation that intra-page back navigations will prematurely close the tab, even though the back navigation was executed and there would be more backwards history available. So unfortunately it's not suitable for production.
