### ISSUE TITLE
Firefox Home can't be opened

### ISSUE THREAD

**Issue by AKimura** [Robbendebiene/Gesturefy#690]
Open home command doesn't work when the home page is set to default (Firefox Home) or "about:home".
Open custom url command is the same too.

I think this action is useful in general.

**Comment by Robbendebiene** [comment]
This is a known limitation. You should get an error notification that links you to [this page](https://github.com/Robbendebiene/Gesturefy/wiki/Illegal-URL).
The explanation basically is: Firefox does not allow extensions to open (most) `about:` URLs for security reasons.
