### ISSUE TITLE
Feature request - input text 

### ISSUE THREAD

**Issue by jiayir** [Robbendebiene/Gesturefy#693]
Hello there! I've been really enjoying Gesturefy and appreciate your work in making it! I was wondering if it was possible to use gestures to input custom text within a text field. It would be similar to how Gesturefy is able to paste text from the clipboard into a text field, except the text has been predefined from the Gesturefy settings pages (like how it's possible to set custom URLs to be opened) so it needn't access the clipboard. 

This could be useful for typing characters that aren't included on one's keyboard, as well as making oft-used messages easy to access. A couple of use-case examples:
- Doing a gesture that makes the integral symbol appear where I was typing, which saves me from having to go search up the integral symbol to copy-paste. (here, '∫' is the custom text)
- Doing a gesture that will input longer messages such as "Thank you, have a good day." so it doesn't need to be typed up over and over.

The most similar issue I could find is #554 , though that one is a bit more specific.
Thank you so much for your time and consideration!

**Comment by Robbendebiene** [comment]
Hi, thanks for your feature request.
I like the idea. This could also be used to map for example emoticons to gestures.

**Comment by Robbendebiene** [comment]
This has been added in [Gesturefy 3.2.11](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.11)
