### ISSUE TITLE
Not working on non-https website in Nightly

### ISSUE THREAD

**Issue by soysource651** [Robbendebiene/Gesturefy#696]
Open non-https website(http://...), then gesturefy not working.

Sample website
http://www.columbia.edu/~fdc/sample.html

### My System
- Operating system:
Windows10 Pro 22H2
- Firefox version:
Nightly 122.0a1 (2023-12-16) 
- Gesturefy version:
3.2.10

**Comment by Robbendebiene** [comment]
Thanks for the report. This is basically a follow-up of #687, so the workaround https://github.com/Robbendebiene/Gesturefy/issues/687#issuecomment-1763446818 still holds.

I'm currently investigating on how to proceed. (see https://bugzilla.mozilla.org/show_bug.cgi?id=1870498)

**Comment by Robbendebiene** [comment]
This has been fixed in the latest Firefox Nightly builds. Additionally I implemented a mitigation for this in [Gesturefy 3.2.11](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.11)
