### ISSUE TITLE
Feature request - [Popup] Only Active Tabs

### ISSUE THREAD

**Issue by justarandomnickname0** [Robbendebiene/Gesturefy#697]
Hello.

Your extension has a very convenient option - "[Popup] All Tabs".
The problem is that when several hundred tabs are open, but only ~50 of them are active, and the rest are in an discard state. In this situation, the [Popup] All Tabs displays all tabs including unloaded (discard) tabs. This makes navigation difficult, when I need to display only active tabs in the popup list.

Please add a gesture: [Popup] Only Active Tabs

Thank you in advance!

**Comment by justarandomnickname0** [comment]
Yes, that would be even better.
In the settings, where sets the tab ordering criteria.

**Comment by Robbendebiene** [comment]
This has been added in [Gesturefy 3.2.11](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.11)
