### ISSUE TITLE
Clarify why does Gesturefy need each permission for in description

### ISSUE THREAD

**Issue by stmr** [Robbendebiene/Gesturefy#7]
Hi,
it would be awesome to want this from all addon developers across AMO, but since that's not the case, please add it in description.
Thanks

**Comment by Robbendebiene** [comment]
Done :) Thanks for the good idea, let me know if you think it needs further clarification.

**Comment by stmr** [comment]
Nice, thanks for that. Will try to open an issue for the whole AMO, it would be nice to know why it does, when they made you see what it does (I know in most cases it's obvious).
Closing :)
