### ISSUE TITLE
[Linux/MacOS] Right Click Gesture Problem

### ISSUE THREAD

**Issue by imrn** [Robbendebiene/Gesturefy#70]
I'm a FireGestures/FF56 user and exploring my options for upcoming FF57.

RightClick+AnyGesture is not a problem with FireGestures but
with Gesturefy 1.1.9, I'm unable to start any gesture due to RightClick
context menu popping up. MiddleClick gestures are ok though.
FireGestures or any other thing that may interfere with right click is
disabled when trying.

Any advices?

**Comment by Robbendebiene** [comment]
I bet you are using Linux or MacOS, If so please read the addon description here: https://addons.mozilla.org/firefox/addon/gesturefy/ or this issue: https://github.com/Robbendebiene/Gesturefy/issues/1

**Comment by imrn** [comment]
Definetely. Linux.. Sorry for not mentioning.
I thought majority of people are using it as their default desktop. ;)

Anyway, "Foxy Gestures" also suffers from the same problem.
Given the Mozilla's speed for resolving issues, do you have any
estimate for a resolution?

Otherwise, this implies that FF57+/Linux-Mac can not have
RightClick gestures..

**Comment by Robbendebiene** [comment]
No problem, I'm currently typing this on a Linux system too :P
As far as I know there already exists a patch which will fix this, but the patch will not land in FF57, but maybe in 58.
Since then I'm using the middle mouse button on my linux system, because I decided against disabling the contextmenu completely or to display it on double right click.

**Comment by imrn** [comment]
On my Logitech mouse, middle click is on the scroll wheel.
So it is not ergonomic as right click. :(

My left click reserved for ScrollAnyWhere (A GrabAndDrag derivative)
for drag scrolling like pdf viewers or like tablets/phones..

**Comment by imrn** [comment]
> because I decided against disabling the contextmenu completely
> or to display it on double right click.

How can I disable right click context menu or change it to double click?
doudou

**Comment by TamasBarta** [comment]
@Robbendebiene,

> or to display it on double right click.

Can you tell me please, how achieve this, and use with right click?

**Comment by Robbendebiene** [comment]
@TamasBarta There is no setting in about:config or elsewhere that I am aware of, if you are asking for that. I would have to directly implement this behaviour in the addon.

**Comment by imrn** [comment]
Opps.. I've recognized that the issue is closed by me. It is accidental.

Reopening it. @Robbendebiene : If you think it should stay so
(because there is #1), feel free to close it again.

Otherwise, the issue can be home of "Right click" related discussions.

**Comment by Robbendebiene** [comment]
I'll close it and rename the other issue. For further discussion please use #1
