### ISSUE TITLE
[Feature Req] - Re-Order & Organization For Gestures

### ISSUE THREAD

**Issue by JamsFM** [Robbendebiene/Gesturefy#701]
The ability to drag and re-order the gestures and maybe even have tags or folders to sort them would be very advantageous, I feel.

**Comment by Robbendebiene** [comment]
> The ability to drag and re-order the gestures 

Re-ordering is something I like as well. It is tracked here: #501

> tags or folders to sort them would be very advantageous, I feel.

This however is out of scope for Gesturefy.

**Comment by Robbendebiene** [comment]
Duplicate of #501
