### ISSUE TITLE
Not work in https://www.4399.com/flash/217629_1.htm comment area

### ISSUE THREAD

**Issue by 0x391F** [Robbendebiene/Gesturefy#704]
### Screenshots or further assistance
![截图 2024-02-05 19 54 00](https://github.com/Robbendebiene/Gesturefy/assets/56181919/fc4bede3-bd60-4dce-b26a-eed4d03347b8)

### Your System
- Operating system: Windows 10 Enterprise LTSC 2021 x64 (21H2)
- Firefox version: 122.0
- Gesturefy version: 3.2.11

**Comment by 0x391F** [comment]
If you make gesture in this area, some gestures doesn't work, for example, scroll to top/bottom.

**Comment by Robbendebiene** [comment]
Thanks for the report. I'll look into it. Maybe I can fix that.

**Comment by Robbendebiene** [comment]
Fixed in Gesturefy [3.2.12](https://github.com/Robbendebiene/Gesturefy/releases)
