### ISSUE TITLE
How to not show right click menu when doing mouse gestures

### ISSUE THREAD

**Issue by tintinmod** [Robbendebiene/Gesturefy#705]
### Describe your matter in detail
How to not show the right click menu when doing a mouse gesture?

### Screenshots or further assistance
N/A

### Your System
- Operating system: Windows 11
- Firefox version: 11.9.0 64-bit (Floorp browser)
- Gesturefy version: 3.2.11

**Comment by Robbendebiene** [comment]
Please follow: https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture

**Comment by tintinmod** [comment]
> Please follow: https://github.com/Robbendebiene/Gesturefy/wiki/Troubleshooting#the-context-menu-opens-after-performing-a-gesture

Thanks for getting back to me.

I did, unfortunately it did not work. `dom.event.contextmenu.enabled` and `ui.context_menus.after_mouseup` are both set to **true** and the context menu still opens when doing mouse gestures.

**Comment by Robbendebiene** [comment]
Then it is most likely caused by some sort of setting from the Floorp browser. Is your context menu suppressed on e.g. https://www.google.com/maps when you right click the map?

**Comment by tintinmod** [comment]
> Then it is most likely caused by some sort of setting from the Floorp browser. Is your context menu suppressed on e.g. https://www.google.com/maps when you right click the map?

You're right... the culprit was actually a userscript I have running on Violentmonkey: it's a userscript that allows the user to be able to right-click on web pages that have this option disabled for visitors. 

I turned off that userscript and Gesturefy works as intended now (no right-click context menu when doing mouse gestures). Thanks, and cheers.

**Comment by Robbendebiene** [comment]
Thanks for the update. Glad you could sort it out.
