### ISSUE TITLE
Add support for "Run on sites with restrictions"

### ISSUE THREAD

**Issue by powerman** [Robbendebiene/Gesturefy#709]
Looks like there is new option available for add-ons: Run on sites with restrictions.
Also it looks like add-on should do something to support it (not all my add-ons currently show this toggle in their preferences).
My guess is this option may be a "right" solution for old issues like #449 without using hack (if it still works today) mentioned at https://github.com/Robbendebiene/Gesturefy/issues/6#issuecomment-340184507.
Details: https://support.mozilla.org/en-US/kb/quarantined-domains

**Comment by Robbendebiene** [comment]
Thanks for the info. These are great news!

However as far as I can tell there is nothing to do on the extension site. Users can now allow extensions to run on quarantined domains, while add-ons recommended by Mozilla seem to get the permission by default and they even hide the option to turn it off. Since Gesturefy is a recommended extension it should work out of the box (and it does so for me 🙂)

**Comment by powerman** [comment]
> Since Gesturefy is a recommended extension it should work out of the box (and it does so for me 🙂)

Hmm. Not for me. Neither on https://addons.mozilla.org/ nor on about:addons latest Gesturefy (3.2.11) does not work for me. Any chance I need to enable some optional permissions to make it work?
![изображение](https://github.com/Robbendebiene/Gesturefy/assets/1354301/aa6549f0-c2bd-4483-a046-907cb3a6b97f)

**Comment by powerman** [comment]
Or maybe you've applied forementioned hack long time ago and that's why it works for you? :wink:

**Comment by Robbendebiene** [comment]
> Or maybe you've applied forementioned hack long time ago and that's why it works for you? 😉

You are right. The mozilla pages are not part of the quarantined domains list. (see about:config `extensions.quarantinedDomains.list`)

At least it is true that recommended extensions can access them by default: https://bugzilla.mozilla.org/show_bug.cgi?id=1833209 but this doesn't solve the original problem.

**Comment by powerman** [comment]
Yeah. I've tested some other add-on - enabling this option does not make it work on mozilla pages. :disappointed:
I'm still not sure is it good idea to use hack with `privacy.resistFingerprinting.block_mozAddonManager`, but looks like there are no other solutions for now.
