### ISSUE TITLE
Feature request: Add unload tab command

### ISSUE THREAD

**Issue by uugaabuugaa** [Robbendebiene/Gesturefy#710]
Add an option to unload current tab. Like how auto tab discard or sidebery's unload works for current tab. It freezes current tab and goes to previous active tab. Could be implemented for unloading all other tabs beside current one as well.

**Comment by Robbendebiene** [comment]
I consider this as a technical and also specific feature. This combination makes me reluctant to add a command for it.
While there are technical commands in Gesturefy, they are more general in function.

What would be the use case other than "saving memory"?

**Comment by No2515** [comment]
> > What would be the use case other than "saving memory"?
> 
> I'd say that is probably the only use case. I am one of those who don't close tabs. So when I'm done with a tree of tabs and move on to next thing I'm doing I unload previous ones using sidebery's feature. While it's useful in case of a lot of tabs, if I only have one or two open using a gesture would be more efficient. And since Floorp's web panel has "unload this panel" option I thought it was a baked in feature for Floorp and not for web panels only. After a look I found that it's not available for regular tabs so I agree with the fact that it'd take more effort to make it work so I guess this feature request can be ignored. On that note, is it possible to add Floorp's split view functions as gestures? Asking since there's a section in command bar for Floorp specific features.

I second Unload tab and Split View!
Saving memory is essential when multitasking. Speed increases workflow. Being able to control speed manages and increases productivity for desired tasks.

**Comment by Robbendebiene** [comment]
> On that note, is it possible to add Floorp's split view functions as gestures?

Short answer is no. Apart from the technical problem that there most likely is no API for Floorp's split view that Gesturefy could use, Gesturefy is also mainly build for Firefox and I don't really have a plan to change this, sorry for that.

> Asking since there's a section in command bar for Floorp specific features.

What do you mean by that? Gesturefy has no Floorp specific commands.

> It freezes current tab and goes to previous active tab. Could be implemented for unloading all other tabs beside current one as well.

I don't think a gesture for unloading a single tab is really useful nor does this "switch to last tab" sound very predictable to me. I'm still thinking about "unload all other tabs" though. However the browser does this behind the back anyway based on certain heuristics and for people who are very eager to save memory a separate add-on that constantly unloads all other tabs or tabs not visited after x minutes might be the better choice after all.

**Comment by uugaabuugaa** [comment]
> What do you mean by that? Gesturefy has no Floorp specific commands.

Isn't this from Gesturefy's end?
![tempsnip](https://github.com/Robbendebiene/Gesturefy/assets/70348189/dddab485-63e4-4a62-afbc-6c5140a6e559)

> I don't think a gesture for unloading a single tab is really useful nor does this "switch to last tab" sound very predictable to me. I'm still thinking about "unload all other tabs" though. However the browser does this behind the back anyway based on certain heuristics and for people who are very eager to save memory a separate add-on that constantly unloads all other tabs or tabs not visited after x minutes might be the better choice after all.

It's understandable to not implement unloading tabs since you're right about other ways to make it happen. It's just that a gesture to do it would've been nice is all. But I can live without it so it's not a big deal.

> Apart from the technical problem that there most likely is no API for Floorp's split view that Gesturefy could use

Floorp being open sourced I thought the API would be available. But I saw in reddit how the developer is sad that his works are being taken by a few other projects without contributions in code or financially so I guess it's understandable to not reveal a few tweaks like these.

**Comment by Robbendebiene** [comment]
> Isn't this from Gesturefy's end?

Wow, that is interesting. Apparently Floorp developers inject some custom code into Gesturefy in order to add these commands as additional functionality. I had no idea about that, so sorry for the confusion.

See:
- https://github.com/Floorp-Projects/Floorp/pull/165
- https://github.com/Floorp-Projects/Floorp/pull/219

So for Floor specific functionality you could open an issue in their project.

> It's understandable to not implement unloading tabs since you're right about other ways to make it happen. It's just that a gesture to do it would've been nice is all. But I can live without it so it's not a big deal.

I really appreciate your understanding.

**Comment by uugaabuugaa** [comment]
> Wow, that is interesting. Apparently Floorp developers inject some custom code into Gesturefy in order to add these commands as additional functionality.

Okay, so now it all makes sense. First time I thought why would an extension have specific commands regarding a specific fork of Firefox but took it for granted since coming from Vivaldi I really got used to gestures and Gesturefy was just the thing I needed even though Firefox's limitation sometimes bugs me on a few pages. 

> So for Floor specific functionality you could open an issue in their project.

Yes I'll do that. And thank you for your communication and your addon. Keep up the good work.
