### ISSUE TITLE
[Feature request] - Add more than one command to a gesture

### ISSUE THREAD

**Issue by Sopor** [Robbendebiene/Gesturefy#711]
I would like to combine two commands on the same gesture to avoid doing two gestures after each other.

Is that something that is possible to add?

**Comment by Robbendebiene** [comment]
Are you looking for

1. https://github.com/Robbendebiene/Gesturefy/wiki/Multi-purpose-command (execute **one of** multiple commands)
2. or rather https://github.com/Robbendebiene/Gesturefy/issues/632 (execute multiple commands **together**)

**Comment by Sopor** [comment]
I must have been blind or very tired. 🥱

I was looking for `Multi-purpose-command` and couldn't find anything, but i should have looked better because this was quite obvious that this feature was already implemented.

Sorry to bother you!
