### ISSUE TITLE
No gestures recognised on this page

### ISSUE THREAD

**Issue by ygoe** [Robbendebiene/Gesturefy#713]
### Describe your matter in detail
Open this page and try to use any gesture:
https://linux-audit.com/upgrading-external-packages-with-unattended-upgrade/

No line will be drawn and nothing happens. As if the add-on was not installed.

### Screenshots or further assistance
Nothing, really

### Your System
- Operating system: Windows 11
- Firefox version: 125.0.1
- Gesturefy version: 3.2.12

**Comment by Robbendebiene** [comment]
Thanks for the report. This seems to be a Firefox bug as even their screenshot tool doesn't work there.
I'll further investigate.

**Comment by Robbendebiene** [comment]
Unfortunately this is caused by the pages Content-Security-Policy that Firefox doesn't handle correctly.

Duplicated of #258
