### ISSUE TITLE
Option to not complete a partial gesture

### ISSUE THREAD

**Issue by RheingoldRiver** [Robbendebiene/Gesturefy#717]
### Describe your matter in detail
1. Create a gesture that is left-down-left-down
2. Don't have any gesture that is left-down or left-down-left
3. Draw left-down

What I want: Nothing happens (or a preference to set it so that nothing happens)
Current behavior: The left-down-left-down gesture happens

### Your System
- Operating system: Windows 10
- Firefox version: 123.0.1
- Gesturefy version: 3.2.12

**Comment by RheingoldRiver** [comment]
> As a "workaround" you can always cancel a started gesture by clicking the left mouse button.

The problem isn't related to intentionally cancelling gestures, it's if I make a mistake haha, for example my destructive actions tend to be longer gestures (such as 'close all tabs to the left') but recently I added a new gesture for "go to previously-visited tab" and I keep forgetting what it is and instead drawing the first part of "close all tabs to the left" which then autocompletes to the full close-tabs gesture and I accidentally lose 20 tabs.

Would it be possible to artificially bind every sub-gesture of an existing gesture that doesn't exist on its own to no-op? (when this preference is enabled)

so e.g. if "left" is "go back" and "left-down" doesn't exist and "left-down-left" doesn't exist and "left-down-left-down" is "close all tabs to the left" then Gesturefy in the background binds "left-down" and "left-down-left" as no-op

I don't mind if this affects the "current gesture" display, and it says "no-op" any time a gesture is incomplete.

**Comment by Robbendebiene** [comment]
>  autocompletes to the full close-tabs gesture and I accidentally lose 20 tabs.

Just to be clear, Gesturefy doesn't have any mechanic for auto-completion. It always selects the best matching gesture that falls into the deviation tolerance. That is why I suggested playing around with it.

> Would it be possible to artificially bind every sub-gesture of an existing gesture that doesn't exist on its own to no-op? (when this preference is enabled)

This is something you can do by creating these no-op gestures yourself (e.g. by assigning an empty "multi purpose command"). In your case a "left-down-left" gesture that does nothing would probably already circumvent your problem.

There are many difficulties with doing this automatically. First and foremost, how to detect these "in between" gestures? Sure in your example it sounds easy but what about more complex gestures like a circle. Should I assign a noop to every quarter, one eighth or one sixteenth of a circle? There are way more complex gestures than a circle like letters and symbols.
If imagine Gesturefy creating a portion of these in between gestures for all your gestures itself then the outcome would be almost identical to simply reducing the deviation tolerance.

**Comment by RheingoldRiver** [comment]
> Just to be clear, Gesturefy doesn't have any mechanic for auto-completion. It always selects the best matching gesture that falls into the deviation tolerance. That is why I suggested playing around with it.

I am using shape-independent matching algorithm which iirc was the old one, is it true in that one? I had a lot of trouble with the old one.

> This is something you can do by creating these no-op gestures yourself (e.g. by assigning an empty "multi purpose command"). In your case a "left-down-left" gesture that does nothing would probably already circumvent your problem.

Aha, yes this could work! I'll try it out, thank you!

**Comment by Robbendebiene** [comment]
> I am using shape-independent matching algorithm which iirc was the old one, is it true in that one? I had a lot of trouble with the new one when it launched.

What I mean by "old one" is the time when gestures could only be composed of one of the 4 directions: up, right, down, left.
The matching algorithms of the new system were both introduced at roughly the same time, though the "strict" algorithm was the first one.

> Aha, yes this could work! I'll try it out, thank you!

Hope it solves your problem.
