### ISSUE TITLE
When the zoom level is less than 100% then the gesture is displayed only in the top left part of the browser window

### ISSUE THREAD

**Issue by toaster95** [Robbendebiene/Gesturefy#718]
### Details
affected websites: cherry24.ru

### Screenshots
here I tried to draw a spiral:

![image](https://github.com/Robbendebiene/Gesturefy/assets/2337689/beb031bf-93f8-4b3a-b5f7-daa8a5a266b0)

### My system
- Operating system: Windows 7
- Firefox version: 102.0 (64-bit)
- Gesturefy version: 3.2.12

**Comment by Robbendebiene** [comment]
Thanks for the detailed report.

However I cannot reproduce your problem. I even tried it on Firefox 102 but it works as expected for me (see screenshot)

Do you have other add-ons that could interfere here?

![image](https://github.com/Robbendebiene/Gesturefy/assets/13716661/807492a8-c737-49db-af98-d461ea0c978c)
