### ISSUE TITLE
Needs "save image as" gesture.

### ISSUE THREAD

**Issue by jm0nster** [Robbendebiene/Gesturefy#72]
I was a bit disappointed not to find this gesture in the list. You seem to be the only one on the ball with a gesture add-on currently, so I switched to yours. I understand if it's not possible due to the constant changes occurring to firefox, but I'm too lazy to do any research to find out. All that aside, great job on this app.

**Comment by jm0nster** [comment]
Also a "stop loading" gesture :)

**Comment by Robbendebiene** [comment]
I totally agree and I wanted to implement this for a while, but due to the lack of [this API](https://bugzilla.mozilla.org/show_bug.cgi?id=1245652), I cannot ensure that every image file will get it's correct file name.

Btw: stop loading gesture will be available in the next version [(more info)](https://github.com/Robbendebiene/Gesturefy/issues/63)

**Comment by nachoparker** [comment]
also looking forward to this

**Comment by terryinflorida** [comment]
Please, not only save image but also view image... I had it on another addon that is no longer being offered for the new firefox and feel handicapped without it. 

Any chance of a custom gesture, that we can add the gesture ourselves?

Thank you for this addon, it is helpful and has some gestures that the other didn't.

**Comment by Robbendebiene** [comment]
@terryinflorida Can you explain what you mean by "view image"? There is a gesture called "image to tab" or do you want to open the downloaded image with your OS specific image viewer?

> Any chance of a custom gesture, that we can add the gesture ourselves?

See here: #58

**Comment by shinji2009** [comment]
+1
save image to default download folder without asking anything. will be excelent

**Comment by timosteffens** [comment]
I too had FireGestures; using a gesture to silently save images to my default folder without asking.
I always dreamed of the possibility to save images to different folders with different gestures. (Sorting them easier while saving)
If you implement a 'just silently save image to' function, can you please make it so one can define an individual folder per gesture?

**Comment by biomatter** [comment]
Another FireGestures refugee reporting in - thanks a bundle for making this plug-in. It's a shame the new Firefox API is so limiting, though. I also really want a "save image..." gesture if it's at all possible.

**Comment by Robbendebiene** [comment]
I'm currently working on this and it's nearly done. You can expect an update during the next week. :)

**Comment by hyagli** [comment]
> Can you explain what you mean by "view image"?
He means the action in the context menu. It opens the image in the current tab.
I also need that feature.

**Comment by Robbendebiene** [comment]
> He means the action in the context menu. It opens the image in the current tab.
> I also need that feature.

This is already implemented and called "Image to Tab"

**Comment by hyagli** [comment]
"Image to Tab" opens the image in a new tab. I want it to open it in the current active tab.

**Comment by hyagli** [comment]
I made a pull request containing this feature :)

**Comment by terryinflorida** [comment]
hyagli,
You are exactly right, thank you...

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/94de6b8f863006ea53231c31fed272ae4e630050
However be aware that sometimes the file extension cannot be detected and is therefore missing. (chrome supports an api to solve this, which firefox currently does not support)
