### ISSUE TITLE
Feature Request: expose tabs.duplicate and tabs.goBack

### ISSUE THREAD

**Issue by visua0** [Robbendebiene/Gesturefy#720]
I'm trying to migrate from Foxy Gestures to Gesturefy because I encountered a page where Gesturefy works better, but I can't replicate one script I was using.
In Foxy Gestures we have [full access to `browser` through `executeInBackground()`](https://github.com/marklieberman/foxygestures/wiki/User-Scripts). Of course I'm not asking for all that, I just require `tabs.duplicate` and `tabs.goBack` for a niche script I made to essentially open the previous page in a new tab.

The resulting script would look something like this:
```js
API.tabs.query({active: true, currentWindow: true}).then(tabs => {
    API.tabs.duplicate(tabs[0].id).then(dupe => {
        API.tabs.goBack(dupe.id);
    });
});
```

**Comment by Robbendebiene** [comment]
Implemented in [Gesturefy version 3.2.13](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.13)
