### ISSUE TITLE
[Feature Request] Move Tab Right/Left ONCE

### ISSUE THREAD

**Issue by snoodude** [Robbendebiene/Gesturefy#721]
Hi there! I have a humble request for a low-priority and hopefully easily-implemented feature.
I would like to replicate the functionality of Ctrl + Shift + PageUp/PageDn; to move a tab right or left just a single time.
(I'm hoping that this would be relatively trivial to implement, considering the existence of Move Tab To Start/End.)
I used to be able to do this in IIRC FireGestures, but that was ages ago, and I've missed the ability to assign a gesture to it.

Not that I suspect it's terribly relevant in this case, but:
Windows 11
FireFox 128 (current)
Gesturefy 3.2.12 (current)

Edit: thank you so much! <3

**Comment by Robbendebiene** [comment]
Hi thanks for the kind and detailed feature request.
I'm surprised nobody requested this before to be honest 🙂
I'll implement it soon.

**Comment by Robbendebiene** [comment]
Implemented in [Gesturefy version 3.2.13](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.13)
