### ISSUE TITLE
Remove icon is too small

### ISSUE THREAD

**Issue by madprops** [Robbendebiene/Gesturefy#723]
![gesture](https://github.com/user-attachments/assets/7af92e09-1989-4bb0-84e8-0bf837240466)

When removing some gestures I noticed it was hard for me to calculate exactly on that small target area.

Maybe the button can be bigger? Or presented in some other way.

**Comment by Robbendebiene** [comment]
I agree that the button is not ideal. For now I will just double the size.
In the future I may move it into the popup of the gesture.

**Comment by Robbendebiene** [comment]
Implemented in [Gesturefy version 3.2.13](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.2.13)
