### ISSUE TITLE
Feature: Import/Export gesture settings

### ISSUE THREAD

**Issue by peterklingelhofer** [Robbendebiene/Gesturefy#725]
### Describe your matter in detail

It would be great to be able to export and import user settings and custom gestures. I'm happy to work this if you point me to the files that would probably need to be exported to get at least all of the gestures, could get up a PR fairly quickly probably.

**Comment by Robbendebiene** [comment]
This is already implemented. It is only placed at an unobvious spot.
If you visit the "About" section in the settings page you will find the options to "backup" and "restore" your config. 😃

In the [future](https://github.com/Robbendebiene/Gesturefy/pull/715) this will get its own section.

**Comment by peterklingelhofer** [comment]
My apologies, I missed that. Thank you so much, for both your quick response and your amazing work on this project. Closing this. :)
