### ISSUE TITLE
cannot select some checkbox when rocker gesture or wheel gesture is enabled

### ISSUE THREAD

**Issue by kkot** [Robbendebiene/Gesturefy#73]
I experience problem on some websites that I cannot select checkbox when rocker gesture or wheel gesture is enabled.

1. Go to https://www.otodom.pl/sprzedaz/mieszkanie/warszawa
2. Click"Więcej opcji" and try to select checkbox. (sorry for Polish website but this is second one I experienced it, first one is badoo but requires login).
3. Disable both options - then it works.

![obraz](https://user-images.githubusercontent.com/1009806/31628663-ae5cf2e6-b2b1-11e7-9614-ad1e0bbe5f38.png)

Regular checkboxes are working for example:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

BTW. I love this addon great work.

**Comment by Robbendebiene** [comment]
Thanks for the detailed bug report! Are you using the latest version of Gesturefy? (Version 1.1.11 It's only available for Firefox 57) Because the bug may be already fixed there.

**Comment by kkot** [comment]
@Robbendebiene Yes, I'm using 1.1.11 and Firefox 57. I forgot to mention it.

**Comment by bnscv** [comment]
Just noticed the same problem on GOG promo pages, like:

https://www.gog.com/promo/20171016_special_sale_witcher_series

Also using Firefox 57b9 and Gesturefy 1.1.11.

**Comment by Robbendebiene** [comment]
This bug has driven me crazy, but it should be fixed in the next version.

**Comment by bnscv** [comment]
Nice, thanks man!
Your extension is great btw.
