### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by BananenRitter** [Robbendebiene/Gesturefy#730]
1. The Gestures should not be activated when i try to select text
2. Option to only activate the gestures when
- i press LMB+RMB at the same time
- OR Hold any key + LMB/RMB/MMB or a combination of 2 of those 3
- OR Just hold any key + drag mouse

**Comment by Robbendebiene** [comment]
Thanks for the ideas.

> The Gestures should not be activated when i try to select text

This has been requested before, see: #540

Every other suggestion already has an open issue, so please add any additional insights or ideas there:

> i press LMB+RMB at the same time

See: #714

> OR Hold any key + LMB/RMB/MMB or a combination of 2 of those 3

See: #682

> OR Just hold any key + drag mouse

See: #274

I'm closing this as a duplicate.
