### ISSUE TITLE
[Bug] Line/Tooltip are not displayed on some sites

### ISSUE THREAD

**Issue by Trixlight** [Robbendebiene/Gesturefy#731]
### Describe your matter in detail

I looked at the issue tracker and didn't find any similar reports.

1. Open [reddit.com](url)
2. Try invoking the gesture, it will work, but the line/tooltip will not be visible

Same issue with my old Firefox Nigtly 103.0a1.

### Screenshots or further assistance

https://github.com/user-attachments/assets/712bcfc9-e3a4-4b28-a634-d8e94c270f02

### Your System
- Operating system: Windows 11 23H2 (22631.4169)
- Firefox version: 128.3.1esr
- Gesturefy version: 3.2.13

**Comment by Robbendebiene** [comment]
Ahhh good catch!

Showing UI with extensions has always been a challenge as developers have to inject the UI into the website's code.
The `!important` statement is used to prevent the website's CSS from overriding any sort of styles on Gesturefy UI elements. So removing it would most likely cause more issues than it solves.

**Comment by Robbendebiene** [comment]
Closing this as there is not much I can do.
