### ISSUE TITLE
Gesturefy settings have be reset to default

### ISSUE THREAD

**Issue by redactedscribe** [Robbendebiene/Gesturefy#733]
### Describe your matter in detail

Not sure what happened, I don't customise Gesturefy ever. It's been working as I like it to work for years, but today I noticed that all of its settings have been presumably reset to default. I don't see my gestures listed and the font of the overlay is completely different now. I do have an old backup of my settings but it's probably slightly outdated.

### Screenshots or further assistance

![firefox_2024-11-25_00-33-35](https://github.com/user-attachments/assets/739be470-3eca-4c6b-815c-09dcaa7e0265)

### Your System
- Operating system: Windows 11 Pro
- Firefox version: 132.0.2
- Gesturefy version: 3.2.13

**Comment by Robbendebiene** [comment]
Sorry, I missed the issue.
Usually there is not much I can do as multiple external programs including Firefox itself can delete extension config data.
Glad you were at least able to restore some settings.
