### ISSUE TITLE
FR: support open in Zen browser glance view

### ISSUE THREAD

**Issue by xtmu** [Robbendebiene/Gesturefy#734]
### Describe your matter in detail
Ctrl click to start a temporary tab which float on current tab. Please add command in Guestify so we can open in glance view without pressing any key.

### Screenshots or further assistance
![image](https://github.com/user-attachments/assets/dd20833a-a44b-46f2-a6e8-b704aa5a0029)
![image](https://github.com/user-attachments/assets/b405feda-7cbe-492e-a636-a2655e2c944f)

### Your System
- Operating system: Win10
- Firefox version: Zen 1.0.1-a.19 (Firefox 132.0.1) (64-bit)
- Gesturefy version: 3.2.13

**Comment by xtmu** [comment]
and  command "split link in new tab" 

![image](https://github.com/user-attachments/assets/c0c71286-e25f-4a1c-aa52-2bd23b3de24d)

**Comment by Robbendebiene** [comment]
Thanks for the feature request.
Your request is about Zen browser specific functionalities which are not available to extensions.
Therefore Gesturefy cannot make use of them. Re-implementing them would be a lot of work and wouldn't be as good as the original functionalities (especially for "split link in new tab").

**Comment by xtmu** [comment]
Thanks for replying, hope these functionalities get introduced by Firefox someday so extensions may access them.

**Comment by Robbendebiene** [comment]
When the day has come we can certainly bring these features to Gesturefy.
Till then I'm closing this. Feel free to comment/reopen on any updates.
