### ISSUE TITLE
Search selected text bug

### ISSUE THREAD

**Issue by happysurf** [Robbendebiene/Gesturefy#74]
Steps to reproduce
    Visit this page:
    http://www.hwupgrade.it/forum/showpost.php?p=45109056&postcount=5198
    Select the **#171b1f** text and perform the gesture for search the element in Google;
    
Actual behaviour:

   The gesture redirect on Google main page only;

Expected behaviour:

   The gesture must redirect on Google color info page.

Version: 1.1.11 on Firefox 57beta9, Windows 10.

**Comment by Robbendebiene** [comment]
Thanks for the report.
It's fixed now and will be available in the next version.

A little bit off-topic: I guess you are from italy? Maybe you want to translate Gesturefy? It's now fairly simple with [Crowdin](https://crowdin.com/project/gesturefy) :)

**Comment by happysurf** [comment]
Thank you for fix.

> A little bit off-topic: I guess you are from italy? Maybe you want to translate Gesturefy? It's now fairly simple with Crowdin :)

Yes I'm Italian and I'm interested to do the translation.
I'm starting ASAP.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/efcb893b47d1e71d377886fef7215fa6313f85c7
