### ISSUE TITLE
Adapt non english font and increase the size of the menubar

### ISSUE THREAD

**Issue by Cepr0** [Robbendebiene/Gesturefy#78]
Please adapt non english font and increase the size of the menubar (see the image):

![2017-10-23_23-35-52](https://user-images.githubusercontent.com/10778600/31912093-80eb108c-b84b-11e7-8603-225e0f263aad.png)

**Comment by Robbendebiene** [comment]
What do you mean width "adapt non english font"? I added a comment on Crowdin if you want to achieve a line break.

**Comment by Cepr0** [comment]
You can see that the rendering of non-english font is different from english one. Maybe it makes sense to change the font to standard one, for example Arial...

And please increase a little the width of the menu bar to avoid word wrapping. Adding second line does not help - it's one word.

**Comment by Robbendebiene** [comment]
You can break your word like this:
```
на-
строй-
ки
```
just write: `на&shy;строй&shy;ки`

**Comment by Cepr0** [comment]
This is not possible. ))
Could you replace, for example, 'Settings' or 'Configuration' to 
```
Set-
tings

Con-
figura-
tion
```
? ))

In different languages the words have different width. For example 'Settings' in English and 'Einstellungen' in German. So I think your menu bar must be adaptive. And  changes its width accordingly to the wider element of the menu.

**Comment by Robbendebiene** [comment]
I feel like we talk past each other.
Just for clarification: I will not change the width of the navigation bar according to the words length, because you can add hyphens as I described by adding the `&shy;` character.

Maybe this little codesnippet will help you understand how it works.
https://codepen.io/anon/pen/MEMKYL

**Comment by Cepr0** [comment]
I will not add hyphens because it looks ugly. 
And word wrapping looks also ugly. 
So if you do not care about the look of your addon, then let everything remain as it is...

**Comment by Robbendebiene** [comment]
> So if you do not care about the look of your addon, then let everything remain as it is...

The reason why I won't expand the navigation bar is, because I do care about it.

**Comment by Itchiii** [comment]
@Cepr0 
In Russian it would be good. But it can also be ugly, if you don't use hyphens. For example in Portuguese (image). There is too much free space around the other menu items. In some other languages, it can be much bigger...
But yeah.. it is a matter of taste.

![unbenannt](https://user-images.githubusercontent.com/15103402/31950379-c09443da-b8db-11e7-9881-3ecedaba4b71.PNG)
