### ISSUE TITLE
Open in background tab doesn't work in firefox < 57.

### ISSUE THREAD

**Issue by biocomp** [Robbendebiene/Gesturefy#80]
The action just doesn't do anything. I set up gesture to just dragging down, and it works neatly in 57, but does nothing in earlier versions. The gesture is visible, and is correctly recognized, but new tab doesn't open.

Open in foreground tab works.

**Comment by biocomp** [comment]
Debugged just a tiny little bit (don't know JS or how to debug extensions).

Looks like in `LinkToBackgroundTab`, `chrome.tabs.query` fails with `Error: Type error for parameter queryInfo (Unexpected property "openerTabId") for tabs.query.`

**Comment by Robbendebiene** [comment]
I guess you are using the current release 1.1.12 which is marked for firefox 57 and higher only, because older ff version do not support some necessary api (like openerTabId).

**Comment by biocomp** [comment]
I have v 1.1.11 installed on that FF. Also, I'd hope 1.1.12 won't even install there if it's marked as incompatible :)

**Comment by Robbendebiene** [comment]
1.1.11 is also marked as incompatible (at least it should be) use https://addons.mozilla.org/de/firefox/addon/gesturefy/versions/?page=1#version-1.1.9 (as statet in the addon description)
