### ISSUE TITLE
Option to not close pinned tabs

### ISSUE THREAD

**Issue by treuherz** [Robbendebiene/Gesturefy#81]
It would be extremely helpful to have an option on the Remove Tab action to not close the tab if it is pinned.

Currently, closing several tabs in succession with the gesture can lead to accidentally closing a pinnde tab, which is designed to stay open unless explicitly removed. For the same reason they do not have easily-available close buttons as part of the UI, it would be nice to prevent them from being carelessly closed with a gesture.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/94de6b8f863006ea53231c31fed272ae4e630050
