### ISSUE TITLE
Can't open Settings on Firefox 57

### ISSUE THREAD

**Issue by aold619** [Robbendebiene/Gesturefy#83]
Firefox 无法在 moz-extension://5d98203d-a530-4e89-83ab-6ddf9b49bb08/ui/html/options.html 找到该文件。
Firefox can' find file moz-extension://5d98203d-a530-4e89-83ab-6ddf9b49bb08/ui/html/options.html

Still not work after I reinstall plugin.

**Comment by uegajde** [comment]
the ui folder is missing for the version 1.1.13 on AMO
there might be something wrong when submit to AMO?

before the fixed version submitted, you can install v1.1.12 and turn off the auto-update
https://addons.mozilla.org/zh-TW/firefox/addon/gesturefy/versions/

**Comment by aold619** [comment]
thank you for the solution `(*∩_∩*)′
Shawn Hu via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dw&cv=9.8.229&pv=10.0&source=email_footer_2]
On Tue, Nov 14, 2017 at 2:12pm, Zhe-Hui Lin < notifications@github.com [notifications@github.com] > wrote:the ui folder is missing for the version 1.1.13 on AMO
there might be something wrong when submit to AMO?

before the fixed version submitted, you can install v1.1.12 and turn off the auto-update
https://addons.mozilla.org/zh-TW/firefox/addon/gesturefy/versions/ [https://addons.mozilla.org/zh-TW/firefox/addon/gesturefy/versions/]

**Comment by happysurf** [comment]
Yes, same problem too.

**Comment by Robbendebiene** [comment]
Thanks for the report. @uegajde is right, I have no idea how this could happen.. 
Anyway I "fixed" it. Sorry for that.
