### ISSUE TITLE
It not work on FireFox 57.0 

### ISSUE THREAD

**Issue by zsmj1994** [Robbendebiene/Gesturefy#88]
after update my firefox ,it become invalid

**Comment by jdreesen** [comment]
Works for me.

**Comment by zsmj1994** [comment]
... not work on mac,don't know why

**Comment by Itchiii** [comment]
This is a known bug. #1 
Read the discription on mozilla or on GitHub. 

> For MacOS & Linux users: The contextmenu is not suppressed on right-click ([see this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1360278))
