### ISSUE TITLE
Search selected text give a choice from user' search engines

### ISSUE THREAD

**Issue by mtychyna** [Robbendebiene/Gesturefy#89]
Firefox gives possibility add search engines directly from sites. It help to start search on exact site (catalog, news etc.), or simple search word in Google Translate (for example).

It would be great after gesture "Search selected text" to show small window with a choice of search engines, that added user has. After selected of engines it will open search result in new tab.

**Comment by Robbendebiene** [comment]
I guess you mean something similar to this one: https://addons.mozilla.org/en-US/firefox/addon/context-search-we/.
But due to high amount of affort it would take, I will not implement it.
In my opinion the addon I posted above, serves a better solution anyway.

**Comment by bubblefoil** [comment]
Too bad, it would be so much more convenient, I used this feature a lot. I had a similar gesture for google search.
Anyway thanks for the tip, it will have to do.

**Comment by Robbendebiene** [comment]
Thank you for your comprehension!
I'll use this [issue](https://github.com/Robbendebiene/Gesturefy/issues/99) to keep track of the feature.
