### ISSUE TITLE
Rocker gestures

### ISSUE THREAD

**Issue by stmr** [Robbendebiene/Gesturefy#9]
Hi, a feature request for distant future - rocker gestures.
Expected behaviour: possibility to set actions for mouse presses, for example when holding left mouse button pressed and pressing right button, switch to next tab, etc.

**Comment by Robbendebiene** [comment]
Done: https://github.com/Robbendebiene/Gesturefy/commit/0d6651ace66e79d9c3789e90163e12ae25a15d0c

**Comment by stmr** [comment]
You're incredibly amazing
