### ISSUE TITLE
Link to foreground/background tab doesn't comunicate with map/area html tags

### ISSUE THREAD

**Issue by mtychyna** [Robbendebiene/Gesturefy#90]
Lots of catalogs work now with map and area html tags above img tag on their online catalogs. Gestures Link to foreground tab and Link to background tab unable to open links on such photos. [Link ](http://www.next.ua/ru/men/new-in/tailoring-smart-looks/1)where its possible to test.

**Comment by Robbendebiene** [comment]
Thanks, I will look into it.
