### ISSUE TITLE
feature request: rocker gestures to display list of open/recently closed tabs

### ISSUE THREAD

**Issue by nachoparker** [Robbendebiene/Gesturefy#91]
hi, thanks for your fantastic job, the addon looks fantastic and it's pretty close to fire gestures!

I am missing some small things only. If possible, I would like to add to the wishlist the ability to rock gesture and open a menu-list of the current open tabs, and another one to menu-list recently closed tabs. It was very nice to move around if you have many tabs open.

You used to be able to do that in FG

**Comment by Robbendebiene** [comment]
> hi, thanks for your fantastic job, the addon looks fantastic and it's pretty close to fire gestures!

Thank you, nice to hear that after a lot of negative reviews.

> open a menu-list of the current open tabs, and another one to menu-list recently closed tabs. 

This sounds like popup gestures. I'm keeping track of this [here](https://github.com/Robbendebiene/Gesturefy/issues/99). (If you mean something different, feel free to reopen the issue)

**Comment by nachoparker** [comment]
> Thank you, nice to hear that after a lot of negative reviews.

that's surprising... it looks and feels really nice, even better that FG.

anyway... I know what you mean. I have my own FOSS project and sometimes you get that. Don't pay attention to that is my advice, there's many silent happy users! Those are the ones you are trying to help
