### ISSUE TITLE
FF57 Linux: can't use right click at all

### ISSUE THREAD

**Issue by nachoparker** [Robbendebiene/Gesturefy#92]
Again, thank you for your great work.

I cannot use the right click for either gestures or wheel gestures.

**Comment by stephanfriedrich** [comment]
Pls, dont open tickets which already exists. -_____- 
#87

**Comment by Robbendebiene** [comment]
Duplicate of #1

**Comment by nachoparker** [comment]
sorry, it seemed like a separate issue to me, because they don't work at all for me.

I thought #1 means that they work, but open the context menu as well

**Comment by Robbendebiene** [comment]
@nachoparker Ok, I renamed it.
